let
    Demo = Binary.Decompress(Binary.FromText("jV1djx03jn3f31IeiNT34yB5GWCwmfUsEOyjk/QMDHjjwG5vkH+/UvVV8bBE6QYIkotGrlqiKOrw8FD9w2+/ff7y+u3Xj69//O3744fff3350v77z8/fvvz8cvzz9cO/X47vvrx8eH355fv2r+O7T5+/Pj7+/cPX17/+/Prx/9pXzx/89X8/f/v19fjHl88/ffjp46f24+O7P37+9PL9hz++Hn/7+sNvL7/+xw//cM7R8Z6O//n87b+//fRy/Pj514Mdp3cuv+Py+Fjfsbt+6ukIoX3NHfQXd8RwuLdh+Hjf/nn518uXLx8+Hf/58u/Prx8/vH68xivvOB4yoD98Pkdxf8nxaIO9jeKP9/748eWnrx9f9WQoybycDJmOEK/JXHMJx/tw/PDt9admgl+O//r24dPHf318+eX6GrHMhNoqw2MmDDOJx/t4meU+ROzzeXxO7zgfVI0h0vE+iUnuY7Rf7WAa8WBrjHy8z5dBTKsSWDUePhlWLcf7IvaYR2k2vSxS+g5TMEapx/t6WaT51W+fv7ZlvX0r9K2QzSpH8I8RZIC23OZpGxc5N0M+VxkEpkHUHW1YxNjbcqDHUZ6N2ra/ednGHqFv6TVK28fKxkR897JhD8uoBCZpBj5nch8kdDe7bHKzareDzKP9wmJYNXYvEw/5/XJRV8BF/VGHe5F8N3Xvugzx989fX9ELrp1I18cWLUJ5jNNGSY8TR7l7mNjid1k3GLI5QI3zJEr3q8sEcujjeSjGOAmHjP469JnHHGp3r2EIWMu5+mktbTrhqHStpcTHOC28NAe7jILzaadxTOL6mLqjJnfNJ9EYh7qXrSJIUt7Romfi2VGb0zQXM0yT1J5UcdUWiSQeypJ897LVmWmOmiGG8FGMM8Ohuxmcmd/llLEKYyFMW9zGaX62MkUGTz2PfTF+feoOZlgitH0Rn3XiOmk4arcEhTxMkbu3rQNq7oPIZPgIxjXVbsbmassLpm2JP/BzImNFtbvZ+oJxGIHqQYZ7tJk2D4OACntSYUebJ5RpT9r5br5lHhcHx65eP22/bdwtcO977q61NEWAeJx79PCGb3nffWuYAqZyesZ1XMXjWXzEHb6OqYTuZcv7ts9GAuLi2vex+9nqpATY2PiuHYmYjCFS9zDjpIS+E2gLpnlXMqIxMEWQrYg9cl2TaMc1XLagceJ9eQLH2saQWKOZOY/rAfy8mRbg2O1yuh3btrXDRWWA4J4hMUAv7Z71xpYEQiRmogYEllmOCqwksMJisilnwFGwlKdNCR5BmNoUkmuA5WZpZ/eKoe2Gco9NCUHhsJs9K/hn7ba9LmxYRtxgsPPgynQa9inzAOkJBkvdMcU2XlApWjMjBrNQqVpKtbekKBQGZj335NqSgLvD4uvD1UNFHDY5KQUVR4ObbBKdwmDzcqK+4vjwBpKLpHHYbFhx0/P0R+NiiawAmTkVkvU023gDIkePaGxjkdqd9sL6MEBYQDK4YuFj7aliFAg0/D1GRGSWm3hSHl8MN4lJwbH5rmV9+r2BHmJGKGZNRIUQuBpwIkWBsenwSXBfOlpFGGZFMoUb2tYYfpbcDYgZjgbXTLMIGylhQ6mAyBTwv5DtifavnxZJgtq+j8OXWOEyNRDwBwRjtgsrykDDV5Lf47IEtil9YqZtgsJlGOUdQNy+wjkPSXEHyM5AhC4SDCCTkgJkClSRwFQqsj0tL5ObIg1UlTKCMzO3xDQ3CQZAaxQFzebbgsRNWsC9sAyMUBGYmVcvsg9snpt2/e1gWQTm4M1KBljOhLBMAV1A6+0LeYZULUFEPGYg1ABx2Ytr4O/3CMvmIdiDKZNcvDhEuCEygYW4l5K3qDVEBGKWPzi4XNqCgnFr56TAmMwgQc5zZrZhxkA5IwpTmWjBYeCYs2SiNJL0XBQOU8k1y6Z6+ZgH6XGO0wDJY6CqiTHxCAdUVnMnP1uzuBsfBl+GANxu2jSHiUIIweCIx34Y4Dxd9mk5pCROaWQrhZ8gsTOAIja8/AL2tHhEYps76UzlDIRegkJh8wgAn9pK8hwkSkT8tYRxLB/TEeUqGRtakkJhc6qggE8SbhDOWMmIwSaKUs5I6F6e56WUG/yC1A1un55+zWRaqYi6jBihT6jFCVS3pMJYThmashxJTsd1K1faA68AqVvsrkUGRKi84MGyzODk9MA9AATScPTqEXypEw8ZLct5oWEbAveoQaEvDF5CpNVza/y0NTUi8JryLhyghTDjlNT0BHRlgLInWEoGuq8ZQZd5ncJMWuTL1rYUhbisUTBu9JBsXMq17uFWBOL2hG9pnkrbJAW3bnbVSWC7JeoUO8gRYi68VVjo58tNzrspS/GpPMAjOVa460dE1DBOwAU9KjbgY+Q8oi6jXoPrSRZQIRcU5jL3WFvFz7tDLu5xVwA4m0/OdQbD5JLCXTowZ3QziNEQmOmybt5xYlnn+skCxuTKghMrClZ3inECcOQqgi/8LqLP9t3psiZyT2iwqGqBSP+AJYkQfRlULfCK7ZbNM4lFxDfsZRw4QLLN5JZfkNdUGFgRoYI/4sTBE4UF8krCLFZM7ztukbuljkNCEYHXFEsZI1gbd7pkidKTaqQ+Ij3VsvYkb5iwDPz3CQiTMY2i8JdB9UL5rO3HXJwlqrtSZATMcJagjFIksVPwy8TVWSLgychJ4OJHrYmYntUiBX0UZPLBosw3GkySZ9bsyFXIFO9ij8gLsQJEXWAW2qkvUp5JcawjKAA2xxqsazQD5TnRIo47HHZjWaMQaDhEWuCwpLIUqAbSUZLcS2ksJyMOUwhKzhmQLC1cPZwEkybiskBi6npjqI+oa5Iv69ZdRTIrlrPvlXG/eadgmK7VwPZKSbJ/FL6nPBgO8rQrSYbu5zKvdvqMXfL8BJSd15FKO2av9x4x2WKnCZisMILJWXzOYzlhxYNF3JiLBDo/XqKRntiOzfZxj8x0GkNsUT/k0x6ZqbumGoUC8hmR2Vz6Qd6HjhnZ+bKAZGdl4pqHVBrbNKpEtlFFJ18Rk93mEbW8IEuKLBMJ7obIIHHA0gAIkiSsBVpUJkFTkJCu6NVrSfYHggqsoNiUmAr9coqJ8lT4oeBtAiwq2rn5KU3UDYWgwNes3MGCdxb4Ar89rhCYXPdnPIwzegtJQbC5GgEXU49/xm/Pe/LrVsKrcivAiQhFAbDZkZCEzDIEjFB3ijDk0E7JUJ5LwxTdogqZlRasQ9k0GTLSogoJkVel5u7SyWBpmCIr/KVJakm1rhvqJBxI6m5+HM3oEYKZlD3sba80GfE3BgXDVJYClxspBU8BCdKImzFumLCqatXtc5z3NyYFxQzBDl5JSShW3OCscZjEGoU6QC8I+1sW+CtqfU4xFDYU69PqI8y+Zwg070VyKzlYUJRswQPrQX3A4zpMpPVgBh4taklsHNnECoVN1CQhIeikPAUjeMRfhu4JNyXITQo7moLCXjM/CiqKLr+M8yQioq4p+srenpqfmWCllBbUV4SoceKVWeZDKSPO0nS1kWCcai4vFak4jlcqCmyp8MNQJswyECHvTZdr1D0JlkDz+LYrM5NG2Sm4tQf5/VYx4GMmBFoG36xlbdWI55lv9cZd3nUmLME4dtkj1HpGDfS03IijOSy0YFoB0TYlztlbjhuQpYXbPROe4UlOT2ivombRzBkN1JrzAm1VUTxpDN29TVzs4WG5KLSlcuogG6Oq04I8w8hQcl1BLpTmcS/pTAYtbge5btXoKgFdbFFoIQRTclxgSblnI3JuH4soWpavYHjB6Yz1dPE3iGuHTYsS5i9v6YyTBAnUEApT0dJ8W+sH6zrLqVHCSL4WFveqMM0+N1BYjTBS0g2PzUfPIS70khPjKEqjbwgH8PZurmZwFqWsMBnoW4NkkqEjtSzg7iKCyk6kn5TMv93oab6t6l2kDyyQpvbSnGlUpc3fC6lOCQMZ5qy8pMScHF8v8LTF9yLnNw5Xq/5P6sLejuCMHmrYViSDOsVtM5MBCKtS5xttJEG5VzF8o6YnmjCkKk++zVDbUc07VgxxzEmyVYP7qWuhPiYgAX9aIZaUsTF1h8qi8rMuZZjvbnZuh8oKGOT0c5puLHa0l4ThyT8pZJ7jB7uVPj8rfb5A524R6Fd6lEjZ+U198jaTIvIpmMhdnT+jKizkd9pz9hF2UUMzUKgA1O4qhykBYZeeIDJMcLtccMba7J5o81Hb8XZHzCoXdmVHfeFSTvVVnioD7LbK/KwqVu3/zbNeiMkt2C/dVwPS1osweGtXeDgGKZE+Er9480tu3Pk0GYbHKFqjj80TV909y2wCdOdh6YdJ6fRxGAYpqPpIUsnvfMFjnL1QX7eBtRsjGL5CSqg/R3eojzaL+wlgMaWtLCypU4fEGk4i72RhCdz1rQBkDVF29FhR4KEf29ldqS6gmWqNcYKoWrQJyDw/4jKz21FkQZWQCErFMhVWUv2NluhNUjA1szHztmWyKKbvlFvNFmX/tGUyqXkYVAhzWEjEbnVBOqaUmzkuFGJKggBaubYQaETjNPYjrakxLacCVBZlZ0cQYaXWVymAtPU61b0ATDxd0yk7pVhR2pUWFqOxu9Vmx24QGWChGNVrkb42hq1mqIJvLyqePW0kYkU3oGahpWQRnlckmSJCsM/QYQZzba/3e0SmVNxQdAVX9yudPgT2KIjspMwex/bEH+OC8NGuUwbMDAnEnV7XKeMYR2v1TaoeYYB/Oz23s+eVWl9TVtD4lK5VdcgLAe1alRbsGxZGhseJx6KF665MmaDEfxYb44zfOWjB/g5PnOGeDDwRaE+aZbhqcl9XnSkiDryFaJpmdqZCkYOS6evLxiiInYXCDOXfR57KYaXUj7rFroqHSCwIURNm0G2c1PUwE+Uc0gKZZURmUL9ujhEEUqURR8JThT425nc9zyy54FAWtUndNtlwV5qvmfBEnJ+U4tQFq5ueoxbnq3sOmsl6L8pUkeJIGwwW4EI4gftcZOaopfma5fLWR+/kcpCgHr39hkVFTgniV+/clPg14kUMC65ME1uKN8Qe4zFMXL5hAQ9XVPypl1HitaaVWj9AyfQkVOZaIce8r1ViPtf22QpbsSw7JlXPBVunLC7U+QlYubcy1OzXaaXOz6pdrBNgE/HKifaPVIBPo4pblp34iSyMUDldhdAH0yUlyl9ytwm9Gsi8IbzkFFYdkhlFFA5OCiPUGPRCUgp9TEahvZqFVuer14ugcsMpPemT1P1rzVBGiyOnnUZ/KuXXOXFLK5G+Ltn0VsCJoeRU7YcqkmrCadEqT2IQzlqdr+pwet1+UqJyvkny7e6fnnjP911eKfF17q9yizIHpuw15QUaEkxpoEgFU7jL7/cP0fSsai7wcI6LYmRQzaSCohm0SZ0WGSlN1np8dGkQs6LK+XrIAXsTOCtF/rbBvbdazDdYLot3KfIiRevQWTjRNJKBrPT4W/VC85c0FYm5uCelyKC5d5aIAxtUyEZWRSnpiCxUVnhRgYw6a2fLxctWeh8AI5+ar2QkQyUsWK6MeS5nPGwMUr7HTpQn2vtb2uBlLmjHtChBZtUTBX2g1/NPWHbjoqT3q4oouHxb3tUL4C7ND5eyAlpA2Bc5MKdGmCBpHQev1EVZMiKVCNqhnpvJhEb3G1e3wFoRCwgwtS4EEBg+bshKmwcqdG9Bs8X8ehJX3nFemn7r3fZzBKh+w3lldej65hhT0MJ8vTegyyCcFNRWedCqVSnzlf9Ha5gOPIWeHdodrnd9vuAvp+/XGXfWvJeEVZVjdrGkUYaoZcV7BeR3dKsCXhOjBMh1K9Av6qmfZiOj0uSdu70VBg+HYIHZC9gh+TL9+RJkFLUM/HatyVclN9hTSEkY5ck0AoB3C31+UK35FV2MsR5xjROeFCOL4s17jXnGgN4pib5iJBNaBKKsER290zL9XQPGm4h8lvB4lxevhmVMGCHp0xnoeNvFu5VGPwm1qny2y7WgODJoVu+2Iv0EyutTfGJ0W3lyT16qgJjUoe4U1DzREqjBtgDi7OptaB0bj7J54gVQS/iiG9T1+WJKzk6KMYy3K5MojYqn/m5KCT1paf62+xP5JrDGU0m+6g42o5qntH0zLN1LVsFwVsq7yuT0EFK0fKPcUJpBGyGnWUU7h4upi8fDqjTB68pEkhYOwSWeV+L8qDTxbQvLlFJ5VuL8WdGNTEMyuno984L8qror0Hq20LNS5CuEB/m4AnsQmdPwbN6K88tdQp2NVdzE+cZLX5dnnUDaYCI9pzX3JXmM1nfBI4zXfuZFLTIjXoWrq8vEBB6OCrHnsiS/bm15YT7wXPfSsFsh0kljHhjEu20lEtnNqB6UgbPmadMqmVUPbwd6Exnl/VKqr0G/+hjFnuNy8k+U+kULw6olc/M+PGHG1AMHMA+0SFwwY+r5NCr4MZbZP3zaMGPgaOK6/eFSCUDhsky2qTEgJHSGFAc7gg9seq+1+1MsUoKG8KY2vW21EvCrd5QIIDuQGwGl9yOcBC3hn9/80fXNOEmJfCAbm0XB3gnxUDuqkJjxuPgDL1soYXuBuuxNGRJQwoBDwS9bKEF1rjYIkpohpPFBy/j1g1eGgPWEsdD0Mt4P9WGn5tdNQGQ9AubDXc1v1PLwNaFg1fJ8WMn69bPdqlk1gjz4Mm95KhxT76GabzL7UO0mSqipFbkATq4ZXsy9Nim6BZkWhaiOeDA7TKqz70XakGm3LLaNO1+pUev6tYQDGFd1GuEdr1Hj91FJ++2XI3UxqAg71mbjL9Os5P1BVVR6qJiych938v4b1gmi6wV7pN1LYhVAyltSQPMIK2l/UTxpRNeFJ14vM5QbYtsXwtu8igF2Yl2wakEmk5WCwuHujiK2T+72qsWucyPiq7UwmbQS+kfsdAAGk0Bp3NUOI/SnldQ/SgYaZYFnPA9Q5hk+m1ZS/6AKmFFG99Iz2n12hMq0f4ZfZzwtmvu5lOaTkvlrAASJhgp5cM9fU7kL/eFhJyimtmynTMVMn56+wa8aQqAnBbd5qfBPqJwAsN1CHjCndaykLsRl+faQANyNyQA++dlj/FHFyV4knheVb3p/i/F/62ieKko+87bdEv9Iw0nkZoOcy0riv1fn9KZeA6Pn7QP805s/eQZMOW4LmqoNxeiU9/mu7/8d/Ro/15lhzErWP8vZ8O4mK7TnP/H6PvRcnSKhDA/yDfbZ52oDNfVeGb7G9HgtTFN6xa1wGmCAis33/WFS4H79CIeF9m2XKM1l0V+KZQrvWDT9xHrzDGuEnay/qFuzP8kySXt90bL+Gcng1V+t7S1xLxzTisf+GqlxRZXV4/taXwPkgB98DUHoKk/k/fU+F4tGK+Vpy6XEnjerGNl9URJ/xSdiFTtIgiRHrmptv9E4iu2SbMnofF3o+jOiZGBa5X12BXSrFvYvsxqVZV31ynYbjMNb/YZKS/d362c1va9hWfC8VVwlkwCJwig++RqXBU8wh1dSrgDa6ZGQ17R/8wIbp3v/2FSW83X1En9FQh8JPpLG3B6IxkzKApapvcZqLg2tL8FrC75WW1aWsFnySrdO8R/+aaTHvR/c0xf5kf0lqyYW3E7mX5Tur+udpisvuGcyf7z4KFh/GyW41aP8moJWVXIsjfthkJXSv+o/rVQMCjq4/Xv8eG66xms2xP05fsCl0Hja78qJ5wzuySv8tzcpk9UuFVxZdFtmlLA79aoI+NUQhwW30PbfUD78PRVZCLkdBtOCi64ImsJPoJ2qX/+pnX68JqY1EO94s9tftwJJA4zgbWVZVE9EdD5zdiMKa2UZ/pWgYDTdBlLi/U3z/llAmBuIAqUV5gpydSQh2c5JJan2jTciAuUN5NICsa6VnwBToLJ6XUwpJ0k3ikMb9JjI04f2FbKu1ss0ge8P7YPMHB/s9ncx1P8D", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Opportunities.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"OpportunityID", type text}, {"OwnerID", type text}, {"Source", type text}, {"Stage", type text}, {"CreatedDate", type date}, {"ClosedDate", type date}, {"LastActivityDate", type date}, {"Amount", Currency.Type}, {"Probability", Currency.Type}, {"CycleDays", Int64.Type}, {"IsOpen", Int64.Type}}, "en-US")
in
    Typed
