let
    Demo = Binary.Decompress(Binary.FromText("VZq9ruC2EYV7P8s1MD+kJJaG3aTOEwSwgRSBkSLvj5Aazohfs9h7lntEUZ94j2b4z//+9fef//jj5/d//+vvv//6z/zbH//6318/v/35z/UPv/ymP7/rj4ldv8r41eVHReSX3+znd4OqS/Wf3x3qtdR2OtjYaj8dlupLvU6HqdpY6g2H50fvpT5wePbYAYep9qWqwOLeFqrwuH/snYUaTKb8TlkdJleObjC5fsK6w2MOfl75gkfPidzw6D8W8gOTvu9RB0zanp8JTNr2NoVJyQYT33cz/3Ka+J7J/G+nif/EFTs8bD/Febenh+1HPhfy9LBk6YGJ5kQGTHRPZGJ1muheVwencyViSRygTjk8AOpUY0UcpM5Fjok4UNWE0sHqkuMdAKzzAWp7ZdA65X03wHXJ79004DrhiNENuH4ycNWEuwHXCZ69M2nAdcnxloLXKau9MnidUMf71MDrlOMuG3hdo+N2wOt8X+z17uB1ynHJDl6nHPsFcJ2vor7WHbhOOW6yA9c1OmTwOl/zeGYdvGqC2cHrkt917eBVk8AOXqccl7zA65Jf7wu8zu3pZeoCrlPdHuB1ybFZglcZe0ku8Lrkd1kv8CqJ8QVe5UkT8PrJ4LXkG7xKgnmD1ynHPnCD1zX6vcsbvMokMDZ/8Cp7e72B6xr8PskbuErfg0HrVOPFvkGr5O56g1aZtL5P7AGtU9b3TXhAqyTED3AV3+/NA1ynvE2A65LfmTzAVWwv6wNcJXF9gOuUYzBoFd2L/YDWKccvT8C6Br/TGwesz69zq41Zj4PWV47pjYPWGP0yMhpMZG8Co8Mk9+JxwSSzxLhPkxUQYvRzmkw55jdOD8sdev4Bk0wOKgqX3LpVDD7PT/wmF4dNZQppsLk3PyodNvdGVuWCz1XTueFz1fgHPtdeSJUBn57XVYFPRQ5V+PRYNFWDTdubjarDpuVqaoPNN77Dx3OaesHHN72qN3w8p/PAJrOE6oBNRg81gU1u8WpgeP4U76kaIF55IlbfQPHS93hgvILGHg+Olx7wGEC2DNBqIFlz81YDyjpqnoB56eHjgLkShDpgrhyiDpiXHuvmoHlli1g3B81Lj/t10LxCR8zTQbPmLq4OmpceFDportyhDppXwgifBpqXHuMbaK5Eog04T1hjeRpoXtkjbreB5qnHLBtgnq/ClsFyxQxtYHmlknhYDTCv/LFvCjBrQd4B89TjnehgeWWKeIYdLFcE0Q6Wp75tgPKKFVsHylqId6CshXgHyitwxFp2oLwSx/YHypI5Wy+gPLe5WIQLJEtuvxdAXlEkZnkBZKlvugsgLz3AuQDy1LcNOJbv+w0cr+CxZwmO1/hA5ALHUl92Nzie+n6fb3A89bjsDYxXzNg6OD50cLxCTKz9DZBX0ohVuEFyBRO9QbLkV6LeIFmK5BskTz2m8wDkNTzQeUCyZLLQByRLEvsAZMlooc9B8v0mka0fJN9fQtHnIPnV9/AbNhlR9Hlgs8O6PgMusic55HSp0oYOPV2qEKLDTpsvpgyHTwE+GnyevReNDpva8McFmzuH33C5azYPbOr1GQM2VyyZicAmw4iJwibDi4nBpu+bNXH45JejSYPPN77DZ38kmlywyZBucsOm1TQf2PjG2GTAJzdwU4FPFU1U4WP7WZkafKx8HD75PpgC5JU64nYVIE89blfBcYUXU4C8wkispgJkS8BNQbLld6cZUF41jhhvQHnpMR8DylOPyxpIXhkl7spA8tL3ZYGyJvlmQFkzWZuB5aXv64Jl3Vu7GVDW/UVpDpT1qoIYUF4JJWbpQFn3Tm0Okiu4mINkzV8E5iB5JZE9Hihr7uzmQHkVU7YOlCdg2wYka36IWgPJWiQ3kLwiytZBslrVBUHyii7bHySvKkkg0kDy1LcNSFataYLklTn2eJC89D1NkKz5OWkdJFdGsQ6Sp77rmgBZMm1bB8kVOqyD5KlvGSBnorEOjqU47uB41Uvipjo4lqxHWwfIlUXsAsmVRewCyWt8XPcCyZJFPruA8tK3P1DOjGIXSK4sYhdIlpbDAfIavmcDkFfk2FcFySuixOrcILkiit0geWWOuKsbJFd0sRskL31XrUGyaF0XJFd2sRsoyw4Xdh8kX29FI7aR+yD51ffwA+RX3rN/5LSx/G60R0+bpYf9Y6ePJeCPwyZrIPY02OTnpD0dNs/OjfZc8Kmt97nhk8UOex74ZLywZ8Anq9I2BD7Xnv5Q2OTXpA2DTc9fWMNhk1+HNhp8kuTRYbO/Am1ccCnAxw2XGv7AxfP1HAM2Xp0NgU0C7qLwyS3ZxeCTW6+LwyfDiEuDT5YCXTp8stThcsFHywckV4pwAclfW0WA8jdegfLXQVGg/DVcFCivEkj4K1heMWL7g+WKHa5gWZ/yB8urpLF1sDx/imVWoFzdGFegrBl93YDy1MPGgLLmpuwGlDNeuIHkarG4geRvOEjWrNq5AeWsc7iB5DU8lsCAsnpNEihX+8UdKE89ZuMguToq7iBZrWxAsmaRzx0k647D7gBZs5PoDpCrY+MOkDVrc+4AWbP47A6QqwDiDSBP3GPRGjiWLFZ7A8eHDo7n27Sn38DxoYNjKe4bOJb9xecNGGehwxswltzBvQHjuRfE8A6Kqy7iHRhnm8Y7KM6GjHdQLBmSvYPiSiLegbG0uiowluxtewfHa3w8qQ6Oqy3jHRzLru/5BYwrcvgFjita+AWOpXbeCxxna8YvYLwSRLycFziW4vgCx1kV8bOF19+GS2B89vBefS/C2cSL8THLs4vXq57hZxfvlbfN2cYLPe7q7OP1r57hZyMv9O3TT5+lx7M9e3n9jSJ7/A2fJ1v9Zzsv9FiGs5/Xvz6Nnw290GP82dF79f1wz5ZefyPK9nH4JPlnT69XcvGzp9e/Lo2fTb1Xj4DlZ1evf4nGz75e/86A+NnYCz0e7tnae/XN2tnb61+bxs/mXq92jJ/NvRi+bRpsLB/i2d579Zjl2d7rX5fGB1D+IscAykvfxyeAsu2vySYgOY99NAHJtut4TQCyZdRuApA1gW0CkKsV0wQg6+5CNgHHVeVoAo71qcuC42M8OK6OS1NwfBwWAcfHeHC86hwaOjjWXeFrCo6/YyQKkOdPsZgKjrWXOzheZZE4dqLgeJU5tj04nnosjgHjKcdVDRRrfjM2A8VZFGkGiqv40QwUV5GjGSiu3NIMGKvVZYFxNWKaAWPNpN0MGC89iHJwrFnHaw6Qq0PTHCRrcu8AuaoZzQHy0mORHSDXCZLmIFmetAfIlUOaA2QpkB0gS34btgaQl74PLAFkyRZkawC5Doy0BpDlO/gEkqWOODWQLNkgbw0oSyHbgHIdJ2kNKEuy2UBy1TlaB8qSNenWwbLso3atA2VJlDtQljwX1TpQlmwptg6Ul76vCpQrurQOlOtISOtAWbK10jpQlh3N29nba8fZ0LO59+p7uzi7e6Hv8X76VPmjnd096P30qaZLO9t77Tsn2s723qvHKpzdvRgej/zs7rWv/NHO7l77TpC2s7vXvmzRzvZeW2EhLnt291458mc7u3uhB1Jnd6+9IWJf9oJPr+nc8MmadDu7e+0NEXuaAz5Zq25ne699R0zb2d5rdWq0nd29Vtmind29V97b0dnda29Y2DYdNrUrn929V9/yDZsi9uzuta/n0s723qvvs4wgeaWFWPsBklf1Y48HyRU6BkCev+1iMgMca9ap2wDHVftoAxx/YWGA46qJtAGQdVek2wDHmmW5LuB46nHUUYCxZqG6CzDW/DjsAo51Z+EuwLjOhHQBxisrxDFNAcbaa5bAuDJHF2D8HTAVYFyZoyswrupHV2CsWcjrCo6XHtdVgPwdSlWA/B0oVYCs2SXsCpCXvg/IgmTdh/e6AmRNwLsC5Eoj3UCyZu7tBpIzRXQDyJpbcjeQXAdLuwHlOubRDSjLKB+gXGWObkC54kU3oCxP3RZYruOl3cFydVe6A2bZ5b3uYLlOmHYHyytd7PGAWa60Act1zqM7WF76Ps8Mlit0dAfLlSK6g2XZhbzegHKe//g/", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Advertising.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"SpendID", type text}, {"ChannelID", type text}, {"Date", type date}, {"AdSpend", Currency.Type}}, "en-US")
in
    Typed
