let
    Demo = Binary.Decompress(Binary.FromText("fX3ZrmXJcd27v8IfcPsi5+G5CQl+MQ3rCwirZRGgSIHDg//esWLIjMjSKQIEqmvXzbszd2SMK1b8/q//+ttf/8fvvn799z/8+c+//Yn+9Ls//P23r1//8be//+U/+Mk///Uvf/vbv/zhT7/97et3f/zb//nLP/7896///du//ePP//r1P3/7+6+//+d/+fqXf//jf/7nH//8f3/9y9/+/vW//vD//uO3P//9n3777euf/vGnf/vjn/BfePLffp/of/nr1/xVUhm/pP1LGec3/Xd+lndO6avOOr5n/0rf6WuOlb9H+aqd/n6177S+6J/IWuXr13LWynGt8pV7obXKGvV7TV5r5LG+05S10vpud6n69WvVpfovZYalKr0ErZRLKd+r8ko1r/XdN6+U+/5u9S7V7g7bLykuhd9Yaa219/dsvFSbKX3nykuV2r9xCrZUvxvsv9QUlupfY+Kt6I/fdfBSZbX9veSscivfbd+lxt3g+KXssNT4yrPTWm2l7y1HtXra3z3zUq307+aOfd4Nzl9wcm6p+ZUrltr0JmnLqZdJP9/l1HP9nvMute4G1ysNixbBBnst31WPfVf6mE02uMf3cBvcd4PzlxzPiv4ZyQIdUGrfS86qrz2/u8hC2fTXd4P44XzOKoWzome8v57mt5xUbvQiWbY3aZ37+XK+u5u/lBXWoX+2Br9S5/fIo+OL6T5x6nRUfdzFyt0fHVUJi5Gw1ykiygIkx14nJECOPeMOnLWq/4JRruhZw3u1nu0KlkT7yipWiT6g22LzHzAKOz3ri29z+Z77i7Y3v0s++yM5+R7u0Lu/gSnur3813JpCKyUVdXpRyKq8U/p2mxvh68VXgqRDEGpp+Xs3HFtftiafVKNl+11s+k9Yc1iMfmfjU8+V7k2RU5+ko7pIaK37u1zFkNfdYfslxx3SQUyovjx3+u5FVV9v0BKi+gr+eNbad5MkDfEL4lLg4ElH0c1ZomUa7XPJfYYe23ct/PTVMlGN0rM8+L1ygjrg19r7vpbosbNU9h/xWYqkpvGFXvtbNAPtmMRVNUPv3+UePAQ8X4UcDp6e5c26fdIPZTmshV21plcn46/PWjUIaXyrCkUCjUxmoom870pmoohsNfpju/JeWlCjQbjoWW2sGpZJA224mzSQ7JYr7rRV/wGDjilHta/5nU21p/HdTLWTxnfbG15GcSPdUhB4XB1SwdC7s5QGmTxKhiR3uO3Nu739S4pL0Y8vts65kMITsZptje8tYlVJS1T3BZe/hzmYiXJ0ezlnRbr9nBV0+3SHtcMOe1iKpL2xhPZMN2+p7tsFakp0X/seV0Sh7e4Wo+6rEG4sRerhu4p6r4U+gtnUQX99TU6Nvky40PQsizTMalp9QKXT1vmtCh381e61BEMYxB2fevBpJRJG0qRkEWv2qrSu6mWrVm8Ko7zTszyhHMg6rG8Slkx6OZtRlMXoM9zPWJsX1Oe8mjlsUJtTRWJhYT37XSEdZ63uHbbnwOhX8nuRWR4kaj1dq8/C5Y1hHUHPxOMaXy2J3wDFTj7jgLazhWCsr7Go03/CHEx0xT/rbFVJjw45IbKNC+8n3lryjl91zkx7BJ6ebeyOfKHvLrsihTxwFUUj7+/qzml/VqOQv8JLkS/T1MNKdGhzqF9LPsiV0ZaCjAY90yBS+HxTLvGGd6ZOm+yP/d2zVPZ2ooT9QUVmqNE5E24be1gNN0/EvdBfT7dU8Wo0he9HzxakvXRapH4t8q/MKeWV4IBc8WzBlYkXB98m8x2k76fXpTdo5/NO7SqG1rySibcG/4w1Q22lQsmxoJe6oIf51EeGHjtrda9konmmZ2Jx6iQ7CteUvKSO8z+yvjscyrPY8J8wuqP0TLzISc6wiBXZ62+VT9pqcqLgfJnXrW3wZTjIobOHKLFY0Rue0CvTsV0V01b4gMEOIlTocuzDFPJsZL5MIdO5V3fuO2wvXEF6xrqdTPssdK3nhJ47HmSiQ79C1ZO/f1FTsfJmrbBzgSNDcrGm3R/xP8p3vofVc7CE4a3w44UVMq2JgJQFa2SSU7mDhULWdJcqXoNGwerl+FfkylR1sBr5ClXdIjIf4wpWr0HHxNeqovhmHtC/7H8McXOxEt2Bq2F6CwIavh8942hwkxFMZgOXnTmZwPvteg/aJdw+elYq62ESbjnnnODAixSQdr76vA9vGJ7THrIO2RjEe+ygQR/L+ZByyE4EZrB8wX9BjJWrKk78yKBr5vTKmN629+Wj+BJXIgEvcNAaXQroooIPXvqVJQoOk3urHRRncF/o2WIbU8nBPlaYFIOGpqR2vOIcwXuJ6pyedeioTj45/ZJeERbdlyKnBoHFWSmHKD58OnrGnnofhdMli6zvvraYzs2FSKN8NuqQ3MrXrpJDplqc1F3Fm0jkneBKnrWC5/KsVb8GRzV9nLOucF2WCubwym60IJnhzOnZ2nxROOxfeZ0oQtQmCZo78u6vXIzih8r4hifFEp7J4W9i1CmuL9fTGMFliaIJRxDnTd5SVlexV1uGPttwy8yQXYpvMyU30cg7JFVW4S6ua1bIREz3/aO3Eo+avsjmCGTTpcty6RaiSXX1W2veQo3trUGMQOhZhwQgkNKMVymj44T5s+Xgus7kw774VpPFCNYASYhx0jgLDp2lcZy3OXMQzGAP6NkWYarH02+4IerpFzJXLmiYJYTuQZpwpqvwsU8LreisMrSJnVW6H3BWbw1y0Lz0bGIlEoZt0XZZdN2KhkW01Lxac7bPgR+Ccvan807NpLvtNs0cFPqj22D3G4y+AT3jNEcnY7f0C9JnhWm3jJDLDs6Qfnn2R+ZRIkj63ZOcFpIoslq/mIRiUbe9GYxCsJv0TL5fbRwY8O5Irr6Lfr+cvUM9g7uS4/bINeegL+Hq6kFxrkrdRNIx1b1VcFdinnFKnhEencXtvXBqSCwMch22zkqfM0srqYNRa8Ur0aLjuFJiYLKPHlf2ucH49ZCP7GyH27qR6CbX0CJRbPse1QqJl5jdXaw+8HLV/NVGPrBmcOicrv5dIecSgwXEFGuxTkicAlzIlNWrgZGrciK1orMSlAI9y6yCF3k9Kp19ktej0ono3ZUMVg9WL6jPZWkXpBn1IpdJ+mntm7B0OxzeqkfxpGe8wYwsvKVbVllnqZ196LGC2xI9V3rGdYwFTay5oAxNbPnY7TXxWiFtFo/d3JaCS6MGq2cyC2ppClKE10KsHQxfuMmIMDv7rQkxggZEFEzCmos7zflCW2unz/HC5pSgBDHZ3mtBw+h7NWiYq0F38Fyia0bP+LVQNLJPWOiIVBcji+lXigWkcO6I5ionJMYiN0EOq5NNVxefQhFXMtjVi2hUxRyiSJ4481XbHTliH2dvn4Tb7XNaaZu4Z5J8+AUSepC/OSz0SEj5nrVCxuV5rw49ALlO48r7HlfeN27UWSpUkFKwgfRs4K0QuKijWDbqF2rkW0j17+DDPBtEJaSIxzgR+Wj0KB6NRo/pqr69PgdEiFf5GhZcnj00e72KeZ/IXrvoYYe0S3SJN9KMLKStDRPSAYuz6ymx3OwnZPBTVJtFg/JHrMPOqw/y2vS8EE70ddfKH5ODeDbMOKMkiI+2ndNPfqR7qeDGBB8Uz0iXsJRCZaodXORsaw2ptOK0Q06xhhRfCgqeNQ00PLL6AzLugpGWOCg8i7Vg6uOLNTGqheSpacl0nzwqxajXEObUg52Pp961NJkHwhlEgwvxzY1rCsl+d6c1gqdWw2JDPWRyzzLnZCk2WT4n28jwl3wXC4WkUOnMXDRleZhdNc1A6KXpksLp1LPQ+qhpMhs6uTxkjNVatEZHr5UD+DJ73rV2sIY7rLW/uFLWOtvV0Vu1FSXcql5Ec8i9BP2OZ5IbzPCLzEaTWj42mtT+DZdzDkWkeFQ4iNE5TUzqoeg1nD1D6UnNTaqptlYJtiLsEBWiplWIzWaBnIVk6Vk5+uz87ZzrxzIEnrG16NCA5A8VciDTlfeVnALMuYVwIoWF2teULEWyfFCtKOt3Pffpyvo592Dvg8DDLVC7Si/VhtlVrsCbXc1urc9JGDzLXVQp2fuicArc7qppZ3IJ09UOeX502fCM5BMuTSpaCByZoriuGS8y19tJQ0jEPJJlZaREpz1VZdGthn6WKM6n1XMOeZgcX2qLm5URD8odLAAeaMkUJa8bD+YS0jDxA5YkxWr8iOqDQg7hsarIPrmVcviA4Z2K1ZCAXYD8iJ0go3WMfXNJ2VxCESl4pHi2uQ44K/zF1ent1pVPKNdbFsmlej1a4v7qFxvovU+asQxkYlVAa7p5xlxaiCbiKyFEZYuzdzGZapss1honRL0Ody4BDROKPniWWRQ2+Z0IeVZDZvD6WG1kV4vPZfiIKfi2eEb/F2jGsnpIR7VAt1ig+66dKMGdyXGPE2+EH1+WtGpkVC1pxdVYt8MVvLW4Q/7OfFr0Vr3R7aEop12NXOgbJCdYwZmJmg+/cieLeVVI157ICEjKYjm4SK4BDxM3WJMiKmgrtJT6WJWWqoqzGnGt/NHlxjPWC4U+XdX6OVlEzYRPjxzKNcBhQpiKZ1lKSJOCiKI+5CLnW8OAulNYK6RkohlEvZTFvbP3IyqUXkWxX1ChTrHXFmLCcJvpGTuQKEBZZEJHZno9Fy8J9TMaJrOXOcRukVBrMRFGXmVqeBtfYz4mHtRQTVw6HY5JegUOySR9OiBFrtGJCbeGnnEIQM6j1v8qvaWFg1rdOAsFKEyNUrCsVAPIgwpUAiBAA8vmopJc98cKBJ6Jz06atFuEQ9FcOXJAf3TbaxEIE+SAa6XsPZIfxNnhSo5RdfUDupU3+ZhbqB9FX6Fx+Yk9UdgtfS9nt2q0Wy0UkEpcq2jAS25osfRqauYOIeAtboc13L5g4rlaKrEJYsCBBFu1SEfUcXeplNyiExNOHrkNTtXmSa7V0B0m5NnXqVKX61m1mJYJTi09Y/QDeyuaANnkLhwwzHaV19yGt4HPWw2Nu6Z8d8kVzXVSomu5wkZu06uY6C7AW+xDwsHFIICayQntVx7gts97odsKwUR8r6WYDHq74zMsBIGqZHJzpY3ctv+I8fLANdTLM9rNy9A1HpaXqS4/kHv6mHnCsy3ZaEFKzpkCQDGT1b7p2twDGiYeFz0rnPhdgqaaFCy7BEgr/qh6dGPCNUQBq7D3AYcMWhPwmiuidGYXsZB7cGNCQI9nUtInU2EKmRzSo5CRcnAKuQdUb7zP9EyQUQXZRjU3G3itU86/cK3cgxsTXXZ4FewvFMBf1GFYjaRdHYZGDsOF7uUe3ZhgmfnTZK4HDkM4NkRK29Ar89t9vflZj9Iz9mg7qsAKbFtS1eVyIFnGu876bAE5XhQEYGJ3U7L2m2VCvNDm73LfXsNEvde34ruHALEFkNG7WYkRRGokr1/i7RvJ4FWGVqIPMDwOpk6Px8gjh7xoXMygAZ12VTXUJSmDVEqKoXsnbRR//UJODc+4cDbh1xVN/JKyaxZHTJfKzKMG+QznPlg9ceJ3nqi0A7LSLABfrkSVRwD1Pms1oMSh2CeEqg3Bkh6dQIbWhd8jlJVCqhbP5CoX4GhQkNuDr9y1N9unBUaEwcRjH1L5HH2rx5A5/yKOY3aY+jxm2Fy4fvRM8nKjm6nJ0J1qaqA63d5CTenZ24LlZUlfjIfaFOkYSl+ctOkjt7FDRjTcY3pWpCyRbQUKBrYhj4DHuC81U4jhg0Bx/ZSDkX3gUIMcR7Uylb6ki7Zm/uyi0TP2qzppzmyiSZdE7WgmD/fubQbv5VkI8Bc2o9DnqqTGqsOUVKUYZ92rNwP85VmrfjHqaNUDoC4IkBWpnEm3lHvzZgs3L7iy9GwJ/pY0p2EQF13D03mQvD2e/fPVo2eLPY46jls80dCi7hl9R+dSzRGS2fGlVMQrXRYF9/R1QtK5XW0xzwjjDTLOKGBWBmkO6xUgs5BNnUPbXbswV9CcQTLpGUcPdW3zCzISu1o4pYDZuXgzYHifA99y77ol3+hjTcNG9unKr3mFQlKMH1E2ZYgIIuymblTGz6tFn3Brz0rZB0YxNYEMAqcTxj74hw2EmOEf4FDd814lfLf4UkVfako5RfwMktG0jp/hVqqfE0v0TOo13NihIeQCEliFCVVPt7+QeomKjp5NLWYYpqqucopIKE86J3H1z3ERX05JnC3G2a6Vq2+oQJ63Xi2+gscSw1F8HI7b68wGGdsJzq9WhV2bR17Tf75ohdc8WWKgqqwzYzcL21Fvnu6lgtMS1S8AQhxsJzRjaEIWCdWhyoD8j+GWClCYmHbhoinnJfaQqnRptRz8OxeRkq+x7FhECtp8a5oR/o82IgFGqrA40lAXVZO381iergU8m1B2mwyUGV/kRzSvm4HJcG8UHZag6+C5MZJiZNYB9BfrHhk+4Arh9o4uS5B1JIA5N895ZY1iSPNZr4gHfubdPtYA8Uz8Ffri5Hg1sjZWCRSrMML2ut9e9BMRGQqiZgjAjr2o1JPF2qWXsFYoH0U/fytGfdAXWwbVpChLtAvqzVcl7BluXxBOeiYu1LRYLyPVrHgoEliXRdjrc0IQrgg3kJWB9C12ivq7TxDP4WDXeUfQbpSDrZnKDYClJj0Rz2QrQnVX0MLrf6qqSP9mkqSPAn+lC1OEU+ACZ6GAggkVSTzjW9zbPBifhAT9PrnT6l4pInbjSkXhQoucREMekQk7yKOUnJUpqYavN8NSFecCWIElgQo2l81hyeGYQudRju/ULOpHkmRaNARknEZDHhhXUsi2hIuHZ9zRkVvtyMnPQT87fdCfHR65pPFROEs6Aeg8meE2KTCrFoAupw5K+ozdxTPGMJWdrShGETIXUqQ6012Wq6TQeVTiSkuaeQHRNcU72oBuEG1evutdaHu9GYwVnmnPZYdh6JrigmFQcEGqzjCUHB0Xf2PwTGrv0OByy8hWOUAxVMt1gkrOHysOeCaak8Kngz3qXFVRWd++qlJy+ehS4xmHHqRSNJZlrIjGsiT/t5BVcvRcdlincjyG44XPqfYYjQrmc6Z1i0YltyCfQSPgvrM7RZK6DYQ2GRTST72h36V6+ILh1nB9lJUeirbJUkCjIjKz5P6VqhzwL89BDUEUM97evttAU4/5+dlFaSXHZEsQUHrGKg99NKrScX215QiNiU6mlt9dinKwFFSwgWazEz/BHg7cCcEOeaQonNs8PJR+8+kySQdUkJYr/ZaSPpoGPJPKGsWytjvEQGawNgpaZ6HQPh1vDD3jUwL4VO1CbabuELFfaSqhUhS8gyI6m42KXZUMh0qzbWSIL0qvlBoSnEGV46OIJUYPVT9w22rQXdQys9tbKBSFAiueCU4Pvr32GnUAsath5j2Qu5RQKooXD2VRYUEASYHe4dHFJZegf4RvF3IsUcZPWXSPYo0zfaEDQqu15DRud1rzY5oTzxSJCPi1FpF7WuVk4rvHl5eyPgbreMauFHxCy9ms0kw4URZx+wtt089C+4sRPUAlqCPcuBCqpTBpL7aVagoudTANNakjXNG1rZZvMbpSgRfZN2CXGuG7ca38xdE6ICr6/Wqh8Fa/H9pxbpNBqSUoliALSEFzM9VeBzI9ej+Q6UpO5CUvKDWUip6XokiUYyK0mBgEoO0LAShOBdcW5DMoKdiPKfI5T61p9nybH5CMcPuL/UbBMqAsKqmkaj1Z3EVh+JSwTqgSRV+DnomDhy+uCbeGrIu1BuQRPl5EugQ5p2eFw9DVDauZkbfN8k6oiV6VUGOFKMhmtZa6Aq8Q2UVuyXKQ6VqLg5uVuj9GtHgmmfNSD56fG7ysZOg6vEpLQXsGiWrJ+vARZrNlRmLS9RIj5XKb+ksLJaJ47PSMs/CzmPqsMFeWvevBXrXYcxS2B7y89GqmuQ6VAkn+4SwAyMvtMFC/RCePa6JctK/cCSUVw3qYJ8oaNyVRWgDuhrRbYdUxBctzwNettgu+phDiVolKi45L3GHXNgP4rfpS5aRM6U/VHfn4bNlhazk4pjMrFuwNZrYxjhzPbFPa/JilLgyf45fa8HvVPGTYZNWfPVjlFnC7z3staUAsY8ASizOFQF1TEiu5Il9pgfgl6gSUQ7eAuF09rft62vaXuadwB8NaMCZNStrz0AAhVZ0upn/dlUKRKMA08ayL84JOWOVYgZNnNANkVIt7qZBzib4CPZP8cubeAklOgUGkn/xyv0fVP2dc8ExLFsgjDvRH0Z2rvhwzvHfWQ9IlxaNqX1wcn+CvEAEtaABuBqbz/BWlx96jcG1QEBVYCWrPepdn49I6SyiaeN1RDR85RPuH1KjAzZargqV8q2BoWbi3uYdC0fNaU0hywD+iBdEN/0BcjuHD2r4+G3d6xlq9AYNAS+6SPR4ZbTbJfb0IdYlfb8P/gjxny+lnQK61WDg87LeM9LEEhmdcvxwnTsvorNQ4DRJxdcuIGJcg4yiEbqFcQnClyKmGAERBDcUHV6N8rKHgmbI3gS6mkGBua8gwz7q6zdXPF2+YjCPpbjqq7H101OA2gbNUqBFFfQcwqHSNXVzYPpRgrbn8ZBmhQBR1HT0TuqUbgpZ0TymHEHSMz1adnimkz0rXraEf0rzX5tJ3ZUx/5UJCGM8kgdANbj/znqdbrG+f3hqh3yjm3OhZOQ27C4dbDaTLMun7dcuI5aFwTYY6LIt+RL1Nlsl+qo1OKGcKWwsLTUY8Ji2gajty63SJk6Umpz+mGUtE4ZhAgiXsT0AZqzoZs3VTJ0CiO9d8RoaXcOnombTo9WROPqmYZomWXJYjWSozZFriUaGowf3khbvVtASGKET9se1zirP9ZH9N/DHmOFDYFSgOtC0djFfX2s0edGVcqCsF0a4nbqRXqhY38jtdQZjjszmfJ81ywMutojNSPR8ygrfUVOYMCfhw7ehZUWSgAUQzypgKDBzbp2tm9FXi7lSF5zTOSgVFE+s4A82gWypAWp6D2hp49Ho4VFpel0MleTqxsgIqNyqDlQQ7Ag9RC9jk441TwAaU4ArUiv1FwbBw+6j4iKjyagZhwO6ZmBfXI1FWCcIZ1O8qJzVJzqB5rntybkxSCMtb4BUSLs8Oq4IZANoxxruOeM/QDNMHfCtAWp6lmpIU4MrpW42Sy8Eg5OSKvWWFHqMoVijbdGn1o3C4o/ENTsWN0kYNhzW8YYguBj3rUnds6dvgDHN/WyNj42KPrhNLRPHQp6WARtrmQg3gkIpxA7bwTutzwICGR+F7SkVQ3SPR18uOT4wM6yXuKmt78xD9aVRDq1DOSBueJJR6OhHR9vW0skOdKEoWWkhZx2RIk+KRuHSRNI+wvB3d2X/CqEFRJ5mSm0Ihe2pKYlcTUibFuZK1I7wlWEB6xuQuCD606FjgvGr7YZY6/lkplIoC7hHPMjv6FSxnVuEBqYamN8b2xYbdPpsIeral9jhvNnePm83drgRddmwwitvr1gQ8k/So1YogyCHnanMx0Q5EdVG10zNOBI1ULTlVoQ7KZV5zFaw9fcz+vNXUOm2BOdXkYlsCnBSHMfukxA4uTCz2cV00MXeOlhpA/2X0jil8vR2c6vj1TNShlSq3P6FO5BrNanaHjt/4icBNOoskDl3mwgxmZ7SyU3chX035Y8yOZ+xXn5rapotYD6/OjRiqZ9qdcXN4Ju19G5ZYbnHNXC0Wn7o7vH71RLtPhI1nksqFpVmI+Q+SyzAN4y4UfJeQLsMzCfVKAUh/mAjkk8MjEbjOZ/U8u08NDM+0Gwjg4qlGC+l05bhDYmO794rUdCWsNVR/bkDpqwJc5qFpBRhvuVMPRLvBlcUzsTTr5IUnqoeW18dhuZVWuHk5rGSFojxIdyJIHmV5TDWaZfJdKngwz1ltbbjmEhrvrtIdTgaa2pcgonqS3QcaimfsxHI0O9Fwszz/EKr1Tjg9ze4Tg+CZwPRTtlxGAXxDHWu0hbuFIstLOG9E9IzxhtdhymCB8lJTLcwFde+dp9h9xQDlUGZqolU5mdv7miGZSx/1dhVVT7L7pJjxTO9MsZ4pNCKvAwO62ZHqKXYfcBmeMUI/W08L+R0HY9qL82FrHh/dMjwTkq0mDCV8WbgVTz086UQ9S8UcS9AG2egXcSuMvS+Vam1OqPe4lwrolmelpVnAjlKjHPMG9MboYle4LPlzkQjPBD1ZSz2smQPFOaMVby4jXEvEtoQvV5IQXgIoruKE3kWVpuJS1LUEfyWyItHlEqqmfoHwLR0gPP2QA8LXEvIskbQEilxYS7oknvidRl1HPVVPclg9re5Ltpasu2KR7Ghf0sKyJ+86XNBXS/BXHqJzlEMz3+F2zHCHA9r7kYRriGvpH+05SNMlPK4DLwBYwpqscw8HEbCHF31VS0y5xKMf3CsAgzyMDXxwkkKhCK06VFH15LrjZSif2viRkbTRi0PnV6zwD/BjdpuM5Lpxk0vb3pAzzdYC1NZhqujc33eWCpmXZ4fbmCrQWqH0yL2XYvTIgIXdhEKN5LoP9zZDZdiQos9CAxH4e8nospMr+lbPrvuSGtGvnHpaTD9EKj5H2ovk8NC1ls+SCsWeJSfUpjVwdWCjDdAFo+y2GMpFD095VXAK7IJlBRFJWloQkeT9iDUgdB8a9qb88DkBLq6k/LMfTQq2Med21JCBeYjKu1Ekwy1QYPTgRkqNAKfLL9UagC6RI4n0+5SkF1c0J0Jmx9KLekN1L/W5MzqJ7mYv2qKQ1Q5VVnMeevXEuo+VYOJ0wQNxKdzwQLQjjW7hfl5FE5l1I3cQ9JGml5ZwkU80JHnWEnrZm2quLWRg4veDdheml94Y47kAE3MN6ei4d3qm5Y8ZNDCny3iGyfTTE11qwxHpo0Z+P18L5aJoLEik5d4k9F9SdNoA0XSMqqM4EszqyXXfgyftL0DBMo9rRdFfM9cKC19b0SLeJZKBN6EmaLmbLLWGJl3rZ/ao4eqpdZ+yDIjTuesUVK7TyjLVQPsU47plxsecfEKUIbkXcPIY188GGkg1aNsOVVI9se5Lpgq/QlMmy3KWGx2Byn0Cp/gmTGpbP9ndskwO042q79EA7FHfoxTvzrbgxzyvZRjdzIQlXwuEd9kJp+crwd98VC41SQUyd3IUDFld14lHkQu9RazqeXWfEgY407cYGyCczJVJXI0UXya5bpnqeXVf1jTS+By0tXVKfeRMDsvhdE9lVHtMvMTtVemUmGTWpwVF9Gejr5w+5Vw9rW57d9eYKYFpp/WVZm6GNazdFR5qj1mXoKZQ62CbXCpaW4wRCbdQ82bNZ1Frj1mXeExDnUfwr1g9hOughnUpPpnQgwfzvJYxSA+gf6bdGS752J1xHp/n131yQSBLX8Ll0WxyT52lHErcNbwr9LDrRtr1rUgsim0ti7qRO7V4O5y6J9d9EnDClS7p2G8rr83jgRbXLlN/xqzLzc8CTkE7UFVwSk2GIoD76d6ohL1FHvGimfkMPzNx1a4PHydzh+cV8xERuuHISbEJi0c+oPaK7GK5l/gy1FVPrvs08YAqXXpNBTzJNw8woClyDsTDlYLIrRsdM0a5iGMmsxLE91z70O/P7VgiqyfYfWnzmhVHkVGwxvNJS5XjtriodMTCUdze4eqCXVeHGICCoqKwq6uPVs+y29+TIjEXkUJyWZUvgl1TLcVRm1XPsfvD9vaXQNHT7aCb+3TQLV+yrTMkXmIYgg/EWWa6rNYXBgoWBawBpDfdSp/rRsyRzs7+RQONCwZCJfCKk2fXfcNbAFxk+NZYFszQp+4WzKCQeHXBDACXeIOhx4SybUxzqDdzpatDvbr38yO57kPa3Q77W8pm1ZlxyJr6SgixZigZRfpZUiE2kei4migdD7t5w/FM1siuG8moAXBpCva1WG0otZJpYHeJPb3ueLnbp7CKrHY4GEuWkF2KmsMHtjPAc6NoouefA9shYAQ+9ZYOBWObIa6d0WeJtOvW8l/BMzotH7+bNb2BVMSl4CLDbjz1kVR5kmfKxrLDFjhyC3QzOkW1AtTlIQHPXzzPAa3w1WzDctOWPIq8Pvy6caWiVZ7ME4yOXB00M+TKOZ4rOC7xKnPTP6sXUNiiowtgRddSgma8e5dXQOlG2l8EF4JjxbZ0i/Tf/WyRPIbiDiv0F/3AmM5p1DbueBeAyF1r9XaHFdlc4lsNA2B0pFGtBLxZ34iSCVnUFWtGwR0mdSDtvusk4xoGUhn2GwGy29/yCdCH7nzpsRfEUpYx4eSwWa24w0iyG89qa+wwoMG1H7ZgZJYiJ5RcU5faEfkSScqhNTm9q9B2sg/bejxXqPV4et03K4E6gIyTAl5Y03pIDVnHTHZcINXT675c9dNG1jEuUGMZNGLpMQFWcCEKdUeQ7g+s6Vzs6Tx1YY5W/MAY4DKT215sLorbs3lGGaNF1PVcqIppdrcJyP2sFd2X+FZdwbUZU14KO8fdyiKWmXDprh3rRkEdw+Zq6uwSZQ+0alZLnWVXKq+eYHe8bO5TppRBQVX8YLZYmUWh+Gh0h7JRvH70zzgRvrMDiZ7of/qGvLpDzejZG+6VsAAOc9GblIpEezoCW7y3dzzDzVvJCJtLOpNdOviMi7ElbmfgWwplo5jcQL5GqY+S1fwqEmYaiYKF81qalkLK5eHvLkIMCmogENyxsrppIBkudhb6yTQjRrwIS1RqpxyNbj4jzsx+imVL7XNel7StdFfDoRPzjnmK2RB1fjZZS6Fs9ANnOrfQrbVP3LBTP3HD7q5m21KoHD0rKd4FWrsL3aKfXeKJWFsKeJeHo/7wW9SRDhQE+AglV0aDYHPHFDIuUTbpNNmyIx2CkXWoyzkEY6nN5U1bCvjcmO0k7c1mb7ZLuznmuCFtdZD2lkO+5WE4h5/D8mRqM8NzVbU5PZ9k80y6D5EPmNI5VyYNq5Iry8d2bk/Y3XL0WcJ5I2M79YwUrJ8nnKph8l3cxmrwOSPh+uGfA8Weundtz9tB0DzDXssBnRsT8YL0YBkwNc65PD3uQK/dcv+cR9oWhDLPBryoPpZPCUOpXE3Xcki2PCc+tJCVUVNTrGDHEDnrzKV4/Vb9WuTQjcEx06Rz9XBvrdXDBn5b9b+7rr6WY64lvtTSHh76x/UkKNM+7UCtt28nUdFdiUsZfnHDxVFdME6BHCkmJwqeQnc8dE4SqScGR1hCg50DQ3NV16XdSv6YjQA9uvr5CYM4NBDFPe42HdInEVr57LIwQ7oSQJRT1Ozptouia/F6+s2T6M53rfqldMrjMCjNPg6DEgWAtzjQIovuw7Uuvf8gp2oKViOlriaP5Mwp8hJqRJHDLlkzdEVgoJ75BK5r2QDaHjY3vEmP1CRJsVzA4ByrgIqDpgJRnStuqZBueUjbp3QaMhVwR9GqWMeMrLS8Sff8uY/fA250RqPzRFbVUyAxKzqObLkcSSsx2RJFaotuwdhn3BHcG0fhgmzJWedhzg0fLluuBalfzSwzQ4q5UM1VVlvkzY1sRfTPZIZcaZZ5LWjytONu24WyzTPnvjyN9F8yGWsfqD6Z/3r5tH1Kqnne3PGuVBVzUTsEx5DoaZ7Busl3P7YavJVIfUW/fSg9ZlNlx6ODtF+xbscC0jxz7uOzghF9cmIZbLc23rUVqwogYruVpuaZc5/qF/OhZ4EyH4Pe+zXo9H7eoHvi3Pa+1JROEkCUEA+MvTzxSvPYm+aJc18qZpRCl+SWraa3Wz0+a5vZ+6w1QHMfhvb9xXyk0kAkMfpKplQ4oLmS2UKaJRIxlSRsG6iha7hIbk+1Fgm4PRdK2zxn7svuVrRnDhg1japLH+1wX5Xl2l9bCzCXKJlFHXKQzBmZ5coG6sTerjloAeISOf6K5RPzysVS+Qst/1baQ8u/WysSuAQ1RytL8+S61SpkQg6Pz6Ubb54r9yXEx+ToIhVsCqVGAkYpgCLc6wyvKx+ucaRWJMldTgvtgAWwFlohizprhbpQtHR03QUSgZU04VPqWYmnlbqVQhP0s9KSoAz8AxaTDToxi8nAhnfluwVP5dnfFt8XxLbmsuL2iXPY3XyZ1mNNKBJxq3TnziPfT51qWmp6eMX08ONGIu5sLQgYX6GRnXicctye2a318tEJY+5zXgkTB4qViMchPit+pG/rwUV52LOrkDxiCIbxj8LbbbcDwSmmHlyUKN3I43AvEYgnNNlAFmafweH0GdJdqfs7Fy0dKfelXXdXBna9MrCHl4FIjxs1OEqfEm0s3t/cMuH2po2my4q1yI8bNUqdigMrM9/0DE9pN6T49P54j25KPPWlVeLRrI9v5mmDZene3Lvi6XHHQ4+L7iPpe84WrWSQ4SsF11qu3tVGzKpEbuok5Ylc15luyLPorb8pzKJvI7gpUWGSehfUK3jJ1IrPcgjw8RXvbYnMuA9/etHsBfk7CsEsSea+SPoi+zzIiCCWIE+ADXLit4s0i81s5fSmzeKvcCTGjTx6PCKaYSzr4CAWnBwrdBRPyddGKAlFykGuHHFutFhrU4f63BYmDldcap4Xt78vNWw6QxunvDS5AGZzqz0deBvBT3l42OcXx2QTfoRKVG4WnMM2XPs7QkXoWWdJLbbOYpNWGkhzrJaQ/ZS95plxn75QkJ1L/wJ9cPVTdtumNMH0dmV8Bi8lrsN5E/YtFlyCMaHxPChqOQRL88S47xAEVD2FzwS8gJZ8AkjOkk/To8Sb58Ydzzl1Aya67H9HUUKz/4w5vWIwQy3oIcuuCl6nc+bYkI7O41kEsHjR1G0GX+U5LaMnymiuODT6JV8a/eFCIM+O+8Zk/ZT4V+kmDP1kSkULVvdaoRz0I925GL7DOTnQZmi1QRi+K+gzIlkiTfnUcCpzSz+rF67nqacZgnzPj/tS9iLHlKUun7slx3i8hvuE7qQCr/+PdOfS4AYWUxtAP/sZWFtl7oat5Wly31B/sP3ktepJ/rVST/KvKMeMrRUcl0gciXpyk9Lg4J8nl7+OM7iKbV/yWTtPlfsO5DrlT2AX2oG8Zgs8AHl1blDkyo3nNaw9lNRNtqMnX23b0eO1nBL1ZLmvOqZjFTcPfflGzwA4gnlCozqYTfNsuS81JreRQrb6gSORUBscCYSIxb3T+ByoIwrn9h8clUZWs/XDZQHlejFgbYUUS4wZEIBJyzgIgap5Z+tMoN/Dof7bCmDcSGsqjcqowmZzPjMmFii2aeZvt05A4kZ3mORIKrvz4JkKJ0fvzGgXpEWW3Id/O0mTBdJG2mQx62myqN7S7FgPCroYpk0QoZW8RKEzXDn2DfTpIOdtxyxLkHOufWrCZpyWMp5ooWpPeMfPWvWzhSe1Lx7xbOa9Ngw/6GZNl4NXtB0cmIcYvCmAjxTEuPzw+PqqQf3gneapct/4inQ+Yz7aYDzSTvV4V1LT6z7ZFolyH2bwIa4eEwaqp3dhW6l5E++Jct+JlHTIHBiDJDBZioxeQyNs7pO/C8WSUHyhU9/vORl3b2cebVXpxWe5I09uTCRO0+k8Q3JIc/wyMyjemZ8hiRP1ujPSVB+lDm7yg2EYw64xkyOUu9bnliKwn3OJuNdhKfOM3h+VqemrJ91z5T7gZ+Y+F7QH3Vj1htZq1fL48LRvCbx7rtx3aCCCVmZssLLgQC1+XuN+hyL2FLAsz97OrBaU4pAW7RiJ4+D0aBW/ct5TSLfEL7jMf2FKMBGFRX+0gdg7O+KAniIQ96U+HzJFrd4oS8A2Ip/NmZiePkNZmPtcnI4+trS1gazDUfgiGXfb3XoKaJZor5ahtyogWxo/LPQSDSMUKa73qnvC3Ic4GeznyuE7LQFfOobsGCmUz7t0T5f7FNJAfV50yukhKUr1cOb0fDvweg5olhj9wS3RAYTTOl4bUAg2Wna5WS3dE+W+oS1pew5tgX1Wa1xGPUSyXL6+C0W/Jb5SlavHtCEat5Mba+jZ5YfE9RxguNFLB+9557plOZBQiKam3XZ2pq9HltwomdzkD7Ow0pk6MOETGP/H8KiKnqPTEkndxxkEi6G5pjtTu/xLQd95mtwHggnmcx3eirwNsvbFeXqSNCvOIPcc/JZo3rdx/AOiam35wL3amA7AJK7Ky7GJKH7ArfQRGXSmeusWmj90XgC6XNyN8Wy5PxBoJwENZMjPPiWiQ2oBm3+VQglo3Mi7m7JNVmAmdQ0fusRE4i/6XGWPnLkPF3cRZC8SNgbcWungtpq/MyV4Lg+3O1pERdaFt0cqRDtZxRHEQN2tFVn+4zs1Zs1hvTBMSkeHd6X7K9PBybrnzF0vQ/jh+UcHtDUeg4hUw9ux3PDI7ilznxnKYEDn6iWSwq0KTtyNiIPXsd1LxTaiwAZDGl/aUCo3AE6QMi3Xd4f5L04UQvolErzBcWZ3P8MT5vY59MKuW8GEhA63wZCBiVwb6A/lzsKis8Fy5kkyjp0NAKezVg3AlshLkpNoLKZktLm5tZsxRZLnpjt6jf5LIFLKJygFIk131jEwuhsF+nbJgF5DtShKO2sWPq7dzmz7jvKezWoHWdu9z5429wFhltP3312r4hinVRFQ9quUa8zBRHJvZZ9D8fKMCzRCtJZdZNs9Ze4DmQMDurQDZqbAm2jbcqVHcE9dVGGvnytGIEDPirhJPORRCqJ7ntFuJKGX2qJH1tyHLX4eV7blQ+AC2h3t14cru91awYGJAooJ0axCMUjKxBI85skKBtUBOnuN/kv8els7P5DfSpxtul6t6JjuiOh6+5yCAQ96lp7Hxf4eKpAnEpTkZfIOnyfOfZkI4T9xqr+uM4VpQiGLVK3tFXILpaOHw7zoqNuMMY3ZepPS6bUAce6V9PbZjQEdOk+GajzSJHeb883hw3KIx96CD/O8UGNQKGdbKjs+5FONMFEmrXBMoXT0MMb3Lx0JxPitgXJ78UiS7pK83dPmvvS7tFVGynBvoREopdNbCIC2C7RaKBxFU0ManyHCPfXD+4fJV0bunTyzZY+UuZG9Fc4Yc+zdzld01muBDbX7u8znxAs40AVozE6npc12mSdt1jy7cO8x9fKyoAs0FKhCvSWojttE4O0J8bvny335H1EdHdIrDt9e+3HRDZ2Nxb666kPv5WPZj1nQmVCW8wjcGc/IRcfR1rsPj3ooH0Xtgu/E1i9ZojgzY7zIueeL75Eu9wcWdMY2zHbmCpUuCXGJjEZ4ocjiEk+qa5RcQLQyLeOc68ksDQ/s7J4v92XrI3XPTjFjyzcZmLFOlxqL+QhnHscqRvbyKWyEIEteZtnBanCyOMm9UmwminzqSzVUGchvdtgcks3mPl71POH9ocyNfPjbpppWqx5lUB5rsnkXl7bunjL35WZrSbJdeQg7g0h6SYfuePsZC30ElEukgERTnLBugsElcXaiHbC3OQnDLVY+f0AoRt2hmZYJ6mUVBcyvdhpv1I/ZM9CgS/sBbMHh+5/HNavFK4UR0i/xC+JGMD8QYLSMcJz1dDqZd33LpH0EbG6kpoSTI9DH2U8WFfB6I+aa3fW79RHcl2epYfOvmlTtMzl925pOxY/NPsXkCXQfZDWo0LWoxb2uZKC3zy+hz8wtFIlcXh50heEszZgWVnrO5cierKY/JLo/UKEXCUaSmyqyDyXa5mSfLRVpdON9tnppxtirZmT9OxujJMjRbp2mexbdl5G3K3sRYg4t5Tf07yQbEVVugazPkIGJwg4/VSJc1Nqmjo0f+0wdq6t5afAkui/nKcqlQuqKvBsQ0q0IR/C1EcOVzbvn0X2JsBHBdkUNb3XWJyahN5tl5yd49BlTMZHB3LT7SNnGoQ1Gd1pNy48E7jP4MHGYS7dRiwVp1GII8nmMDnjbXJTruXRfClzUS9n3AJqKk3zFvHbTDhe+1mcAv0TPvys0oE0G0S1MNWiu3yJX7zJ4Lt35nvrWdxrpaiz0gJjGqg713T2V7hu0jaStQGvZSg2tj9b6nzysoz9UumF3JH3Cq73aad0AwF0zJ5gSfu/fKh9rEEyILhmKNVmoN0oZgarfV336+oyAYUp0xpogwaEBUgcQNllrp5vM1Vf0YiJzfNOhm5mHKtoFzCdJv3j85lkq4HQfCvIuvWUZPfD0Mx0eqPM9eKyEW2p8NhIolA6lgswHUYValt2/MVwDR1/zYw2CmdElMAUfgl6a1vO5NChsuUvjqXRfWt6xbPIx2RIFIc6EbnTVCslnVSOP7vMFt7aVtHYIXUl8LqErOvTuBvfn3iLmRxcGFigojeI3TxpXDDFG1twN/oxHl7Q+h4Cwo4cHYiZLG+OG3/15Et1nNiXI0TVJUc5c2bHPCBYkKdwb1Y8FCOZGF+QRMouqP+fc/ehPtHe5tUKDUfSIpnZdrDM/dzqsyfTZpR1cmCgFSGjJlISJ2ruh5Osy5kV0x2738YaXzqjS58V6nV68VefpxWsyqussFTG7kYl8Ki0MJi3QQTGzqGt8Q1ufyxZHBt0f+NGFgaXg96t4ktpKRvUFUIdL0z80upEmf0syZ4N51+iBVjsDyJKf8I2v4z2YyGqeTvu/IGt7Iz3XnGO1/LCTkSJ2N4gCXdPBCnSsY/YwQN7GE2Bmxl0ouDDR+pHKl2zA4P7lhjHPfhqIJGLOStGBidzhVbIBbQ0DsmWWJDkomTpzFgrI3SgIq8mJlzN8pYHmaVpvrs9fD8+iux4rumwIQO/7yDnnk65w3lTjSAG4G2Nc+MHsfhbQQBiFznDDnZengRgpJmAi9fvUljVODyoQSmapm8Ox3UkFMpeo7lBHYeOO0QEYy21DE/TAr14ZKeB2H2HayglDlwaBupR8UroMLMn1XoycPn+7nSyXs+sw+MWYQmIssfJ2JMgj0ug+PNj5S5nHthFzFXSdZqvdNtfmO3LE7kb2ce0wsr5jHrFn5b/iaWGGp9B9x9TiInCgTLrq+C0DjRjqt9Chfbs3CriX5420F7owfXWDa+jSgqm6utHIwWmJnw6CMiSGBLeFzirKl9sCiSV3XfL4ybdTcDrI2TSWaciBjnLk8naWjByALz+woU/jB85G7JSWaV8oqlssGHn9ZH/rqwhu99y6lc+la8nfuUih+3y6LUmz1i81G3oMNH06hmNrGJ5A93HHWJtkromlw+0Mb0CzZml7a1ACajfk38CDzo7rTHzdmTMgORlorgN2lOCqBAgVU6GzPhH2bfaedmo2rhpki/6VIntL3Ju1z7XBmD5eCgGMQSFX9faphFpRsMD18OdmEKBrAQtNcwYM6sNVU8ZDnxsJ2vsXM8+BpEopanmKE7/RcLHZKMFRiVTapNxZL6FAb+g+0LYYui/QtowSKkXBuQcJunQUgC9JozwoOBuvsB2iZHjK3CfDzBzoMmg8JcNaD/WjDEvQ3DtFyrl4RlunVXGQAgTwumhIS7Tcm1JjlSiSaSfte9yH7rGC46jOc3dv5DJq8FFCihI06FmbTcESbbTVvV92Ps9wMzxh7nrXKkZsMnSAZcUNGb4QtlyOctRQKApKhanQRav0ZKQtHbMa+g1eijutUC2Kco4uUS6uulQN4kdD6fb4UpEv9wcudJnlm8wnBPmnQgla0Cs1eiqRxv545MxignObc9h1NvCMs3ieL/cHJvupYCX05uLUM2pO7tTJErqy/aifq0UgRO+CpTtYSJn3IOpuXsaVUYOz8tD0b5tKCho0FSrU1lWmsp+mNjxb7sPXIFzoSm2amFqMYsvteVLQI3bTk6OFclEk2oR/pBQ31RA4g/MY7Vzmm9ofni/3JbWEQp8y/YiUic0SBdylWFe874UdnjD3yd6BEl264lMvp10wzXraBbuHIw/PmPtcZ6ZEX4rgn6avFhoGjRkKDYP3I3rO3PHQ5iD2EiqCVMxoUVC8zGghKHZeSwtey0NiPlQeWl0GHJ0g1zeuhdlcxWF42twfOMwh7UWXMlJuwBNUX5Xhy9rD0+a299yXDOFF75yCBYvA9NjdyM5NbAHq8lDHb2l/wsRq+DzgIHQpKQDq7vv0z7OKwIMuMQfQ7XTgC6G/h2eiCfjKgSfMfTlc6Mx4+APXYnTqI1hlVOUByHo1Xo+OS2QILzqgpoC2UxPxffTTUwdSiJvTGD0Uix6K8GpEsNYnNvG1jPlxBMelx1pRfKmmbZVDpgg1MGb5HPx2Sc7hKXMfggQmQBdqGQBOSQp2F4KTc+bV83oNT5n7NLOCAZ2t327LtG9G+lWhggKMPAvNj6UwEKAPHWG/zLwXtNkv08MeSjd6SLJEDh56wybNLjxnqnEvwrUMAJO6zIEnzH05XLLyFGX4GcZWzrpXXQ43wmV4vtyX1hIaXYb4pmXTOudM0+ZVre4KKGPE/EokGs86lqLfgVUb0DnjROx+cPIY5WOKGvTnWZKS8GBt5BhIsGzk2FjehkbG3HhlyCthWOw+Q8LK7GdIGAhc/EIhx/ID/bmQztHV28wnNZhP0U/RHj68HqFE9FDFdwFZkwYHwqyh43peK8qdM+6sfsI5Vwysu6F1ba4TBVUWg47uXeLImRvFE0pOuMYvYXVFR8cZYu8Z+obnzH1Z5+gK8anDBNNGGrwE37SNwSV3ocji8hKgyxwX4FxUzOf8Nno3zwYzZkC5RG1Xkxw4tmYhSJ0nBMnLVULHjF5LXCgbpyxaqmFxJ3JlyYlBXW7m5pifK0SgP7cZaOOSkjLPppZ1mmehHJE3N54UGpFkyjucFRvg2cchGWpl+dBvhlxLFE/6+Nw6Cu5JzUsi4tJuz+FZq8YMOJdoQ8l7l7He+WRaGvxizbRAnTtXypPmPhAeMKBLfahJA4F6UtXOPPsWjuE5c9uPBOisz1G8LCcPXE8LBxzQK+SeM/flEKWjGcKDTz6LLlV6LWcpdIq5g4rJlrjUFhAWqGmGpcxHtkoF2Jkv9mZExty4vWYues7SKyxiAF/aGty7P6qVPyYBmQVdGi86GltsWDzdP0vl9+WmdgzPmfuQAzENuvQ2o+cRtrdhQLurVnBi3i0WfZe4WFWM59KqYIFYTN9UkFxz0IisudECNquHImkK13go9atX6y4tvCJQN9KzdxtNglMGwyHPAnGqYXiF5Wlz2/taQyHbaHtCGaCiEWo4CFXzpDxjxTpRZLOfBswD18npuk7jdl0n18g4ViwURQ7zZW3lcFeM9gDVOaM9QBv8XWp/NhLtUIrykBXVD9x3pkuFvrOxYw4mkmon5THP3P+UgWd3sFHgU+5LRercSCnalW8RqKBx4GbbTgpwM7dQ8Sb+YdQuoh0Gmr/NbUR+wdzGHF4ploleRnTpP0z1goraMmcI9/GCa4cnzv2Berx9NcnpmoDTv5unTwXD99xxRxq6uLkudVVUFJYV6y/DqedCH54x97WmZHRZq9OdQ7J6AA7paG4xktwtFMEtkcd+6hhs8mPNDSod9JjlZCunWyr6LkG5kAfPRZSOkUTzqyGscaNzc+4OyzV2gOlGh4o8eCnTj5SOrYH3qESSZK8dxgyX6hO8hYnQk6Yr+yUDIG8mGxlAcaplpvyxyAcidEklUHxrwcNsydrbUTi47e3Tk+a+zic3w8qgopxOPw9oRa2fB8PV210r+C/x2IdSLU6wNOn3K8VQKcxq7xaKhaL4UloMBejOcN91t4P7zttNPJopthhFbnZlze0k5daqm9Y8dOOpOSjQTMF9+ZEEXVRdJ3+avLANhpHlsoLV0zTNFByYaGRI6XN2X9O3kvbsRgrRtgtsZwoJl8iZOoz2YqETWfR4y7cRGfUjd06R8f8lQNcqfTUwOl3kZVmujLrmWSgHiG5MCU4mS4cITcM+5j1OALKXiz+mZ8198IpMgL50ku+hr5kUKJpjDXzudTamZ859w6J5olHg19nzXSA8cGmJ6Qcuzoc99yVBZ8cFpOCWCsL0ZTWeY7jmqempc/d/wYFeBK3N+UCguWbIT80ddhj6ox9u766lJ/RhdWbP3d3DtYtQ25y1Pg+IZg50LvtzpKX1R4xzyTZyI7tqz4zkuc8W8a1l4tiEl7fXKt7JA9mol4fYXxRp7JdOv2KzXlDv3b6DHzb02vXp6XPfiXGHCB1QY+s6xMj2O0fZXeQS0C3xqFaS9D6SXRodydBbI5f1U29nyZ+3t7Km4JDLVzT0BIGNjuCpILCpd6lQNoqHDpgxM9wtBliXlgO+eiRvsSJ17kPKXa2LmBu0uwUPZwgBBw93qTgnOlLGNxUEVEYNUYQWS2OMr8NVMGb5jM0FETqz5XHoqKqqVs51inEfzqmeJVSNHm52CLqomHowIBPylY0Ebruawyzzs1ONjrsmnnBpZ0bGQnJKbXLzXGmzrM+xEf6ZzFkACa/1EINs2HqI13JR9yzBgYkGEDCXwy9ZjV8fA3juvKnb6D5r+iyigLnItNPGuZ+WkPx0WWI/HHbWmIEJn5C8d6mTzzMkgyJVAwf24nVCDUWjh+fbiLummN6MxsDuFOiq3uXwLLr9faUqfjVtaVrjTMlWyIJf7VRejb5LXEg5jAqQe5oPRABhLSqruIzCrCH18px3N0LAepvWYCssmddyWCqy0wU9hau1RScME6iNviIbEjySA99MT6L7Ooykz7oCVw3ZyV66FrGy4JbOSoHg5eHXx21QCoZtWdg2BPgqSqG4sH3WUDOKwSMKlgqkpK1oiLU4Z2kEKOPmK2cLHkzkc5CcvPg8xahGsu2veCTXbJ9TL0yILuC5YUXIjmmL1da52Y0ZWXQjz0Eq+j5MNpNRH/LV2nBZHhbdQFeCeqD2ao/T20dvtK23D/2at2A0W3BdIn9YOsx0QDulU8VaVtrGW94yz2yhZBT5JVAWlaw8A9QMsVj6SXdlB+OYLeBdIocR8C6soOqyZEQhYTXkFCKQ7laa4eMF4hOcaVmmgg/5UKmHfMjH/jOS6UY+nbQ0hERCCYwCaCXwjAJ7uH7t2UK6JZLEoDLKVd++TcZ5BEA7zvVFds7+E2K6nCSryyNlp02jHO00dOXq6EGmJ9R9t0c/IX3fSHya8zpHNhYOdHPcxOeMjLqRrYs+AZORobrTbVIGcrzNtncp0WcPFaN4ZeAoKUCb9LnGaBN7TUalUl3VfvbPwFymRC9i15fWRBmQaSLVnGxGQt1IzQuoC8e0e1vMhyn0Gvu34kD682HTje8zlNqg8OAWpcAFPtAYowEQvKol0ulGVYcsuQCq2U0djnWP751jn5qeSvel6kLv/1TAjMplQ93Pan2leJcssulGnspsNBe56OiQglqKa01CotNpqRFxuS8nunR+gNFAa3OLZF9rT0wZew/dE+q+VE9FkecZKKlk+LfUDuSpeoDY/Bmlbik2TI0JfTHkEtWncc+9CqbjLBa5/4OgX2Z0qDmj1XVIfcwUcdmbSKv7nFZTBE5WMjQp0GSbD4WR6v61PgN0QY4uGD+EQtyi+X0zgiO52tMcoS/6YaIftjsIlraErd0P7VeTWRVnrTisKB77tFhmAePQNVO9zqxbEMu5AMvz6j7oG9CjyxDQrZMRpgNLgB303hpPqvuyn5JJlVPqh74os4WphpdxFuZh1Y1c3ZKf5HaUzAIVKGtQV7m3bwaUy8Nlnb90lPpeNkKybTekGIC1e0aRUzeqYNRFZcrUOMnzCQ55Pe4aOOTnDAmXh6i7GjQMpVAL04Y0uZy17kWesVQULjI3HCsB1TZUSUM3Zr5UZLd3Z86fOC7VHBfuYK42w67cVovm29HnDFiXhwJ+GLH5zqdGNBAUKdoFrZ7OjM75WcOgPCoZ3dpNnxcQ0B5l5Yuac67PGhTAEU6cDbbtWViNp1PGfij3nAGtG0kvrT4KyHdmjqUavaB54WEzkupGmrSWtHmnM/KOd8dtEUZVObzr4il1XzVF3nuTxsBu0l6AYz3FlOVfqXx2rbn/X1zYUQ4nDwzXNprR5N1hz6f7FDOZKF2miY58YPsd3Z1KOAvc2CWcnZFPN34+cuH5DgKDZQn5lG5CvjvY0/Rsui/XGvnvWxzPwyvRMOVEneFSvafwsOlGQnnLLWY0iQIXMYDe9tiLVL/d7iIxXRSEqZZ0T2kD5JEQ2bkKrbqGtxn5dJ+TWkpLgDSJugoD83RUw5SQk18B7hKNFnf/C8A2H87uvS6lEsaI3Q16St0HlZ75rjKXKt1Yg5KDHtSg5DJi+ywVaeki/7dOBMA10/tbgJbXlAvgbE6mPKXuO5uLTAFzLnCTobZL7GSC3rb3q/fnYhEzpcukcGhMDZBXr9si5FY8TcL0hLqvsUHnPyfMdKAALzXL5c6sw6emdgDpPvTfXUcfg/dEwe2Tmcf2iRyu7tzBe4nBGn0whuWNeUYo15bbiYum7+OZnlJ3v3IwNQOAYRAnkWAlrJBI8IS6L5EjXVHhS8RMGTqlUQVdfUu12/vDnlD39aa60kaju5t+pDFnnwO/JT8HC8ra7y0SWXMikcVApreK4SNrZweOlrx+14rjoSOZdZayWsHwrGV5RY4aNa94hWCl8lmzoLwgiak9Ti9X7vn0cnVnrFaKMJfAd0m+nKQRoL81YsfwOu3NxnydfBeKjktQUCQ1Yj57OtMENjgJ1FZtP+1geSrd16azwyy7I/dC/YM25j4GplZXtVgPmW5kNDcyOgZKaW/gWMOOHHWx6l5rfo78OEDkji5BIYhjtrgpRRwz32O0PJfuO0+HO/5l5l8rBkUfYJ7tFiJ7mO7yXLr7UVPD2kQLRo6pbamSQJP8uceQrxyLRZHaHEcufQnz1HgaepC1xoMMww1BVg6uS3T5SWoULNEZT90RTPpOOsyAuivFJqNIRq4ko/sMWkRznhUauitALk+n294Xql/MeVPzNA2cGSAjN6ZP//FyBLhE/vAmzRs9M+n04BYQt7ExXUlm5ZhxieTvXbISG80pKlC1L3sljBrfbqVYKIrvNKwjaHIzX87M7uSqq3M5T395Ot134hdCMclwpCn8tOTaN09WitTncC8W3Zagh4GHsWz8OLMkYSdcJ+xN7K8cHJfnxbZu8s677bueebdopruJ/VWC3xINzUqSpszjZAQLl+WsmNLdZKz1EzZd8KMLCACydai1MInVqLX2dlXfVYLjEnPW5MBzAo5vTLESiHWn+PLAimS6P9CjS04iCfe/iBUYH4wy0/ceL8+l+861W00TADVZeyYPXuynYcap9EikGy8fwExCtcfITGs6BFZiHoXnLnIJbkuOLzV0sE5mllQ98eSGVHSHVVueSvcdUoGs9hZge7ZYe6PQbkCC0V0qb5WQconWgd17rh9DT6lGB5pOcVhAi/oNBja6H9jRM3czlypsZqTaET66hElebiDoqj9Jveyk7Tx7nfG5MNE2hKj6hMl6qHTDDkkV8Vmho+fIVRr7yFWqrm6/HibdyNhdhOIeNN3VwDxIUWgJsvp5a8vz6L6xNm2JXUaQdJinOPopG6KYeZ3P5Xl0H+ZFsKRzK/I45Ktl5jOGA/lTpxJqzLpEavOu8RUph24+R0cqLhuieXv1WSNCN25vyPTNzTMvxjrc9OKgZwdJWJ5H953CQafJgG2MBuIKzx1TKc6Z5yld9SeuC+syyQ7ncoESGBJrQAkPuF81wFyia00OtDBUViadLkjv5wuYAQnD1ZyeQ/cZzS3tj5I026dDhaKodmab7elVlefQHQ8HBN1FaXuicNQy6RUe8ba+p+LwU6tFeG7k/LYhRrtZdLwzhidYt5KnzlmRRPehf686+1iYDEbFNm9KAoHRzaCuFr2XH+nRZZD9vtUZVAqsOlM9M8FqAejy0L8frZ4K5z0pSicntEZyPOfCeCrd/pKRD0kFNSkaddTpm2/nWeG1QtrlYbifRghykegUcBwkOgZVuLvsuXTHf8GQLrU1ZfOaQQ8XD7VfLfguz1Fto9Na81DirSms0ZIB6DertHpwXiLfVE7KNItUhjH6lG7DM2Z2DWLLc+k+OEFwo28hrrrkxSD/PyBWz868esDoRo4S9IwKMReCYYXPUdRyvCBG/t67HIl0Hz7zqoDYVQ+vWurr8Kql4nCQy3Pp/kD43SxyB+9gY2jCYOL368j62RerRw8mCBX3jfIYBkxPxM/U25EjWn25NsYV6XQf8vehVQykmNWQIgNq8L6ywxZDb3RkdyJdzqhYgEXp1jdwcNBv/uXemuqDv0ioG/VelmlGQnQkNqvd8TXTpzh6wOk+57RNFATmy5KA5PDSpFn11H/Lk+m+3P3FpgD0IwmsaIwLGWN675X5GZcu0u3C/AefWOt0k4mmjKbNF3vWCL5LpOaSKirng8ilsyA5gfZiHgktbq3P1C7gRpdQa7Fz31Ju3x6v5sm5lufSfa/yLY0y5bgeO8brKBQLeb3lDisidV929Mzt7QPBtdoH8qOMJLFuNxl9jVAzijyzpIck0bybYRw2CA/UuWbs7lnnM9YF3OhKkLh3NsowCrub1bGAKCjuneLk6MizvkwU0DYAuRgw6FcnAMzT3UnF2dHx1LeJQpOwW1Eqp75WQo/t8kS647k3XCJlboLUpvWCjFmGYRSQYnc+mmfSfWmVqlFHlyYc2BJtoQipx7Vd2WHNz4Uj5kgXntn+bWTrwHkdpIMTqlk/hkegRxfWMPaEGKLrKPZg6106dga0y8Oz3r62VBx45Olao/jsC2oat8t2RQrdh/69W9UWjCcWujMGyjgqgimdMf8StzcU50n+VcLt37VvP8ShSEvpWesnHLpAXGzhLDkt0hvMTHaVR/F2eQacbrw4XB3lRtR8apkDhJna/Ibs53CCsP0OHzr5LekzlOfGtNT19qnra/xWwLzEhRoitKRNtrIOTL0amrm9oVnRe4mU5srURY6JBQ3c+6Z1HqT27iGtkHaJt7gVGx+VjO5touRnA9f7dLw8a4WKUZRNuqnSFVT2AScAyZxMG2zX9LRWrBdFEnKgAGSeMW3J5p7stU6Rjo7eJTlW8FwiVS0aRoXVDm1FXAjOxcdZDCC8S40QPLzc6FKkYwYlOXOYTm03zMvnElZIvDxCoP1FyEU1G9vWirGG9+LTG5479yUNb8YpmjGjK1vWLBc7KCQrhjuo2GIUP5+x0cHzPC3py0qQI6SVdsi5/ECKzmmzyTPWCpS4o3AYvkV+7VAuilSLPEKaY9HWTh/WBAG8QfZ3dlXftcvnT9dNkdOqZ5JqB52YDS/q24fbO9aMIjd31WrmKtsI+8mn74eGo/hu5hXJc6PZ65phHDzJuMzafdZ6LG8WPHvuGxTxAIjELnWyVPWAfrJKdPJtkGtHryUEIH3oJEewMXerj+dhKE/g5i8f8/Lkuf0lMTcxb906LjKaYfOZTlidJHxmdQEbehac4IEXrXzQRaHutPfHdBKo0NmjhlJSF6OgR8K6fBEYn++GD+zt+UuF3oShgluYST63n/QMDaM+8P8H", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Orders.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"OrderID", type text}, {"ChannelID", type text}, {"Date", type date}, {"CustomerID", type text}, {"GrossSales", Currency.Type}, {"Discount", Currency.Type}, {"Refund", Currency.Type}, {"NetCOGS", Currency.Type}, {"ShippingCost", Currency.Type}, {"PaymentFee", Currency.Type}, {"FulfilmentCost", Currency.Type}}, "en-US")
in
    Typed
