let
    Demo = Binary.Decompress(Binary.FromText("jZvLbiXHDYb3eQrvUwK67l1LO16M4RgIosT7Y0nwCJ5IgaQJ4KzyDnnDPEmqu0gWyT5qyos5x7eqPizWz4+X/vnh8+Pdl4cfvnc/XX57cD893z98cd+9XJ7uPrvby5eH138+vLw+P7nbt8vb11f3l68vd58vrw/fX94e9n+/f8F/+qfn1zf314e756f7x7fH56fHp1/3/+gvL493D+77y++vnx6+3Ltvf3347vJ0/4efl2Xx7m/Pvz+/Xdztw/3lyf14ebncfX50397/6/H1+eUb7354+ub27fnuNxeWkG98uFmScyks21/Ot/1jcbH/2ZY/7ksG96k/wMV9urzdff7l0v/XP18+P7880KLB3T73x+gLlpsl3oQVvtabUFxIY+kQ94/o17FTmBtEd/v1319/e3S3f//Z/fD65fKPyy+Xe1o+8uXLjV/g63oTqksFntzvHzmMz7q64v/3n/+2Zd8huR8f3zNJUsv7+fTJVXj6NFbNwz4p9t/RVy9j9ew+/f61W+jxfRNlYfd9o+Cdiytfvv+Kfn5olUInedUqhT926Ac5rdJcgcceti4NbN5WWr3CoV63SeWLpxufpnlyXw5MnodR/PjbEoTJVzzUd23i+Sbr7iv713YToqtVnGtdy/Ci1S19jzj2aONYr9onaIuv3UzODXchd+we0/hZdufCs7xuGeGMeVpm3bylgDMOL6nL+PR9XzC7p+v5rlWStIpvZJW+F9o6gDvW8XeFGcXjdb1uliy9fWlzp+oiGMdHMDb6Dz9ZP6/rVQsVbfiuCJvhE3/0zRmnVcb1fNckVdm8zDuUXUDpynCuGW6UONZ5Ra+bxcstlpW+9i0i+uK4pmn8FNcNxsxezoVXa+R0dr959wIes1/asZ/zha6rr5YGR211v52ty/DoAYU9lESLrue6q4Sxiy3dz+S8UC4/NMGt0lPaiewKR2xTdttN3LRExKMaYJvGLB4WW3a1SMa5X3ExCilIQ4xd6M4CFgr+XIOrjqZ+u6+uggyECkaPbMlwKrzTD/fVemjB0+wPnBaxboogA0J4QzSFN/BNwhaISCG7BmR+sDGNEwg9qOAvSCeqG2XgCDOYdhdGeRxLlzQ+1yoePxsCnI4Es0VS8piCjr5GeuJiqm5Wsahxx8zSUXKFcBq5N9ZT2S1K1We07t5O+gLmCUPCPI91YT1X3aooJs8z7QEOjTMePBb4IZlrZGjnKuy1wuzaOGPGgsIeSLbiYsiu8MRlkqPf1MY3HjFCGV7fiJCiwbpRSi4PdXHe0bH6mkBzc6XlTe5NUsLosu7qklZxWTNs1N1pHmo0yPdAjX7zzH7xhTr2PRKJejxD3SLVhcy9e2GGB/bjQTPYO1TSrvgB0BV+WLm29BPFSwoXqVTICSr3w2iAr1fHmqfTs2wj48ODc5IYxHPyPWBjF+HiuveNdVe0eJl+YpNulEYhaKz77S/C7rGAo3Coi2ekmxRahPm1uQpyDgCwQgbD0SVZzKuY0Rcujsh1oC0VoqhU9WRzb7kSS7uuJ1geZT0GOsl0TrpVxn7mJ122yNk9eOL47IRHqxuY61WkK3SmPYfDyw9QmkEjSxFGMbA3qB9Q52YZrhCmGgFBSVrdot54pRrQJb1glpHR2xtF/2RwblLENa2+MTX6yviIHg9hnqkJutoZ2bEulDViFQCONXNvN6i3SFEPk0u7XNJtGsJVIUESt+kMeq8BY1cXkoAJjBRD8wcwV1Njmce5UoIEDB1AAXp4Y6KbDdINKnKEGZASaAtZPeZxWUvkzpjPwVeBIzn7yIArF4E4xLjzF0W9bENv0sIetjs7fXBBX+8Hgqueka7KX0KaX/stjzxcVMynmZtki3OLgvQ271R1Cf1c6ksWSW+2sbcq/mp0rN0BKd2AjBpOefXiWM+591BvXPZiQNK0HhNJQDZIN6hg2uhrP4MkSTcjsnPLG5wrPNFPbMzbvYq8ANMfewW+8IQDxWLe9L7A1J77c09vC4Qn9vjFoN58xeJd02vjC28Gp0hXTNBV2csysxe/UCSCs4zwyZOXYnBulb6+TDfcQjWuD2ljhBqsgMZyhr3+HSatm8NTbjRMneBTPP4HuDccQ2lnO7g7cEM3damkWcXgXJ1Kz6q6n4ABycWIe64vzq5mOSddhY1UG1m3rTBVH2dZM+DRrEgVm3qzikqMXypFJeAXKDP4StldOUPeKzVGv8kKYhfG0TBLr9WiXFVlDKzK6Iedpz0qVKP5xaw24ypHZAljNw62GuDhK+QBRZxpPWfeIH8DtUryHjTQ0yHBg8yUw0s1oPdQZWwbYegmzJZV80UNzk1KcD1/aKIXrP+DJ0aK0tWi3KyuPyvZ90idxfoVGUZ0eKoBvSqvpgQp7T8mS31M5fALTOit2u57wkHghe7OqhfVwFyvIn+a9zSRUcAVCxZHeO2innGuqnYTpMe9CgCCDkWAUc3oXskWXz8AvVHF0ZmVxj288V8Q2/D5xPcwkPcAjOueHCUERpT0XLirrOeYm6+ZfaRHpd9IWBosA/ASAlVgVptzi8qPlnlT+w5YHmmgZlCCFd3S9Qx76zv0taPAKnu9DblXHK0Fvoc64x77CHnJ7j5Ps9ikG94RmR0xgqxhhISf/LnPQVd7Y+DeiGb3mBgdGWM1qFcXeVhdbaX1x/IZolPfjQxkMO+1QuPm65jYUVE9EQA0i3OLkt3piJscYMSApBRaallAXTNQtyrZjdMt11mXBsJoSBokkc3kXiWSrPHIbmuAVAO6AiFSJtMM7D3UGuOoBmirs759O+PcKDGdtY63zEh2AnODBo9Qr/YB0k0qMWXVQNaghtkAqL+GQhzWDOxV0XoR9Re6qFA4htgh247tnHsPhcawDwaIzG6fgJmPbLOukkWWIfVwilMe2H5p8PSCMdoZ73ppcyog5z0XwHkMONkKzVK6q/2XGZoblOcwRJodQWiTgu1598svNvse0LFsYx7U+kZVp0qjX85RN8nLT4K4lzAx24XwvyLq8vqrXwzYVZXGkKe8RMIAaMVCs4S37PxicK9qTlPIKPudynz9sML6IZF5LOw9MOO6aTDVipAZk2de6BeDdDU2LvNrpJkASDB8hY4Gt4mJurq8s3CvJBEDnAOsi1n8BgN9dV8w0GXqJ0a9NdgBZjFELdMvZ+x7pUG9jdjh4JHHwaM5Yuf9B3A3v4PU24NTAhbYZdr9nj+1N4BX+GPauIX5O6Id4NeaQeCT2OEcfnW1EVVmrw1gt9fjqAeO3IkNbP69MuEYfdcZ7OFTB69GMv8Z8AalApWs0g2UZG6XMcfjyu69RbxRqvtS6JS7iTCTybAybLiQuHsbflVTJsziepfNgo1qgFPMsKnv6/05+h7gMQ14BCcMWBTweT6zQbuaHVlxvdL8IfRggLuKdBQDeDU6FtKAreaAFoE4vUDEW5EIfLDg16ssbFZ6+m+hoSys3oFe0vCnDwb5HshxB6WJRzhP2uaKJuwqWQzskXNXElCU/c9GFqFwFAzWVdQYJ9Ytc8AOKrsLojr5SzjD3veIsX/tuoXpOlTUwRtZRurDB6D3Snd6GwtIso289abmMxugq/rTjOm2ph3mR3DtQW5XEYbCOeh6tUEWPi67ghHgkTmMDb1BBgwOvbNBDU4eEjg5FTN8OCPeAy7uYjgnSBYUlUZRNFqUm+TzUr6YeZkOElJIFwXQRZtydZReSQK6L1KZFHaqmCTxQ43n2KvKO3Fm1T2GJtE9Sg26R02sb1DvARv36DxLGGj4UAoZ3gBdlb0sM+73O0K9b0gvMqTTIoRGC3bDNT0fu3lidbj7CYc9Mj9bA3zjNfDdz5jXd6Bwh+84FLpN0eTeQ7kx7aX1KIVAxOVogK4qNrJOaT9RqtVBilRxlnw+8xnl6snaSvbY7j4Ndow1qX3EDJ4+wLx6qJG1epc5yQ+EDp9R5DPJYN5DsRGSpMrFQCdJ6RxzlSyGOXTcDxSrRgCMGZsBFDaSjbiq1kgis9caUWSgGJABp3nAS2e8q9rTrH68jWTKeBcKPH7lq1u4e+hQw9RRkzafQ0c+2Yir/HFh0TTOWqAcahZlb5/OKbcqZWej5HH64rilpeAEL/FRMohXvwwzl9961HJIBVMCMTfpk4G8VzrU2+B0lfjPB6d9tjBXVRzZLIM/RCP0Ge4r2eBc9QrCMutS2yyGKB0hQ8pMPZvYKyK2n1tEXliHFANnG+UWBvle61X3gFqVxPhWyexntKsrjWxQivmhfANJOkr+AO/qTjVTXk8Hi8M1AV/p4ydr0O/VgI1RL8hkPUI/xqfpmefoe63YWBg9Iq43Yphs425SCNBm8fGYlELnq3GTnPGuTmLYNEaZIzaQGIGodz9hx1os/NVJ9dyi+2MV6ruuOCzInr/Y+HuAxzGXEXXvLlBx3Zdz3lWJdBDvq2kEWLEsKOxiAK+ufc+h+C3vRU8cZoFMnUtYMeBXz34zYV/mWwjQx4AXMySxFwt+DxXHMfIVZRmDz3z5YuCucMcsmneJilAAXAGnA0jAikm75R2c3uxOvA6ZABQbQiQyLQb4Km7krwhEDb4NXqLkiV45I99DgXEPGoRGNGAXydj1A6iroXE2A7rB0c+haw8TvDJFqgbp6uZgmW6e5msT8l0bbpN6Dr2qHUO3aH/VEYsw+BICJtezWFJt6j2UGcMGpzS/Nwu7kbSlnoFukUAX5nja1t7BajTOSmFLg1vEAl3lhmyCb2tRyVGMWg4vZvhqY696b5UNfMVlvkAF5sYW+ML3OKfeK4XGbRgDy1MIL2JIzVeDdbUkzvyl00yWrpihbpRFBlYN1tXe6Al5+9lGuUOCTzEQ71cLfdUbg8sc+Oixm7oNEC9K1Vv8Hw==", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Vehicles.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"VehicleID", type text}, {"Make", type text}, {"Model", type text}, {"Branch", type text}, {"Salesperson", type text}, {"Status", type text}, {"PurchaseDate", type date}, {"SaleDate", type date}, {"PurchaseCost", Currency.Type}, {"Reconditioning", Currency.Type}, {"SalePrice", Currency.Type}, {"DaysHeld", Int64.Type}, {"AgeBand", type text}}, "en-US")
in
    Typed
