let
    Demo = Binary.Decompress(Binary.FromText("jZvLbiXHDYb3eQrvUwK67l1LO16M4RgIosT7Y0nwCJ5IgaQJ4KzyDnnDPEmqu0gWyT5qyos5x7eqPizWz4+X/vnh8+Pdl4cfvnc/XX57cD893z98cd+9XJ7uPrvby5eH138+vLw+P7nbt8vb11f3l68vd58vrw/fX94e9n+/f8F/+qfn1zf314e756f7x7fH56fHp1/3/+gvL493D+77y++vnx6+3Ltvf3347vJ0/4efl2Xx7m/Pvz+/Xdztw/3lyf14ebncfX50397/6/H1+eUb7354+ub27fnuNxeWkG98uFmScyks21/Ot/1jcbH/2fwf9yWD+9Qf4OI+Xd7uPv9y6f/rny+fn18eaNHgbp/7Y/QFy80Sb8IKX+tNKC6ksXSI+0f069gpzA2iu/3676+/Pbrbv//sfnj9cvnH5ZfLPS0f+fLlxi/wdb0J1aUCT+73jxzGZ11d8f/7z3/bsu+Q3I+P75kkqeX9fPrkKjx9GqvmYZ8U++/oq5exenaffv/aLfT4vomysPu+UfDOxZUv339FPz+0SqGTvGqVwh879IOcVmmuwGMPW5cGNm8rrV7hUK/bpPLF041P0zy5Lwcmz8MofvxtCcLkKx7quzbxfJN195X9a7sJ0dUqzrWuZXjR6pa+Rxx7tHGsV+0TtMXXbibnhruQO3aPafwsu3PhWV63jHDGPC2zbt5SwBmHl9RlfPq+L5jd0/V81ypJWsU3skrfC20dwB3r+LvCjOLxul43S5bevrS5U3URjOMjGBv9h5+sn9f1qoWKNnxXhM3wiT/65ozTKuN6vmuSqmxe5h3KLqB0ZTjXDDdKHOu8otfN4uUWy0pf+xYRfXFc0zR+iusGY2Yv58KrNXI6u9+8ewGP2S/t2M/5QtfVV0uDo7a6387WZXj0gMIeSqJF13PdVcLYxZbuZ3JeKJcfmuBW6SntRHaFI7Ypu+0mbloi4lENsE1jFg+LLbtaJOPcr7gYhRSkIcYudGcBCwV/rsFVR1O/3VdXQQZCBaNHtmQ4Fd7ph/tqPbTgafYHTotYN0WQASG8IZrCG/gmYQtEpJBdAzI/2JjGCYQeVPAXpBPVjTJwhBlMuwujPI6lSxqfaxWPnw0BTkeC2SIpeUxBR18jPXExVTerWNS4Y2bpKLlCOI3cG+up7Bal6jNad28nfQHzhCFhnse6sJ6rblUUk+eZ9gCHxhkPHgv8kMw1MrRzFfZaYXZtnDFjQWEPJFtxMWRXeOIyydFvauMbjxihDK9vREjRYN0oJZeHujjv6Fh9TaC5udLyJvcmKWF0WXd1Sau4rBk26u40DzUa5HugRr95Zr/4Qh37HolEPZ6hbpHqQubevTDDA/vxoBnsHSppV/wA6Ao/rFxb+oniJYWLVCrkBJX7YTTA16tjzdPpWbaR8eHBOUkM4jn5HrCxi3Bx3fvGuitavEw/sUk3SqMQNNb99hdh91jAUTjUxTPSTQotwvzaXAU5BwBYIYPh6JIs5lXM6AsXR+Q60JYKUVSqerK5t1yJpV3XEyyPsh4DnWQ6J90qYz/zky5b5OwePHF8dsKj1Q3M9SrSFTrTnsPh5QcozaCRpQijGNgb1A+oc7MMVwhTjYCgJK1uUW+8Ug3okl4wy8jo7Y2ifzI4NynimlbfmBp9ZXxEj4cwz9QEXe2M7FgXyhqxCgDHmrm3G9RbpKiHyaVdLuk2DeGqkCCJ23QGvdeAsasLScAERoqh+QOYq6mxzONcKUEChg6gAD28MdHNBukGFTnCDEgJtIWsHvO4rCVyZ8zn4KvAkZx9ZMCVi0AcYtz5i6JetqE3aWEP252dPrigr/cDwVXPSFflLyHNr/2WRx4uKubTzE2yxblFQXqbd6q6hH4u9SWLpDfb2FsVfzU61u6AlG5ARg2nvHpxrOfce6g3LnsxIGlaj4kkIBukG1QwbfS1n0GSpJsR2bnlDc4VnugnNubtXkVegOmPvQJfeMKBYjFvel9gas/9uae3BcITe/xiUG++YvGu6bXxhTeDU6QrJuiq7GWZ2YtfKBLBWUb45MlLMTi3Sl9fphtuoRrXh7QxQg1WQGM5w17/DpPWzeEpNxqmTvApHv8D3BuOobSzHdwduKGbulTSrGJwrk6lZ1XdT8CA5GLEPdcXZ1eznJOuwkaqjazbVpiqj7OsGfBoVqSKTb1ZRSXGL5WiEvALlBl8peyunCHvlRqj32QFsQvjaJil12pRrqoyBlZl9MPO0x4VqtH8YlabcZUjsoSxGwdbDfDwFfKAIs60njNvkL+BWiV5Dxro6ZDgQWbK4aUa0HuoMraNMHQTZsuq+aIG5yYluJ4/NNEL1v/BEyNF6WpRblbXn5Xse6TOYv2KDCM6PNWAXpVXU4KU9h+TpT6mcvgFJvRWbfc94SDwQndn1YtqYK5XkT/Ne5rIKOCKBYsjvHZRzzhXVbsJ0uNeBQBBhyLAqGZ0r2SLrx+A3qji6MxK4x7e+C+Ibfh84nsYyHsAxnVPjhICI0p6LtxV1nPMzdfMPtKj0m8kLA2WAXgJgSowq825ReVHy7ypfQcsjzRQMyjBim7peoa99R362lFglb3ehtwrjtYC30OdcY99hLxkd5+nWWzSDe+IzI4YQdYwQsJP/tznoKu9MXBvRLN7TIyOjLEa1KuLPKyuttL6Y/kM0anvRgYymPdaoXHzdUzsqKieCACaxblFye50xE0OMGJAUgottSygrhmoW5XsxumW66xLA2E0JA2SyGZyrxJJ1nhktzVAqgFdgRApk2kG9h5qjXFUA7TVWd++nXFulJjOWsdbZiQ7gblBg0eoV/sA6SaVmLJqIGtQw2wA1F9DIQ5rBvaqaL2I+gtdVCgcQ+yQbcd2zr2HQmPYBwNEZrdPwMxHtllXySLLkHo4xSkPbL80eHrBGO2Md720ORWQ854L4DwGnGyFZind1f7LDM0NynMYIs2OILRJwfa8++UXm30P6Fi2MQ9qfaOqU6XRL+eom+TlJ0HcS5iY7UL4XxF1ef3VLwbsqkpjyFNeImEAtGKhWcJbdn4xuFc1pylklP1OZb5+WGH9kMg8FvYemHHdNJhqRciMyTMv9ItBuhobl/k10kwAJBi+QkeD28REXV3eWbhXkogBzgHWxSx+g4G+ui8Y6DL1E6PeGuwAsxiilumXM/a90qDeRuxw8Mjj4NEcsfP+A7ib30Hq7cEpAQvsMu1+z5/aG8Ar/DFt3ML8HdEO8GvNIPBJ7HAOv7raiCqz1waw2+tx1ANH7sQGNv9emXCMvusM9vCpg1cjmf8MeINSgUpW6QZKMrfLmONxZffeIt4o1X0pdMrdRJjJZFgZNlxI3L0Nv6opE2ZxvctmwUY1wClm2NT39f4cfQ/wmAY8ghMGLAr4PJ/ZoF3Njqy4Xmn+EHowwF1FOooBvBodC2nAVnNAi0CcXiDirUgEPljw61UWNis9/bfQUBZW70AvafjTB4N8D+S4g9LEI5wnbXNFE3aVLAb2yLkrCSjK/mcji1A4CgbrKmqME+uWOWAHld0FUZ38JZxh73vE2L923cJ0HSrq4I0sI/XhA9B7pTu9jQUk2UbeelPzmQ3QVf1pxnRb0w7zI7j2ILerCEPhHHS92iALH5ddwQjwyBzGht4gAwaH3tmgBicPCZycihk+nBHvARd3MZwTJAuKSqMoGi3KTfJ5KV/MvEwHCSmkiwLook25OkqvJAHdF6lMCjtVTJL4ocZz7FXlnTiz6h5Dk+gepQbdoybWN6j3gI17dJ4lDDR8KIUMb4Cuyl6WGff7HaHeN6QXGdJpEUKjBbvhmp6P3TyxOtz9hMMemZ+tAb7xGvjuZ8zrO1C4w3ccCt2maHLvodyY9tJ6lEIg4nI0QFcVG1mntJ8o1eogRao4Sz6f+Yxy9WRtJXtsd58GO8aa1D5iBk8fYF491Mhavcuc5AdCh88o8plkMO+h2AhJUuVioJOkdI65ShbDHDruB4pVIwDGjM0AChvJRlxVaySR2WuNKDJQDMiA0zzgpTPeVe1pVj/eRjJlvAsFHr/y1S3cPXSoYeqoSZvPoSOfbMRV/riwaBpnLVAONYuyt0/nlFuVsrNR8jh9cdzSUnCCl/goGcSrX4aZy289ajmkgimBmJv0yUDeKx3qbXC6Svzng9M+W5irKo5slsEfohH6DPeVbHCuegVhmXWpbRZDlI6QIWWmnk3sFRHbzy0iL6xDioGzjXILg3yv9ap7QK1KYnyrZPYz2tWVRjYoxfxQvoEkHSV/gHd1p5opr6eDxeGagK/08ZM16PdqwMaoF2SyHqEf49P0zHP0vVZsLIweEdcbMUy2cTcpBGiz+HhMSqHz1bhJznhXJzFsGqPMERtIjEDUu5+wYy0W/uqkem7R/bEK9V1XHBZkz19s/D3A45jLiLp3F6i47ss576pEOoj31TQCrFgWFHYxgFfXvudQ/Jb3oicOs0CmziWsGPCrZ7+ZsC/zLQToY8CLGZLYiwW/h4rjGPmKsozBZ758MXBXuGMWzbtERSgAroDTASRgxaTd8g5Ob3YnXodMAIoNIRKZFgN8FTfyVwSiBt8GL1HyRK+cke+hwLgHDUIjGrCLZOz6AdTV0DibAd3g6OfQtYcJXpkiVYN0dXOwTDdP87UJ+a4Nt0k9h17VjqFbtL/qiEUYfAkBk+tZLKk29R7KjGGDU5rfm4XdSNpSz0C3SKALczxta+9gNRpnpbClwS1iga5yQzbBt7Wo5ChGLYcXM3y1sVe9t8oGvuIyX6ACc2MLfOF7nFPvlULjNoyB5SmEFzGk5qvBuloSZ/7SaSZLV8xQN8oiA6sG62pv9IS8/Wyj3CHBpxiI96uFvuqNwWUOfPTYTd0GiBel6i3+Dw==", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Vehicles.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"VehicleID", type text}, {"Make", type text}, {"Model", type text}, {"Branch", type text}, {"Salesperson", type text}, {"Status", type text}, {"PurchaseDate", type date}, {"SaleDate", type date}, {"PurchaseCost", Currency.Type}, {"Reconditioning", Currency.Type}, {"SalePrice", Currency.Type}, {"DaysHeld", Int64.Type}, {"AgeBand", type text}}, "en-US")
in
    Typed
