let
    Demo = Binary.Decompress(Binary.FromText("nV1drx3HcXzPb7kEdr53n62H2EDgIGZ+AGNf2EQkyqBoB/r3Ofee3e6q3plu0Q5gH1DRcHdnpqe6urrmDz//z+9/ePn4+umnx//86fXrPz//+fXlP79+/vnr52+/vvzu6+unb69/+eHxXy8//OP1/X9/9/NPf//x9frTP3379O0fv7z87tc///j4x7/+8vLHLx8///T68l+v//fz1/99/D//8u3f/rA9/pNePqaXH15//PzP16+/vv1rX/7y6etfXvKW+4etf8hFf+4vL3/8++uXl+39//J4/NvPMfLLx/zy+y+/fPv044+fvn3++cvLv3/+69/Of7F9KJuMsbXz5/4hHfrIL3t6H7M0GbO8fCwv//Hp85dvr18+fXm8/H9//evrl2/nv14/bEN+pk0GzRUGTeWwT1pfPtbl27YPuemTJv1Jgz7ffpch28vH5rx8zrPRM7582Z+PeciY/eVj915eBq1vb4yzUqoMMvyZTVV/HufPwbNS2vuYSR9s92a660wPnZ/jw2N96Ji9vo+pU3K4E/14uB1X4DXm41vqmMdznst2DfqYJGeeh36/x8+uKxLHzM/nTPKgKXkT/XjOoc/ZaU6SrOqU3Yl9PII+Tdat8vissADfHiy9dBmzePP8WHX6XFvR6dlhyJqfz6ljVm+ed10w9JiPvwl29HPIIkM2d56HRpqhj/z+pzrm23s/plmW4+Nr+dNc9ScHryRDDH9WN9glWScYd0k+d4nsvMeK9Wa5vf3rMv6uj4jLr41nTNAHPbxprhhntqxTgtOc8hlo5Enz5s3zofN86Dybvdff5yRLPMzJnefHy2/6M/OJIi/7+AfOxD6mQk8l2TGd18oZp2VJP/6hH6dhm+iQCZd0Tu8rMGUZswYTnZr+3PWvKrd9okM2b5p3DIFyQh1vTwzRkA+oRzBy5rjqiO1tMdImkY32+DjepB76orRQ+Ou9LxSNMY+/1z+L631uGseY8owHMuLhTfGOOEH28uN50z0SygZ5RF5vhh/nZdKfDfeNjjkMYigu5HpMpm661OdRq7iIq+r+qLo/6tuJD/vj+e1k4RUfcB34ySAspP0WC/QYLi7c4o1WdW5we/T9uef067l4q75N5/UTcCdtuV6eX1PH9PHWrpt3vx0kcrYXF29VPd8gQB/maO8niJNNUlzA1RS9AGAdvO+aPdxLhLgAHW36M/U7OtKpri7i2nVz0MecBQhZkdUFXLtGhf3tQKWDRN61RoArA0zt8pOWSx4cE6oLuIYCQcA05lXLM91JsqGrC7h4SpI/JRK0q4+4dn3hnbZfpdPpLU7oq7uA69Bh3gMDTolsk+oCrl1X9KFw9YGAMUi394UiwLz6cAvGOfQIOPgkudC+PqYLt+Z75OBMcdgxm4u2xttLytToMZ8we6rFwOrmwy0OO4VTRdklzYVbOx7p8LK8+rJJtZuLt6ouvoqTsuHBmVo326T5gIvhka5FSnbSSTXok7qQi5PFMZ+WK8bqmC7oavrKbXnGNx9zdeVSIDUxSexIhhRoLuiCDHvo9xu8+0oxYL25sKvjGZXhHKXvN8xEdx93EbLO23zQkxXQY767wIuogM2wKrKHu4u8DkGtacOtQmlYZdTaI+C1NVx0U2ydnutPQn93gdeOGeKmkZ/yulyYp+kBz1WAL4NZxhixD851ug+7Dp3Z40Zz6aQGNBeTbvJcCLvew0yCBL67qOug6KwRgRZfqiZQdx91EfyAgJi228pRdDMCmktWzsCTmZLFbnfzcFEXZ52D5kQ+3/BBV9fl1zV/MudJ2roJXSPguTaNCDg/TAhnJgWGC7uqJjqQVwzOeY5zQcpEDx92HTrSoYezIVUqb5QRwC4ckU8TeCwXd3EiqyGB0pNmU57hIy9IiRkK3zjmBBt6uMhrIGOW+nyfnByzjrm7yKtpEGyaOu98xD82iNkpuw+9OMqupmV3oZcleeBPLSuqj+UCL6aYAa7j8iubZHfPISPYBZnEpkGWxjw4RuwBz7URLQ+DW/YnSQq6u5iLCfrGmEsfKwJdeJyM+UqpT0qv6Iy4oItKWcj94NdL3WaMe0B2AZgpgK+rmZIEbPDhgy4+lxaRKzVGIoeLuXjnbXMgfLiQCypNQx9w8Oc7Z0QC6uFjro7MFBwmtPyOxkH6CDAXptgQt3Dl5BOx6pgu6CIuAOA6oc2TvdBYeISoCyBsYl5FxghA16YFjrSo+J6piSaMhwu6OO7DsUKLb9h5DouLQBFCGoH0z5XGX4O+HQR+yKY9DAezeVCt4aXNBV0Wh0yr8GmLqC6MzLp7t3FfgE3GdDEX0yn6k0BD3nhO0hbUFrmgKI9ZbmcJvHpYW9RX35RkoSTgJDCSjOliLshqh90luwwRUF1YRQWKCkN0fqLgrDPiQ66dFBbAChCOez849TEDqgvqnokSCjiKMyWLKQVMF3w8YByIkTP1iZQitMWnHJ0k+lxRXXGbvTXXFYtZfMnFW4zx+3yPDEYhKfl4i46nBICE8GqXkH0OGiAuXI1w5M2SWolbKaC5uIZHceuQMXzI1fTgbMt8KZVKsCOlCHI1+SmJT+OyfjuTMNknyUVcVQ8oKrpRefFcPJJBpexDrqrFEshATeRKF/OvowaiLiyfj8Vxkl3URXF0o0IMBK9n7U4fK9J0ZS1bZog0VC5PzKu8vbzPXWsQhAjB3HUzyzoHNUYJEzDTzZB8O0fEHJUY8XTmapZUdFJ2YRftFNjNhFovDk5iTXZhV9UxKyo3KI+4jnidaB92UX0aeBUWq2z26CtBiRFoR6zX0qFy8CFfIk0XUOz7PIN/45SC8hMVIiR+zSREEmtKJOqC/AQOfGJb85NYkVVdXODVtEzWKLuj+FUTJQKp+Mir6VHSDUkAp98zKArTl4oLvYjpS5zIy3YrLvSqOicVD/qNhE3Zrr+wzgjVobH6gGZLlwB8bRCqgU6iBy0G5VQXfVVd1RWVn/Scx2AO423ig4k+5GdJ00Q+1YjrAtqWGE34frs5lGuAvrBeCVQzM3tETaXqo68DaTNUpNoaTwKQUyO6C1jHgk8MGPswJ191wRed0CnN+a5UffDFoEY3CqHXvRikWQPwBUtlVed+iwEME2uAvhBy6fHMi8eG7uajL+ZsDlynt9CtwKkF8i4k682ZIl+wueCLAFzWuhtXP1+oxp+aD75Yf9vxaSHSPJ9Tx3SxF+843TMseTpMQGwu9iKwCVQ9z/OT2IR59sHXoDDY58l8c7HXgZwexgdCH6Yan1pAeWVdflhLII1ENzu6RdgLjj4sOVKOe559cvT1iPKaQpzEYg5GDj2ivEDCuM9lwm+PGfRJQKSB6glNyqXFkg3cXezFLTFaUpgk9Hp69kDehSLmFWW4KUF1DhoVGpF9zPgTHzTR6ukB6wWVW0uy6MwGlUYkrRdC0nHYD+hjLyapgJmjSN15R3cXeh2SLqbNlib0qBuBgP5aICwHobXyLGNpQjZCpFVxOmgOJOKNQNGF2TtgfQwCrTAsGkFdESt2EJjTPQZoABxhYZHCHsRagFrNQMLhYq1OxYlFp8R+fk9Zf8PFWlQOM9FK99bwsRahDQQJmGrXswVBF6CLtfi4XNAf1TL0I4BaWTkPCPx8glSuGKX9ewRdIKikEHjxj/L2e1Rd1Cc1EFjfdg/Ki8Ia8a7BWTmXtazAPSK68HDTI4rAQjXq0bRHvYvQwAJaDqpMd/ugLtiyrQjTFXntaRkywlqFQs+svJj2QEqPEIa6VyCqVgPL9whrAfwFRiXdcaUOGdJc2osAn4/bSc85kShxBFDrO3CmbJPDxVq2N2m+TY6wvAjzCrkSbuAzqYNBI6gF5dkD/9SqXyQlOQKkNRPNDuZTigU0x29uXdxJDJ5t4MbtfESarq7IwYQuXSv/AtKyytsTVUr+dfhIqyq1VUkBQ+WYixGWQHNEcnrVcEDHJRPCT0rlevm8udCLKJUVRXqWYyRJzpuPvTh4tWmimLcIelH7iywWDDTZlJ7y5mIvbnQ98G+axulzzKh5MUNhDAqCFGm2w7x8oKXH3pgxX5FXkCgyZoC9WCI3LfzmLSwyQgiEuEA46eBFnbeA58Iy0b5YgWdLbpIxAzE9J2CA8oCleX7Aa0fnFEGv3O8TbWqM+1MirTsluciLo0S/sVzPIQIp/Vz6yKSCkdrlFAm78EQBXeGkx0amOQXAa143YX1+GRxmc4porikhzHLc28tHthHomdHnWUpOAc+FkBDelnYwt+nnFDUxAnJti71n4EhOIc0FxDWURakL79QRXWdyzi726uQJAnCEJHyJmLOcgyZGLPuabngdI9TTgxwE1g11AtkPmKMKI6gu9vmYu1Ez5BxJu+i8E6QzabYUJiPnqItx3hFPOco5qOzoHBQYsZeFT3k9knOkpwcpKlCiVLgzup+cIz09Sl2B0aNJMbWEnCPoBQWERTXmqvDIRBcXe7E4DjxHyAfmSXvJYxYfeqmO6kmlTaFXCeRdCP63+VJJ6cmwFH3XSE8PesUFw3LK4xS7lu8ReAHFMinRSoabi4u9WL29yhyNgDaXyDxCT5Sy4EhzicwjroP4bWZJLHdTA8qQLvLifQLYn2hXI+vNxUVeBwavfOBPiDPPp5THrJF7xFyXymjELJ0aAC8k58wZL+CtRpTXnB0mysuwrrn6yAtKvQC2jYy0P2XRsvWqi7y4h1iplpkMEuYkkNQnTaVQEdnvAFFDRI3EXSDdM9tEEWGNCozUaTiP/SYi1EjbBSAdWE5C2BfnqhPtIy8W4i60DMl4UuQWaLvYDAt+WlWzzEmLpF0g9Z1bFeTm4y7OkEmkakOCTkkLYNe8r5k+3n7iflk5LehiBPscOAFpmt+XtFKbuYW6rinbPMPsUkTJLbDr2rQKn+atpbkFknpkehZtY9UAjxaVFkGKiikpWT0kc5g0F3Q1FB0n4EFoj5wFXz2Me6DrkjVYcZPwAZ+1DH8O6uMuFsIz7tLMs7vAi18X+Gvm4nYGcz3gvLAus9CrnCVMERHl7uMuFgysiLTNULm5RwXHSXrWjYD97MXTt4+aGRW124Kjvm1UcMTUaUEyFLYByD0S1kNpBly7cKZPyllo7Nwj5AVUOMCRey+oJigjbGUEreaBf2orC0p5je/w7WpzsXAegVUqtEPCquHPZ+R2eUTKro0KHVM4t1uYOSLSa/qgVAO+4r9+wEBWv0FVlAqkd7mTRJ4RQi+QJuW5YiWPCHrBqgPoxYqfRJBwBE6p6GqqiJO63E7GXl81cpBAt0ZI8NINjiiY24NqI74ueUHaracfcw8MJFiGgBMiC2X3gRcXtqjMA491HnQ6qIu8LBMnEJO+npGE5z2Q1KPRJwiR2Y6IvVvyHlUbyzZ75o3NVxORaHsk6yJic9p8kvdAUo/JBAj0iRx9ej3Ac0XYa2EoTEmjUQrn3cVebIBA6vCbVEzm+Qj8I1CSlXAZ3Xg52SZHhLsy4K6FXUE+AsILeTjIa2eaLNknx3f0M4L6feItKVHmCEuNExvDbkqNxmAsH5GkHrTbZb73qtGj5eO39jP2JQd5RJVG1CQ1XOh3ckVC/xGovNgKcR75n3sv6wJ0URdltBhxcE6G+X5lC1Ve4HtG4uY7FCkyqIu7SG1olcJZxghqjZiV5Pmi5oa+EhvUKzmFtSj2cyJqpfj29ORtipZ83GFqyKniG9SzShj2ySRl1iEjCwnshFr40xffn5497qGJjGySKseu4vvTD10qpNkhwvBCrbr8Qg8J6MCGYkeysFXpleL703OamHF6JvSAzIpvUH9gGcq4qekKDAzquRkb9vLdlVnS0OIb1Fu/kene24SzeY4YEV4kCpQoQxYSZ+1NpyS07fqtj5lkyMgtdSkaljys+P70bJG3qEocVDspgTs9d/xW/IsQNJi2neLb068QOyGRUyInsKH47vQ7bWEIYsNmAQnHjMqMiNO3uRay+Pb0OhMOYfFcKjLNvjs9oSJoqmKm/jIok4AQ29ODMALYBuJ/hh00UHhh7QgqFgi7zsWjnzMSeC2nRLK7EjjUzxuRjbPpaRsH7xrALiz9LrQwl75LNopvUs9nPCCwdD+ihAEqgUs9Y2GozqT7g2rk8W3qGwnX07SAUnybemqFhKLRpH6iDxVVGSFr2qA60+9oRpaO71LPXiGLKs/p9qB403epn5sYGnXNyYcLd1hil/qCy3GqJSqhSz200Wo5hrKTw2SMxTep5woCVd2sGkQ2SWBRb7vNAWtiPLQr2veoJw581S1oRAPF96i3dDhNicxr4FE/L0AZcXR5yqN1zMijfgKEzb0Bz22iAMm3qKdxih72dOidmh+Z5sChnnKTtGj/ShwgfIf6rhuvW5I+65tGTBe4sQHTNe7RVDdvYFI/sBsBJAhMq7DLVok86uc3fG0T23bFR75HPZ3FWEuY9FnKHgks6hnD7lNWpfgO9atyNLs8m+ax4jvUA0zoyLOy9cFJqsjyCwzq5yoY47x9ieolZvsG9UT5rOz5k9EMlNCgnhb21LmrBA71O5a2QUszKbIJ01V8g3oKXOiiSZbWza7pSFNPck/YPbdOETnyAn96VisuSqtnyUi2c2RPj70T25wQLqE9fcetNk2ZjPFeCfzpO+IENCFtTkgI/elBcQwqGC7DPzM7WTmRQT36g5OMFlbOc5fIAg8M6jt1Y7QFz+Ub1DMfvOEM33hWpWl8g3p2fiSvekAM3azo7xHUwypi/1WLbSKHenBng8LJNNuRxeM71IOg5paYaOgKLerRLBqU3PQFNz6OfYN6LvlCF8ptUSOn5xvU8wKEjgQSpQ77/UJFPXTFQ/W8WCiSVGVefIt6lqWWRQ7vW9RbsbG8LPU+JTtmhLvQY2VhEHX53uugv/UuRgKIlDGeriMypO9Qz6YjUNSbaCN0TgKDeqbpF1cxlsigHq8kAbaQHozv/Si+Q/38dkfjunTZGEpEDCzquRkPdIZkmVQMcPBN6gfqmIH/oUlptzEjsovUSPNTPnCpXzqUtfsxL0MGuAtsGjHhpitLT22OBETfop7v21lUY87gJdsksKifkzXWg68f5kF9k3ruTi5TyUrxTepZm7MwgTQ3S5fApB5gDNG36abrxe3su9TbCpYsdOqmOnl6HTMgu9BagYy2bjUjOfcCk3pKLawqVafVRV7UJbItnuvSZeq7BpJ64GwBDFPsOtGcznMkqF/ctjxZO8LJVd+knhEiNBgRpzTsmEGBEQyTjDnUkCFCSf30BvZ8uzEGuJXqu9Tb6wKm2cTZDSSovfou9Uzg6jwXx1G+Bi71fdXbPXHg0+8ZdDJyhWd6cWn1berJrL0skrHzsjCpctTApn5uYDtY2FWee0/I1roFovpC0iE5UNP9iJfSSfWd6nettrFu7IaF4TipoVU9prd1rhSuvlU991VCpwNVEAovQN+pnr8f3W5wg62Cu2pgVU9NCXiNM20UNiyovlP9vEXLQPZuIHv1neqplrzq0KqhUz04ATDbYAsIulSiCuM0TFMqlo0vYPV96tnsMs+3ybuwJgk6rIFNfcM0B1Izdjri4mD1Ter5jgjWpMqE+B717HcA83GTpAJoqIFJPfXyoVtGvaEZfVMXc/HVa5BREFo/yWvZy75FPXXcINlQJthQFk7gUc9q3H2ujai+Rz1beaykTYNBa4086hF0LS7jvXRx8AXDGuPAhSx/Omn4lWjoW9Tbxk3I1nhIqCjUyKKeGetpDl9Di/prIb8hN2KILVGvAMl3qO9kXA4RgXQgbD5afYN6uogXr3KgHNRw/zUwqGdiBQ4Tol8P+z1d1LWbO6+mF8lW36F+Lt02h9zYDZILHOqXVxlPbD/11Isc6hPwjqse9mqCrO9Qz/c3UDfxje0SSrcGDvXc25fncrvqW9QzbIXGExJFF06Pq29R31FUjpchTVRE8JyRcSpKkwA4TK7tkNXje9Szm/eir3ujm6Wq71DPUKHPmfoaONSvegfYTd4YrVTfoZ6CF1+1dO9H0DGDLsZEpVn5ySoYwuuBPf1hMncJ29ttSA3bvju9d62Zpia+O/3yNlCrfIdmhBq407OPbcVVbgX6UuKuvjs9D0l3zt22iFIgvjs9Z2UL4vXsb9CvGbl24XUGRretSyWguvIxe21O7d73roRo35ueTVsWdhSbUMznkD7iYg0McPSTbkNZz74z/fxyUHOSXD5q8py+NT3vERO2ZIjwUiBQNsFz3bsulFbwfenZDQVCPtX227nxZJP4zvRQvyI9IH2/bszaa2xMT9fYT9fOZc2pXzTAXOj8MJejVt+YnkN9ns/JYdPFwJjennHytPQBb4MG9UVslF75tmTjDlh9q/puSghTGHJqBhQbBl711rRm2lhafa96elvQILBK2MZp36zeipenqP9yvtElGLjV88VUMC+7XUBJpRzVd6uHKw8bxh0qyJyGCpqf+G713HF+v6vpHCPEXYCRQDBAbOtmIqvvVs+HClTv7npPfdVITn/cZ8fayl+GzzIngVk949+GT3/DhxJ8fKt67urOi1Pet6qfezYOA7yMa1wNvOrZzinjF7izU4JpfK/6jloVVKZSysPXT1Tfqp7jPzQYHfYxkVsJvOqVr7mbcOux7JvVLwUSJPs5c1mJNL5ZfaNbJ6EXjW8FNZazNbCrHyh0WtUZr+5I+YSRXf1G8jNIgBC3M0yM3Ooz9XVM7z+pgVs96RmwPE11WnNO+Wb1fKaQZ9KtzChrx3er576dxTxXI++qgVs9yQY2eOQJuaKf8zuuBdrn6q7qm9Xz5oCmuTEBhRKoA7N6nmb9lnlyKQE8aFBmnBEOJnidpfNrnpvvVc83MkKDAnlZsRKmBVb1nGEYGeQug/x2cdeqLf485wRnNt+rvuL2XX2+kSmbaoFVPefvUJ7Jt90sXGnznerBynttCN84k2++Ub29NnhKQLbAqJ6bT6C/g2ik7YkxdUpc2MWVDs1RZk1fSR80Mu2C9bK49tyQmi02qgc7HdgmE9MkXeK+UT3Xo9IcdzXfqd5W7aaHiRF3tcConk0bEy7Fe+3ykEGjTkbIpBZ3dqfKFxK0yKieTVKn8OYCDfqcPu7izWdilwQF36ie79SDUvLMoVLHjHAXPZf8TSRmeF56rhMdqbuwe2fRUVXsu/tG9Tb2w7EKE70z6dB8p3rCCvYubB0jvJARnBlAosNymjMuyHLxrer5kIedSLrwZ5uRfsDIqR6cEckCDSYlM+ZsgVO9DTXyp3cfQ12QvlO9d5mWRFXfqJ6VqYtrNjbqzm2hTT0mEiQeu8XDpEsncO2CZ4NUjxsP38kBeXHfpB6OdevThhyQecrApZ5T8Pu9J+cgwQ1BqDkDWRJ162+cxjffpZ6mBFvtaY+YMncLXOrJdgpF4TP/bX35wCwVWeZFm9FujqjIpB47l8Y8YWyBST0IS+jSavYar8U8WIS7YLHQPY23Gr/sPd+lnkx5MAkldVIzp15gU78bi2KZ526PKGgIapFPPQr18+KI933quf458OeyXtQCm/qKUQGz2sldbooxfZ96SuM3irZ32YU+6L/kU79NWHF9zBB2VVya0+b45tvUs88KsBf1vqaLvmtUayQ+YBoTMtHCLTCpZ5059CCSkONM7yRlDE3qCdEAfrA4RN88dKkHlFkXKWNgU8+f78AvaWuNsvFCl3o4OkG8SJfbVMML+C71rGCAB76XqCUWBib13DENgGuf7Dud5O+gusZc29V8l/p53LeGHkbI1gKb+rnQ2qhIj8wBwXep5zsSQIiM0PC6V0p4Kd+knnupIC2jd0/MnoUW9TjmvZ71HCOQ08+uazKlk+3psSJfzzeo5zZGkMGQd2026CgwqG/GClF+7nfQKtvEt6fnboSFItdcUtt8d3qu4xnvWv18PuIiZSbKPekqDFO1bL49PTuzKXjgzIT9D5rvTk/cLdRVC1/lYGoJLfSnX2TwJE4ybtTNN6jny9RN4UTe1jeot3bq8Kc2W5SdF9jTdxLbwfHE2aK5H6FF/vTYdw199xNRpYZY35+eTWIhh6Ja8mbHjK7DhthlGk8kNwnt6ad3GfCiVq3/c8iA6MJsBzw9JqpoPTkDf3oobVRTaoQTykiam29Qzz1LUMebXHGsR5TvUM/30DDTJUdS4FDPNx8t7jQ7K9y6pn2HembggKnhasxuGAvfop672mBvU5fDs24OY4ZeqTsuw+mKzIzlIod61Nzlqeau+Qb1bKOW8f1vS0VpgcCgfs49mjY8c49D8/3pV62lKd/huqycyJ8ebzcGZpNRQzFYJHCot5c5U+jSJ4vEXYpa0aqXnuzsD5RmvuZb1M8vJzFH8s63DbXAop468fICjVw0vcy0b1FPXp8ri/WniyHcR9l8j3or9Z2zXYFJPa/BMX+yotvvHDQS1UPJbnHn1ZlyK9sQmdSjurLhJzDVUA3dPfCo55sYV9d2mxb07nvUMw2+KGh136PetqhOw382xfgeuNTPwZepnbRqPuB3+KWCIPLW2g2ai+6b1FsHfYllVMwz5eQeuNR7eHiXMaIiI/mZTmH6ZeeX9MECl/pZE4HRXG98APTApJ7ZlUVF0FTOu29Sz30JALFn7IC8uu9Rzx2mxlBN1nTgUc8+FKYGIxvWN6Vn4m1xJ/lZfpdjqfu29Est3B0V6RoOXOlXtqGM/U2e031f+k5+iMaeQN810tKTM56sNy6uPU3EdEwfbLGaPM0HbXzSdd+Xnny7NxJq3vPs66Drvi/9KiikiQ+FxNTAlt76Xk4Vdt23pZ8XPE1cqdnEKt+YntXBVDNfsbY9cKXnWYaf1DHBt61135SeCUKyFAZAWM1ujlzp+TGnbEqPXemh8Eya8vv5oYE5sqWHi2Ohy5xkUmdKp0MGnhGo1Fu031VTVuyBKz1fSQU/CftXE7t8V3r2UljNSmRLj0rUPF8tjS9Y64EvPSeHi4vMTsN33XuRMb3Efntnx02dKYC6+8b0c/8l43vZTKLYA2N68uHYuB9ecqUeGdOjeBK4vTwJXrKFfWP6uTrYBOqLPNIPGKro6d5YWUiUkqh75vuYvjE9a1rBKI8tR/gxfWN6vlO1TvmUHvjSz3N3C36Hyd2770wP3rKVWv9pUV8FeB00sEkFJ3TQ7dGRcgZZnZMIeSFxu3JEtKjJd6fnHd3muXv33ek5qgJooCvW+GbbHpjTMyxfOC5dqbuc8747PTuh08ULGL2M0qJH9vQI/Y1tuYCFwI+e2bI23xuRH/3MCcqo1VIyRaHuG9IzViUvBjjXkzlDAkN6MsdjeA3hSvVW56CBUwTaySwkrZtZgr4fPWsrTHucjhGhLdS3gMYOY8thigXdN6Rf3jxAibXxM+q+IT3JjFe+DlfTouyMwJEe7PLHsuX1cnCVreJb0ltKfSY/7b4jfddw1REEUhgoNgELLOkHFmLxakwa1J6Yvic9e3YvqMaL1tIxo6ZF0gXA5r5ViWBOQr8I0FiXefjyPek7UbWLDOIwF4N135Pe3uI1BVtGgNoDT3oi+uGSodkt5HouRZb02Py+40zdoqwOGRlGAOboU31KDwzp+V4w8s40GRj0/XTfkZ7dQXXGy6S9UGp/PXKkR6iV8bXvSYkM6UOtuZ+6IS6Gxf6+Ib13wQm8awC1EmnfIOLc9M+w/CKshczj4sr1tJ2BWmc66lkE2RAkEzgrZ7O+BprQkh5WNdSIZhmZDBk5o2I3kVFy6XP9dr+IlHANwQc8LUt0zO/QcgESufn6gESlB5b08xbD3epJmlk/kSf9Iv0kob8lRHxP+o4Yx5qj6hhR4yI2n2mFiDUBfFFA903pbWPhFGdmvnKs+570lNNyMnbT1ykcCUzpWbix2H1SJZK94pvSc5mSj3nFNL4r/XyxGEyzcedUD1zpu5I9na42JFMybpztvik9NUBivTJbjAjqzO6b0rOLAPgSkxrE5CiBKT1Dh4UXZ49M6TGUAvTCHKUeJh/zTenJLgLcGjdPTNgDV/p5imt89+zVPcN3pefMGxRitHYK5T3DN6UnI1x7zncZI1TQU3SRn3ShC9+RPnxTet6+cOgRzNzNqwZeXbMrTsw0n15nSceM/FHxKnL4CnSabul59OnLR2ZddAX09FrM4dvSz9WE5nK5iz+S+vMIfOlXcji+K6AweBi+L/3ymuBJiivQc0S+9Hwx03T5NL5TYwS29KCKG7fWBpkV35be2iHNvx/XToZvS78iWkkiVo3n6ghs6aEMOOiRidE8iMkYvi09N5yDfdzEsVfgyPBt6SH77jcn4U3GiK5hxHogmKDQfUovREUO35eevQYhQBAe1gz3HDNyjDjn2WENk1k6gS89Z44ARqjf/BI+vr/8/wM=", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Jobs.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"JobID", type text}, {"TeamID", type text}, {"Service", type text}, {"Priority", type text}, {"CreatedDate", type date}, {"DueDate", type date}, {"CompletedDate", type date}, {"Status", type text}, {"CycleDays", Int64.Type}, {"OnTime", Int64.Type}, {"Rework", Int64.Type}, {"Cost", Currency.Type}}, "en-US")
in
    Typed
