{
  "name": "Model",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Vehicles",
        "lineageTag": "8030aae4-77a3-5715-810c-ab87752a3ded",
        "columns": [
          {
            "name": "VehicleID",
            "dataType": "string",
            "sourceColumn": "VehicleID",
            "summarizeBy": "none",
            "lineageTag": "1ddfa21b-09c3-50bc-9132-1aeaeeda5537",
            "isHidden": true
          },
          {
            "name": "Make",
            "dataType": "string",
            "sourceColumn": "Make",
            "summarizeBy": "none",
            "lineageTag": "8ffc192d-1022-52b5-896b-4f44ca8b9be6"
          },
          {
            "name": "Model",
            "dataType": "string",
            "sourceColumn": "Model",
            "summarizeBy": "none",
            "lineageTag": "491784f6-b389-5652-a6cd-f41c43793e49"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "summarizeBy": "none",
            "lineageTag": "75c18e5b-2a6a-596a-a874-8ddef5970df8"
          },
          {
            "name": "Salesperson",
            "dataType": "string",
            "sourceColumn": "Salesperson",
            "summarizeBy": "none",
            "lineageTag": "f1f4b2df-c71b-5ce7-9c1b-d53444c7fef9"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "summarizeBy": "none",
            "lineageTag": "0b99bb09-5eff-5f75-bb0b-4405fe038d0b"
          },
          {
            "name": "PurchaseDate",
            "dataType": "dateTime",
            "sourceColumn": "PurchaseDate",
            "summarizeBy": "none",
            "lineageTag": "95f79532-5555-5a65-b88d-2801f6331ce0",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "SaleDate",
            "dataType": "dateTime",
            "sourceColumn": "SaleDate",
            "summarizeBy": "none",
            "lineageTag": "24954e87-3d7e-5f2f-9a4a-b8566d525a70",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "PurchaseCost",
            "dataType": "decimal",
            "sourceColumn": "PurchaseCost",
            "summarizeBy": "none",
            "lineageTag": "69f0cfef-097b-5ff4-9c25-3654fa064ff6"
          },
          {
            "name": "Reconditioning",
            "dataType": "decimal",
            "sourceColumn": "Reconditioning",
            "summarizeBy": "none",
            "lineageTag": "d046a0cc-49ff-5356-8835-c2db27e7ac1a"
          },
          {
            "name": "SalePrice",
            "dataType": "decimal",
            "sourceColumn": "SalePrice",
            "summarizeBy": "none",
            "lineageTag": "8e18f3e3-d454-58cc-8894-133057f42280"
          },
          {
            "name": "DaysHeld",
            "dataType": "int64",
            "sourceColumn": "DaysHeld",
            "summarizeBy": "none",
            "lineageTag": "f381ba58-c95a-54d3-a873-36ef19ea5ec0"
          },
          {
            "name": "AgeBand",
            "dataType": "string",
            "sourceColumn": "AgeBand",
            "summarizeBy": "none",
            "lineageTag": "21b803fd-fd93-5da2-b8f5-3e644821a3e3"
          }
        ],
        "partitions": [
          {
            "name": "Vehicles",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"jZvLbiXHDYb3eQrvUwK67l1LO16M4RgIosT7Y0nwCJ5IgaQJ4KzyDnnDPEmqu0gWyT5qyos5x7eqPizWz4+X/vnh8+Pdl4cfvnc/XX57cD893z98cd+9XJ7uPrvby5eH138+vLw+P7nbt8vb11f3l68vd58vrw/fX94e9n+/f8F/+qfn1zf314e756f7x7fH56fHp1/3/+gvL493D+77y++vnx6+3Ltvf3347vJ0/4efl2Xx7m/Pvz+/Xdztw/3lyf14ebncfX50397/6/H1+eUb7354+ub27fnuNxeWkG98uFmScyks21/Ot/1jcbH/2fwf9yWD+9Qf4OI+Xd7uPv9y6f/rny+fn18eaNHgbp/7Y/QFy80Sb8IKX+tNKC6ksXSI+0f069gpzA2iu/3676+/Pbrbv//sfnj9cvnH5ZfLPS0f+fLlxi/wdb0J1aUCT+73jxzGZ11d8f/7z3/bsu+Q3I+P75kkqeX9fPrkKjx9GqvmYZ8U++/oq5exenaffv/aLfT4vomysPu+UfDOxZUv339FPz+0SqGTvGqVwh879IOcVmmuwGMPW5cGNm8rrV7hUK/bpPLF041P0zy5Lwcmz8MofvxtCcLkKx7quzbxfJN195X9a7sJ0dUqzrWuZXjR6pa+Rxx7tHGsV+0TtMXXbibnhruQO3aPafwsu3PhWV63jHDGPC2zbt5SwBmHl9RlfPq+L5jd0/V81ypJWsU3skrfC20dwB3r+LvCjOLxul43S5bevrS5U3URjOMjGBv9h5+sn9f1qoWKNnxXhM3wiT/65ozTKuN6vmuSqmxe5h3KLqB0ZTjXDDdKHOu8otfN4uUWy0pf+xYRfXFc0zR+iusGY2Yv58KrNXI6u9+8ewGP2S/t2M/5QtfVV0uDo7a6387WZXj0gMIeSqJF13PdVcLYxZbuZ3JeKJcfmuBW6SntRHaFI7Ypu+0mbloi4lENsE1jFg+LLbtaJOPcr7gYhRSkIcYudGcBCwV/rsFVR1O/3VdXQQZCBaNHtmQ4Fd7ph/tqPbTgafYHTotYN0WQASG8IZrCG/gmYQtEpJBdAzI/2JjGCYQeVPAXpBPVjTJwhBlMuwujPI6lSxqfaxWPnw0BTkeC2SIpeUxBR18jPXExVTerWNS4Y2bpKLlCOI3cG+up7Bal6jNad28nfQHzhCFhnse6sJ6rblUUk+eZ9gCHxhkPHgv8kMw1MrRzFfZaYXZtnDFjQWEPJFtxMWRXeOIyydFvauMbjxihDK9vREjRYN0oJZeHujjv6Fh9TaC5udLyJvcmKWF0WXd1Sau4rBk26u40DzUa5HugRr95Zr/4Qh37HolEPZ6hbpHqQubevTDDA/vxoBnsHSppV/wA6Ao/rFxb+oniJYWLVCrkBJX7YTTA16tjzdPpWbaR8eHBOUkM4jn5HrCxi3Bx3fvGuitavEw/sUk3SqMQNNb99hdh91jAUTjUxTPSTQotwvzaXAU5BwBYIYPh6JIs5lXM6AsXR+Q60JYKUVSqerK5t1yJpV3XEyyPsh4DnWQ6J90qYz/zky5b5OwePHF8dsKj1Q3M9SrSFTrTnsPh5QcozaCRpQijGNgb1A+oc7MMVwhTjYCgJK1uUW+8Ug3okl4wy8jo7Y2ifzI4NynimlbfmBp9ZXxEj4cwz9QEXe2M7FgXyhqxCgDHmrm3G9RbpKiHyaVdLuk2DeGqkCCJ23QGvdeAsasLScAERoqh+QOYq6mxzONcKUEChg6gAD28MdHNBukGFTnCDEgJtIWsHvO4rCVyZ8zn4KvAkZx9ZMCVi0AcYtz5i6JetqE3aWEP252dPrigr/cDwVXPSFflLyHNr/2WRx4uKubTzE2yxblFQXqbd6q6hH4u9SWLpDfb2FsVfzU61u6AlG5ARg2nvHpxrOfce6g3LnsxIGlaj4kkIBukG1QwbfS1n0GSpJsR2bnlDc4VnugnNubtXkVegOmPvQJfeMKBYjFvel9gas/9uae3BcITe/xiUG++YvGu6bXxhTeDU6QrJuiq7GWZ2YtfKBLBWUb45MlLMTi3Sl9fphtuoRrXh7QxQg1WQGM5w17/DpPWzeEpNxqmTvApHv8D3BuOobSzHdwduKGbulTSrGJwrk6lZ1XdT8CA5GLEPdcXZ1eznJOuwkaqjazbVpiqj7OsGfBoVqSKTb1ZRSXGL5WiEvALlBl8peyunCHvlRqj32QFsQvjaJil12pRrqoyBlZl9MPO0x4VqtH8YlabcZUjsoSxGwdbDfDwFfKAIs60njNvkL+BWiV5Dxro6ZDgQWbK4aUa0HuoMraNMHQTZsuq+aIG5yYluJ4/NNEL1v/BEyNF6WpRblbXn5Xse6TOYv2KDCM6PNWAXpVXU4KU9h+TpT6mcvgFJvRWbfc94SDwQndn1YtqYK5XkT/Ne5rIKOCKBYsjvHZRzzhXVbsJ0uNeBQBBhyLAqGZ0r2SLrx+A3qji6MxK4x7e+C+Ibfh84nsYyHsAxnVPjhICI0p6LtxV1nPMzdfMPtKj0m8kLA2WAXgJgSowq825ReVHy7ypfQcsjzRQMyjBim7peoa99R362lFglb3ehtwrjtYC30OdcY99hLxkd5+nWWzSDe+IzI4YQdYwQsJP/tznoKu9MXBvRLN7TIyOjLEa1KuLPKyuttL6Y/kM0anvRgYymPdaoXHzdUzsqKieCACaxblFye50xE0OMGJAUgottSygrhmoW5XsxumW66xLA2E0JA2SyGZyrxJJ1nhktzVAqgFdgRApk2kG9h5qjXFUA7TVWd++nXFulJjOWsdbZiQ7gblBg0eoV/sA6SaVmLJqIGtQw2wA1F9DIQ5rBvaqaL2I+gtdVCgcQ+yQbcd2zr2HQmPYBwNEZrdPwMxHtllXySLLkHo4xSkPbL80eHrBGO2Md720ORWQ854L4DwGnGyFZind1f7LDM0NynMYIs2OILRJwfa8++UXm30P6Fi2MQ9qfaOqU6XRL+eom+TlJ0HcS5iY7UL4XxF1ef3VLwbsqkpjyFNeImEAtGKhWcJbdn4xuFc1pylklP1OZb5+WGH9kMg8FvYemHHdNJhqRciMyTMv9ItBuhobl/k10kwAJBi+QkeD28REXV3eWbhXkogBzgHWxSx+g4G+ui8Y6DL1E6PeGuwAsxiilumXM/a90qDeRuxw8Mjj4NEcsfP+A7ib30Hq7cEpAQvsMu1+z5/aG8Ar/DFt3ML8HdEO8GvNIPBJ7HAOv7raiCqz1waw2+tx1ANH7sQGNv9emXCMvusM9vCpg1cjmf8MeINSgUpW6QZKMrfLmONxZffeIt4o1X0pdMrdRJjJZFgZNlxI3L0Nv6opE2ZxvctmwUY1wClm2NT39f4cfQ/wmAY8ghMGLAr4PJ/ZoF3Njqy4Xmn+EHowwF1FOooBvBodC2nAVnNAi0CcXiDirUgEPljw61UWNis9/bfQUBZW70AvafjTB4N8D+S4g9LEI5wnbXNFE3aVLAb2yLkrCSjK/mcji1A4CgbrKmqME+uWOWAHld0FUZ38JZxh73vE2L923cJ0HSrq4I0sI/XhA9B7pTu9jQUk2UbeelPzmQ3QVf1pxnRb0w7zI7j2ILerCEPhHHS92iALH5ddwQjwyBzGht4gAwaH3tmgBicPCZycihk+nBHvARd3MZwTJAuKSqMoGi3KTfJ5KV/MvEwHCSmkiwLook25OkqvJAHdF6lMCjtVTJL4ocZz7FXlnTiz6h5Dk+gepQbdoybWN6j3gI17dJ4lDDR8KIUMb4Cuyl6WGff7HaHeN6QXGdJpEUKjBbvhmp6P3TyxOtz9hMMemZ+tAb7xGvjuZ8zrO1C4w3ccCt2maHLvodyY9tJ6lEIg4nI0QFcVG1mntJ8o1eogRao4Sz6f+Yxy9WRtJXtsd58GO8aa1D5iBk8fYF491Mhavcuc5AdCh88o8plkMO+h2AhJUuVioJOkdI65ShbDHDruB4pVIwDGjM0AChvJRlxVaySR2WuNKDJQDMiA0zzgpTPeVe1pVj/eRjJlvAsFHr/y1S3cPXSoYeqoSZvPoSOfbMRV/riwaBpnLVAONYuyt0/nlFuVsrNR8jh9cdzSUnCCl/goGcSrX4aZy289ajmkgimBmJv0yUDeKx3qbXC6Svzng9M+W5irKo5slsEfohH6DPeVbHCuegVhmXWpbRZDlI6QIWWmnk3sFRHbzy0iL6xDioGzjXILg3yv9ap7QK1KYnyrZPYz2tWVRjYoxfxQvoEkHSV/gHd1p5opr6eDxeGagK/08ZM16PdqwMaoF2SyHqEf49P0zHP0vVZsLIweEdcbMUy2cTcpBGiz+HhMSqHz1bhJznhXJzFsGqPMERtIjEDUu5+wYy0W/uqkem7R/bEK9V1XHBZkz19s/D3A45jLiLp3F6i47ss576pEOoj31TQCrFgWFHYxgFfXvudQ/Jb3oicOs0CmziWsGPCrZ7+ZsC/zLQToY8CLGZLYiwW/h4rjGPmKsozBZ758MXBXuGMWzbtERSgAroDTASRgxaTd8g5Ob3YnXodMAIoNIRKZFgN8FTfyVwSiBt8GL1HyRK+cke+hwLgHDUIjGrCLZOz6AdTV0DibAd3g6OfQtYcJXpkiVYN0dXOwTDdP87UJ+a4Nt0k9h17VjqFbtL/qiEUYfAkBk+tZLKk29R7KjGGDU5rfm4XdSNpSz0C3SKALczxta+9gNRpnpbClwS1iga5yQzbBt7Wo5ChGLYcXM3y1sVe9t8oGvuIyX6ACc2MLfOF7nFPvlULjNoyB5SmEFzGk5qvBuloSZ/7SaSZLV8xQN8oiA6sG62pv9IS8/Wyj3CHBpxiI96uFvuqNwWUOfPTYTd0GiBel6i3+Dw==\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Vehicles.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"VehicleID\", type text}, {\"Make\", type text}, {\"Model\", type text}, {\"Branch\", type text}, {\"Salesperson\", type text}, {\"Status\", type text}, {\"PurchaseDate\", type date}, {\"SaleDate\", type date}, {\"PurchaseCost\", Currency.Type}, {\"Reconditioning\", Currency.Type}, {\"SalePrice\", Currency.Type}, {\"DaysHeld\", Int64.Type}, {\"AgeBand\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "lineageTag": "801e62bd-5049-5ece-bb8c-75469907dea6",
        "columns": [
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "summarizeBy": "none",
            "lineageTag": "c2227322-8f05-5877-9d34-cab9621e5b89",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"80lMSs3hCo70C/FwDfF0VnBx9fXnAgA=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Metrics.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Label\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Units Sold",
            "expression": "CALCULATE(COUNTROWS(Vehicles), KEEPFILTERS(Vehicles[Status] = \"Sold\"))",
            "formatString": "#,0",
            "description": "Count of vehicles with completed sales.",
            "displayFolder": "Business metrics",
            "lineageTag": "1dd20ebf-d0a0-5071-a28a-bca04010e0da"
          },
          {
            "name": "Sales Revenue",
            "expression": "CALCULATE(SUM(Vehicles[SalePrice]), KEEPFILTERS(Vehicles[Status] = \"Sold\"))",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Sale price of sold vehicles, excluding tax.",
            "displayFolder": "Business metrics",
            "lineageTag": "52401810-ffa0-5d10-b6ff-6be2575b548b"
          },
          {
            "name": "Sold Vehicle Cost",
            "expression": "CALCULATE(SUMX(Vehicles, Vehicles[PurchaseCost] + Vehicles[Reconditioning]), KEEPFILTERS(Vehicles[Status] = \"Sold\"))",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Purchase plus reconditioning cost of sold vehicles.",
            "displayFolder": "Business metrics",
            "lineageTag": "03e0080f-b749-56e5-9c48-58b56f6affbb"
          },
          {
            "name": "Gross Profit",
            "expression": "[Sales Revenue] - [Sold Vehicle Cost]",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Vehicle gross profit before finance costs and operating overhead.",
            "displayFolder": "Business metrics",
            "lineageTag": "49ee90ad-69bf-5fe0-94ba-1bcf67c783ec"
          },
          {
            "name": "Gross Margin",
            "expression": "DIVIDE([Gross Profit], [Sales Revenue])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Vehicle gross profit divided by sales revenue.",
            "displayFolder": "Business metrics",
            "lineageTag": "85159cc8-3e81-50a1-aec1-6b86561da145"
          },
          {
            "name": "Stock Units",
            "expression": "CALCULATE(COUNTROWS(Vehicles), KEEPFILTERS(Vehicles[Status] = \"In Stock\"))",
            "formatString": "#,0",
            "description": "Vehicles in stock at the 30 September 2026 snapshot.",
            "displayFolder": "Business metrics",
            "lineageTag": "caa6ac9c-030f-59c2-b577-315ac2713866"
          },
          {
            "name": "Stock Value",
            "expression": "CALCULATE(SUMX(Vehicles, Vehicles[PurchaseCost] + Vehicles[Reconditioning]), KEEPFILTERS(Vehicles[Status] = \"In Stock\"))",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Capitalized purchase and reconditioning cost of current stock.",
            "displayFolder": "Business metrics",
            "lineageTag": "c039caa0-a260-57a4-805d-03c0474cf8a4"
          },
          {
            "name": "Average Stock Age",
            "expression": "CALCULATE(AVERAGE(Vehicles[DaysHeld]), KEEPFILTERS(Vehicles[Status] = \"In Stock\"))",
            "formatString": "#,0.0",
            "description": "Average days since purchase for current stock.",
            "displayFolder": "Business metrics",
            "lineageTag": "48a39863-c84a-54eb-8d4a-05b516e69c79"
          },
          {
            "name": "Aged Stock Units",
            "expression": "CALCULATE([Stock Units], KEEPFILTERS(Vehicles[DaysHeld] > 90))",
            "formatString": "#,0",
            "description": "Current unsold vehicles older than 90 days.",
            "displayFolder": "Business metrics",
            "lineageTag": "4406f1fa-8d56-5b39-b88d-1809b8585ec2"
          },
          {
            "name": "Aged Stock Value",
            "expression": "CALCULATE([Stock Value], KEEPFILTERS(Vehicles[DaysHeld] > 90))",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Cost tied up in stock older than 90 days.",
            "displayFolder": "Business metrics",
            "lineageTag": "5227d6a1-61d1-5b0f-80ea-49dad45331fe"
          },
          {
            "name": "Average Days to Sell",
            "expression": "CALCULATE(AVERAGE(Vehicles[DaysHeld]), KEEPFILTERS(Vehicles[Status] = \"Sold\"))",
            "formatString": "#,0.0",
            "description": "Mean purchase-to-sale duration of completed sales.",
            "displayFolder": "Business metrics",
            "lineageTag": "28c55a0c-34a0-5fa5-99ed-e7630fe02a5a"
          },
          {
            "name": "Profit per Vehicle",
            "expression": "DIVIDE([Gross Profit], [Units Sold])",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Mean gross profit per sold vehicle.",
            "displayFolder": "Business metrics",
            "lineageTag": "2c426308-6a7c-547c-adc0-c1b4f0cdecee"
          }
        ]
      },
      {
        "name": "Calendar",
        "lineageTag": "920002b7-2210-515a-8784-0366920ad96d",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "lineageTag": "9e9e2a02-7963-5974-92dc-65d77abe2ba5",
            "formatString": "dd MMM yyyy",
            "isKey": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "lineageTag": "cc527976-473d-5b88-89ae-ff2a72b1c474"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "lineageTag": "21975d70-951a-598f-a94f-f19ce8c152aa"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "lineageTag": "54d1a52c-1ee1-5adc-8622-457fb169f9fa"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"hdo9qyNXGoXRfH7LNfTepz5zpxN0OGEHDRPZ0LT/v2fs232pUvksEEjiibTQRoHeX798//r2n69fvr39+/ffvv/37fMfX759//rtX/3U9ZdP+d/j7f8v397f//38OR+96AN9QV/RN/Qd/UA/5z2f0OEX+AV+gV/gF/gFfoFf4Ff4FX6FX+FX+BV+hV/hV/gVfgN+Y+rX27772os+0Bf0FX1D39EP9HPer/t+6PAL/AK/wC/wC/wCv8Av8Cv8Cr/Cr/Ar/Aq/wq/w69Rv3PY3XnvRB/qCvqJv6Dv6gX7O+3V/Dx1+gV/gF/gFfoFf4Bf4BX6FX+FX+BV+hV/hV/gVfoVf4TfgN6Z+y23fy3vvRy/6QF/QV/QNfUc/0M95v+77ocMv8Av8Ar/AL/AL/AK/wK/wK/wKv8Kv8Cv8Cr/Cr/Ar/MbUb73td33tRR/oC/qKvqHv6Af6Oe/X/T50+AV+gV/gF/gFfoFf4Bf4FX6FX+FX+BV+hV/hV/gVfoXfgN+Y+m23fW+vvegDfUFf0Tf0Hf1AP+f9uu+HDr/AL/AL/AK/wC/wC/wCv8Kv8Cv8Cr/Cr/Ar/Aq/wq/wG1O//bbf/b2Pj170gb6gr+gb+o5+oJ/zft3vQ4df4Bf4BX6BX+AX+AV+gV/hV/gVfoVf4Vf4FX6FX+FX+A34janfcdv38dqLPtAX9BV9Q9/RD/Rz3q/7fujwC/wCv8Av8Av8Ar/AL/Ar/Aq/wq/wK/wKv8Kv8Cv8Cr8BvzH1O2/7Pl970Qf6gr6ib+g7+oF+zvt13w8dfoFf4Bf4BX6BX+AX+AV+hV/hV/gVfoVf4Vf4FX6FX+E3Zn75dN3v+5f1l8/LRy/6QF/QV/QNfUc/0M95v+z3qcMv8Av8Ar/AL/AL/AK/wK/wK/wKv8Kv8Cv8Cr/Cr/Ar/Ab8xtTvdv+VvPaiD/QFfUXf0Hf0A/2c9+u+Hzr8Ar/AL/AL/AK/wC/wC/wKv8Kv8Cv8Cr/Cr/Ar/Aq/wm9M/W73XelrL/pAX9BX9A19Rz/Qz3m/7vehwy/wC/wCv8Av8Av8Ar/Ar/Ar/Aq/wq/wK/wKv8Kv8Cv8BvzGP/ttH/fZf32IH39mbe/3J9vHffakD/QFfUXf0Hf0A/2c97/3PenwC/wCv8Av8Av8Ar/AL/Ar/Aq/wq/wK/wKv8Kv8Cv8Cr8BvzH1+/H7/aP3tRd9oC/oK/qGvqMf6Oe8X/f90OEX+AV+gV/gF/gFfoFf4Ff4FX6FX+FX+BV+hV/h16nfuO1vvPaiD/QFfUXf0Hf0A/2c9+v+Hjr8Ar/AL/AL/AK/wC/wC/wKv8Kv8Cv8Cr/Cr/Ar/Aq/wm/Ab0z9ltu+l/fej170gb6gr+gb+o5+oJ/zft33Q4df4Bf4BX6BX+AX+AV+gV/hV/gVfoVf4Vf4FX6FX+FX+I2p33rb7/raiz7QF/QVfUPf0Q/0c96v+33o8Av8Ar/AL/AL/AK/wC/wK/wKv8Kv8Cv8Cr/Cr/Ar/Aq/Ab8x9dtu+95ee9EH+oK+om/oO/qBfs77dd8PHX6BX+AX+AV+gV/gF/gFfoVf4Vf4FX6FX+FX+BV+hV/hN6Z++22/+3sfH73oA31BX9E39B39QD/n/brfhw6/wC/wC/wCv8Av8Av8Ar/Cr/Ar/Aq/wq/wK/wKv8Kv8BvwG1O/47bv47UXfaAv6Cv6hr6jH+jnvF/3/dDhF/gFfoFf4Bf4BX6BX+BX+BV+hV/hV/gVfoVf4Vf4FX4DfmPqd972fb72og/0BX1F39B39AP9nPfrvh86/AK/wC/wC/wCv8Av8Av8Cr/Cr/Ar/Aq/wq/wK/wKv8JvzPx+3me/9/cv68/7kZ/32ZM+0Bf0FX1D39EP9HPeL/t96vAL/AK/wC/wC/wCv8Av8Cv8Cr/Cr/Ar/Aq/wq/wK/wKvwG/MfW73X8lr73oA31BX9E39B39QD/n/brvhw6/wC/wC/wCv8Av8Av8Ar/Cr/Ar/Aq/wq/wK/wKv8Kv8BtTv9t9V/raiz7QF/QVfUPf0Q/0c96v+33o8Av8Ar/AL/AL/AK/wC/wK/wKv8Kv8Cv8Cr/Cr/Ar/Aq/Ab/xD35/Ag==\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Calendar.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Date\", type date}, {\"Year\", Int64.Type}, {\"Month\", type text}, {\"Quarter\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "dataCategory": "Time"
      }
    ],
    "relationships": [
      {
        "name": "24954e87-3d7e-5f2f-9a4a-b8566d525a70",
        "fromTable": "Vehicles",
        "fromColumn": "SaleDate",
        "toTable": "Calendar",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      }
    ],
    "expressions": [
      {
        "name": "DataMode",
        "kind": "m",
        "expression": "\"Demo\" meta [IsParameterQuery=true, List={\"Demo\", \"Folder\"}, DefaultValue=\"Demo\", Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "DataFolder",
        "kind": "m",
        "expression": "\"C:/PowerBI/Astra/power-bi/01-dealership-profitability/data/demo\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
