let
    Demo = Binary.Decompress(Binary.FromText("jVvbqh3JDX3Pr6Q2dKnuj5n4IcMYEmYY8nwyPsSGxB5sTyBv+Yf8Yb4kWlVSdfc2rWq8ofcxVNdtSVrS0n776ev3b9xfPn9699sv+PbXl8+v7z/99uXV/fTx5dcv7z99ffPy9dX9+PrL64dfx/c//P31zcu/v+D53cvHd+7PH/+Ex4+vX14//+v1nfv544evf/z05evv3m7b5t1PP/yMxw8vn19+ef/B0Ub5sbVH2ORrfZB3cXPB/+8//82ba96l6qhtW38BjReQe/vy/tPn12/Hh4evzrfMA3/vvM+uFOeLjA5jdHDff/nHyz9f/vby7tsXlEfwLuPDC2ibS82l7GKSV8Txini9A2yCZ459BZlccr7K4DQGp8vV49NXjbEluuB06XkMzdbS04MPxic/9h74RfvUZYwv1+sOD74X4mEYTQGfFGV0HaPr5cLrw+OQ5rVRc8R/BRnfxvhmrd4/MCiOc4t8azSv3W99PD+MU8duveydjziQC7J5P2DHj+tz59221gczdnJxeZOxA3H8MJbecOVEbuPN838yavgNQRc/UMePy8WXB0WX68Qcwy/xBegSBub4cX36fLSJ5unzYGxfbs8P2PHD2ELF+aXd7nK3u5jlFQN+/LjcQ3wQQzcVuQC+PzYSLwDwA378MABELrZ9fv6LpuX6AUB+mLfgGzC/3wLep7cwIMgPwwAOrqOMI6AxmgYA+XG1/tQHhyTbZxSz+Qj+aOCPH8bq6cEXTFQHBpNjQMn90YAgPy6XnmC7nhHQBzMWXJSTp4E+flyvnB2eJxKPyd8ZPDJ4II8fxsIDTN+3sfDCJlz5EmX8QB4/rEPnS2tybvyVT1FnH6Djx9XS4wNermx9MGN+Wi0NvPHDxovHlIIX/qNOm6MBOH4YkeqM2MgvK/vWB974YficBpRg7QnAm2gLA238sFePvevq+YLZXAVwYQAuGHE29khThrnW5gp7H8FbGHgL10GW5+aolubJwdj5I8MH4oIZZTnYsIMTd82g4XMk3f0AXTBCbOqLj2PxKXbXJ3YeBuTCdYw9xbnCzp5n16kH4oIZZRvunWEqmw/wUuy85Q0DeMGIsxGG7vMINhys8dHFD9SF6zhbYC4lzEjhEfF5P0n4SRiwC2akbQ+2yNPtxemr4sBeNEJt7AdQJNR2IAhy4sBdvA60AfTOC+qxFd6JjB2oi4tAyzgvu8VumDzI3uMAXjQCbeuwmy+oAQDwEuTiAF68jrMRw5lSjdUXx0Fbbi4O2EUzxias3gcZ7sft6bkP6EUjwhLunmicXYWXnSE+DtjF6/h68rMNBHWaTByoi2ZwZW8FpG3KTDNYuoxvS1ZPYKYczwbme2jPEtrTtqL0Jy/P0ClpetnkbzB69haAeFZanCYxTLRk8wHUijaN625nhims2DxzAr7jOC6sFTASnTjeoPMFjqp5zSNgNzI6Lcl87EE5Dw+ZM8i0BvWUV2T+5KHYlfHNJ910ucHkK6hgOCQD/JUNVd5Ql1w+dQcTx87ZRhk389Dbisrz4vm2s9x2hW9TLpS3G1y+4tIYV4cEtPL6Ba3ZL8l8RFz3aeQxpft39TCZVkzewzVTHGQK89YZF3O4QeNjp6F5wDUOQxPU5Ljk8E+cAjSW0RJ09WlF4guMpe7RqXY+p7wi5xsk/uRi2T63ffqyZPCpoz5IDsJsnW9BcZfrisI3+Al2r7J79uVlOtjcblD4YxZZ84GOlm3J4E9BlX0Vn5JMXfyKwTfYW5yEhOdlPiWD6QaDP4c1vnQmg3rqJSwpPPXsN0TFLKKUmEuJKwqf+769UHh+T55Zf0k3SDxPzmlTkLRp6+5Kx+clhz/ZKjsctj3xFaXc4O/FSUBNgwUJ1Eq9wd9T91Nh+Cl2qzBWiWqlLen7ObRkrENXXrcVfSecOQkPwQG0mWhXf4O8x84lsni4ioCcxUlVWpL3gjPPBwrLvlbjYg032PsejxEUtcZU4w3uHvuxlTCDwzaz7JqWzL31Ms3uHXkRcXL3mlfcPfSsSfwDKpMz063lBmt/DkwE/6TerdYlbQ+9QFOnpbA/TWLkta14e+uedfoYRiivQPlI225Qd54eI6I4mZ7yya03vyTuhM1TIKUEjFPNNxutaHuBpXL0miXdBFtXF9nCDerOxl6dLL726lQS3LW4JO65V2dIa5PUg6oYXEsr5h4xtU9J6W8F/sfYfI+4j0RDIB8mb2/lRjUebi1PzNVu7GIxra6Z+8G9Ik2tuAcZ3W5Qdw7JCUDXIocjvTakIivufipJstGnyWO9KhEmed+5BByNpPheNQjT0RzxAmdJyoK8ihCGn8n42rQgN8rRWUbHFXl/riV39ypg9apALMoDsLVtHnovqkqa7kWIsOk7T+OFw6KIzMcgg8uKvRcwUHiXuXo21KDhyYsQYTP40HncJtWhhvmTjm9L+t5QW6Lp6RixbHrCwb0KEde+5qk01kOj1pe8ChErCr8zQSZQKMrreFpS+FMRG/aiF6cyhFWC5+OFdKAleDiaefSqQpjOpsLTcvCfQoTH6avJqhBhMPjnIIctM48THcKLDmGQeA8AUR7cJvYIL7TMiwhhc/hj0g0FgcmlDq9LEn8qhSPgaP7gRX4wSPw3p5+AXTl81R9MGl/hc8L+htAVQKGFXkUIk8gj+fRFK6NB7VYViGsa/+SoGbZ+d9WqQZhE/lQc4/CeYMMyPt4h8kiz1We2Tsd1+rSi8gUbh5cVr8PkP2qtxosMYbP53Esmm9x8RclFz70syTw9+j0JP+CDY6ejoBUhwmDzBV8zHUrCXdXIOn+7wegrlh/Lwey6+WvUUUHCiLUEv0M0Il6v/WiRzqsacR1rK84/7DSDYzUbnmTPXvUIM+Ce8sBREdcs1KsiYYRcguMir2W+jLK+ek4VJK5jrofdkxANFLvm0HSD2D/HPDjNrHmJF03CYvYn5RyO3rcJfhEkzJI8POa2s1M/kxovgoTN7L/RJCBFkb6hLbl96FcnJYCOOhWyvKoRlvRNEH92htqFOElsvAoSZsANnWDXrLbLQNb9qyhhkvtdxit95xKsVY64Drj52CmCJ7JisXsVI8xwm8D1YOGixOzXLnqExe1PeUXtYVZpoogRdk1+LxGj2cHpiZcbtN53a9OKPKS4osmkFzXC4vXnPJxjY5yeSrWIa19T4Gzr3t8DWcPP8apGrPpsdoILi2EPIa0yXhUJu9FmL2Ew2BGqxVOpIGEKgKWzSl0+zp7EXFSSMN1NgrnhoKTPJ2sRwYsqYXH7U62vgeCIpxNNwqD2FRpQ2i0VGZwv08+JLGFTe+qOlgZw2Or9hKwIExazP2V0GWsXS1VJwhL+wOpzPXZWCV5VkTBdjO/NHUkMFVYP1AjmVJYwnExFUpJ2RYWT59q09OVVlLj2NKfuFAYuuoMEcqpJrFpr0JehJtdvT/mR6hIGq39mh6Vnpbr9uOL0z+1N+VAGEFFi1VtzQC3aisKMECJKWKz+SRdAi0tWTcmLKmEQ+1NGVkvHvE5eb9D60ImxpiSEIKNZhaoSBqd/dneFkJJrfFNh4prYn5xVgDYFYjsG+xu0vo1AMUUVqJJauvOqTthdNqEjVuM7otRkx6pOXFP7537SUcac+483uH0EO4WT0Ep9mE5LJAqL3J+rvsgJ5+LzitpXcIuwA39cnvR0epEobGZ/7vXoqpRWI1SmMGv1Wy84KnriXnD3qlJch9pzXsNv4vXLwalIYcbZ52oC9Yxaplelwgi0vn9VkaR3BIoS61WnuA60+GtwExC7Am1KzU5VilWTDW98igVumy5HlAqL0T+5HOQzTTUWL0qFQekrGHk84KZTBnW4olTYpD51jUdcJjpmJksQscJi9LET25L21gWdut7g86fegdTZnfgL1SkWXTaYPIrHyszIpd3Dq05hKuCdUMm5s91MR68ihVU/O9df/Kmd0atOYQbaU/mpq9+ydVEpLELferV90mLUfbV4JyKFQeifU3DmgkiB5c5FpVgV64/zw95nZ5gXqWLRabO3BLauFWgqpUqFJQsecjioFOS0eqQyxaLXhhlA7/mVMNl6AUy3327U7EELt6ZBAjgYoCdVKixfg+qVpODUu3WkF5RUqDB9TT4KTAjSs2JKolZYnP5UvcidacUio8OK1Z9bcHvyHHRwvMHon+19VM+lb5xEr7BY/aljxndNdyZEpGqF2XBzSEUhUanRkKoVi+IBYtwWtJHVZzVZUrHCcDfPpZ/YA6wMbytWHzqtFsxF+CrZtsoUi1o9anTbbq+9D1QCJKlUYbD6Uw0AkTIqNSERKkxO/22xenZPk4gVNqt/6vcntM87XX5c0nrfK5ZS/xh1BKF1JEKF2XJz1sMrNt9kdL7B6lM3eRG0UcU5HH25UalHFkFj7Wx8+LmMrr2uKP0pG4K1cKCRKEeqU5ic/uk3Vih8Ky0jVSoMSp+PP3LCFW7TW6lIcc3nG3BDh653P9u3SWQKm823oYdP2Pf5SXAnSoXdOH/orBwNR3rxolMYhP7U/tx/baN1ehKVYlWnPycE+Jd09ryk8wFfwT8lSOEjsFGZwhLEQYilytx/GzQjnIoUC0n8EKR4DdrgRqpQGNG14NLKrnEwN+CVirNRdcKsz+P3aJL/g5Ro3YhUnFiUzMBsRNzgZRSank7ECYvMP9fHm5tuSpQJm8qf8t/WNWW5clEmbCZPSEBxvyptwOTl6EWfsKvzPBSkX6vzcT+7vGLzT4Ufzlwg64mxqTRhxtczIW/9lybSwEKqTpgB9vxrzthDXtTttxWnP/9MBv3+yudJtYkVn0+962X2M/R+gu6x/g8=", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Stock.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"LotID", type text}, {"ProductID", type text}, {"Warehouse", type text}, {"SnapshotDate", type date}, {"ReceiptDate", type date}, {"AgeDays", Int64.Type}, {"AgeBand", type text}, {"OnHand", Int64.Type}, {"Reserved", Int64.Type}, {"UnitCost", Currency.Type}}, "en-US")
in
    Typed
