let
    Demo = Binary.Decompress(Binary.FromText("jVvbqh3JDX3Pr6Q2dKnuj5n4IcMYEmYY8nwyPsSGxB5sTyBv+Yf8Yb4kWlVSdfc2rWq8ofcxVNdtSVrS0n776ev3b9xfPn9699sv+PbXl8+v7z/99uXV/fTx5dcv7z99ffPy9dX9+PrL64dfx/c//P31zcu/v+D53cvHd+7PH/+Ex4+vX14//+v1nfv544evf/z05evv3m7b5t1PP/yMxw8vn19+ef/B0Ub5sbVH2ORrfZB3cXPB/+8//82ba96l6qhtW38BjReQe/vy/tPn12/Hh4evzrfs2vZ75312pThfZHQYo4P7/ss/Xv758reXd9++oDyCdxkfXkDbXGouZReTvCKOV8TrHWATPHPsK8jkkvNVBqcxOF2uHp++aowt0QWnS89jaLaWnh58MD75sffAL9qnLmN8uV53ePC9EA/DaAr4pCij6xhdLxdeHx6HNK+NmiP+K8j4NsY3a/X+gUFxnFvkW6N57X7r4/lhnDp262XvfMSBXJDN+wE7flyfO++2tT6YsZOLy5uMHYjjh7H0hisnchtvnv+TUcNvCLr4gTp+XC6+PCi6XCfmGH6JL0CXMDDHj+vT56NNNE+fB2P7cnt+wI4fxhYqzi/tdpe73cUsrxjw48flHuKDGLqpyAXw/bGReAGAH/DjhwEgcrHt8/NfNC3XDwDyw7wF34D5/RbwPr2FAUF+GAZwcB1lHAGN0TQAyI+r9ac+OCTZPqOYzUfwRwN//DBWTw++YKI6MJgcA0rujwYE+XG59ATb9YyAPpix4KKcPA308eN65ezwPJF4TP7O4JHBA3n8MBYeYPq+jYUXNuHKlyjjB/L4YR06X1qTc+OvfIo6+wAdP66WHh/wcmXrgxnz02pp4I0fNl48phS88B912hwNwPHDiFRnxEZ+Wdm3PvDGD8PnNKAEa08A3kRbGGjjh7167F1XzxfM5iqACwNwwYizsUeaMsy1NlfY+wjewsBbuA6yPDdHtTRPDsbOHxk+EBfMKMvBhh2cuGsGDZ8j6e4H6IIRYlNffByLT7G7PrHzMCAXrmPsKc4VdvY8u049EBfMKNtw7wxT2XyAl2LnLW8YwAtGnI0wdJ9HsOFgjY8ufqAuXMfZAnMpYUYKj4jP+0nCT8KAXTAjbXuwRZ5uL05fFQf2ohFqYz+AIqG2A0GQEwfu4nWgDaB3XlCPrfBOZOxAXVwEWsZ52S12w+RB9h4H8KIRaFuH3XxBDQCAlyAXB/DidZyNGM6Uaqy+OA7acnNxwC6aMTZh9T7IcD9uT899QC8aEZZw90Tj7Cq87AzxccAuXsfXk59tIKjTZOJAXTSDK3srIG1TZprB0mV8W7J6AjPleDYw30N7ltCethWlP3l5hk5J08smf4PRs7cAxLPS4jSJYaIlmw+gVrRpXHc7M0xhxeaZE/Adx3FhDd5KbzvFG3S+wFE1r3kE7EZGpyWZjz0o5+EhcwaZ1qCe8orMnzwUuzK++aSbLjeYfAUVDIdkgL+yocob6pLLp+5g4tg52yjjZh56W1F5XjzfdpbbrvBtyoXydoPLV1wa4+qQgFZev6A1+yWZj4jrPo08pnT/rh4m04rJe7hmioNMYd4642ION2h87DQ0D7jGYWiCmhyXHP6JU4DGMlqCrj6tSHyBsdQ9OtXO55RX5HyDxJ9cLNvntk9flgw+ddQHyUGYrfMtKO5yXVH4Bj/B7lV2z768TAeb2w0Kf8wiaz7Q0bItGfwpqLKv4lOSqYtfMfgGe4uTkPC8zKdkMN1g8OewxpfOZFBPvYQlhaee/YaomEWUEnMpcUXhc9+3FwrP78kz6y/pBonnyTltCpI2bd1d6fi85PAnW2WHw7YnvqKUG/y9OAmoabAggVqpN/h76n4qDD/FbhXGKlGttCV9P4eWjHXoyuu2ou+EMyfhITiANhPt6m+Q99i5RBYPVxGQszipSkvyXnDm+UBh2ddqXKzhBnvf4zGCotaYarzB3WM/thJmcNhmll3Tkrm3XqbZvSMvIk7uXvOKu4eeNYl/QGVyZrq13GDtz4GJ4J/Uu9W6pO2hF2jqtBT2p0mMvLYVb2/ds04fwwjlFSgfadsN6s7TY0QUJ9NTPrn15pfEnbB5CqSUgHGq+WajFW0vsFSOXrOkm2Dr6iJbuEHd2dirk8XXXp1KgrsWl8Q99+oMaW2SelAVg2tpxdwjpvYpKf2twP8Ym+8R95FoCOTD5O2t3KjGw63libnajV0sptU1cz+4V6SpFfcgo9sN6s4hOQHoWuRwpNeGVGTF3U8lSTb6NHmsVyXCJO87l4CjkRTfqwZhOpojXuAsSVmQVxHC8DMZX5sW5EY5OsvouCLvz7Xk7l4FrF4ViEV5ALa2zUPvRVVJ070IETZ952m8cFgUkXEMY3BZsfcCBgrvMlfPhho0PHkRImwGHzqP26Q61DB/0vFtSd8baks0PR0jlk1POLhXIeLa1zyVxnpo1PqSVyFiReF3JsgECkV5HU9LCn8qYsNe9OJUhrBK8Hy8kA60BA9HM49eVQjT2VR4Wg7+U4jwOH01WRUiDAb/HOSwZeZxokN40SEMEu8BIMqD28Qe4YWWeREhbA5/TLqhIDC51OF1SeJPpXAEHM0fvMgPBon/5vQTsCuHr/qDSeMrfE7Y3xC6Aii00KsIYRJ5JJ++aGU0qN2qAnFN458cNcPW765aNQiTyJ+KYxzeE2xYxsc7RB5ptvrM1um4Tp9WVL5g4/Cy4nWY/Eet1XiRIWw2n3vJZJObryi56LmXJZmnR78n4Qd8cOx0FLQiRBhsvuBrpkNJuKsaWedvNxh9xfJjOZhdN3+NOipIGLGW4HeIRsTrtR8t0nlVI65jbcX5h51mcKxmw5Ps2aseYQbcUx44KuKahXpVJIyQS3Bc5LXMl1HWV8+pgsR1zPWwexKigWLXHJpuEPvnmAenmTUv8aJJWMz+pJzD0fs2wS+ChFmSh8fcdnbqZ1LjRZCwmf03mgSkKNI3tCW3D/3qpATQUadCllc1wpK+CeLPzlC7ECeJjVdBwgy4oRPsmtV2Gci6fxUlTHK/y3il71yCtcoR1wE3HztF8ERWLHavYoQZbhO4HixclJj92kWPsLj9Ka+oPcwqTRQxwq7J7yViNDs4PfFyg9b7bm1akYcUVzSZ9KJGWLz+nIdzbIzTU6kWce1rCpxt3ft7IGv4OV7ViFWfzU5wYTHsIaRVxqsiYTfa7CUMBjtCtXgqFSRMAbB0VqnLx9mTmItKEqa7STA3HJT0+WQtInhRJSxuf6r1NRAc8XSiSRjUvkIDSrulIoPzZfo5kSVsak/d0dIADlu9n5AVYcJi9qeMLmPtYqkqSVjCH1h9rsfOKsGrKhKmi/G9uSOJocLqgRrBnMoShpOpSErSrqhw8lyblr68ihLXnubUncLARXeQQE41iVVrDfoy1OT67Sk/Ul3CYPXP7LD0rFS3H1ec/rm9KR/KACJKrHprDqhFW1GYEUJECYvVP+kCaHHJqil5USUMYn/KyGrpmNfJ6w1aHzox1pSEEGQ0q1BVwuD0z+6uEFJyjW8qTFwT+5OzCtCmQGzHYH+D1rcRKKaoAlVSS3de1Qm7yyZ0xGp8R5Sa7FjViWtq/9xPOsqYc//xBrePYKdwElqpD9NpiURhkftz1Rc54Vx8XlH7Cm4RduCPy5OeTi8Shc3sz70eXZXSaoTKFGatfusFR0VP3AvuXlWK61B7zmv4Tbx+OTgVKcw4+1xNoJ5Ry/SqVBiB1vevKpL0jkBRYr3qFNeBFn8NbgJiV6BNqdmpSrFqsuGNT7HAbdPliFJhMfonl4N8pqnG4kWpMCh9BSOPB9x0yqAOV5QKm9SnrvGIy0THzGQJIlZYjD52YlvS3rqgU9cbfP7UO5A6uxN/oTrFossGk0fxWJkZubR7eNUpTAW8Eyo5d7ab6ehVpLDqZ+f6iz+1M3rVKcxAeyo/dfVbti4qhUXoW6+2T1qMuq8W70SkMAj9cwrOXBApsNy5qBSrYv1xftj77AzzIlUsOm32lsDWtQJNpVSpsGTBQw4HlYKcVo9Uplj02jAD6D2/EiZbL4Dp9tuNmj1o4dY0SAAHA/SkSoXla1C9khScereO9IKSChWmr8lHgQlBelZMSdQKi9Ofqhe5M61YZHRYsfpzC25PnoMOjjcY/bO9j+q59I2T6BUWqz91zPiu6c6EiFStMBtuDqkoJCo1GlK1YlE8QIzbgjay+qwmSypWGO7mufQTe4CV4W3F6kOn1YK5CF8l21aZYlGrR41u2+2194FKgCSVKgxWf6oBIFJGpSYkQoXJ6b8tVs/uaRKxwmb1T/3+hPZ5p8uPS1rve8VS6h+jjiC0jkSoMFtuznp4xeabjM43WH3qJi+CNqo4h6MvNyr1yCJorJ2NDz+X0bXXFaU/ZUOwFg40EuVIdQqT0z/9xgqFb6VlpEqFQenz8UdOuMJteisVKa75fANu6ND17mf7NolMYbP5NvTwCfs+PwnuRKmwG+cPnZWj4UgvXnQKg9Cf2p/7r220Tk+iUqzq9OeEAP+Szp6XdD7gK/inBCl8BDYqU1iCOAixVJn7b4NmhFORYiGJH4IUr0Eb3EgVCiO6Flxa2TUO5ga8UnE2qk6Y9Xn8Hk3yf5ASrRuRihOLkhmYjYgbvIxC09OJOGGR+ef6eHPTTYkyYVP5U/7buqYsVy7KhM3kCQko7lelDZi8HL3oE3Z1noeC9Gt1Pu5nl1ds/qnww5kLZD0xNpUmzPh6JuSt/9JEGlhI1QkzwJ5/zRl7yIu6/bbi9OefyaDfX/k8qTax4vOpd73MfobeT9A91v8B", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Stock.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"LotID", type text}, {"ProductID", type text}, {"Warehouse", type text}, {"SnapshotDate", type date}, {"ReceiptDate", type date}, {"AgeDays", Int64.Type}, {"AgeBand", type text}, {"OnHand", Int64.Type}, {"Reserved", Int64.Type}, {"UnitCost", Currency.Type}}, "en-US")
in
    Typed
