let
    Demo = Binary.Decompress(Binary.FromText("hZhdalsxEIXfu4os4AakGelKerb7UGihtCsw7aUNJLGxnf7svg6euVKOR2oIISEfOjqa0ZHkze7088N22i6H3fH8tDyfX//YnZdpc/nxY3/8e/nl9PPT/tfy+s93Gz9t/USO5nvnL9/T5uV03j8tx7svy7fl4XA+Td67y9e7DQH59eVweHy4kJ93f1/HOk335K4oA3ohjvvHx+nez1cgoOru8HDePd69/3NYnr8/nF+OywUuVzgC/HG/e77bHne/v+9/P08+Xal52tLYSBAyAWkZkXlmQFcjHK9AQVXLCMuyeAf0WydB/PpLTXhsRefnCVDLi9TPM7CrmaCjBRQ2y0JCR6ChLjroXMtHthvWGSZADTc+CJuBraXR+RUUttzoopMDGmojsuRrCTtugrQGEaCGmyCdQQxs3TFZiIDClhvSaUagoTZqeq4l7NVG0QToYPtTBnZ1QyxEQeFRbdgB/dYNyxJxk2XcqY0GFAFq1UbVGdi6b6TSHFDYTAHZEByBhk7TQZtA67mRfcMJUMuNrDxnYKsbJQoKmykg2sEBDW4kc0OTaR03GuSBALVSQBYpMLC10yQFQkBhs9NUOwL91g2pbJNpoZPQ0mkhATrItJCBrSmgoxUUHnVadECDGyl4bDKt50ZmGAlQKwVkkSIDWztNVjsGFDY7TceLQIMbKXhsMq3nRkdMgA4SOmZgbzotFhQ2O032zeyAhoQW2bnJtNjZN1KbmQC1Ok3mOjOwtTY6v4DCZm2kheYINCS0LPjcZNr/3CRArdqomwzszek5FxQ2ayPjJQc0uFGsybSOG9IrJwFquGFlGdjqRmqTAgqbdwFJgRSB7rhpMm0eJ3RKgFopIKdnysBWN9I7qaCw6UbGyw5oe9/kJtM6blj0MwE6yLTMwFY30rc5oLDpRlYyR6DtO3RuMq3jRns3J0AtN+o8A1tTQFe7oPDo1lkc0PatszSZljq1kfUpBOig0woDe3PelIDCQzcRaPv0LE2mddysxhOgVkIrm4Gt540+PQsKD19rzgEOMaBvMNekWsePWveOgB092BwDfHOP9i6gtlmgrHgEHCq0WmqiLY9L5F0C1kpqfdq6DHCNg6RIQW3z5FFL3gFuP0O9b/KtZ0mn4AnYwfPAewa4vqudIgG1TUsrHgGHKuli+ibkOpZotZSAHbzfvM8A3wSD9wW1R7cdTw5w+7rjqUm68p/PPoiAHXws5YkBrpa0QyigtmlJG48i4J3PpqiJu46ltUqUgLWqtFrKAN/uJSqoPUw8doBD4+mw3CRex9IaD0zADo5Xzwzw7V7igNrmg24dMQIOVbou5j8=", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Cash.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"CashID", type text}, {"DepartmentID", type text}, {"Date", type date}, {"Category", type text}, {"CashMovement", Currency.Type}}, "en-US")
in
    Typed
