let
    Demo = Binary.Decompress(Binary.FromText("fZftaiVFEIb/n6vwAsam67v6p25EBGGDXkHQQ1jQGGIievdWT/c66XLOhiUQ9uni7be+en789HT94W67uz4/vLz+fn167X88vF63D/Hr8Y+Xf7Zvfnl9e/ht+/bt18fr6+UetjvYsKJ+XSH+bT9d/7o+vV03gho/GzGLUyG83GMiP3z8/ucNbMdAmRkLt8s9Jezj8/Xl4fXT0+NX3/39fH3687rtkeNMVQbeQ/N2h6cieIgQcaYifLmXRO4icAZsCMjF7XKvCTsRMe4HCE2kVLnc23ZHZyJ4RGcQalYkruiJHCJoinCqrVgEbAn7vwgc90NGBSlGkY562IeLFTiswEauBeOOAAkdCZkyGK1x0bAMMHEnZvg45ERIhfshOhxcdPDQwdK4UQEIlBO66ACs4ZpqcJK4234otNYKhdWgh4mrDpg6mKI0tOuwhA4dMvPcwrnSIi3giTvRgdOPVl2G2e0wkZa8jPhUOf6vWOjAmtChY4asSIJFI9UIiTvJy+wuqdbqXnqIh4mLDh1VqlURQ3KkECmh78sUQeNuBboOTtztjoVqLCVyiXJ4uMjwKcM1pO9pR03osGNwLYpjumEJO8nKsBrNhVuJTKIfDvJixvBN3ACxSB9eLaHDjDaTRyi69x/VxJ2YMSs7zhAU8zgEh4N8MjqiY82x+0aYyCHD5higVmMMRO6IEnci43NBuTYvHHckPixcZNh/tcHGpXVUEjp06DRYK8meFdLEnWRlHtJoXigcDUB2eChn49wsblokMkie0FEcbY5SEtWxVFribvYsVnD3onGI62HiosNGfEOMBi8U92RI6PBjhkRjteJxNcbEnegYwdG5Me81xXSYuPoxZzprNHjhjnJClxnGDjrWIEvibvZsCyZy3mPr4aEu3TIK2irG/iy1h7eEDhlzZcayFygU6WNP3ImMqT3mJLS99rgdHupZeRCpwT7SpSZ0WS3hXjQghg6BxJ2kZfaYNiAu/SWBh4WLDBvL0MhjfoxHByV0fXXEwrd9kgon7kTGHL/MzlC8B5fDQ1vSMhpLe3lggY5qQhc7YnfHkMFumyXuJC08S0qNrFBsOPHDw0UHjwxyrOTo2r5ZpCU0vzy87RWnNXEnfsBcR2yg+xRTOExcdJDPbjHViB86FBP6frVEtfbdAjF1lRL3ha7V/mzqb1Llw0RfdMyhHlO9RbvEoFFJ6PsphmAeLzaKPaGauNtlGipic/UppnaY6Cd5ocYaz+jetuoJHXU6LUbBeGTuV2uJu922Up19r1Orh4mLDrG5XaD3S9dhkNDUL/HmLtQ5TNztZzrEg7PtM8fefWC0RceILyixXva9bJzQZctFA2ItGH6YJO62H910Kxb9Yu++MRYdn6d6haimwh21hA4d8vklJhJzJvrFPHG3ty0pKBbvl3z3mbHqGHkhbeoxJvt3S03o8jIFcucS48MhYV9oF6ToAaTLvw==", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/PnL.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"LineID", type text}, {"DepartmentID", type text}, {"Date", type date}, {"Category", type text}, {"Actual", Currency.Type}, {"Budget", Currency.Type}}, "en-US")
in
    Typed
