let
    Demo = Binary.Decompress(Binary.FromText("bP3Ljm7JjqWL9c+zeDnsfmmrgAN1JODsI/UTUkooQKgCKlMNvb34Ddr/OxlS1XLsyIhlPuc0o5mRg4OD//rP//E///2//tv/5//4X3/+xT/a//7Xf/vPf//5v/63//hv9n//x8///j//7b//x7/93/7zv/2P//4fP/+X//7f/vM/fv7X//k//uM//vVv/69//4+f/+3f/x//7//+f/+Pn//Tv//n/+H//L/+6+d//7f/+f/89//8X/63+vOv+tNKW/+l3P/Sy8+Y+6euo58zSin2H+/5rfVnlr3vb7X/PO1fl//lf2s//2px6Drjp177i7vzw9h+7py/o/30XmvZv2t8R/eff/U4uq37U+v6ab391DOXjb77nN9p/7rcUvpv+Xv0+PnXyG99f5b9utl+VhnHxtaz7LXXT1+9n/Z7/sbOn3/NOHZum4A9fuY4/OiT1+nl99yf3npt4/fM7+j186+VPrrbXA3/aa0xuu49xu+2f9eW/eff9vfR++dfO310tfe2X84/tqrB65b72xg7+/rt36Hn518nPZi5slevxaa9jdvt2fYtc83fwyj7bbf/2u///IL786+b33z+2N/sNt/TvpJntz7br71Pb7b887ev7+Baop00mxnZyLC/am+12mB4nddmja+ds9Rf/sZneI22YsMns2x2sZs9Y9lSMb60scrvnLbwdc/yO8LzWzQX+wVr2aebMbZuzxuF55v9bZbqtFPab/+butqjudjgdu1v8wJYztKKn34XFmbTXuv4HX9rVkc0GB7NHihTP7vzJaPc8dv2z+ilVz7gO3ZGc7Gx1cyCBb/2G6fGVtsa83cvLOjak1t47xXNxUYP21m12frsyaRr+Km9/RZe14bZRg0vvqPJ8Nn2H5kWdliXqdp8X2Zqn2ubpLW/sSdaC482+7b1stWd5S32YEAv057fw1LfZCmHPfRzCn9q0+6qt8zfsuyhNhu/52+RW0lWYjPVNciOkfEz7sVG+xj1/NrMt3PM/n5P/Rtek43Ybr6+1Has2Nbg2bbQ++zBcdCH7e39O//e3L4mmolNHQb4bGzaKcJws9T+aytQZytvp73RPZmJPX3aq9mLs1PmObLwNewQtFfudtAc253h20eylMME29T9XPaH9vYYbfHi94xui/a3zmYQ0UxYcluva3/RJm+zWLfbdrT/c3c7oX53OMJXMhFmmiPTtqXZsk9363ylTcWq0TbN2qOBHOzYPpk/R6s8m83usrPFTM2WO0zzSQZiL3P7P3Zj3SxtscfuVsxGwmNvMpHNzHIE8rpm3xo9xtQp1PsaPS6wWVM0EBaWX6Arp/mGMPO6OjRH3TZnfzu512QcZj/Tzk4mzN79nV72MNsQu9hMjb+tZL88GoZ9r63dsrXmMjy6rE7Z5bdxlt+52+/4WyCb1GgW9rrM1PGfsf3sMlPRGt1+OAH+jnx7ULQMO6A4NW39t9ZjMt7+2a4eRl37X/bGn1HaDRHNg6VipvljE8Wj5966oe9ulwvzO3Il89h26LFpmn6qr/K8dlfZ2pt18gJhxnaykGWbj0OeQ4j1Mk+CJ596f5depO0ed6ItSbSRZefW/OFA39j2XTLOUrifWpu3pUOg32Qj62cNjMC2sU3ZbJ3R9nftoLYj0k4BO920ch/HpCQzWexaW2k7634OJ5DNwzJ7tpW4dtv+rjCyJjPhVW1GNteaTls3bdskl9c1L4HjoPytlT0nWopNGpvSXnzY71lX7pgZdWW5bMbKzk/vyVKWHz/6M642Rl3t166fdobNew0jR7KRt1gVWzu2tG+lz9IZMDlVOi7Gd/hMhmLDx9ABtjA3mz0W204UszPbgnZLD7tqoye4kq3YL2bCB+fm8+XuWL/bHrHNRfq9fyZqthTNxD4UN8+WoR08Iq2WOQXu/PayJwd2ePBJhmJTxVVkZ9YwSx7TT8/NXYWfdhZX3d/gm8yEed6cCewvO5S0LZdtisJJZKa+fu/f9pglWcr8WWbY9jUX91vn/bYDwf4P8y7NER1/k203UrQR+yVtvMnys2BwEB28dfO8/9bYjrVoHTZVuAqdO06ufdMZNnxLmas+j9zfz+ieLIS92D9e75qyy350p5tfYyHGCA8eyTrseuHgtDXf9nA7CI6M+tqpJ+9omzMbzy87c6Jx2LFrQzmBLq7tuPpmc31Gw6TOtkP1ppleyUTMCyBIKXy/TfLHc9zX/DfWvJy1om3bmkYTsa3ISWGhRifUsINA7l9ZG/+tm7Fkx9O2eTSSIeswI2ucwOaE8vBesU8CgWNbu4ZJv8lI7Pds5vmH2Wna0XY/2lHys83ptP/9m3O7YKKRDH3s1J+j1bKDa//yBZUdtf+m286TaCb4bLggnVPXrHsoxjDzOGzlUaZtsd8WQquW7ISJOD+yI6JCxaKXeAr/pV/bar83PLsnS7H5tF1rm2Jw9Wiir8U29j79TgttanjsSEZiC8bhW34UVmqFm22nrtDAjtxwOdtSR/OwG2iwkez0Y/NNduI4fp/vse2eCeeW2XG0Df6RiIJwm2NevqrdLhbIDEKFYtcFc/4dvpNtdD95hp2Uz/2ySO7+EtXaYtmZHybqJMPo7lzLP/eRdlUwxbMTEoTNYGsY7aJzOP6wJW2I5sm+cLCedsifG9fGLC/ahY3kXDMbsBgGP77puLuNsHd3gqATQuaarKILZmj8r71Q78ODILsUOl+1WKu/tbVtGa3CPFRbx8qFaj+6mzCMRTyCG1XsuPy7IOy2i4bRBG5ogj9+27Qw9beDW9Ruu7iFTx7JNPBNzZZ5iN7W998193SwdMeum2gcFt5F47D7m19t77NYj3e52DdX8z2Aaea0yDe49bYno3XggdiC8p6HSFcmdpumrG6LQ0v86p3sw573N7Z6GLO1IfhXdjW1GKbbbo02Yg+2T2E7NMUWOm+beamVm9ScL/t/xM3f4TcZip2ph/uQ243QU65bu+1Uzls7bufdMc63NY2mYlcTswueQRx5PSw5XXFrtcW0Yz9cU3ayRlvhr5i9DEUXtjllpKzyIga3s2DFFTOXIdpK/Vl2wpjrofhkF8FZdtTLRkZfBFN/Vmq+azQW8zYGCImOA/879vajEvPduu/iMPqOHclUbKyZnnk5ODp2NfHFth9x7/cyJyPG+ObuRCupBLc/BCUefeqDq3mrd7LX7GIOZ7VdI9FK7Hvtgb3q9GA7PLfP1g7v2Jx/uysiMGJxbDSUyjkFZmev34BTFGtPMzDcVbMYi5liYGOTGg2l8pFa6WW31226KwYB/q8dH3PY/18xYrZAJRpK1XFgloqxdj/zDxfNtev22i15/178lmQlVUiW7kAzt6VTwdwuc+2vvR/7o0dI5ia4lXvVdtXVUWQ3s1572i2jm9yGrL4icnkT4trknnJB4tGM5cd+aaz2xCMgVAhLdhPi2vAGhu5WDe/yRuyW0Z4ABZsW0P3tjpsg1+aQK9eKDW4+4Xb7mZfPKrW7T4qqbgJdGW1LwOYEElt7y6uw+PPXbs9rcaH5Y38OyU2YK5/NnFTbSGasFtIooBseh3GkmDsTIpubMFcbvfB7zX20CbKL9gxHpDjID5jcttMlHOQ34a7vuxsB7cG/WPtd17hw9gUWnuBkfEcn0LXpkvnBh7Rn3SU3fxKeLDxpO83DV7P5g63YtE7bGpVogjD6VB2G5nqPX47SDupRbhieIFcNx7ngrj9M/zuRQKqBDuw1RjyKa0mIK+PNjWnaTvb4puOhnjZxMuyf7T5xFPIzPGGu9QqgAfW0U2eBD2MvhYSCGaA54uYKBl/DbuJoMAx/YeGoiiIFPlz7CGzUohUc/2Dr+OjBZhhvh5pNc2vfw7xt36W2Sbl+I3BaEvDKt8uqlxIMz2YWoRKLvswZGNHYa0nAayX2BCVyp2O/fVrHwc2xq3TZpbLjtyfsVcOFyJmn9M1u7FUrx5IdOXa5CIL5Dk8ALCjFYSb/HDyiUZISE1fgdwa8uSYA1oYOjofLGeMQ/zB/VjM+wXBD0FBrAl9ZJJ0ujpv0Lr/B5q2yymaFx6z+xOEJe8VN4RJiO/DTzVCZM7OxbgGLeQXR2+GejsZizwY6eUksi5Dc3yE+IsIex87XE3MTCXrVq9vFX/lj4b/Qor1AI4nYVowvAUmioXB9djlM/Bzh+9de1uba/uqONxjnVzQSm+vBWcjFT3qh6kg1z/QqlTFv5TLc8dkJgdVi2dY6/Nkyks7lg8GOh9X/DU0QrP2iLhTVPY72go9mK/f73AjzAka0k4TCarx/tvnjtkxFyTsMBIRznlo41/9SOQmGrUB6BFcHCEE+JcN7nzasA27sYgF23F8tYbF4krymZzX89leYCZBgm4uEWJj3luBYvTsJP/7oDrW7wWarA9rMGRNwBLLRTiy2NMMTqGiTPB2ktyvAHAfSC+YMmXMbH5zAWD7bXsU8jq7r6835AkGw0W0BW62YAEtYLE8HYy4E0sPsxHHzA3y9dSzgJYcol9MrmgszXh+A3ZrOFMDBy27DcQgAdm0JjzXDxdlrePf42FdXiXnl5hrbvx71mqu34rwlPJY9yHofuQ5VuLt5jRZR4MzYd0TgCf8g2gpAQDcvhT/mwFftr95/FYtYIBvvXuClaCbM5SWq5yR2Gz+LS48bubQEnBOcRitZit8EqhI56IPHMgfJdptNXjq+ewJi64OAAY0qF7ADXsQefEOzYK7+hqunJyCWuRYU4T9KEXOHFM8dtX3t+o/Xbk9oLHcrCZnxOQ2LNmY9xGz3AEXHZGVPWCyD2ThsEU7DK1+nm1Xbw/lXxa6gEuc7QbFmexPPerxchaOxExbAILFjflRXEPkdnvBYG74KL2PHAju7+fjedAXsbodERGNxqKKh2NoNMsGen77vwrcn4uIfM6t8BfSEx9poLj6cPbMW923tiBGP4ZA+jInxkdBYhrLrgOjMdoX52+/Y5pYTTgxbL1uxuDtGwmR5cXZHVaZVt2az85udZUGhGU3c0iPBsjy68Ej7mzABfL7uAQcizd85CeM5PBIuW/0kwvnn5j5bDh4xu7zSssnNnzg8YbMs9x5KbG/wlengytq4iKT0LZozj6fGmUvobNUpZnvMf2wjyFexGeMOO+WS5ApLNhI2iy9PJs9399CabTuMYZycseeJEFgdCZgFnrBXXu5odcVhuC7X88y28hYKhRwPVI9oLUNECGD283322ENb9CxQ1sAAIY0V7QWgcuNqyDUfvuIVMAzHj4ByRTSszoTOMhwzOzGbWIXcCbkwN23F1FidCaJl+CXiIgIyD31ri24iEsC53fdOp8tMCK3mnHwPf+q7gZbd1SScLBY86VicCaBlzjtnkSZtuLfDGT6wtoa3NnRAfocnlBZkBkjaYanpGaoxC19tkRCZiGCpM+G0XNqH+4tpm7r67DhQLg0P8+QvTjCt7vsGjse27+UhSudqi5yNxxS92plQWl76ls+VX52PUBf7w35vlasXj7SZkFobPa5OJByo9kn9AisTxMxttpIchpnw2spX2G0CMgV+5bfQ1qFm721jo2+5EmJbyc9PzFI/fTictQibNn/N/Hq7C8NirwTaMm1VWbk2PMVPNmJxDLbFNRD9s5Ug29pFSagKcOxfT6Wd72ruJVTt7HAqrITZ2kMnl7aj6u/Sn3bl4sTvykUYkAJ2cbQTrnqlAa6WScfZMif8kjBjW0dnYyXI1sYuRWzAlqSanD3Sh925PBJgbrfoHa4E2TKeYHlkWoRZmoB1C8NLsXg7zniCbflwMhYQMqo2ll6/maetpPnadqble2gl6BaIgeQyjCj2qjt553RnR5xir/AbbHUl5JapK/cljaYDanYFg090IBYdTp+hO6G2DDV7xswXUYA+fMtPY3o6PkvcJDuhtsybzlJ+wX5cEnvTQzoalkHkde2E2ZLklXNgU8eStam0kbm4nGjmc6yxbcl2sJedcFuQHTByd03x1ap71fbh3Ki6SJLHsxN2C8Vy49xZ+AbcganCHhSWB78sWNtO0C1PhhFGooATwDaVdsnoUCA3JLtiLxE36E74ba3Cqt/dP1d1cKg+spL9MoC9cD7sBN9WJzqZJ2OPMFdaITOsMFxAMzV2zN/QBN1WT2ce/bEJkZc7zKPnd9pTLWgecbUTcMt3Q92x4+Nw3tvgKewWUAy60zmntXSNnATfKrFvDsILhqqHcOt6tIzLkvhD9ST4tooe9cNht8yudnm4kN0lDY7MNINJn34SfluLAw3iw/y4u9aU7hun2xUcXeuTsNsqaJ0QygY+kq6t8S9MzkLuLTIvTwJuGQptcfHnytuwm1r5gXk6fLrIAUyoLZ/LTcMnE9E09xBJhFRlZI9t7Lg1T8Jtq3KS8NJwv8wA5WXZLpm8N2cxBJMwOuG21YmAQ3+cq9A3KTeSO/ZPZJT/hibMthZPn9mZA2fWNqQTGOVRYiXKaiXs9CTYtoLwdpAj/YwijoXtlNMFAPZD9DjDxN0E3XISgotwD4wPXaL1+ZyrW1i76CLeBN0ynAU9kOug41yBp4urBETzOuQQvv8m6La4X6vUNwm58Sa+etbf5qb2eBPdhNzy9Orwo1//7qjN40QJnMSRkNebkFvdAk1h3GC85/AsmhobyoZ58dsio2ivNyG3Gt/JSuHI98dSHs5HP3Z/n/joBNvCIcKHdnIfXByNHjC2wKybvXxPp+pNuC3zZkZ4NEfkpTx5OcbL7dh9sPhFf8MTblu0o8QLZ7PaB2vZzxAsNo/FFzehmDfhtux+mwoQ4/aNnhukXyGoq+9eIc99hvPLo9HAu23f+3vsL0exiFBwpsL4FsYnABeuFm5be+7mdGZ7J7N1tIVXSXhmKwnB1fPJ6mnpm285+4+levJywn4LsWwrCcPFXEr/kj+W4vd+bca0HOI1pZdPEC5z18qDaxzUsxBanOF7S4Q8gGWiyYBzO6YXyIJkFxbxo3nb2/Z8j7OeUFxliqlb4I+dvNxm5CqUKQYBTrdoKwnB5a3tdCSO0wo7Y/jITLqm7KxUflESissj7n0ckHqdqNigBxWhY8BVgR9ELiXayzaHs37X+7nKtsp2xJEps/so3GSwGKKxmHeFTXME4ShNubrQ13D3BSOHr64JvVUOfb+4BF6ikK76W8U5tpMpTHZN0K1Mu3w8xebB2L5V0ZTts5Wyn60m9JZX7qR3zUy5FzwoGWRGQHnsSjQXImCgbKJoKFvZmJf8xNf26QYof04upLAw3TXBt2U7tvYoHeuDwBYY6XbW3F4SR4mzN5rKVp4cGxXLswl1ECnsYCx2prabt2dNGG5ZXkegnJj5JboSOkx+DvVic7djTgnwMxrL0mWMZwqBhOU+0zHf0iGYxxdPAG5ZQol0JmiXCrCwbXaZtg24mHZISxAuEfr57Ota3PG5tmRc7Y2YsIcntwTh8s7kwpb4HJ6oh3+ma/FQgRE+tyUIt/hp4OS5vf36HCJn2qFe09UPMSnayRLl+uiP7V8F/mU4a6V6NBg/N6G3fK5NsO27zv1dtEp28k/xueboNo601N/whN/q2eK92AUEHX4tXYAiwuE4dqLYyLaE+BaNZJp7Tc4TzqP9w2oeF1iwpyuQVLlNQ7gCyYtHO5nyz6vy/cX5uHAdgIY4jfeAFhwrOFpCcWHE7c+R1vz7OQf9q80HIQaN9RsJxYVPOpkD/szyOLVsCjuRQHPDe/cE4grrIEhWVmrMdzj0VUUyW6IBxSOtJwyXzyaHIwPH+yjXfS4LD23qRY82k7O4KN5EPYG5xdFEGC3zQ5KF2AC6u8e+0V0lJRLNhg/ZL46sXT7Tvk1Ttc1nbr/xqQnELQ58kytStrvfl2evwhrGmrtHCLn1BOEqfccwZnz5kbTnVVWEnSg7JHYgdUVLGUrsg0zYLhNWMg7uqYXidrIEZgAlG9FEhhu5wgoO3i0aS7+E/PylmVw8eB/RRIYun66al/HxLh1isThuxqRp6wm4VdINOrz/2EaYmucj/PC0bZ8b74+RcFtGQ2hgLguFTtVTj+bZNOBT2yN25KTipJGQW+IOYjm/ciGKFnH02ZdXEd2IYxNuy5zZF767b4/5ol5IfZBIp9ydMDoht5rxSpa5cQV9a5OUULnH/immittIuC1JdNVyELdwgTmNxI4YoUnFXPqd7r2RoFuGM8vOo7T4SzfAhoA98Nbt4F6/8bsTeqt6IryZVyMA6Az63sT3sWDd3I64Ygm8LaRQtog7+lk6FFZZCyf+nmunUqzmStgtTyY1fQSzUGUpW5nn16sXQZBjKdlI0K2YB0LzKTghIVjcWemiFnebRI7RsC1ngm8ZT9HHBMh0SrPFoJWw2yZ+jXSGzoTcasL3K/zzzLpdCeLSmZWMkp+akFu+GRr2cf7nh3NjF8ZD1yzua+EQmwm5teNGWXXKcjHTD1LelaqANx7fOeG2NnRymdt+tZPbtlb1ih9zvm1VbLY4C8M6z4Tc8mDC0Q7ViJqAuYX7mm3IeM+BiBlWeibgtjTxq16G2rHuLe7mxEeyQy2NTaBtaQ7jsakLR1N/rFOKSkHIit2XiaTVZgJteXezL780PkVWdt3D4ridfNaIE54gW873tT6eil9YtgJdj7MIaOSDfyXQljfXHPPHQw+ISjDq5rBt+VvCyATYMhJHWBiBQFK/NRan6J6kRGKB6EqQLeQHeynqtEHQFLTAn5zCOkexIDl/8kqArch2MO+gvJBAK/Iv7nwps040kIolE17L00lWqgBn4oQ70D2gg9kxvG38XSlMXQm2FXfDK9M6yK0ueZK9pYrft/KMJ8SWv4KFkUyamIifCYCtXbWbHUwoPjohtgXEuKhWYesagOZkTsn+VSVCobY1Xrorgba8eFd1qsKAR0mzGNFjADJbiVhAaX+0lgpIyqGCk6EyGsKYSoRpv9dCj/DknQBb5Qa5O8Bsh/hVdqRs4CA7ftZKXvwOaO35L72KskkQAJu89+IYeb0CiK/NwE7O+A5orQ9nuoBn+XYHZMxWuviT5aIYEG1tB8hWw/vC0H5EmVk+YQcsxVwhgqc4NEC2GjqUY+766fOIfnI5fZWUg6Md0p1Q7r+W4i8OHQ7oFJRaEgdUktudQcjdj2rA45QH3FbjcYYfpfwckhqbMmK2D5HnTJHiDrCtfzaXq+hUsCcEQ9kbqvTIgkNyMoFGCFHyaylvzV5JHwmG5uijrdyk6GluIomQHW87ALc+nONW+WiKsN3D67IX8+Y5EUNBICSAaDCq/PnRAcDtK8/SLoBKpnh14TLh0acmc8F3PzrXxLf1xL7tc/NvtoqxqBIOx+JpyVwYfhV2bhyudyyOMdzUL0X/odIMFzSaTJGsQ3/LVhwtLyrauhzMceRI1lLE4xvQXHG+HeHn9jLvx+KP6FWemeykqFLjq8nwCCQWH1cFyOXMWmOtSDsrmYoAvk92fD8Aalb2BuDxgTgTCAVgs9FUHi2cEmmhh55fWARtTks7rSdk4pxkKzB9rmhehxS/UykG9slZZU+nGirssnOjsaCI0ZzwGuptt3gFCCdYHNRSrH5LNBcpYnwIZsvBJJgvqoUgpAjTfmu0FPQoJHEAGAG6IpR7m1cvHuGwez8pceB2B0vBAzPL1bEJV9Y3GMxg3bvmb4wRWent9mgu0tKYhHs4xUco1uqUq3LKkpcJNTL4vsFgeHPwI2IszkVPqwCF6dK1KTNnPoJBd0Z7+WiAvOyb/YpXmw1LqkCB5WKIUfpd0WA0fohMb2ttXktzziyRDCI2drLvDAHeHQ2mOSEfH46ffsRptwDTjiQVEdoviilyimuiwVDgsb4CEc09rjtfzd1eFP3Gg/XeZDBHvCFVnRALbn38IZlCJmzZidFieoA9Fa3GhpOF+wT6D97fdqwpNw9qmx7fS01mc5TL4o6vGidrL0VhNwAXFflReKElqzmiBhJYXgq53rl8oTUyH2a0S9oRf+N7shxWsX4o8e2x2gtYt2iOFpiv6PwwQ9FyDtX3H8mJ6d++yfVCbrEAwU6scKn0MpPdHDkBDnJ4DUftiEYMztY5I6EeCkU0mSNgiBTZBnetr+Kn2CwwXZDNd+LF97KT0VCWOb3MVPzAl/uFYiBJk3Fuj6IAYFDRah5nuVf/Od2BX9vtS6U8x1znGt//JqvZIqgn1Hia5crrsnPKbuWgEEI1WDSZ7ZRhZdR2E6++tE0oOVo5ys/8Da3JXmBvoLXjf3QxwKoDrMBnDccbtUzRUp7whHKBwBO6hs1rOAPXy07LaeNDOV2vPZkKOYZNffxXTwBsn0SKzbrFRCV+70h2snUgAyWpiFHu5rYQlnN1tH53vE4I7KOlbC8Ju6rcHJ5q7/VoukC6z46Zz15XMpMlftqDSaYD5eZ7meMDWnUIS0589k5Gsrg9H+p6PXu2Beqba27nSyiU6fUk+xBs9sHYa3POEDJWFg3NMlNCptebzEOROtkvImq79by8CYyhkwoqu0V/iaRotJAlHMyLNrpC9qr0POd7HZFvRFoyWshyFA7669CPHybkoLjdSsXRi2ouLRmIp0K0KeGiM3jNJRmnuWxDx5wbSkjRQoAdPSKxa0fZJx3Cp3rB9mgKf4OFtZGMZPmlLc6r021RcqEqaJfVItWIPEI0EAtZOUQ/8mG1fE4SQpGDOgOOQ+SH4cZHI5l+6yL1ptqoR+trKhonzDiFcr748TvZCnGUnEv/cfmdZT4Ap4kdj+auBq4VNO5oLVPFoi9+rf1jpSJkHAsrStKTaTcZC1RloLztum9NuYFRSZ5ha1h5YopRPhxNhl+F28UfvwHWNb++CHCi7iSMrMlanNJXRUs4ZOZfQFJ0HNkscu3GY6G3ZDFTMktNlaq+4uYzt19JSrA3w/bqPdmKF0GP6qJtLlm0dj94OBaHzXqSpfaR7GV4jQ6mQix3yzkfQ1+4AdfcnwgY9D6TtRDYuxQEP/ZYvXnT0wcpiqgg1vtKljJcyAsuBs5eUZLYzsIhtlJfYIuRnw1OG22FydFtK92N7l6qRbBP1cH8xrOy5tJJ5gKI2b6yH6+6eJpRqTQanQS2Spz6m8xl6BD3JMNWMdocdhRfJEOE4UbBppLsZVD+pAwcP8PTvKsXEbYo3CcOD9M+ajIXG074bst2CMGOc3/Wphh7q9aqjLWTpzZaMhuyHA0sEzzjVdzY3x2q1BWFakYKLQX30W4QgvQoGFfoVZ1ifSLGWcxc944xZR8j2Y0SK49h7jmOZhEVeVFu0ng+jJlspqMGI3lFDG85s8+mu6i4t094FTG7g4VEm9ERSAJMP3YayuaK2TkhBdB3z07i2MlmlN79lFd5oe9Ywn5tPm8sMMYmo7V0VXF8Sh9V2PWjaheAowlFb8XBN9lLz2mlVr2ExC418jPy+socSUkE+DDaTHfRBXSQ+KmqgDzd3VIz7ZloJFQGRXvh+MRY+DNVtWl/cxL2mytqXm60ldmSrYA31E8ZRW+fioDavGzTj4uoTdaTqTThBigIgHI5YGLmSJkQG9fiqZEMZo5kMM2xmheRvRqQPYAsOCMO3N+obzZnshfySShxqEJYDrmOqOq+sa05xTPhNp0rmYtk45LIDhQUcBP22kmx0NzJXjxR8smoteuRnPlSXaDetmgsAVV9nmQyTflL0YcpINLDB2oPF7frFHRn4uibrKXJzp+42oOplu1z0gZmhuQr4sm4SrKWJhIOJCr9OEXOIvchPHOchaReGJ0AXer2XFkNvKk3FxcpwjuUJZole18rAboMV6HSeV6UeMurkfIQDZykWvRfVgJ0m24i1APtz/UrBYkvSd9CqA2LvRKeS+QLRcBVAEgX6GhhkJLsWxhAHJ7wXCQ+wCyeDlR3Mmo9VxEBmKjZbI/DE5yre/J+Zm2M4ZoqFnzjv9hwsQzC6ITnNmB7iHDk6WsXEt1FxqPc2RYsbfCVwFzG6mTDULjTHa+5pAQhZcxpl2Pa4Suhubw5f0/3qG9QihCgxdqxdKPOGZspWkp5OUj+vMJq8zMpzwLoCm+8E4jbVOMDMY00dvUqQvQHleG208Fu3xtHJwy3qfbgQ4Hsnp0SoU4MP3Mck8e0E4Krwe0VVv186rqqkNhZH5b7NzZhuE1BqmoQ9eMyMGZhwj/3BVINsBxVD9FAijbj8hNtNkfsifap+rQbcM2EMOyE4kL1gS68hZt7ce9A2ULxO6UYMRTbCcJlLHYP8kzh/vBHz1muXwGkLmKmou8E4Wp882I8+1+Qbt0/EKY6iZOF0lE8EXbCcNHIcThFcjLHbWy16XWTlK6iQhjM7CQQFy3nLTEo/xnif862dAnYYVZqlqlMQK5UJqiTFB64n3Ci/Azp7R0ztuiknoTj8mwqlVxE5yug4xITNgOjR5Ya5frBYAjgJAoi5mndjoQepq0KzRtZVfQkHJc9KdScP7P5zYfCBBJsd8TCS5QogrFIVETcANVG9+W6WOWgCuVy2uORXz/jE4SLd1e/Wm2u31qWklnmu5iLHV3jk9BbqWoMCdj8CZ1LD5j8AbqxQeISdYRoJ0eyPZA/UUW2jeXYzjH/kI2F4f0jojkJvCUFScgutlP1pNZsDulw+9WEId6E3DKWaOSpQI8qFeh2KL7g/Lc9sUsen5BbWFZEU1VxBNoQPud7STTXfFVSB3GT3ITdAlYgX3qkTDx1hm9or2T+y0B9LUz6TbgtY10zTnkYEUcXKL/thNthtcU5uwm0Zaw2V4lqXpVgUG51Xf22PD7Btpo3bS9JqDmgZic2n3oseu8Jm7oJt2XOWv1WdpnPooL8jnoZRce2b1c+2G6CbaUXjrHwR1WjpKCVIT/ISUczvQmwpfZeusBPmuPJRGz2M6kJmxLzV0r86oTY8mRqyo4yBdUJnEOu6J4QeULaGRuOhrKliP+RcPn4tAsGPREIMdWN+fZREmhLHnAWgeQqpHRCifsma7FsoXxylATbom4h+qrGOtXKvn9amG5mR/AccFcKBaKhbLFBXkXZLWI2VMAoNRiocFpuHJ1QW301KM3WzxAvgHKJKv5PM+9n1ZiVgsERTWWLk/GSxq9CuB6QW3btvuskHTQ+M1qK1Dl/NEWvalMlJ0TLC+HjiL6OknDbCstVjE8lUrvnfUl7diGZtlV30vQnMR1thf8yH+XqarVt3iU2NykojAA9jly0FfMXpleL4OJvD0LstJeE9li7rptEe2tCb8UZdfXL7viGxzCw+UAzT4EvEMhioyYMV1Vd30qA6k8f057puE8DVAtLXhOEW50nDcmhqcBbpjpR6FBQOBBCC7NeE4jLrFPH3GWqXet9tmu3WPDUd/7uBOBWp+9/JPndy7sbNUpPmM8TY06EJaKtAMG69s25EkRb4mZALYbWQGXWTb0ruCyjwXiqvas2BWEVDQcikf7C5StufPkE4FaXxX4ibs3VQcgg6YNPR+8owBzQe6PFUIxThZsXKO7TUQ6patt8npJEtWvCbxlr8/VC/en9CODzOBDa7C6L6oqAdtFYpnTjvPz/zfm2E/zXi5bJ2AfYG8XeaCtq2/Bpm2GHtQdfGCopod5PFuJEJzkay1ShqYdPgql1eeBcmcdaUyk7JYfRVqacy+fgmc8g35TDWBxmwv0bvznht2hrQG6QnSKdKyEa0TgbK5dstCXotnpo72C3uTq6s2v3movSnRvyNzYht9L9vKAiQLrHKRlboIjtOTDnbJ4t4bZqVoH/TqTNw1xYY94hQadu/5Q1JZF4i2YylByA4ty+5G4L0cV6vTX6KUi1RBPBMZyPBOOsV+SdBHV3qT0Hu+4JseWh3ikDXF0Bo4Utz5nsLQapoyewloeOm93o9Uy69hFVbZHSi6YxVLtFdunaIpkDOT0V5EUO7dh1u9Iy9YTSqs5vfbjkFvF7naTddcAwZpYoLAXvBt3IaCEIU3wquCy6FugHt80m/wjqDUbdE0yLusP6Vn831/Lda7hcabkrJN5GTwgtYhqkV0VLm9dbkhyxH+wKuj2GDaMncJbSDspXhvxHfapf03WoxI6tOZTaCL8hgbQS0xhZbA29LqAwc0NvTL2BcEUDeefldmlZFZVucuhD/IGTcIwxEjbLdIm14QT+OxzkLGB0CmYQqAtwxhgJnOWt0R/ZqZdBgTIwJUNzbHeUODwBtEhCDFfFlTKuyvwqXRg4fW9J/WOQeI82AsB5viylDw9wSruQXAwAd7xrRkJnGd4/XWS2X++nT4qmhzZJjXOWkNkqIOBl8K9CLTO5LYrPJjSPIxMoS3gn99PZg9yvmu7Tr/jFdviKQxmWeiRoVgIisOE4OveUI7ptmpYcjtLSlhwJleXZxGCbrU2t/nwwnYQmLXgAWA3cJrQDo6E4mdtVpKorpALOEhnbG9yk6z1mAmX16PoqrocL2pqXIhfSPKmEwY+ZEFmKsjlF7Jdvmj+8erEDgEPnjqnbNSCjYyZIFlamytGcSGdOo8PJV3X+NLSCcxkMdCZI1p0YVabAmXwSp1e0Rfwk6S/3+PSEy+qjWX75vS8uF17Y1G7HAiD82ROfn5BZBOfpz1MlImLPk/due/sIQV9LInfByGdCZvX154uPLkeA7LZGTk8JAlR24qLPhM1K7x6usAtxFA9wu8oUDxBOoMmglRXtpWp7bqqBwDaKixhzntH4IrFF0L+N5lJFK4YXRBuKU/2rKRl24uSiq0FctJWwWXAIbsePblh5scPeQ+E8XdDM+Q/ET6qPotEUl5KXb1PlAgOlH7hlBIxhvVfCZ6Xt019ty2Ohk+XhDG83AUBjJXCWRyqjRUHNlZUo+06kBNianPaVsFkkALdouWAMw+ufGsLRqPjue1e2sJWwWXHtMBP+zOpLjHGZZd0bK0OoTIi2IekicTWh5+Oyen6tbKAPWJjmRveWpyuhs6o26yqVOKe4cFaRrFz5RdF/2fKnjjIrgbNPROOpUNyio2F9FKOnSxtF93clbJaiaicc8gLdOXsTriWZK1sNhAXC6J2Q2eIQ5Sc0Xvs4gIPyLrw5m/Zd05m4EzYr+lhxtWp4o+5gzXu46O1CoB4zjE3IbHEJxdcoQcZiI0RKnnafjnQL7ITLSjhkSgr3VtWRutZ1odHCUX9B0XtDmcjYCZvVi1f1VpzQ9rxzQNuotMHbHRYstkjAHzshtMXLKl/Huup9HqqoVdL+Rs04QsNc7sFmGK6Ukdjknooe5nrLtWfKRxyaAFoJf/wpCM/jlYLqLXMF8SAmHDKTYyeQlrzNqd/SgeYQb58vxbQ7pbgrTlyCaIHDubWH/9EWJ/uANJPFyTWqIVDbHI3liO+Bl0ZGaLmIhN2+W9wDe+2W1dLGSQgtyaKCd+eNiIrnNc1zuGqRY8Nn4nYBB0ejOeqMUVX6zPnp2hlmBpLBMtsTXSW+fgJpJdcs30GZRjl59r6irc5UJj9OQmgZqLyY9/Bs/mA7SZ+B2oLl4/gkgLYcP54+paFD1586YxA8TnjhAegcJ0G0fPVUQYre/iPIYHGRyns6+ZMamRPc1NFctlow7fenFCcUAxvZCX52nrCE0YL4M+GAAksvr3hgH9d93JegIlraSRAtw5UsB5KlaZ9Lyh87plUAbf9AAV3sHZVwWpQ7lp9vF8qKLZPm3a6OJmarxY7S+gkzfxNSS4GnVHm9+8LyckuaaFY1WNuDkD2QwXGLo8W47nNVUag04/x0ttNC0P5qKkfY8RMSZMsLEKl3kCDnF/EL1qGmirqCI25xRF1vQm2ZQ+2xJmdkOlbtTG6sGMXC3HXsJtSWOSTV9diMdqgqb7nooUOkZqG7mX6EKm6CbSEvsGFUvtE+UswO+Zr3ms/4m1BbRB5INnZ57PU1uZxr+QFPV4S8dAmzFXNifPMDT1NSXWcFIYpLEffcTbitFP5uOp876hRQBAfvEHx9JjgajStqPQDvSQsju7KZsYtETwyNZkmILV8NTF75M1xZibifYgqJjwQ3Gf2oaCxLdzg8wqZuXtel5acX/90OzLLjkxNeiwKJWD4KJO1vnUc0UpbazOJWRK3iinEPRWNZ7t+7+sm7EbugljMzIoXUWjSTKTErAmDQA1f46Qf5LipIbiFUKPHVE16r+u/x1zjJJSmrmh8poTaR6WtxyRJiC+lEjPKjfTo9QDKveMuFXPYfUoM8KpKisUwdzFvE8jr9PkVMa7Fh7ITpcc0SYlucrvuMZXrjWnUy7NQcUSYUHlsTXuvW9SOM2bt0QiQQemeeZFLgmjWBtTxqqSJIZYCvZYacl6uMg5y+ODyBtVqt6wTjvyJZyky9c+KxYyZlt3GPo51MtcdDyG7a399HoozL/IKr/md2D+weN+esCbSVRsT59JZ5HOcNYZQ2VEWncxibUFuVUktWmMSjXU3ytqFTOcoNezJcSSi8RUPB0e7KEcd+VeVTp2qLuFNMN2tCbovzTim7c6Wi5UD3OUrNV4kjtTjxCbjV3vBkzHG9da8rKxc9SioiK/VFNc5cwm8lyrdfvcjVsu0udG4e6jfDVTZbgm/5csKjK3Egrn5ZuWpcyAKCHLU4OkG4KsTCbRPs4hwM0ijsSbtLeoreUf+P1oJIG1NYpSsynxQWdboEJrbxr9et/o1PIK7G7G+l7fB+HRajDEBU5HZL0i2YLYG4ym3OV1jtHqvEmGYVxSA185ktgbjI87GzX+uK4c2uLJBQ/qcNXLeAsiHIG22l+4xzBdts3qcesK/3IJhbvM8aXzyBuRIH1MuoEcLxCh+q98S6mWSPU1hLxi3aCiHhUfUGh8UT2jMPXzp35rnYcRu97dkSnAuAYK/+WDtnOGWoqPUECh1JbW72BOcy9n7VifvL7Zs3MNnhDb2jxCqYPcG55fXR0+2Nw/5KTodLDDV78xkLXmdPcC6KC4A20tb/eXjAHV0x7YY+HMB3hEqjtTRJ1VICOJSJe9IJXVyESS3CjbEdmi/RYhBXXU+Q5MN/IQ1FwKWC/DAyobkSmmjfM/kJFFk0uwWb22DzVAMOwD0XjQVGHekCbyp355N0/AUS35XujvHRCc3V2PItV32KyrqCkNjtzWnOf6MToFuemHQoAhiqN2GrUnoY+372BOYWtVj12n8u9+U8eOipZrj3WoSXrs+R4FyWudWPfmd3ES1EKLk3j+30HkMbGNjRRqru3tdi7OkCoxTU2Vs0ruejg4mNhOcWRx6SWkMFQSbcWci9xqEJyy3VZ3urZcSPgiLofVSiXVG0wH5KGJ6w3KLACQKcJOlw0BSNHkQ9RKaYEt0JREZoH9FUIDtWoR9NIrHz9UNY0j4b3cLuE3vK4VVGc6lS5p+pvOnDC6gS1g/370hIruOm39rg8QQ2zqvKNquHvhoyNRB1osVUpZmVZ6JXdH1BBeEMEMAyn2RGAimJx2gzVdvk0W/cQR44hwrvySdEhBMh/q/NbEQXpBz6+n58esMVcsaA+93upJkO5BnwXB8vv8WdxS2zmc27N41GJ/tQr4KH9TUbDYaQ44HYK2puaqvWzfxTUhAP52sxGonHpDhWLfFckBHHXjwt0iZpymbAdf3BrnpAPpCG10/9rEiN2fzjOaMMDkq+X2vx4d5cVNqj7ubCVDKfZdMEKrUVngHb9TenDgq0hnY0mLkjLZwwqXp/zgDp+lRL+1qqAy4xAXZOHeSkkC/gJXMGOFdDqe+FpSn1Mg9EpiLHTSwW7eMm+1CTwm83te4dGDaN88A4odDsdGmuksxD0dZXA9ItmyIR+AioH8QSZPzuaB1FTVk++6K6FIqtl1ACO9XMw4rzvFqyEHXUepnbXVyjrrpZljlSLxwoQdE6lCj9kY3RndMbktlJuFTEbf5CPIPXSKZRVCiJb6didxfyL5C4q6SJ4QbEs2TNZB3wqa54i1Pt25W2vQi4qHiSs7zG0StZSJH6M4RwWFN2CCsFygWm8utaiMXitbd2MhO5sKTEKIJ4KTHKyDxVYIf4jRoJ0L6DqQhql3I17kKvcg0b3GKiELt5R2r6BwoXLIWV3uPbOO+l4za7qijHCeE0Hgi7RGNp3lLMLfy1+kZ3Rr10ACPjvbdrtJSnyfHpzOmRW4Wv8usMIEEd8cktWos++69x9qzLq+aW5H97PfStiADJ7tFguHWoORTL1mPt5fLHtk9mS3trj2grzZMsXwmX6jgohBt1Pdm15/bmM9oKHdihVni1xDzO2ry8NuGzXbj7JDvfK5oKXw1hqEqJ0QJdR3Dt69X4lv7ZtDyMn72TsRzJnKPHyJ3dhgCxBidEOpi0MkqWuk+ylid4TeS3y4c9Oe5VpsW+SJUi8ek3WcvjhHMvHiX3lO6fR42HYLbcnry0U5LFHJ0t0nA4H3GpjXIaRHXUm2dsS4NvEw3m6dXpj3nujlNMz5+qe3ngOs3TkrUc5+AzXkVBHuuTaQfPGeTgU/xzejKZo/7hUzebajV81r/N62ZmfiJbEW3meONyscmb544H6ICkfI4ocWHJzkwW4xKUduKo+YNz+KttrYLGBLXNQSRwnpWsRW3hJVcwvWblvTghjBquI9AQEmNclNFctq6QV/ffrtcEX7NwAJZ9/iGUShfoaC2u44EeHH2TAO718pvyIGqj9viHmNk8N9nLlqJukwQGWg0uHkfj3KlaXVTqI8JySzIYFzKTbMDPe/bqUu+w42Uk2Z15a7KXrQisV1ERvf9tH93B3rJJaMYY6rZkLf7aagBBEFDmq2vqLu1EiqnFKpd5ezKXrRJs6uag0p6Xg27Vix/QLOj5ZL0jWQwoa/90+lrrKQoXNWgZ5YJZxEm/M9nMkij99+lOT6EAX6sOY3i3tOp3JZtRESwXUlW0d1zxB6ifCznrvc67k8UsaX9Wyeao97mTS2izIkVjov90RNyTDEblldCnAkV60mYMSMpFlSM6dG+yl4/OuNfvH7EsJHELjsz9FB/NuR0tZilgFqAITOL06uHykETR9NENg2uymKUQzPt+vKpcmJiADCdlI7HKaCqLNL/Y0fx0z27YjdalFdCAzVcsIwB1i6ayVAH+0t5sKc1YdcW4dagEb3H0SKbi/Qc/8ryvLvYslU7sCjjV46vPZCdTZbHosC2VgrkUmbT88SfstMlOG33zoq0AXNdHjTzO9j0oMpKfw9gDcrvKTmYy1bBeelzkBMaL+OcTdLz2C9ZvfPJJdjLlQHxS/m9zei3woewkPvgmI1HI8W2k7gnA3a+zYU6nvDX417AxopUAtR+XtuBGenzOvWgUrKq2/iz9O74mY5m6vfnkNpzD6ecSMS/KoLa7YqXnqi3ZypTKAAXTm6PFr9B1HD9Ft7YlbsuqPRnLUOzo5WAqyGLiixh3086FWP2NixRNhWNLoZf/eOb6mq/71Pjp8hUtpc5kKeMjp4n3pVKZxs2B57rg/544ZStZyvCW3JFdTYkiDB0kWGMeatWdrESdCukV1SQF7HhWH2JHw6ZNik7oNkVDYaK2EmFI2JzqhcAXDStY5WffWaLHQQ+YaCpDh/dQuYijMkhoarq810bYl60kKxkquf5IBX1un1qc+WUBBVdoHF6Tlaihp3qyiXbcPljzmBSB8ckDHbcayW6rtWQqXVRvvHOVb19pWHOILnmKl3qVeHvTziTaSxe88XHXXGoAPXttk90k+BsGj2QtOGr106Ckr1eUXFxNynw1NTwO90CbyWIUfRLICn/zriyz/qqbPXJ1oYUThf3RYjokAhUTXIWjD42zQ8WCQfLy9ovqSjxgBkS74cu/JzJN3QQc61CAGrvSLmsn2YyExohD9cfdJfdw6cudHNzVbrKZrlhOHU3LUnGAkivmnXbJIx27RfcMFHmqMqPVdMcCn9ThUYezKfwOgg+p6lApQ9otmgvt8OiBG9zrzc1FRNTUEO/GJ7dkK2qB9ilBp+WfANQn0G4fYwdFSPmu3pOxNO+69SmGfn0IWlHIjsbVCenL1UcyFUDr9Xn0er1s/HTpZ+18uvSZbKV5QsmVAaVDrWONGBizNafsJpo7ueFoKE0uNW2wiPGWqpKdxjQQXe7msEcXk9Mo2oqqMj8kZC8tUO39wtQsomn5IusnmUtTDP3K58frF3KWKtBo2JEu336TpTRFvk8zbvaXoK9buVaEX2qNtIY1Em4rWYr+zWS5ANvmMIaicTf8sUDwXyOhtvR6Upz8zLWs+xR3pmqqbYFnH2mLj4Tc8gte20j9eOHlpH0EilFFzd7CvI2E3j41SaxCTSi8e+KhWRMSSrToDsRvNHKixVSda0oZY6rbC5XMCyguRVp6QWwqRKIQxaPNVBVnPXzvFWfZMHhjfPEs/7jTRkJwW3WPa/+J3dNGXWjFQaDwxndPEG5ziWPCGX5eAeLAy6W9UQc6vnHVEorLl9MT3aPY+kjj0vPAobAYeERKLzVk0WKKOHOfLOB6+oh9eAjeT6UwJS7aTFCu+ord7wHjMNdB/YRbZt1dIgANvS/aC+HL8vySQLLq5aNneI7kblrDRodzJjS3KeX4znTblO5GTR1p+xDIRX9vJji3qZPrB1l8eglqz6IgmMY8kRRLHBGNReJhUBOqdHN1hYtLQnBIz8p0n8wE5/JoyTIKdnlxXOdQ0UFLT9v86ATnNhc5Brns89PMr0MxU1xbjyfH/kYnMLc5Vd81zF22ZnQ0ips0XNJCJxxXqi37I7Zgwb4XbB5xKU7FxT1xcIJx63WyvVNa7QtlJZc606OOIQQY4VRbCcVVX0vRlaTL/Imbqe+CBmJxMwzmuNQrQbnVezc2wXCqgDnP3dTNCau2R1EPpNaDpTCcl/uIFM/XOtleQoWTlxdKlRkwX4KxMHUdd0GP717riql7P1wztjbTLbwSolvvI9W6pMp0F6AvqOtAAnegZhrvo5UwXUELn9CEYgHuhLq9Hp1oMPIT6D0bzKW6pjRYEx0xvKoQhw+e6KVJQwxMVgJz1dR7flmRrs2skhDdjpCCo8WsBOVKn6N8gGjz9t0BGC/DZHFpTRkm6LPRZDwQfEqk7bVeHuf16R6Xaqj46jtBuYhFaLkcx76+ZJuetqsq29Nv8tB3wnLRqejzK0TmzUKRN4KhY87fXdFt2gnLVQel43tbnYQfKRPFdxiqS31m4psnLJd5Y4tJiV0/7unSDxdU0aIDSqnC8ITlStVkfDXrj9eOTRg0v1IM2dTrRuxhJziXKwcGFTtW3D4i2aKI4kxVA4V7bCc0t3pyzEt5Xj34nGJ+N1SAUhy7E5CL4MP/H+I4d/4vSMIaqU83mFK0lS2eQZVwS/GuzUVidXY+gKnC1Y+7eycYF50L4aA49pCXhrfJpMEpdC66C8VXPwnFldLFfUz96pWk4sEIRo6O/UkQrtQ17j+SDXa4Nu1m1FB3agu3TgJxK3j7+IK4L4F7mG8IbHa8t9TwcZ2E4fLWhFrFaU/NKcsH/04ZQQD8YGMnAbjSQ8EMvGukXb1buPvyZidFBW/R0zsJwZWK1PmU7+8nbowi6C90B3tYYtqvk/BbIs/57e1TVUO0vJ/obgjApqVK8C2HQR2fqMBuPie5VYlnNlpRnGTeJ4G31eW+P1q5r6ED+qV+TtYSKY1wfKOVePAIcEEHDvfrzeHqUrGuFFjcSMcgcxmNZYkX1wQ8mone18m146ZJ/RSoasXxCcCFdIR2j6JQJ6Igt0qezKznRBYnnTCjoXCALr8A1vqILTDtYoDA382iiusmBFftis8ncW6LpWtA1S9qQG3//+QXTxCuVCZq1omglwUBgfe6iUMTgFunZE+5PRQOOCWxm5vDXWwzn0uPqPCNtjK9r5AaahQvaXT2rVyeS7oj1iJQyx6NZUpcX6X8KiV9GhUUaF/pU0LtCwJP6yYMl+8W4OFUFOdj9ol6KTHBRgwgZJYQk4rmMiUA+mHv2BIrHqnqa3oUzASMhs0bbQU9q792Lx8BuEITd5bsHlpLBOd4lwTjMn6Xb1eDR3ar6jfJNrCraPZIGN8l4bg8uwqhIlUiZcRxuiDkcYd5LuFU2yVhuFWiyk4hIpZsLo04PHVekU2dMXfODRktZohlpjiImo76qEsI4MBDKDR2avHDE45bvbW5AMqf1wu2iNRyNDA+N6G4H+mI6q3lHtPbDscjn1ioWjwRd0lIrnRFmlQGIdaMpuHNvnZKeQJ/c8c9tksCc2Fkt+rKo3Sx8kaXk6gC4vEut/f8+ITlVkciX/eR5l0o6Ck4dAes0uaI0e+uCc/l7Wlsw6biaOue7IBbLiH5jmDtiMMTnsuasQ2VGPt28GjsN20Vu/fWSiZTE5arDsfnFfM61eLpZ9LnLZwuuyYMt7pEorio5UkabErzEKOmqCCiLLsmCBd+Rq+ef1TZsFNTyqTwBAT82tUUYZ5dE4Yr5lWRUuB4lqYiYldxNhf57vzFCcZFv4LgtQmreL5toykerA27Uux02PG7E4LLs7cu+R+pxT5Z5UYtAQCjvIDAD9k1gbjIlAxnwR5zU59fbvch0ipIyasjU2Ck7pqQXKZuzQ/E9GlkX/H0pL+7zXtIxtYSjlsf8l4/ve50Lm7pX1S7y3rSv9gt4bi1iVD0iUJhEjnARC0tdeOHgt4Rxycot0o6+tscabosWcPLFSZaRAidcXwCc3n++itlqc0L5KaZixBk9CgsJKvxFyRAF2Svzy/V/SkroLT1K2ZyE10/zH1LmG51oeCqzCa30YtMiq2dBIRpLhXdr90Spkt2HuhYHtjLxjZii47bflaMSnZLeG71yJkj6pbXPlO0JqAxySVaTNXjmydAt7ryeX0Zl097iUahGEjLpXNo1BPaLYG6WvklpsgmIN5eer6QuQShBsRfkVW1e0J11ejMq/y62A+fJtKr/Yoabt+RStZ2T7guohiE+B+ezwuPhoRbcMbNFpO42u4J1hVetJ86w+u4yq025PaufDn0hOmiJlIlpYcfNs5UyEDiSFpbR40lQ7pt94TqVrWT/1HtFFWZL0e5X0EN+mYnFdTsnjBdkStJl/gfbVelXZDtp+CgxUlPeK6UOB6zSSoy3v6Zoim4YcVsMRXt754wXebs7Me9/twrFda20BYsdkRq0u4J1PUGcWSjqeY93r26q3sqCBjphBG7Y+yeUF0Jg0rp8IddNF2q54Ja0Il8DhJe8dtHAnWrJFc+/CBve9doDAUdoapDVHjzkTBdHi2lFqkrKz3sjLAzrw4KwBfU7eJJMRKsq343V5p2XEheYUmjXbKv9HSOzPU9EqzLWCU3gZiAElxE1062ASfMZk6xaRyfgF0pZDgYwGmzXkfPi4g8AczBN4jqcHskbFctjdH1UJBolq4ztjaXRaVwsMci6j0StittEFEI4f6PpbJYiwUlDSUJ6FiFtUeCdqu6d4n9iKjxeHzXo3a9ABkU0UWEF5J7MJriCK+0K6HA709jK9cQHuO0m4Qi9kggr7dOEfPUxTJc1bzQtHd7GEGDlWB1M8G8ZIyuRP0Q//d1gxSOsrBKJkPCbs+E8EpkowrrIwG13H2m/5pEo/eiUfuJT04Ib9F1/D1mXla8Ffud+N3AITm3vGcCeBFdB6vzFMxHMHT17fcZuy9Jgu2ZAF4+nAVzVTFqXRzLUZHKsot9xBqVPRO6y+D17XPfnxgNKuyN0BPbSR+e4N3i97EnrfyrB0x6LH1Dngyo9J4J3S3egtVJXQ4fWaSuCxGabo6zZsJ2EZlo38ZzTnfhNgIRGKoJinfxTMCu+nDOf2SVbxmPgWCmGud5JVSXIOToNqDX1nbunl19U2WCtLChyDHY90qorh5dhcAEFGZch9zqkfpNgNz2SsBucabqR/T5NPciUApV1eX9RMjf4QnY5eXhwqli/Ymr9u5H2UbyKJrnSqCulkq0YHB/gQ/yW4dLN1rcMFaqj9wrgbp4m/OLPjU3sUsyHbNctjdSl+O9Eq5b5LE4Af+TN7q0XVMWAMXswAPYKwG7Zbt+inrHdNe0AtRVucyYiTaBWlk0lO0kbqQrXkUNImZCsel/lM7wlRBd3niEAOvleywMk+qNvYF9c7pDdsJ0Ge/h+o+XbGu1uuQ9L6WmDX3zcJjtBO1SRUtsxIev8akWWdOCOple2bkYlnsuGsqTMiFQY8WHWDqneyNNmzQ4GHHKd4J2GS7BORFyflzOHchMHeyym7wTrqsy8fKQl63oRpr1R21EvSfY39CE6SLosNQ+VD8vqoTALsFOOi2MxCKn9WK0k6Ur64ioB+bkOkO2M+mfU9rJ3s5OuC4AG7v+U+PfpAxuVk0iGUBEokHx3ROwWyQH9LNdNLTW8zoqSr/XrryWVMn3TsCulEPErFE+mbo877awOXzpbrrwHeLePgnaLR/OwFIJQG+fpjfcPVTpkGYLJW/7JGSXiT8ibfsP+QryAEBeFiutmiQG9kngrgqKvAfbVFMuP40HQtlbTK/SU/uVfRK4y8Or2voiCI65CcmgRP/yC9a1AL8lrO8keBeH7no6gB/pSdHsAYrulNwSTcHC6ITwSguDHlGSxnLwZu4tSpj5XPOk0/gkfJcnq3GsXMqn8l3UNWD9qs34pelDjGxOQnhxai5TeSUS2cqTZ2iPMNFUDxedrZMQXleR+rSHVLdElzpQxTv8/9Rbep+E8PJ0u15QSlGXHe1xLhEREMhlpFe/CeFV35uj3A0MTrtzPSg7To8CV3+J/e/4hPBK0mOqHMx5yq+JzMR90NHRCJPiprkJ4tXkXwHrCBGO+srezezUZK2weVZ8/wTz4perzkU36dMxWY7rQzKO2dV9E8SLwEN3BgSJxlcVZgcETW9xeSefHo6pmyBe0kbkj5V9QORbQOkQi8C+xNyHE2ctobxPSUTAPBxpO+ic3WUnujqK2haicL7EaUtAL08nLHL3Zzlvtg7wJ2q7jtJfQZp+34TzSpYeCct31Ln3clRnYhbUU6PIfRPIiySHukFdbdj5NFybnXkkaKn5uJEnxMREi5GgpR1L/KGM12F554VDl0royykJ4nWVnq/g7nEMoRfFExMUJymanZIAXmlDrK9YgXl5VQFdlalWCXPFjXZKwnlRxpjzo73XXe5xEpHBeTLD9dZmf6MT0lscrvwowCx/c1QqabZxLLKLN8MpCeblzdW3jJMGmUD1tqaNgbqCbVgr0Q84JeG8vHnzFpdXAi4uVIy8sQJx+gHMHo+JUxLUi7QFeQEJqbw6guoQtf0mfkl89QTz8uwlfvf5gOMLlPIoz2/2Gi7zUxLCqwmvsJO7JJqKV4zYR0u/SGmJAF6cmgBeJrzqPfynuYR3v15vWtGfrRHePjVhvOhLaJKXahlOfyJ0SEJ7s3D1RQsLXhPGizRGdcUE72u2PnrptlHMNu6ws7bFTXpqAnnVhaS+Tbq8sfVpUsM3J2UmQY9TE7yr/o71U13ks85RLsBpSYA3GEtN2C7fPf9kA4cn/cwToIYdjRKML7ZIOTVhuxpf5IJ1dXP1TuiIn5PUomlUTIicmuBd7Y2SWgjZMjURhWbLgiCnJmiXRZ71g3R1Eco3/Q8W3uRr6f03NsG6TNgsfy26nNW2WSpJANexe8SzT0uoLgIN23VFu17BxaXNnofYJk4yCqbWEqiLHMJYn/rk15msdtqoqgwCAZcYvp+WMF3kKSTESmocaQxlUobNnl0h8JfLSOr6pyVcl6dTTrwkbDp89AGQBme3mHj1ZKUtwbp8OvEZIaeKpHSNTgLgjRrKKYkadloCdVFX2n9wiecrOzlS6rI2zPDAdz0twbo8Wklaz223rhP5UOFUnHqLiHl88wTrMm3rr4tQ99jM1nq7TD/zfyK0eVrCdXm81BGrBBSG90Pdcpimsp9kwuKqBVx3SYOAhlEKsZrTICnYwNlZzRW6v0N7wHQ1lOz06/rn5+J8Pejmuanv8OkB0vWh5j8+qiwNrd1VHd2v3QEX4sQnBzhXw6XORPJG0smf6mQzNfEvC1KHgb55eoB0fTzwg5RMvPHvwFVkIg6cshIfHdBcf/PyEXmu5dX6LLF017gQKOPYgORq7BivrYrKKOSu1QYNQv9+qUVkHB+wXI0nnGzeTY55enJeAx46zjcs6whqnh7wXP8FvT6tvuFZeXqS4ePa3X9j6eLpJ9pJexXsal3rKXUwDCJo81lHUsg4/UY7gQIw7mtI3p8M5pWoY+PuiRY2SjQT9TxqL9lijpGiaNQM8bqKOpKFoTWaSLte5+F0zU+CSg2tl5RBaskPbtFAeGV4uN5W5XZfZbxirhXYXUEi6IweLYQnk9hSs9vu6Sm8UspFC67GjI8d0UCaKlL/Ue44gHqbPA2UpcPYGY0DguSuHxqaR90SOZuIVyLtFL2jsaJdqPMEx5haU47mrSsqpHmAaNRfeoT5z9jJNuy85mDflKFRquJlWMoeK+2kHHr0iMdJBnJcmuIJCz6dV5u6wVHSIV3WdNWPm6zkyKetimXWJ5CAgn1+aXVgExfFv84syVAkhvyK3l8TCcgDEOLtul6/cWRNRuLNUjGv9XoF9ip4YBaq/+IHz5ZM5KiMtwlfcgr0Bt4BKUPaLspAn9mTiRy1VSHxLH5MU7u8rm6UtC0fZMWSZc+RzITP+dR2zle01tXkz/ZXS3q8Z85kJUfuv19FwMwaXC209t0w0GWIV/RcyUpcIoAMomrVP3rC1eFq8zfQ/kpvvpOV7NdtvgrZsxvSvaNzYU5vuHUQkUPO/syT7MRbzxHwcfx9zu6NIi8tIii1D8XuZ95kJ1sguzqKkZK5T5/OHl7UFFutFsPDV0nGwsPH8yif+FXzirGBcxJvjVWTsWzHxJb0qll1+VUWY/I6lOUk0a+zWrKXrfrnGTmig+0oZV/S/eGLV0+msuUEv0jzsbhqn9vlamBCpbNsjWQtm3yhuq81FUb6uQ+goAOqKdqOD5/JWkTl+UIL3mR39H1UrjcooroRqz9rJWNZ3un9/vVhVicw2CYWAqXW12ftZCZLIBwEuyvWvdO/kLEi0DS7ranm7KyT7GTJPr4VjkvKSqCuhMaXZHc6y9ZNZrIk6/Q6MzbPVNtpPRXTb6lgRVd0l2QqS01aPIP2wVNIjIP9F+ozQtiya7ITby/ySFgWRnzoAVVC6d72LbDezm7JVpZQiXw2eOMkrbHthpGWa/dkLE+9+UV702FbgmO1qqUjJy0H4+NHshav1MeTJYCaLxNGgYirl1Q48xGa2DOZC0xDdZmX+qQOBrhz/N6+ZqIWnL2SuUx36qQMiFC43/i9bLXONve92P0T33wnc5liAjUBE1/mHOIXtM4ufSV/cJ9kLPIoPlSYqoJCulAIal17IRYQxt5kKlNil3vG3oqdVA6r3NdBciWs1ynJWqZyA5/OGVMImqZZ97wFIh0JtDi+JnOZDpiO2C4W4g6oY7GwN3atO6clW5nyMv7RvMJG0ysFgVs6Uccn92QpwxvlbkmrepcuNaqaOpcGAruJrHjOSJYyXD16NVW0moU64Y/JHvKB5k3lT+fMZC5DdArPj893KDbxJHvDe0+PXslUkLv6a4R9XMjQnG/QO7O8QqevdDqcncxlqLfvZ8k/OcTbmrfTvKOkLoVE8dFihjhbrh/ymrxXSRR0nKza0yY5N9nL0Fpxj0zV5dfquAi9R+kkMoakif7G35LsZbid4VGhRuaBEzlT9U1EVSwSGs6tyWKecvQa/vMEpchOiKm77xmxYuDclkwGfupfGW91JGrRdpUTyb6BQzmM7slgukoMP7ItZi79lbzZ9bkoNV30Myjx8SNZTJdj/x5f+/Js4BF95ABWxKDgzmQyXd0+XsGcReuOXR4yiOBLA3na+OorGcxTKQAcuGDdLgllnpPqHYAuR8KT7k4G8xSgXwOIu15HPNuirmZl2z5Rc889yWi6ACXU+vjpHqh3FIGX+MFZIP7cm0ymS+lHMF57mh6yGbsSloo/6kk6B2Bl0WjAN//axg8v2b9Uy8PkXweIYcXhNRlNUyj3Kc6xnS0/nQpRZ/J3O69GGN2S0Ug36iO1Oj59K1TybVurj5gMu6Une2me0nms3vXKzufegpHoarQSKfeWkWxGPuan+6LXWFogVHHNjwpbQyLslpksprkg8dsqLxK7VHGpJNyGjXgt3LKSxTQFkmclgdojfgaqh4UApYXRO9lLUzWt0rdNje0EnsIjBwS4M3l9t5xkLk3eNVSf8wV2UA4loFh2ucx4qN9yk6008SvGcQmUFwuWIjqLXbN09okTXksylapT7aNS4NyQTTkOBIRJd78wY7UmQ6lOgf7A3F4N1XsXqGPXODzecLbQMCraSlV30XrfT5V2mTlHeCwIU5Voo7UnO5FzS3Xlq6wpSmMVCenvARe2xPceyVAk+fuzXnTwadzV3OewiDQearfOZCVVMJgaZUqi/RFhaTlhEU1JYmsIw0QbQUJgO1cfEtMTXbXDFCozurGp79WtOxkJlbpLb32KSzLw8ntKPAyhoNojdfnWk8ykeivpj6u45/a84RYdstOKIomX3Zqw2ibQ7i9z6LniiwrkJflb6L8VtkdLcK2isPIq194dSClRV2hh8S+Z/hlGJ8S26ez8NDHYjxbxavzKRP8lENVuS3itd1PNit92+XoVnFck/Y1MSO2TJvhW03wb9j5XZYivH8rWKNmJtlIeG6XrZLnOml4FvXEk32EGlN84PCG2zRVjPh3Mh2e4e0FsFnaoGQ6tlsOKtYTYtof4dn0pLQmaz5sSzRa7IxIYMIfbEl7bXCz7nWi9ePd1tNZUlbUkBR0fniBbZ998Qv+Xl9ik31RMB2EuyMvflkBbJAr2ebURHn2by6NoZKoFVLi3b0+obfW2eP11uGut+zfrQ+2UgrcVPrkn3FbSCPuvver0fmFg+0dyzPQLSdIMtyfoVvSf9qUWet5wqudUk6jWK9b8jk7gLe+ucpSpn+pNk2uhZksHzr5ZoP72hOBqvMvVptfvrlNzl4WyK6a4b08orsp42pcR2lxzptqVIMHwWsWYLmF4AnJVCdRel1aXlLLXFWOgJlmm2xOCS0GsKmJFVf7ZT8OMsmu8HfN9aOIQ2Bi3JwS3PvKO/ng2p9NBklNNvUpmnLGE3lIFDPCsBl0SnfS7YBCAql1fkSJzWPCRAFyKnftXFKKrBZFiSm8NdlZuiXNHAnEZDWpHGo50ePOXN4d/crTZxEEsSE9PUC7iCo5Gavxu2qNNwr5D8JGF95GifkfCc58uBLyGpcYmW9moBVhF9Wi7K6sz3JHwXKZveBcJWmCanbub212dodOibMZLfCRMt7ouBP1x6ab31O29CyWNL6KljwTnPpqeMyqqB5MWi0spFb3WROC9I0G5aAWQW7nUqaP61h0K3lUFIf1sEP8VJz0huUgVIBHUdIm37R6AXaY6Dc29vT1me+9ISK5kIZaIbkfxs25xtdGVpktvKymB3ZmQXF6eNLmjLm1KmfGccRxKpWl19FFnAnM1a/Mrlufcykt2RvOxuI7jFT4TmMujJUUlZqJdY69PbHG+Fh3OKcwNazYToiuNBl/x6W3OvUz0cCiKprupIo9e8kygLqc/gSN1Wqep78ILKCVtJOLeicmWOxOqqw2p9tPnq4I2Ku3scXSJEoLzNBOiSwU21IfuNSHqMIuxjikijF0Qtvcixe/OBOuiWADY5qHJkeu06Nmt6NbOt3SnzITpolYw19OjfqSpUa9qM21oIujdmQBdhkapn/aIKHa+qKJ2l87xFtImdyVMV+h3+RRxuzRF8fYNBXcxeqsrQbo8mhmDtUTfC48NqK/zaAp56bRNVoJ0pWuxdLK9H9lKG2JC2qHZEsvtroToSl9CzgdYene0B2qaNHpp0BtGJiz3leu/NmGtUc0Bsa26YPuVEHXYIishuRDMl0fA/MzXGOHu1/PRTHankvu7EpxbvXS7KR346c/SqHeiydpMgnF3JSiXF+dE4DB56HtFFkFJK2RUwrW9EpAr6dDzIXzbLvJk9RgeLFuEZ1doeueE5VZvSQc1/3yaX0x0kOVxlhb9251w3CoWnw6U6dDr0xQ+UvWzS3Sd1Ano7oTjMtt8Xke9k3/95P0pifRebjDVRoIG705wrqoC9lNe9WvE1sh2Iwj8Hgmh2QnK1fXoQSCSSt2TJYjiXx1GdkRQUBKGJySXLadz7EehnyNj2xs4SJMo+uU7gbgIFIgS5fx+OkYXdXGmHVw5qMXHy28nGJfXhkcmUcXlqgzbYSHbkzdF3DsBuHosnJ6jn1meoCBCNWJvd8QU47W5E4IrYYT16BT3oXFHN7Z9TvnHSycAF1a25Awlqj9Uh4fyiJ2IBR5leOeTkFt9rXyE/ieoT9K3/iKGXcZNLY/uSchtHQ5vPOmqT8tBs6ounioFGT1FEydBtxb2iZu1/Rh8WUiafvhNc3GTAunlnoTd1u6p1xc9WpzevncOjK6FmGMshrsnQbcqmOHLdeG77oh4i3TzowPGjUMTcssjmeqXbn55Clp5SqTMDB6KVMiI3ZOwW2QRWO/nly5vQUcrAWWp++kzK5fck8BbjZ9/ii37TM/fOpxUrvrRxccn7LaKMKjs7/rr9mQXsEsgojBXI9XgngTe8nSBdz9oxSnvqdN4KVFyL7oIQSzt3gTdoslA4lj92EQCerIK9GkESl8XwlQgOt+bwFtVZxfhJOsryd+q173Y2U37pDA2QbeiiKrm0vvwTY8gVegK3ZYdHhHQm8BbRgtRcb3TLalX9WzeUtZu6UC7CbiVJsH+xPuqBoSfoPa5tmN3Sfv7JuBWOk7owkipfd/XcqObOyminIWCO+2zm4BbxZxd3SOGOli4OFE/3iDa/NJVUwx4E3KrLvbjU2z1yaktnFktf+Fw2nG5Enbr6vfSc5rS8PCW8nYHqXuB/TvzU5O13QTfasn8IlE3vOWMHDLncLma9C+/g/Vp0Vhoi9b/EgVPfFMVeQrASk0QrI1PEC4Je/vPjyXtumc2gRRbDQo6YpLBxib8tqqrxwd4tqjRbzG29lLXUfbrTeMThltVhC3WKw2dXoG2hTBV1eUDLbL9j1+QcNwq7cJX+aK/w+XZRBu7aJameUswLkOB5I6KOcd+CmJwTp3kiBZ0CJxtfIJynVn2I3rA+shp2dz398KDJhihdJeserIaaqrwg4U9OPNLdUqkgaWPHA4I6K3JZKrQCpR6VALiFBO6RasYYI5BL9206AnKrY6IPnri8BYWZnhIEkDGQ/87Mr3xvpPRiNnxJanU6QwX+mZJBE3CecnoaoJzqwObf1avlYPqzTbuftLGtasJ0OX1KSPxjplN1Tfee1Knsl0OMSNKl79kNEUH1SfX4iZPhaYW7l0tceFqwnSrbpLHO5aaJepF/t1lpPvchiY8t6qHrDPMp7qEeyj3sjvcKykjSYiVbEakkn90ioFxUKg9hkRQktoPNO5kNkVSnODwVF2qXRyFGV0FMEMQbUQHbXyCdKnto62ok+SfYOCEqH7E59gZjbbhCdRlOKHc8Z+hpqHApWCakAfNgpKyljoSBLNRlLH+ChRKkfQrUQ6FWJt0cotbtiVwl+FKH9CRkFYPxcMNxJ3V3bKNO2P1kv2CBO7qAzpmz2s8bhbQ5hQhZM+eN21L4K7oOJ0cBPlkaK1KdtkjdQjMaef8SR+fsF3OtIYMtDdZeL3tid5BiyG8pz7pNjxBuwxXiYVKr1zCBABIjXqmWufFsQnX1bqfP6Wl/joKT5jX9kL7DghOPb18QnhZVGGz2rG9e+hwoS8eVSkSLybLawnhBYlF/6Vc9VyYRXc0OWmlgOyOpEoiJHJoOJZM53gJPHVDaoXmvvS5djXTYpoIbMfAHtpvMp7jzjhXgv/oxEbRDoevmQ+XDtyecF6+H3hYPQ8cZKbbgkpjUfjceel6AnmRK6Djqjqp3e6tc1ZxgJgE84jf3RPAWzxY8z6cVayZMZrXGdJBe8Q16wnbZc4psDge8pBpfOd0pfBKEQzqBzXSIOjukkzniEpw9ac1j88r/lhVA1okr/PwBPNKeeB+AMunLH7tvpFnZjcFTVLSJySkV5oJJfUShbGs5qeLXqIzjU0or8LCyWHnhPjiod9RAHMEysx4yfSE8kroYX2Eb7qgnB+3Nsj0h51T41E1EsorKra69lBzx0nnmcOKpNiW8mrfN2KG9hsS1Cs8Fflg/kzvjYXmz1FRw1kxUYxgdzIasWs+n67rGRKQ+rHsev5xu44E8pbHFVbm7pXNQVklFzdoSNrj+ToSvstYRxq5jl6rxithDYu/e6JQ2tiE7RYpvEiVHZfwPpcICRU8EbTJ1sjmPhLCK9kDNQ6Snp/TV6k6V78SlLJHPB1GgnclO/D/A+qbkzJcbwfadER0UFNM5rIeMcAV0ex6vQ4IIcAP7lgOfbbi+ITz8vz2l4ex13anprsCXUNso8b8ujlbCeflFyjj55nH5jXJ9Exsyg2Yf0yjjjh9M8G9zD+ZUzAB4LCi681Wz4uLThOpNPo2M+G9vIDUe5w3pIbORU2DvfrCoihui55+Q8J8y3JFmFQObqOufJq+JnTgEtdwJuRXGgJTQBOajNvz3ZuObJOMrl33J4b98A6SAU3njPOG0iTzqjJUoKVgcEfNV9xM0C8qBGd9G/nBblBOq4omBg1pJWqJjU/4b5HwjVfSkMq7y/OgdogB1PRZ0PpN4xMKDIR3//D6Pl9IQpM2dWFBGDnFYjPBwJ6v/lA0XJrYgrAlHR5bVnowxgNvJSiYrxccenQ9vv4VXlxXtQVstSgcSJtoJThYtqter1XSnXQfpHfFr2ddeus5IFsJCS4uY4RqrMAn+UdTLgGNt2OyAaHqZDlDee+mS/XTKLsh3wAV6XBTxLEJB5Z4g5OYZhEGLqsr6AeQwDikclu02pXAYMl+1g9l/91T5lQ2rI4L52a3aCU0GAmFOb9Kio+QZNc77w4Wcuet2adfCRSWGMH89FNAzV+nrtmegEmqFWp26VcChcWE8k5Q6GF7hsluGIdl6clc/vH1CRjW2SjQiWPvVcXYb6KoRtkbNTWM43fChzV7YhW3i3vq1LmDU0VafAyVx8fP3wkhLoI5uOq47XRideg1Kr+bNJSOG24ndLg81MY1rR9h0D6j90fuoQVJui13gofhcA1vQIJ3bmvu2tA0v6almUVXM/UdpRNqMh3iV1Kf4qIvr7i2bdeU32MN14xgoY1PIDHjz/7q4z0q3FC3F1Kss/zDp98JI9ZWHZJCH2rc7kwbNO62YvOaxXZQ9E2m49q5Xtj5qbob7mlcukvsNHcJIJaWxPoTg9jexttCfwfUC8I3O+bC4d4ky+mynE8/7N1fxo3SO9jKNv19RIQdlyKZTvfGVK/qm4uuqH5a9k4qvWd/5ySQmGL9i0hMFJIfnPD8m9V65JWRpEmmIwWxb9PAJwBbzUm4bNZml31LpcD2CxJQLKmAKtvzej4nChX2PWfB3tK+ibZ3ElqsWvEB7PjCC7nHFlZAcOxA3CdazklwMeoK2KV67Xy6uHSXMLNZnCW7aieBxUXkXCH7+AnDZUDgXUynVqtYp8TxCS3m09fTVUTHxVuCT7oFQ2WZItWlmUtoMcPF2/eeua0KQbofcfN222z5wDwJLZbAQ3+N1OvDPGH4IhLSKGGP83YTVsyuPirwDW8+AJr15tTRZPzkJqiYWn9JibYPVcv3HGChShMsVDn5wLgJLxb+0L75tA/u516qlBvph3ei1dwEGIsIsL+twYa+3q48JRFPhy+djPYmtBiMh0c7Sbs40RmhA/MpFsdP2jE3wcVoNGAd/C8Hd1sOXm0Yzo1Yab8cf/gNCTBm9tQryovEXs0TInyqvjHjt3M7uac3AcZ8O2m5HSPpRiQMInPLTS06bXRCjIvrFleyr/iwxdOBCLhsbxlZpC0Wj8wbMOP5X7oLbHzE0dZ06znXVh8a2N7UD0X0jJjzaz76BYppn8TYu2/oWUHeZ1tU3xKSQfLwazwajvTB69jcvE2KHZsUYl73F1dMhpKd/bMdjWcFvz1a91N98K+eVADF5Dcy5H/Go+FqOiXM52O6IsNeZRTpsh4ve0Cir/347IkB6oJR+1Okjtg4xVyU+Z1YeF3Je37Nx1+f204MEZFDjivabPRVptrq1ZbDaxRFvxb0VrDT4va8RBHFYEq1WGzVSiQyV/bZ13588YQdThXJvwDTgpqqHmsNfb5U+FY5maP56Jh/7vUqLupapdaBzF3/Te99k+EIs/IqnCEYzpHTUwR9OqEnBoaEwdFy1FyMVE+7cqmdJLItsNFpLNZZzFZQORstxxH/B7tbUP+23lI/CfMVT5IXqHxntBzyoE2hCcpbD/g1P63IuzHPpbZ07LLNo+nIp8QpV1ExfV7eXU/dAM5nb4hJpjcYyXa8p+G63pKijyejVMTsHIqMQiE25XHJboqXzRFGaRe+bj1nvp6tXfdPNJ66kvGAFatqSaVY01U4GvrJ8jThTs5/rOCOxkOCED+5eJkwpFhdHFeUuw6vOnF0K32ngwUBIXLnv9pFWpd473PUCS8gHyUF2XzrjTaEJMf2TqAI5rXq7l5BwJpDq0lfccZf0Eo0IomJqPu1/7RnBdQwDHMfV+piVvEPgg0xmntL8hqnSoqUvqvEbKfXJCWKdmO0H8buD0/2g6HOfr0tsrlvnB/x4Gk9Gg9fvrwXqPqBzuXIOW2p1bXD4o2R7b+NaD78Am24LohpPN5QH+YxSZDtUme908fPaD7N1aj/IYZqR/D2/nMdIH2k8StZz1PTXI7sOSUf2TiJEMCvTl+/k+Ucv+/RrgVaHG66s9HCHOJ0Q3hhpYefZDjHa08zDfJS0UUeaQ3S+6GkrRINRLs5qkhoZjtX2Jq3Dt63dynO7Xl3asxSaZUXTeeouBw+DGbQXNjzoPDoWN1oN8Up7PFoPkeF8d2Vg1yCDWkS7byz/rnxekvG8zgN0p1wsUDzdxCzoII1ewu9J6s56j+/XWjEQhMAGQ5+Jvs2cMVo8n0ki/GDhlLnidyQt8deVZ1BQJah5kVYAZc0Wsz2roEU/mIcftVeW3zRm2nPkjTz0V9OVrPl4LtckavIwiEp4jmMVD5ZcaiivYBmjK8gV72u59WaC65XeifnzdJPspet3hr5rF+0mGoKtBeipunNb7IWp1M+OOllyQit1K2EC3vFNRslmcp2BThlbaRer62GU89aTVQLo4dM3B+NZb9+U95Lx7zkx3crauYBIEr2I45vyWS2h1aSukZP0uvbyClzA98cjnMeRZPBJvengdGj6rWXpzI/DzZI3KVjJIOBDr/15c0bQDmHyBuDVcFwJT18JntZQj8/dZSteXcNiI4Kh8y9PP84JcZKVrO8HELBgeuZL84VOWo9yrsAkSR7WQ/EeUy/l9ds6MYi7k0zlvqPVTvJYlQJ8OMdUX+8lYsdEv2Xdt81N9es+L/RYJbSuoo+n4aR2jNLI1QSEHGPz5KsRVpLP6+HTX0F1kry2IVud2LLMz5rspUl+KQ6V9olcVRKcFSGYZOJe7jiq8+W7GW9bIs68Tlny07eBtZ7J61BUjQwezKXqae+lo/NtYjsXar3W7INTK4gDh/JXKbaoes9AbFeMaUkKdV0CuGtmFAmkRmtxZZLyh8d/qxkyQW7Hvp7Syv9TFT40gesZDVTyIua70l9WBtd7SaZc0l0ps02d7IZRDRegZ4k951hWa5DZnegWt3T+JPsBgnY+s1WPdKbHVxdevjodLedoAC852g8U227QM7UhsfhK2Jyob2jIZiTvLlVkvlM76dLt4EtX1ilKLTOUiMfWz8af+XfUJP9TKlCPHmj1t34X/3NGAonowWslgxoCAF58kavUED1JBVFlpN7WCLtl+wHss/5NP58bb9sMy3vpmKx9Mr5YXDqaD9Dbc5fi7vqYpmrbbUyRhp1JAIVXK1oO+hQqehLycLqvjyMty2xelu5FIyslUxnuFqbqt5EHnQg4iywENhJ9p/sds+Tt5P1DNGwvsnWK2U/yoi8LS59EWY233WS9dCgcH/UOj+KncpN7Xv3zcfWuslyHO73BnvNXWFcIUm2rycB/R27S7KZoSwvuCElHONV+uNA481IiHJmT3jXZDZirH3M/lOSM0lOA+jN2ec/oqDdkuF0V5hff/V69kvUQ2FYHNySS7Z7splHZn9Coeu+TpbFlltCXQX155uePZLZAPf3b8/X6SLr5iPSCxNyj6St0viZDKcrVSMSEJPvjRF32RLCuAvhux7PzL2S0XRvljLfz9GhS1Yd1gFqg0lHGVQ0mUxX6Zq3RW4P/LEISn2EKClOJrNPMpmu047fuMUFelW5KMY5r2ndlWBTYL5oN0ihwD7b+jGHXytHGx74KQuWbXJuTklWowZEX+HQ6aIcR/oz3RbzrHRXnZpMpqnor+uy6mI7yWgb9RvIXtyObMGOn39ashwWXMLASjV4Pwp7IU8wmpMYRRL/v12dDY7kOoyDLzQYxL+x73+x8Uc5PWIvXmOB3UlVJZFtiaJIHJAtakJs6RKIeg83zQLlESgDN86ax/awu7CoqUGCCnkKSoqvUyTvFXmKVCSQbNmuYaFT5QM1YxJ/hcXjHHKo6bj2GBOI4dAcOCHew9ZYQu1H0I3GHF/kuA01WK8Fjsxt7rzj+uQimiQi0e3u9s6XhQxvpoTde4g363yrJaoH8k+z4SjIs+aYEdss1FqVwkdvU7ogc7cy/HzZhhTXAOrh7qOSr1y6rtDLOftMHX60b8OJawC18sylgx6nEyzZKDwRbqwOk24Divn2s6yuEHW5rmNo6yo1EfMuR+s2nLiGFHRQzpaYAAP5UXhwtZkMNHonFiewuttvJ1JYsdrT99kqu+9w2yBiUZKfJNBbylWJnKKwzLWwyrGltg0hrgHS3WDr1J7M7qi9szAayKLlBUu9HDLcefkY7d/YygboeJEeGNMSym3wcBUk9WP7Ao1RVTOvS/wtTIqG75LbUGL6/9z5EprGoRrs6qcylbb/nIxKFigp5vn/58h5YpvSFnniLvSqWuG+q1R8ka948vWGE1M34kASLbIP59qopvNO2zwnmkVufQwo5vuVtVXRw0lvVtT+RVvNgNTmLXFA5RxBPMVoSudhkHM8CKWpq5biGQYJYA6hJ7a66xi9pAcOU7sqHe27cUrntjT5d46gJ2TYr+FACXfNk5eLaLzO/RnMSZ2fQ0iyNn/EXBF16rlUGEJbKsL++gwkRrtjBFDZYeMHA3DTS5aX8ZDAXMnXG0jM9V0uO8xn01bU6we0QJC+PvJ7tNdnEDHiG1gVnqDYYom3FiB1k6vphNmzDPKik5Lih9E0pE6LXmDt1zm6Xy/Vkz4V33NrMZCYH6CiRE0CmjIh//Gy7/Bk3qe9zQdqSKdSADG4yijNUrfldlqgZzcZEMnA0TJjFIVS/PAML7EAJ5tyadKrtCL37HnqnPn+uglDi7mJGRaATZtonNgbf1D5Ykt4Lb/FYmAx1wtfD/iuXJleOP5IAJ/K6rHSGHgyBxGCGvK5/COKWtGEh6xGoUQxnIbR8a87MMi4KDOXOiV/NbCgLrY1VQbCf91uwABjXf7IU4dhwaFNGC8GEc1lwl79/g0v5nJN3IkX0iNbgSso4bTa5aWdd3GIUzmIltJsDlUOo5cHptYdaAxTM+cANIOYAmEyh9CKhA+ERVatMyZ960m5aGA2GmbWaiSpzDG0pFMVRYYoWYxcappNkk/bfryBxiXAdth/sOXf4MpvWZZNGf3NX/tnNdz4CtFgFct40nPN06EQyu6O9Wd3bqixjFbGH/VSAMzDs1OTDTIchhBo23810Bh1CzXYRWn4oVe8TGWJQdrPwvANsBp0XIIsH7tnvW++QdBXl64XpDZrvtyQY003tA/6vSL751C+IvvLvLzPxYYb6+LxW3qvfefVORP48rxxNIOOS+g13+5+qRdPW7JBZwk6pID2SQ6ZN+QOsbDS2ELUhidjku8aooPNZFHpWVrgvD/nXrCPp7KXhVsd2848dSLSIvYJhh8X9TQorZc+VmFLa2WpcHDzEbzKLXIABLawTJUn/Cu0VoL/BxjtxJzaDD4uAcSE/lFYUnMHcuipTCRmKJIBnBw0U6yMsl1ne6LDo9FKbN0t4aU/kMNmarEAczR1HMKk59Q32jBQDB3dl00zAJlEfYe6K5Sw2a439NlpCdyzjhoiK/YLDEVWgwksh/9ikPN8oGy0+4MzdyZwwt7IkRN+ga/y/ctg3CBZSF0yKG5wCkzbHDUE7KNmQxc0ojELMAGe10l2nu0JQzcIWSIlk75mlV6YptmYGivAAlsTqJm7yr/KQTNucyqcndGK0o+fUvhqzNj3v3bnBiKTiJwfPoMXcO1ymKdaiIhNd15D1sKiZoTMOA9NUnJxSjOmrc2X8yJPXJ/rDT+OpsqnGdJqSIWdMwp+0qmavCaHaJkDZuiIYla7r8/OuyNjfA6stRknXPmM6IYdIxoimRPpZNFlerRNQ7zUqEaDcG0v3aBj5E4kTXAX6+VxMe4rVLZgG5irNL4lB82I/LyrcdBDJa0xOihr8LNqcjsaM6ccMuCm41O9fEMcnsEA/H6V4Po3G2gsSdchIxUGYE8qyA209YQUfm+AaB6ww3BjYApEQYWYIwYS4qzYOgHqtpMZbN9rhuHG0SoI6ek7OttArqRltbwLDU0sB0w4DQKBvR/DfoBbYZEk3wsLmGGYcQnikPIpOJdvHI1MdjCti9q4txvqMMAYytgOX1JmxkeQ7Pt7Fgvb7slt0A7PG9QwvFjg2bjg3wg84sS6bK6eX7wxiDo5Wrra4KH99MlmFkb4HjFvVv/12KYhxjzxXj/qRLnWuThiD50UTOe0fLXBxeSbYkMH6WXUa+SNLsMS72at15f5NLy4hCiDMy/Oa/srZZTnNQ/ygvREjpamdIbuyNKf1hmu1oKgTpLJ5G1+6tMAY3JIXgr6Mjoaw49s00pHZJimv+2P0/DiEkSdT0MkJvSLJFp53qfS6tbfqdPw4hJi4Vckrr8rSC8C0DTs0EvzKmIaYMzdCwCJLkkfYfI4V4gwQ/WzI3EaZFzat1IFdkc+dA5uxPzwsVXA2qM3wBieae8fkhEUhCKzZDLC/hrYDDcnBw2NhS3QEjSl37cOz3NqBhDxU8uFXgOM1UJ6f0jCo6izhjQcMD9vqXrIvYYWf1ogIXONskYIO6w7wTOZ5LMs/DXAmEX5aqGuftfqWW4aukThyPSjCw2FHDKVelXwF5JQOy7H9fcljWC64O3WZACezUFTmVvTscbfiBnIU+F2HSmtSuLX0vDX0OLvAxr6PRMvVYHV++mIJZ0adEqnOF1ugLFuoF0P3T93mEgGMedH71J/QZ9MFueoqbLHiW7+G/bDsKrp2PRZTV4P2XuLmqLTNOaUR5XoGkkz2XuRD0W6dBlaXAB8191dAzas2CxPDQyvx6YW+YE5WopmXy7eQowLcwVeVwxNDCny9roMKuby6xwMp7j021Xqe6gbSGYyfGiwLoOLpae4v1ZqDcwpijYA8rPrrel4xTLMGEpWwunnHeB6etPRiJ9Eq16uLwONr4bLx1yp13sYpXgVYoxNGjWTseYcMkUVa9cg0zXrRr9lhifT8FRsGWLM4yv7ws1966U/Vfp4dY+x/KUbXgyBXLLCoNVdD6pGzaSq491nsf6qOpbBxZLx6CBdA6zwiXROs8K4aEwD6us2oBgFEa6V4Mun7X9K3K09dWOiZewyhqlz1Dxqhcr14vl81iDx6j2tBp/TcsBtMHGRbcZNID/LFpluna2Q28+rbBs+rB+uYVQd6LvEyBjDL2zt/TyRbewwCNM5WJ4wD765b6TOJ1qlZ9YeGJnTvt2w4aK238+Q8p3WK1J63WJvnLzETqVt6DDXsagvK++cLuGJsGQjVR9oWibhwExfihkpaDxXnvjWiaByEKtJTmxYDSZaCheoe0HehqKgAukJpyFxcJ9zqv2CNbeBw48mkz4dzdhX5ZT8wjXIZwqnfgoWLiS5v3heUIU2M4aE/zxPzXco4OcULFyO4gbhHoMLz52UmyAyIjk2cfeTGBs8phw2zzUGjLZQAEudHQYVmncudfXSxQYJ01hGCSFcFa6ktGSNt94lFU8SGIbgmoOGBz+iaHmH9FtDCeHUOi1kSFn51Xrv0EtS3PDzz6uRGCn84Tu2tJt8l+vZoVe1uMUSKcdN0Hevc80byx0dBE6nkxvsPn69AsODpV0SCU0HIrtqdAsyI0fTQtLNWsAcZzl2VljPiQOt/PvqEJ6CS+ov65T6Z+kUewmGCkMTKOV7BPW9iuqII8iv9jknpeWTBEwOoxUGD9dOZIbw7kKIg3o/LMvz8c635Qhaotx8bg1XSLHJck9UsvfZ2dWMTcGCCLbS/9bYbGE0sXFqWMrYThVsI4N00nIYLQ0dfdTU9/2YN6fw7nSK39mqCSQwKJSDaN3Nq4jHj8eFdu1HlD2GzcnM8uWGDT9oJ1//oELnXn2x8SJJSLPwJAHT+SegiTmKXslTfB5GmgFgNz9vUgf922SNZx9g6DCCILjwwP+JWlfF5Mke6E/uE0QvPkbFXqIBxE848g1Gyf68cpTRoLhc40KuLl1q8DC/XlLCoVwVQ+5deldAn4tdLFfBqHXm8HmDH6vcUOSvqEjGewF5PHvtyOUl5/h5VcmGKkmIH8HDbpr579kquKDbmAPnTYfG9cJZV0zjJGfNeyGtGigsDRneLv9dLeDKxJT4Uize/LSrYcKPZDs+iKyrEbsYjt78r1+dQESec7BM1G7EBMC2fU6hTPhvD0GquAdNm1ogtnOwTCld0b8a+J+/0QqvqJDES9SkdD62qqHC/HoOxqY9Z0VWGjNPTeoqqxsruVXDhKXlEerPtJH79WQlwf4rtSY8s7p9vUHCJCl1/5hArEirNeryiAAGmSD3ghFKzfEyBZV9KtCPihlIqkrM6gn7ZkVoawYMc3kP/aD4GE0vINa1OWfRBoTKkeO1GTQsOZbyCRsG8rGH1NV4CU9mUrAd5bgZMjplo4DhfEXeRltNNuynssB303674cIcUThYBD4ZzNJ6Po37xQzBbDOZ3bW4GXLyuRdHD0lqfhqb0KhixpsghOWg4VH1H4G4GhYSskjlhb6LQb9lT82A4efKQDzX2efR/iYBmlfGXcMem8HCOpljLruhKLajFbBitRauH7/emMHCT7ghhrPel2TR+gdgHx9P8OfibpgwX44ZGzM+2DdrrdO5oBJvGmGwtdYNFJZyTFgoqRoNm1X4N4LHylYHMb/xbriwBHrfnxp01qCTnygNeE4d3wxvtm6wMLPkUtla+mv90kpLxHgVEcZz3G648EMGvb8JtQ9qq1iGkpZN6PO/Hp+Bw0/gymcNysZgiHfRoWtwmsFxeawuaN3gYY5VWt0aqQ/h2nOcVtj/Z9stZkp8rjVomHsXFTmGP0rbtzhq8qg5YYCplF1v0DDX90/wfVzn6ZMOPsK6zDsDuzsLmi4vZpnk9ufqdDHspFHCRoXDSHlmujF4ngOni4v7w2ltQkjPGUcVthTxGbpA8SGHzbXQKFIUvDMr59VX9ajP8jg1SrfLDRt+rjNhjYnqFuLraJSIGCnxrMdQ+TYMH+YDRri2BrofyMVJTJRJnn2OHlSOmmH4cNjp/iAffdcQTDpl/COwDznJjB2hlJPD5vt+skFQDI1l1g6hk/9fnb8AZkwccuiAb68YYjml0HtbcJIuqVGStmVU+DYMIoYWB8cyDrk7RCEDb1YCTHSvaoZBxPzEk6Nu0R1o0GvRVFnFrc1IcCZaYJKTI6eFlOcTYEILKxBExUb0PmO2O9/8NJT4qaGcL8vbz+9uV/V5J+IKJj9L6yeHThXH5fPF+pQEOgoAdMhGmfPxXHgaSKwPWBepDKGt70Cmz+B71TR8+Km3mJ7SbfqxKq4rdBza3sO1e7E0ymETbn2XJoHuUGgiNmhe0D362tZYYHY9h00NJct7fb/S6s8+FZx0SBuGcJbbTcOIpSCiLpJqqfcWg++uIluctPRUSsZTa9NQYp7enJ9SXt2hf1I0EIvwS7H2KbBkjhxuPzRoYbnsdh2DmDeisnjF88wcHeR1cuQI5P2dGp5sMZxYKqVwsW4gY685ekr0hZ6Q/S4xn7l2OM+QyL4G/tEOyLFTYtkO+UX8GNm2F4YZCrOLcYptH2CgsTq0749MWdl3jqHrnDjZ2PDBM2QNc/xQA60fiL9GAE5SS5XyENR923oNMUYFhdY5nyGrkfA2x1ilzPCvcI4wqmg5fEKD5WtsBeDMREH/G47E6EdlxLq9BhjHwD/tTPpgAXhPujtD6oEvTNO8a70GGUtFpQeUxF+r1+Bs6Lxmj9/71+0n4LhLzKBdobgHVvDtD42wCRkbLZVf7z8Bx/qAdjnOcgxrNawsTlQLyHpJv7rvACvBx/oEbZ4QzZGqjImIk1lPOdqfJUCD1jbPlQDk+AB6aSenWV3Um1hE5/CNAduzJgpDszmKVgKR72PY9y3E9GIX0VvUt90NC20rocjx9ezOXSrrf0Z8+9knA4g92dWezROulWBkfYBcRJpyzsAhEJjk2BwSEcpt3bYSihzPH8RWleW8dekW+INAYJFc5f9rE4J8n/xzx9EDxOpAD1BYZuuuv8xYbAocVAjqfw2KFQXC2W7Oecuo63uyLQdw1spxI5Gv/Y0V9OfKmz7YQCOCMPv0M2/tHDSSsKAcJNHUlF6YxuDQSk10dm2pd+UKZz85avgB0iLRJFEtMXTKgrkwMNq2hqHskkNGm9tQ2Eq9KpSrpH4yWlSK2zouCOunsKlK6pCbk/358xEMxUY92+9rtuvwpnPM1Jgrj7mKGON5A3iugpEMSdk9R4zsBeqP0F4IKJwjsEjY8jyA6eM7bY8cNPxuKZfo3V9qYu/IwzHdwkKznz0tapYks2sMiUqH5RIJsEv7uwIUeYoRM9t+LXJWJPoUZ0FBeaI92qVN2M5G2F1FmTIwx87KzM4SGcdkxnZrABNydqYEY3aeA2fJbu2qbrVb2y4olcT7K+f29PiJqxw3slD5Hv9ZVcFhwaGga/gZol/OGNgcc9ysEKvjA3r/1LPPWtzE/Xl45KwlX14tcJYwMMg/Q7Y2RX3GcdJFyhzs+16zSCwgXzl8wK5jLmIpVW5xYtJjPhG5llqsuWEHUJsDiF8QAigYhZyHf7v6rw7Kk7DAbx52C8OC6FWVU8UDinFXwlamwR1idq7xaNDl4LmeeTddwkVVReJQSbwHbLltL++10Am1r6/IQQZWdcIkW6UZdG5+/7WvXxY7UtX88UG/EuI4PMMXHZNzO0cuOECOnajNdjSpEajTdo8dm4YZy7zOqD/Xl8di55U4AfsOjIw1vzG2U5WfQ208e1Bq5N9fikXPq6EOdT2geu6r+3NqFXXFz/PE3CU/wFItet5gGFCt43FyoW9VZ/D0aX38evmlWfRonl2TcP+n4cqO7tvAAsG6b2gH59AJFj5KkbIIU62C7jx6XnLuynFbhoXOjJ9+WdU1dKdeEl22EgqFx/YtbjDHDrVp+9EMux7dENo16f1ieZnLW5riOXSmZlFIdMJ84BsII9wY0R922vWyLHI4KCSOgCbFf7m0xfzexv1hn39p510v22IHZxSIHVFrBS25DHmLitbchwGKvT4WOTNYkjENUCJLVJYD5aHx3jI6gv9RDhul0v/RkSuZ9aAPqjFUSUysfH21qJlRJf5kqSv86NcTwgbrkXTPsl/QLHKGhEF2U7P9jXnnup7z9ki1JiR7O7DJinL0sGLCSpnOxnt1MivuqJLYhh5lwiK9DgufoPn+Nok5e6Mw4FOwz2UJF1PCOX6GlOBRYyNxa9G35hEKumcIdfkTfC2ABCQ4B24ieQZ3UeJT2x7estgZf0JdMpzHY3p2CdZgrkfDBHnXqttCZ8gHmQSbv9bFhypxYEjyom5nU/X2WPQM7RkX0b1a7OLI/JUjAj6vzS4vFjzog/zfcobwZNGMmWs5pf7w99aqBU4XVeIqJV7T8pNuQbCW2HWrXp/31ixwunT60LORtnIceO8zpT10DmeEdfPDa93CpmvdZQOCBrhQQmWjGJLOmHEOma6iVrxPuYJFZcNGId+4ITPJ/NrbtJgJorGxlCdWXAylnoTFJmB7ey1kIBnXzyLkrdcM+Q3FpZPlFLNoQcAjh0w4JP7IyxUNHyqzo0ySIXS1L98WMF1zj+e5bdQhg7EZVhPnqDpPL5eSMP9ztAQ1W50HdqbYZyFisTuezP7cgoVLLxYuTT3doIjcTmFrEp85N38So0wOQQcyh0oLRdNgZkjFWOy7qlmlE+UQJ/27m8VKu9Oq8ddm8BLGmIJwK9P+j6W2vVu8tNhlPygpLIUrWiZM+r8S1M07VB8WLk1Y2McMmZ/LooR8mCA7p8XybaZPi5kWo4Yl/mJoqXJAd1XDIBJ29Wsx04QgmsPJy/ZMVruHOGHp2mUB06SHx9DOlIF5KOaPuaR+PE6etH8/+m1RQ4Pi+XHKrd8GGx4Fp6xaLmnRx2NRUy+GEjBsf4KaTnOTWg6RTQag8vXFIqdqkOLTFAzn2YIsgtCnVUCyLS8c1SKnivGp8u7iJ5VbpxmxNzlZ3qFGs6iR9MpnFxDM8BcSBnKQ1WcjmYjKEVPDo3Amr12VoixyKAW+rY9h0VJF4gGf3+uzr6rIh2gEYwyKcf/d0+KlSvKcW6etGO2SMNE5yYDLcIDP53AJxe4wTYtcjAahbNOwsumG+YHN51Bh5KKpAljahjUL8Gf3EknwKUGYL7cseGyLlnLx2kio1opQf0vY7Z7fY2JXjC7nWMGqb2s2f4oCtHa8sgEfAFnhk42/hlmhmJmjpWjSS0QjDsfIwpfQiw0pwxLZWS1aQij8Uyr7ztNVZCvBubqrb+2zWcjwGN6fAvDUe2HMAlzOVRNbUjuOZ7eoucozV37luYfD2SFDERTYzCJ2DguaIrgMAa/+ok0Xe1T46vSzBfRhau1g2jlwwt7y600HEWNBv5D4Pvbcv378a6FTQqkJjdf1hAWURhmWlMLb2WfOq5/29Awu5qnv8tk8tpjrPG+gNNVAJwTe7aFjYLGkBAvW2hrBHeEWiCAh6fCv1fYaSlyVLP+MpLIzaIfbb/2rduWL0bO9+NdQ4irGys/hcClEmDhonvgkg6UZyozAbQ6cR1NPKk3V6qW9OVE9JiQQBXBCRX8NJZYeB+kD/7Wq3miTJ8D5F+P3Lzd8WN1wKTtzHv15x+W6vSf70mzFVOloH2AYsZCGV0oI56KTvEfQLVo7DTSGatJL39eAYpVd0nUK2aPxcQp62ImcFGP6FAvSzClukCFoz49u7ElkIhFlnwcMo183PTd4DS7mA6rIL3oLV4qhauyICXlcyqfnsq8BxnzAJd2+UDd7CdEnCaies08qBunqZWCxtChEQEoTyQWsecqwldjJ3IC+DCvWl7cfyPKsiiu2vlR4nIKo/Bq5Qx09RU/ZQWxo6cBAk/+FVfGetMw7430ZWFwk8hpwszSAgi6Kzpum7s767d4oII1KAcTXt8/ks4QGQisnkWdI811vtbNuGV5cQipa1qSCTq6OzyyimlZ4681Yg3RTcuys6DLov0hJUY+FE1B5A5YQLoOKuZTlVgRbNAmonuRf7+qdgFYGdC6DiSn1IJWrv8Z2FZvtCKu6F+K0TYdipJhDhoY6nx6kN8rER52uk0KT6Amxzd++DSbm21HdCaDwntH8W+l8vQPX80x5ZFvOARPj/58m5lUu6QzWkmKfQ680Rxq3wcSSrfh0+UKpGG9NSgsooX66bwOIufET/rezM0N0hW/uvKr2bmaD81wD4+45YFZoQIaHUgly60kmxYGAzeSqT30bOAz1A56fjphv/ig0CKtm9w2h2wYOc61AMs2AX6mPB2AIA59GyWnQ5jZsWJZ+72cncguI/eICASyORnQeHOrbkOESZnE3iY4ZbsjMiBO2yWvLK2QbLEypGlC8JMUx+1RSg0wR892tKi9NH0Ao5miJcQq6Gufb3xCZOc9uv7HMpDScjSVRtsrR8oYfKQwQTANvN29Jm0brFKmojBSMx2Bhkg/akJJsQAVerlcy39nqZpZ8qQHC5b0SPwHJ95BJoqHUovQRVNDtuw0TluTDEtXw3T98OYwWQ+WOmeL82sdjsDBYujLBsEOB0Cyo642c7BQCvyavQINy2CDsEkkpYPUKo7eOcrBKoBP4j/FX0FPLgTNFfPj0dch3FfMndiARbmhbwy43YJi7Fy0wBI93vUrPq4oAhHZu94YSvoQ5dmIKIKbYP+oSzstIqlbkMPMgA1MHOXCCWPz1Q+pNSKWzosmg83s8IaVuyoEzNZ8KZjDUVwhUfW5ZtuEuUt9TQ9vzLwYNqxeyP8+0ERgXGgsPR3N7BlrT+fkVw4VLtFOu1WW9M6IS35QjLITbbQ/AYGH4WeX5sZFhYw6FHzCf8wnvib+rQ/v/EwwXlgbCUkXBrOuItceWoUbYyTRXLTYUj7l8DiBNsHwEnJOaxijIYn6iqbVyVvGwH2DIsPQn3h8mAPP/eodYOcPIYfN4TK17FEOH2aJE3dFs/fwgTuZcCwAvKcN6raAdxRBiRCgk59SldQbnJjaB2PjPCjyns+38kK1yGI0rXRKuGHXudfd+nVTn553j0hZhNYhYzmE/jOWnhyNLD+plFY8wp1fI1uYY6reYZLw+1j8lXZHWJTT3HP/V0GFKn6f+LN8ewt0Vcjmn5Dny3pMX26Orhg8X1q3UQ4oAx2iszPfClQ2QPh+3FGE5eHr08mSocf0GY/RonMBpNj9DAyrHDTxpDUH9Hy1vTdKr5wClosmXGjisux5fP6GEB8eLFYDcENrjmskkUjlaQl0nUKPQAmhnvf2lEhLeZ+/ZgGF+Mw9TLn3Q6COnAzBC57nbPDgRlWOkaz73ayPUt8RC67xhnvAi3LJL32gGDdNp0Sl31eUjTrpsT97xRn6VLjZsWL3+rY2Sv2/s7kT6A89yS1kyI4zgDDlOmgTQLkr3SYSDDKpbSylYjWiGP1IOFH30Zbhegz0cbAnSySZpR3wzYJhr5/ioOi18uxvJhSrxAUpo2U0zWLjE1M6PDkG8cqrs+lfjISfD8/IHgYwcMC3ErNSipwJQ+bQeSkYBWJBeml1v6DDPPuq9a/9xYRM6zxK2O9nbtAQPMloOnabeK/nFYrVF93JopdEZHZiqZooqZ2GOHEkOsNTY3PZ11hSgPdcvH93RDRlmE+LS0ImuMflUUZbX60BL3chGmO3msKliY+PUvi62y9b8V62G2YoB8mxEOWRCfoHvnVFv6MvP2c46UWrDwFuOm27wsH57+1KTKgfiFx+FgQjkcv9bxC5z0Eiy9FoMlUdiVI3dAcBkMz1k32vIMGXPmv9Nas7r6dF+wnz5/N8edvXsejK64cO686ubR4He2x3R02R5fRbKJdOeukHE/ACAzh/p2xWmkHP0HWUf7PuxPK/oBhJLC6L8zIyNN7QMJu6GUmqCn5krSEg9OXCKzuMr3/tJTZ//ESmdNK24lyxqpTlyikwRKEh4++Me6avRvBT8DE0oE9UQI8rhc5LSmaQvQ+ZogrVqaL+dZWeYFah6jp4ixJGjYqtmfkNuqFOQNBgbktOodguGFaO4Jimz6nPGpUvZ6zwR6XbnIByGFusd7NDNJEO6PipNcmRy+duvC9/gqZgDqWiErErlS3+PkJ9amypLSLY+KT2GIcZFBmefKe4qn8leQSDhaUhE+NUGFyOw8ISpBX/tWh5pbvOVgaEKy3y94cUlRIyvHfLFrVB5aiFAM09xYg3RMQ00VlY0RLmBjnKz88UQksA2VIp835yGGRcVgp9VXu/XsanTRi6iHK6Ru4LMPuUIEkb4Q9mZMXZJbSHt7FOZVF+B0yDjoiUv8ImibYbR3ImiJVozFOvzSZmpOKYBx0Vix/Kq0mhFlDbojb6icZzk0JKsaaixdDn0bvX3Ruiczeuv9JCYwssoDtPUOXCeT+Reh+/1nBoMiPxVBwOy2q+7N8iYWRrNZYjlxGCIksuzEUWu8Aq0NExhGmSMTJc8BjSG9VW25ymeNJE2ykDTMad60wBj1ld/RFhiIrCGPoYE3U4AVg/b19BiVCZY8xcuRxJWDToOTWY619nCLD99DS3mzlu00SGajRa5cZ1NhHhwqOI0QVCfFDgSqNgyNOFnzNsMRs3wrIYNQuCv7jW4GI0JUj363iLbClGZZ/8jbMnN62sP7jWwWNqTTZ0a4aZvNJNlMiDnegZZrck1XkOM+X6J4AmGC3/JU1OFVNQDndSQTwhdOW7W1bUwN6ABDCJxHsQZPdF9DTN+YmwzXJA+djFPnFHzU5Xv+evofg01ljpF/+8O+Yb+aBtxdpdZ1WKz7zfc+BHDKDJd9D8fNSqqJgk1zXXOWTdSZ9o0h8+VZmhLgBJD6nqAYwiJLFDV3Bh4LMOONYjWyHugXY1INk/atCU2LKkH9/hDMjTHD3tVUfYy4/CNknYAxD1SKEI8zSqdZRCynsH6AVW+NiVMjiUkfsGYtV9gEPIj7agveVv3FT6h/MRyXDbAi4JEjqDrYy6S6MWfK62ak7otGLoWu8sgZCkrPJosYN6ARPm5uhihPld+dRmJ9Bw+J1cmdKYk/T65OCQOBQNUBOSr0Y/GMhyZD1BSE0o3tM/FtOxIkG5kXx4sipf9BEOTNVYwf/xNegjE9NY18H12FDS4bPfZBibDRKYv8spiAZkagdkSAQMqYt7YupVjG5jMNBXIK52tJUGYEvKWEtZsss8YZwcyPHobnCyBDCWt+huh4oXbn5bQOYm3j4CPbZgyD7FLCweZCiiC8QEq+aZUdpTDZJo+vO4cRNEGQP2YuqkFpDWAZdXCe8/GYISgsQ1W1uQQTHEJb/8wek5w0HupfUMoyuIB+CjnQAoNZXxb71+cv6FV+T6ICFvNvA1VBswTkckMjiseHZy5J67reRTVPsBwZTkWiqFP6hGF21Sr/pS73cWzed05gEDEJeyjieJ66tvAVOP8aJvGd+5W82hzAM0Y0AiLTkhugSa+MnY9a1FYT7raEOUnLDdoVUFzuD4xCD/rxs9etKsRfZGXyLEzYyCOk1rbb/i1FJq1Q0Yc50lZ1oZAf46ccStHMY1X+DZQK0tzYqBX8dj2NR+DlEl21bTTE7yDRWfzZMkMKe6fo2zZ9QYow/zjDJ95vmQiSMuw6svqX/brDU1G8Z24Rw7mzzfKR72OvDHmi5mijElkjpkhgKa2RLs8L03a80C5GaaAKZhjZkhyG5OOEszBP8x7ixb3SxyGOcccLSMG730ghpK+Sqj+nXO6LOwshh1zx5Liuk4rdZQYIR2PdogXm5BlO+4shh7zxIUyFIkavTFTNZhhE7mcstCnsGcxADkQS7h3ULt7nLeneg8IH2vu4KWl6w1FZoPRw6Udsz6BmFfSri9qbr++3BBkKe+Wa2W+qQkZphqE6DjRNizJn8XgYzLrtr9d8jxC7RPBh4Yn6AMZsxiAjF7D1YgPDyn+2R9ZeujoAt/L67QYhqyfve4EXfCLO/iMxpJQitj2yg1B5ps11y+RCgg18cDhhIPd9JcUv9sbNxwZiQ6ZP2d71UZjnWp28s9N2QXuSw6Yrj1KKDS3ei3Y2Rc1GVcgGf93xf0H", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Trading.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"StoreDayID", type text}, {"StoreID", type text}, {"Date", type date}, {"Visitors", Int64.Type}, {"Transactions", Int64.Type}, {"Units", Int64.Type}, {"GrossSales", Currency.Type}, {"Refunds", Currency.Type}, {"NetCOGS", Currency.Type}, {"Target", Currency.Type}}, "en-US")
in
    Typed
