let
    Demo = Binary.Decompress(Binary.FromText("bX3Ljig5jt2+viU7IVKkHsuBZ+PtFOYDBoNaGDB6Ft3j7zcPKYVE2UABdW8mb0RI4uvwpT//43//9Y//+a8///Kf//lf//33f9qf/vU//vnXz7///X/98x8///bX//nr7//918//+K9//POPP+nnX0qZP1y4/a3Mv9XyQ/2HtJZif+KqrL+T/viTjYw1kZFRNierk7T/Dvnjz2pk9rtNxhNP484gYxq9zl+xp4mR2b//yMbPsJcNUA3uQr/2KAUN3zR4/Xof198x//iz4avGTdN+pn9Txwp+afzxZ8dzrk/qP/IT3y3SZ/1V+56B59Sbxr5u+Pc0Hjx+uf/x58ROnS3g9kP21SM+SacU/bXX2auMrCWy/lPZN5SNSPqvstFh4yk9Tn5iC5i7jl9VI8K207yJ9gJbEZ2/ZBtF2HRORDibpv5hNEZvvkjCrpdr1+3lP9UfZp/H9FtBhG0vfBPZj5ovUqs967dXo8LGl56obMka7CCNBv82fBo2n8tN138m+QGVZhvW8Erf/fRd9iOm9bDSZgM/EPaf5Saz3YiDpD6MxhiCy8MReCGxU03VUYOKns+XHyp7kTykOJOyb/64qcR+7SdkvNF+RzMi33y+idp6Uu3Y1Akieb5KXCzYN4KGmPi49LBv/rXE+mMHOUMUu9ob8VnYe2qJiO37Q3rmmPJb8SxsfbneSbfEkrFh+W3GYvzuvhHZE2dwT7VTstfakfN8uMe2/Ye2/DfTEraxtTwba+f807vza+91/NpmVHrOEYdsvBMbW4aa+Fc861E5oLNVmwj5plHr8tttP2rNH2Z8Yv/V5pvLvY0hv2QLqJLll27dRK2Z4vklE8yqeeNAt4XOTp36bzVlUFtehVFtbqxNqnGQ6YLquuciGuBG8jfO0tQWgBeOrKGgf00X1Vhot4XQb7eTqjNrDNC1T7mWWIC9VVwGWqI78mTSNOfvtOeJH0R/3ksUxzVV7LhspcLP55l6+ekhKqbLpvGaPELgH/njJ4WjatqHs4fI82WKN26R6o1/xfZDNEsLqMCJeFYBE018VcuWBkSfFPQxe3fJk0f722FgL3oJPWv8NX8Zezaek5Iff2IJxWHy9qt43Mz6DGTGHrECE9EiZpdsCVqer3MF42swJnLT1Oxx+tgAbMZPSF5r3WwcLK/ys7mwUz/gbjyrd2NIcJHW5zTrjz3Nz0mUbTuKLVMla3fbMiNzBVNJmxkdExTVrPewr7LZdkizYxrGPtqevWAz4mEB6rT//068sD8fzzjLsc5S1A9cxyNLDEUbmt1cgOLiqzOrFvNZ8FW89FmtpoIILkHJDg3ojFXjwGcR9u9qz87jH/ysFbYW9rJxXuB6Y3B1N61tLzSqmu29aY7Lgapt9vlb8F3yfNdIJlMr0S/heZpNPujqspnaqtnyZrvRWj7I4h6LOVjxVjXl4j5Le/jf6ObetM5sVAVPG9nXwtPkJ4REjQ/HbzFubfP5sn47QLWz2WC24+wlWxTQwYsIOiIxa4cT7ZStXYEHJOEBNWNZ1z6dn+1tcBWLLBfIXIMGH69mh7K408WqIea2a9UX2uU5djz4J1agc5iFVVNnXbOFxdP4U6CmqHCkdlS9PRsCzbgcEi2/HR/Wn71oh7XbhDtiNCNrRTwGpnVsu2+K2OStuwAcJ7W4Z7YNtfka5oKzHdN4tx9+0gymNbtWfiuIHiNcXMeGYzbNsA779sEPjetEd1pw3kxd3d6M+nw/hGRrAnNIulubIc/nV3BiC81ZhrkHfpLjsb4FKnH4Grsw3mhMMdrDr9W1ejjs5mlXCU4cPbsGJjDfw9TAiIvSGI8oQY8FG9ZhKvu3GM18vgp6c9HMaZILKzix8VRvIij92K9hPh65ep2U1auRme/g6sLQVpnuvU3OiMSIDLf4ZlXztqof0KzZUOKF+jn+9nlmjeDTz8fslnDxRuy99GoHDrLkfY6/VXJDE/puNnPE3R7Ndu+Fk12OpRj3mKxhCf3eDqfbnrEMYXEjMhPyiofxx/sya+kAVXPe8j0APz9bY4Zp+sbaRt/SPRZInTOM7oQfCExV6LZJQdbClbV1zlHGb3Ugl1TPAJg1Y7k8B2mhFKnU2y6NBXnhNzveEy22HcB7RfK+8bx8gmkaSt0noJIMQNDZx/LakgYRBjyh0m6HdgRCXtDDFl0DqZXkgzrVXHvSTXeHOTQBzHvCwOMbSvM01hX/tvmsoR+yUc3R/63YYcfAn9VxMhOYEBdjfeMjENEtxPEsaBhZas9MnmtZChAsNyFsYnzbaGQQvoOs3lo7nnfwwjRnVR3IECU0NlZEgMOjtS9yWEQZCA9H1WV7hL10+7rpr22ZNY3OuCTQvnZzfKEiiZImGo5xGUp0e0I0AwvTeHZFoSbDrZ3STGdVf+vMcuNYfkVHepcJpUUOhu8lhBcatsBU7zRJBeIhpiz5IAwXX4rZKA9XBBqmTONG/WcMCh+HHA1fMr/e2JfJqNVkEECXWLKo2t/NMxkLedjjCOzmeJjTAiAJy2My/yte2m6gGC+dn8AMIfNfxIMp/XaRx4Lh21UzNTKLay5yTHyzeXU3v9MSQTtXd/PJQfHN6I7Fg5ekVhq/OCxHxffWwfQF/xrsNbjLOHnHxdRvqh1usH0zPVjxxkDFiYo2DLfT2BGhFIfb37UMlvE+RXSpysMgfMWqbOdMuEIVBibWm9AEWgJhqwl0829rz27w51TPObt7YBSYmG4i8/pCawlP+i2+ZeORFzLdJhpGsvH4HU6VMIFT1U1l/DHj2OXVRvQZeLNppgEBACnQ8LypjvW2E0V8DN8vrxwgxLFNESyza11HxJfOosAOy+SyoQKOkwpInAl5q5khjsnA5AGKZ6KbGyualarugpC053GIiPYRjnydwzWvg+Lr2J3pfjhMByPmI8HejoovyYK07HiUeaXqXggFKB6JCk9cilwGLBve66i4HO0Aq3v8kGpKbscgH320wL1I+KdaA4GSQ+NLWYIOJzPXAw1VBTsFOKZEOHcUuE9mBKZIk58UVMeUm3KjFvpSE0AYO1qwkJAYZQ1brgkhOCFvabUt0/AMHCTf+3L0Qy0K/9nX8CglB/gLu3MzlTn9WY+nFNGCHYqpbErfIwHkOJlGfumn4risqBm1x1ui0IXLiJjEGtJxy9X4YT3XTAGpzQL8diwi0PK1VPC68XkcRDFg1f1Zkl0vo9lsbNqX268T6Y2o97OW8qUuS5m3x0ATX9jQjGVrAXeoPQ4rCM3RmAuHKZIFLhZtPPJDH6wwtxBKH2ffUqzIqa7PMxQZNs7R8qX2yb3RFjtCMCEFrN7fYzCx3wrdvAJ1g985v7LM25u2s+ASJtPx8rWCMq5v6yaJoav7cwwFeZqdFim2HX7wAZcpPezgxCaVlpvRWxZXEH5pltmGaWJQ9cyYYPlta4zGrKXvx8iyGmGXrXR6MyPhTNIf5VTGzeb2deYbYKmBmudNJz/hnpmFQ5gBvOSw+d6QUHV1uRpadYSj7Nj54qUVKwkNZkZlaKBiGo+hCMKlc4z3TKyCnRw/X4Y/Xr1dK1OF9mr3IxxBX7Y/QkM7UVLBxJBEx9AXQ62ow3K/S0XUxy2Ug+hLrkto7RW4qoZvauCR8R5Ju+IAbBrDwxM03hNpn/tt+rq1eKuD6csBKPCDl2kfFQ4Adm9SVgHF9To5Zv0ZptiXwp6PoSh6J+X6QMoRXDDf09BPstX0uP4Kti7wdLmp6s/OSyCo6QDC4fRlPJ3qAwamdNyuO5q+N03d7dhZxeZZH9A9NrvIdfzTPPAFlhxQ3xwqV1DfoLkJGdJW9CLqEp76AsF2puyWkwNTp/e2pa87I1LKyA05pL7sHJ72pSaMp8y1dsXOjqk5vbZGOB55AuFIg5X6bIq4ESuL1weCg558KymnM1YgaOfCemNxq8jlAXMec1kxMfJYnT/tiWwUtzq8XCzj3+EZxp4VtseLQl/X2VokbjkAdclvXPxblPdC5yOreNaOtJsMzJWufIAcAjhfJHoi/e4+LNOrnggmOFxJhGWgcZhSPieIvihJgfnyV9ZnlREMiiMYaitxCWQH0/fJR2xpRTWmKQVP5rHDac5v7Vu0bKENSImpPbohYkt1YYjGNdgo8sr5rcfQVRP87oFCdjj9+Rvd40v4WxCasQb6At28d66v2NdyiW0R5o25BWBOGc544NriNky3euo18PQ4RAhXrSjzgJPDnl7me7FOddkItk0hx3zsqPrTch0RoQ/s6xgzcsyciiqc6koP2kOMgbs/Tu+j3YRfLYehhOJ6jnOmuXtQ6GhNM8mVPMjNnI6jRx1GXXtXeihrDlQth6pnbx1avfjGzJvd+6q0WBlifGeLGA0HsJZEeKfjlKdHuzlyzpQI2644wenJhJblQNftpttxRpmzFrcmnNF1j6qMhedtMexomB1c3x+nx4+xreOQi5pCHH0Fhna2WQ3XNSdrz5ZEjCOsuu2/bzL2zuH1pxGD8LLW07NW/nkj8yhCBOr23LdEu4qHxzmnnZ2QP0tBZSqxAxQOnN1uwl1po2aSTcKxksDZ9Xnclys2LpkOZVnes6i3w2MibEtuXlxRH8bnL4tqbzeQ5bpR3uOAcl+ewqxNuoMAdpx9r5ZdA8mqhzLkvlSQtKwImG6Eb6zF6+ikP+KW4uWmoWqk6jhy0PMmrD+8AVmNYhkOtK031QeNpEbpFGt5+B1oYUcRGR4bUqXsOPt+VrkyvU2LsQCijaycd9iLHZZh5Gms7OrCQfb1/fjjjpcryaojU8laLyIjO0zbzRcrnhRm1cygHspYa9BpKj4UckBsyWTraa3PSO+zQ+zrWGncRTMVYRaXCgfZ12FRYJngTtu4VmfwiePsS25p3Nxp5tEMBoAFt0cqIoayQo6KeBfe2x6LQe3zi+zk4YqD0x1iX4bAddgOFhmjNFYPUrHD7Hu57UpxQHZaD8fNgTal9wJ+rExTse+byD2yY+2LobCgrcwKhKc4VbsxSjzNvnasNKy545EgYIfanF97vN46TDpCytpjM1YkaOdGW20UYhHJ6ZoITy0gmX73mqhyeyFBJSvu3EWUPQfJPcUC98NOpQ2jtBDrcMBd0/M+ke2KYL1TpaBH31UjgQXMtzBWVn+tZJVCcpUImA+rcEFxaoG45SaU7RCI9iW1DrfvM0v5216N/TyFxb0/31fvBHRVtU0uvn2vdNQ7vC9iUrz25VFSOJgduO/mi4T6yZg7HneF0ZrhhjCSAbsvYUNgeddKikF4RKo4Y26nur4OMQENNh31EUm+HRGpAHruoQXmTu89WZtekbRxzeeQm/ObL53WDBaE8huPGaewBSvEpE1M4wZhz/4owRZEtsVMRhWPpvFIlWOLKmTXJHaI5/bYATfll37R1MGwzIgI8iyP0oBlWU8zlLTcmvnKhj9t5XUZMTIEQNgR981T7tzuorYxu52ar2G+h3HFv8z9AQ7FhsyEM4JsmoYKFWQiZK6ea9Kpz/eVy78woApP3v2L+RhwBMtOPYWdCcpZ/At71molHOvlsZhFAPZ2wpG1QZQe7VApLH2LwtKZ0qjdg1c/kZJtWl3Ga0lJo0Xz1cQW/e0oty6PBfdgGa+AtVAEGWpksi8qZFBX7nFoU1dTNWey+64pmhsrTdNTONvqqPtSLCtmtY1GNXzuCq2WRy7KsX1ILkVVo6PuS6kUtwWr+MgsZHc7X8tjMko7Cl69XAhYqZaRJay4wdhxwQoM+etvfQBf0QsRTPN9DBfitQG9R6K7kovGTux8XCOdnR64Y6Xm6kExYkdyQXe/Q0e2exq1jZVSGKpH0GX5qr2husULVSORXW+yL2MoqCRBvKKSPlwpqTzc3LbuJrTSo5yKB/DDQS5GhG1z4E2Z5iTZa0NZNPvDRnYsjPCri26A+82/bT6iBTuxoq40QYXt4PcMThmPdDsyhwHVQfe9aajRUbfFtZqyi0Xmou4ehTUL4dVOzVOGlevDbCkVYH42amH801L6riMQMTZTDtOabnAq6/O4CKas6lJzFOai8xPYgtUQETD+iIOapoeAUSsnhOdEJ65o2+SorXIyDU51pTPrNAigvmvzZlunmxsFDpURCeXqSJvTS68skClx0/t+7jWV1jcEF3b1mZJDBRAlP9aJdjjOfEnTWsUflSpaneraNYMK1Z2NWlNhTfMwxamfFvYKdhxWTdguCD+Z761p9/r0SGOPhyy8kmZAezgCqDX1NrQov+nBlWZ7e6je+pyDrefbD2M7CmUfGFtuqpMnNEfDI+dVnkPgfkPnPospBqejGzk73W3Z1J7h4dMq/Oww9HPEKE0/xAIkOa8NwY6veMHOX0MORJ7NCMCx8x2ejEdctEoCEkH4Qc4+O/x5p2u3GQ+6XcFgzgWTV2pW6VliWL/CPHOnATfASYGs9aa6UARQXfMYWpWE6pzwi8gN9/d8EQGvJT3vBEdnR5eM070HoXedYpm2MdFMoJxlGlEb/tpIJnnCswbALolqlzab7pjDsW4NhD0T2Z3zYqmuyzXV+7WI1+wOK50RI6jaHumqhzUZNeouWpqqOpxq1/PY51f1MFwNdF1vqrkrrxRvhCzoKwv1NOcg9ROZ5NpS3rStEpdtmHWgjA/OVm0pKN4Q0bmirA32w4WhvUqJT7yhCfVI6deA1uMmO/XZhhjEfcHa5OFzt1mhQ9TExZ3p2vThN3YVNz7I0iLxWFt7GOQOs/eK/Iq7Pw6s70XQVegwzJ0OFomC73aTbYeQkYldWzwf9UA3PrPTtNNn8EhPXVdOOL9scjG+bN4MQ7cj8j1u14WbNhwORGrUfF8cUE4iUZybcBC9Pi8tORdrDrwnPGp/5aE4Dl5RCVUvSgOndM2b7KnE1b4kJjfLYe0tiyGdulBTKS1Kj2tUfrebqtvX+7NQ8LdeOfK3oaZn79zQSqGD+yMSEWza6bWOKqaw+o6oaSbCXV6hgjwRoE/N1d9OdorqTWst2+WA+hJ96kdy+jTHMXq+HE5fx0Xtyk6ZXEwarr4cTV/ST1+5vLJZrupflhJ1bQVoAgxINzFcHVPteWUo4GAlwykSKYc6euZgtDJud5tQR+Lfn3JE7anmMVcP8Qp/2nz4A0WLK4xDBYGG8MszkG676ejLX7DMsEvzcZa8GuorOFIUFIRdivx1IqxfBWGz/WXvD3scJqPazmgz6xD9MTWQ9LXF8ICpaHhVaA7zxU7Nes4NJtzQJa0DvSM4svkYCLoyYkhzeI9eYOiaiHZRghaoOYQqamSvr50rd9+UabcZwpWz1x9dsJz53QiUoc24lGetVyLOHU1wkxR6Pq58fRxF1Y9KAkKfJ0Vpze4JmUiDoARHSs0SGI1FoabFdgORKimPcYjOogV5bYebFxFKSRUETva1LkP41xrb82XjGFXztCNMLiU1YrVVe7MbhohQ6tl8M1IBQQvMHtltQzseXpYAzzPRnMYD41aKkJJQyedkhB+vNVe87I2IlAXGu5SiJcKwVovyXcnYua3mnbrKFrWIsPvJEg3R9Sa83S50unkgQ0ierUO38Ib2BiC88lno8ZOKe3GriWp4G7Y3QdJjo+2PBsjX1iEw5mdPqSOrRYkJb+uhYWOExnNc+iFBr1xz0ZPIWl9f9tQhGoQCZBR+j0EuJDUaWggnvo0py3yROyNdAoL6A1Pc2wm/9pSu08spJYrBrzVUZ7klDAMtasXp5Nm36Decq19Vu4EM8bfqw5p0mS2zISXOK9LW9SabP1HXJFH7DKL+iGBEYnn1piO9FO9MGkk9378zBqhrae7ZCifgEGQbDTbuLfCFBIyuNxlYeAUnZeLrXKijGJwOYbnKeAxGo7AFZKk1wsmuQhmDly2yrpJT1vG8z6UaiAa4xslQWgG5T/0TKj39wKrmj2NXX6uIcyKC6cJfW34nyFb0z4zRdNdRIl/dD9H4OU1HxIoOv1jBeF46DsuZLDpCkppaFJ3oRCZpTlRxI7YgAaX5Jtwp/EoyJfSD0EPV7x4Q+zV5iE0kVXIE3RWBmK31X4HASupV17+5f3iFkuErk79Zbi0RhDvfBh51b0kcTN+P06u7mVpXdkgl0p5j1ROqGIhNInIukkRCF0pezmjjGZU8Isll1TUhIp5mBseWqr7D8zkvuQs0TYehCxSSqAnIaUxQ2In5goQreVN4ygGp472vNAjF1C2cKtGE43ThxwXOtXmMDw3kmtTT+0CiZrwCYCiacqRBeJVomksfVXDigJr7++ZdKt167b++lPYcG981U6ZVor1PNCWBgm6e+ps5jP+qL2U8QhR5qu2rdXTDg1/00VIM12/HF6dGHk1aeeSWT0iQqMrKL0r0UF90XtJlR+HS0dBd5Hqg8bPRrmqXYTSwwV6jJ60+fEB5EbZ/YaWaPNtMX6e7AerBaz7AKxvl7jftqF72STQZWeuGkYtPiXsP1dL6s4py6YLWsCs+SCBDa3UQ+ZUkmguIzLt/X+rg0gU2v7IQFfAplttT1C8Iv4DDkEjQS6fM9R6uPv0hNbxTR9b3x40rgqQocHJPq9fMJ3T1oA8k77w8XHoKfm+yVSszVEfgeXFczemtX5CuQTf6p7V8qoFJt4tiutFDb9IfmYihFeF5KrYjeKSPfFpGpouqmkbrqDaU/ogDnnVyiubuSHQGyCjP5t69gNNwXaS9ZaQy2KDb0w7M/RzhUoxUpb+fFocgqJLwkLuMx2RTKtDmyoiXQT8Neb5ObxNalGYUHIqD60tgo79lj6Gpw5ymRdhuRKwOYI+CEkyT8HEeoz8PlNQo34r65B4ZI4u2hwe+pZgxWNXLErXh7Sbc6KlRj6JfmSkdpAFzvyIYUw9rFTOhCqc77QY6pYdjMV+ZQBh0hRtrR9obDDUfyx2lAF+4sXKPrlyZkvWJM2HE1lbh3/RwmMzHi4JO3DG42hDmBEvN9mxdGs9D2iet1fZn6+hKuNsRV0x9AdfP8RxaKLwxF4waHOWfEiC7J8IDGU2tN3YYoo6yryWXcYYujWqq1hesJVUOONnXr9zMg/71wSmpQFwjVf1VdJo+FpcOLfV5WL8KuhojdIZohxbJrBzZ5W2TjaUxogl0mvVKpJd3ofAwhywqybS0rPRKO404FYNuii8jZaud6vPfBpKR7C99tFSRy8Cb2d5ZSy2PX1tSX22ZBpbcqiiVzAWeOa67F71FMEMpxZ0UyOz0MAKD+KwY4sygnpxdDB8jfbBSSi2/61mB3e2JkFkMbyF53sgnaUkoXvX9oEckCn8ZaNNj6MDE0VN7di28nY16VTBKwl/as2R7Pb8uQC5oB/ctS5lqXVMU9oggExuMjPGvm8/Ju2TzbtXoKFpD0bny40CV8Nt2YQ5Sl+5BadSJX+ulz0rZYY0Y06TMD2tegxQqajT9tLhmsQagPQxMBvF6MDA/Vtvh8ZcdmjsEoZwKaWRlhvdcG0PSEVnSSFq3j+4ak0CeqENYSTkliGRNP1g5X+3VUblyMhQS+HOFPSbGrpCvIOUl4lnj8+24dqRXMBEptU2Io8ErANHCddKcspZV5r79WNuYGFejNZU0CVDeLjAwvA5EDi6pKfgkGwvuWW/dYwHYt5rG8cmqIo9961VjOpvmzmtJ6dcxKcrFtKYiWFlDB9uqlbUVe4OL1lQFKzFzcAUfWkdW2AdJjWd7obtWS5V56R5j0zqfU9evL8i8sCphGaQ8m3FNMzABA37BwyRVMckaJ7gdMY9OxgIy0JYFUbcVtu2QQEQqyXmSBVIXiJlz4gNxpiLP9qbIWOk4Bp+b9R7DrQsBZZu/NWWGnOqqFJu1rcZKlRSNlT3Db6fLTalOD7WojIdJ+FT4TTQvOtF8ngai1USEAWdwczSPJJOFETfOgYNdw7JqQhLiOOwE/psJfgBtVX4Ot5y5HHbGcLBcQWjNcuOZsL13gyL0rypZQTjVrpH11JVTaRZp6O1vCqEpp1+fX5bCHbJQzs4OSV01Mqo9r9SNwNf0Y/B6Rs+/6sin7+phZ6W8zMe/LdkH2XP3dI/ZwcAh0LXyrLRdamn2aSfmcthS9UDQXSXmnRvFiUXn9bwJv9GMBiRLLMLxNR8G8Fpl2uGTEkMXtUnmpVX6vGLnGLvoSFKbZpGFVtnFYuBL55CW0nTy4ANUFI711hQFlFX5vOvVyXWT+sy58Zw/p2K2hq6VePV8eIB3aYtgre5V9fKcP58+TuMSjmPolIXaqZYXIXBKXNP1VFcmq8t8GZGmyOlgSo32VxjoFBeZ5i0+uUWjElxuqk/ddHTBkX9/qqWR5fKf/Dz0EvoHtae2OlkputXpg6pUd4R66n8X+Ptf/kJHX9LcU35IkJSan1PVMV4MRM/uG9E34Hcqhmq5ERklS0zx0MaO6BuDSGjBqP8+zObN2bsWFn1trvNHAnISFbMB+RtSEv6kRwhiCt9XRtwxYMc1dJR+p1eeSXGDaGGaDKll18yGtZ/egCz+uMdAx4S91b+FPhWDj+gI1dGfD+xpRkZDES5izhpZ68O8BY7BWGUotUeHnEbt97ipjtslGGYKqKezZKkvqSqrm6Z0fK4zZUrFU2FH/Kp9JQf+mfycmJyI86QRU5d11oeX5HPQzcx0z3HolGeL5QwNrd0wl8Nanfqc/j1y05QrramnmhF1EPI1LgjpfleYM9WWCZDN15NjkEW8gFLnyKK6slxfwxjqkPz75sMB9ergI8wmDg5ojqYv96vU1PJiHmGP2dfl8VsLp4i4yZm6yLaSgJzkLuOKAX1ouGqlZnWy5tet+hyEEEKIWpGHC/jzXBG+6l6a3oo+6zjBZozoi2Bzy0PMZMOW3ToxEFxHMVIrj++6EnYrGmGYAJPiFITjkVw6VTzmKo0YqNNKGkPgZF/QwhApetHhcjZKDb91Nfyu/q0yIkfQIoNdbyr9PGs4COJUCUHU1fG7jCu1pjWaGJqD6m9XajQQf65VGa14WUWj1NRY18S7VVbhg3fAyS03XwfZNaHDJL96BqNRMtgVyOoDCFXaXIvteUsY2n1R9YrJBv6skb+N51cSOEzyNU6LkoKqq7d5z3juAUkap7qmGrhQF1CeKFnBGzmVNe3vGgugaUy+bJzyQ9Xhnnx1Y+b+IqvnL00FZnXBx2UQzdOokOvGks90jbFbPZRsGhsgs7E+6+wn7d+RY3AG4ZbPfY1ylz2hTDBwGXQpCl7TXHgGRvOJszyec2q3J18Lenp8/CunDqEaM+yW8kd3GjohWk15uroH4pWAShVNpQgItUrPStvdajkIXVg+N/cRBvZSr82UZrnQhQW6RxZctGOaoOsbr17ASN9ouG7pgd+IAdTc+XnV5DQF1Un8V3RNuZKr7fk8OXEtROi8cqVF+lpuqm9ClqHHqKFudTxbJwmQMEUHTqtpxnpdLc8fjN+zf6U8O1JPBlY8i9OdLMW/60pw6hqPhgFEvm3Cz8ed+Lca5zlmaRlP1zUR70Pogsp+t16SKghqVNsu3WBEGnpLktvkVKfnxwf+YzukPRqET0NamzWqVFv0V8/0rKjeMmMzvCSkSZrGsWhi3K1JzfSaixYwmm6i7eiLGdsoE26aXKVNtdpMvOwf+xWV32kb9iB8YQQoC4j42VROo0Mrpo7Df29aH764h3F0O7wZel7l4Ua6Qkqjx4DRpu/mRxFKPM3QQ6UIKTZtD2ek3IMpQjNXbja0P6ulq2sayJejYKHpeFYMM7kyX+Y+TneWm75iUE7bGDrcXabaY5cjH7s6K+aUaJBrjZ5DLScJ1KUbAFUnS8PLgoy/sQlove0hoi1VDVRvcj9FaOadIQLlhKnatUZl78JJA2OsyKlSPKPufnNenZ69juX+tBRlDcJvuJKBgun+fmspzOpkshSIoM7HVWAbz6fFtQQxAaajknH4iPGZxe9K2xpQ0vCSW0/97euN230TirnzLY8vy680l2y1GbWeZj7EKpec+rx1dyx6KnOtu/V+e4ITWCoI5dnc/g0koDFMOcc70xg5p/oKtTG/16PhrbdnYx2XrcmKDUM/UJjaevJS18P2XFN7pufqWk8ph3jY5ctOM0bhq/SZ2TIqsL+xJbgCwy1C7qSuO/S0ojY8cNUEIpQtkPR19O0bIsj2y+pYqo1HGtCQ+8UyzIvVMH7jMQpG1pcSN5dCZwiCI+mbKg1p7NppecfjlQW5ZcG0g52FL/ZxUlF7tk0Mm1vh4fU2Uptc3SGlqK+YPsPd3ZoxnoOV67YJXBfgtnTMR2TqhaOHCaoHNNosz8bVazJYXUMQ26SHgS/7rfZbn1zXAkJfH8bnJh4xizZ8M2Z9JIbTzIDJdTntM83dqFH2vYypAgA4m099XnoyUkoInMFuxcyyehPdw02L7f16Z3/Yku7BAlKQ9im+I+kSmhp12msGIlIma3fns2/lHoJTzNPbFxCUZ60lzckwlBdy0/PcshpxqjWM1hEDOxXnr/M67KVUvRlfnapmtiwJV0yfBe10aahiXZGlVSBAmG3XvQqnlzQApUa+fFX0zDn8LHpJt3DUGNH4IcXONQpieun5zMq4RyUVOF0u1L2MvMllXG6+LXo6d/Yyn/f2k9A1l7J49r1Tyex0jwSUgibrBirKonqFsgxAUVSddnr81Cj/5u9KMDiXzQnrc6jt4nRIF0JeneR5qV61OhgcF8/SZ9v0SpbynLV77LRTyvxUr7DeObNmK0D1Z4+pZXoTXbF1oaFx0U+nkeWmnFnbmBkT07E7zay5vF87HAzi6N7r/FjnglqZ1RyAkmmvrey5dbrujPqeG6oNQX+8kvn5MP5mvHYYI0T1Oqc5AtW7nb90lBRnn5yEdppvBntDEzP73R+a5XgNl2trUEeDAwp3u+fGaV5QfXl5w34Y4p5hc5B9PmOBgyH+tFQh42THpcEAqOl7Me+9eN7ZMd4AfmrPV2IxgP+8EpEzaj17TTLAMXlsjwGrKKnGtlV+vqydWtlB5kDEOmuKXPBust161+ijcqfnO7HYwfAXWy1TosWk5yuxgmxdAaUl9EHA5ZlITs+xeSwakeFeU1EGL9h/bAIAePdFpHGivOD81xxVMNvJj6vOZ1PkUqjMXtgqfvlL6gbiDcO3WahlxUN6bqAOwoNnjMFr1BB34YcHIn288lb2Cbq4QNLAXQ6Qvcv+MVoS2a2eu6h5j1pbbU1QS3HbjaS20U232wgme9rBX5ssNa+Awncf40QTkTOWpCGvHP27u1uxa8wx6JJ8JV6z29dIO6W9KclMc8D2VeclGHzr2kvLw6Ocrm2bhvQ8zN01tY1y7stFx60jnx4zyi5Wpu92QxY0JLlnkAeB857apnt+hWckscUqz4bQHe3qfuEdWEX1WQYdJbwmUHdtj9opd6SrcUdCGqeQE9JBeKZVmnVtXkDedTyMXG7+HMP0YbCdzkfYykkSCeYiAML19h5FSaMAG0oWERHtjR52L6fBsBpejFVEI/U5/8jkrzsYG3iz+sNqViox0f7Lw8xSl9lskj8vCqB3L4ypmLgHsDfNfEfj0rQsJrPkZI+tgFLZ1cjGnVGd01vP7LQg2h6P3JH/EX9cwnIcIEjWlWqoWferrtrMEptH3zN5pBts3EuWWH/cBsqVm4+o6J0yA3j2feUuBkoq4FX3/ogE6XVDGwYwuSAGnE5UV+Fo0Vricsre5dnfq5jHkGodawWamQTQ5nP5cHmNH1Z/ZGKBvdWULROjMVwX9551DrqvTqXMxGwyt1F9ZMmmM1mYSTgmMvT+6CZKCtv+X6PdqI+StQ7J3V0+Hd6inK6PVB7AMeossAFabt1tGvwcV73qGjHmFUVcfSS/laOuebXfTFqx5D7kWWeax0+M6WrdbxXTZ+P4TI01PpZQ6SM1y/FCmatFczQuUUzdR38+jq8xiz7fDIc13kO4B6YZ8GpxM00facIrx6ixVT2mWtVTqz0KveWm+kZgFVRU4JV5BDjvIog16xKlVF6A2HMLNUe59W6TNesRGm6+Z0B3+XEda2x3n68s3BN9jLmpx5Vt+nB52YO+mlC0z/fZnnMqd07dL00OkzTTTU68C7fXRQY6Wl0XHucuas5lFWYTwHDQD7nAO+gOnq612mn5DWklwTjemHBNnzCdHhnkUZ6ziGlkq2zFB204FecFx6j95dbhsmXxW+xqZsxy+v24o8YftmaURxq85iMuMC3oG8ZlceU5hJhCtqpHMNdj+PtS0RjvnublwGpFKyUEfpTHSLulO/gdQyndpxpl5PMq/WpSJ1TesYPHUR4rXfo3XlUExcLYNXoMw9WXjTY/RPcGpQTo98Z9Z5Vib0HGz6ZFYdkKAJv4RR/1oNQGxLt2PuL1Y9Q+4tjpEYZVO7+1A7vb4g98TIP3W68yOnLv2z/vMdDRhfwFMwVDEmFUB6W5lbwmmy0EZtawukEa9IqDnOASY9gFXOVBD4pYZSH7FpsyOcKUI0NqXkX7XydI8cEzWAc/RtpHoK0oKrKbUb03mB9Gr0dPV9zY0fyt9ZHVehe9m7Wscfnv4JQD4hiWFlysXo/kMsj6fNtVj99W2/jgFFtyoju2OABe4UAO7g9v8sHV5tFQcc9r8HgEka5Ly7RGpmPwq5XoHk+uXm2L/MSo5WFPui5/wDwOFGdghzO2plScYfrVr20fNVWzOtGy4zrAmU6T8nAUo9fWHbsdgurLrKmS1akuI4gLycTbHUZNg9hpNWV/Y6lKoyijHvmyaVplHl/VYxXkQv2JKeDqhJ/SnD4+1h+X4ANFZcausvegnFMlrUTrYsPlAZk89GVuhiT4QKscv64xK5VoXZU+hPLGrHr8fSV5MzzqRZJD+PnAmOgmkR+xN5sz5JeFSs07uJ64befo64Lqkeu8aY1O+4aYM0b/xmJSnUYQbhOmuKF6OlW6tYOiFWCnUeDkuEqRdAU7rar87cwXwL7hdGk8Ga1wzUqkkLEvHJ0hadgDxaizff+TlLh0c2gKN1FMnQ9j593vfvlrLvGmKMvf4ooL6RAuGXnqN62Qzh7EhQqe7m98z0DvKhMpflspdI6+ZyAn6W/r0OEu+tA03DjIlqFDs6vrCE2X11AUZ+wQb8M98/6knsWG5XM0TNOtuP3QVFJMCH18KMl7RHyRqQGLVsH+8lh7rXHn02jlOUm+S8BRCBZ539HoOSa6x/TjOp/qldGj8fNEur14U4W+H60+Ihju6NeaxLR8ryZZQcSM+T17HYlTf5w+G4c5lJGHM6iK/krsSUv3LtLKma8EMeanBBtlJE2rIfqbBOwxMvcyWwIPTriLA+wgZtzNPNrMK1h903uEMuGaV1fWPd02RwgHbK1vztyIepXRH1GItuOdFpkjho2NfLMW5ZYCwiUXMeB19OS2EuIGH06afc2aG/keaqfaA2/MnYfA4Oy7Zqa7qQyYRQRq9Pas0/MiO2ETrVW+0p5ZLmbCf6XPtroY7zv6yGorprjvVgw1DeHIfPT57Ek7XYQTF1a6FzSS30rRnLAizDzNhXQlkieS0e6JWJO2ByakBh1nZbMGf33jQrREAc4Y9WGTPHrRXJzpOYYxUjqONtDfqArRXu8oGEOf5calRDvoJm1EHfoYj3GgUzkmHsGJ96bRZBRxjbiFpzVdl8iNMZ5lyN2caL5mi3s/RkbUtJqddy9+3NCKQ5uPfQi6XeWPqBZKB8ekZ5/rue0VkSO3NfMVinqXlbKi9hHBgzHTDR20ktR7xjcUilvVKY/sIEUdUwc64YoGcarUikV7hvq+vsZWWkMw5qOfiM4gSdvgvXO5zJvWAPIddOUuEq0bI99VvQlDx4riOtogm89rS+qfauZMeAxhZlRNPirsMFTHjHSP481CmUXL/Ka/Vb9rEiZllpQbcqpv1l1BIQ6yVrPUvAhv39jBWRRdOnfOkoo26Jl5Lq7vphM+PqxD/nCbaYXwZs5RJxrbNj/VWXrmX58Utu+OM8fPEd8sqdieVtZ5dUPiykrxe9hn5pDST/O1or0Zux+p6XYTXUFvmrhkFpcbTUrJ0SDcRZmiY7mEkx7NFEPRd68TxoQNr4eZ9FiIchXX9I5iZgQFJqVqVie7g/IeZvCb4unRS6Wda8oVSfF4a3vOvd1tqTGaGR7CpEcv+fV831RViWjapPEsQr++xBohSF/DAyFKlO6uYrmOjLf7YJMfCOGBgTU+Vg2vIGg4c7c0LYT+3WNQkfQAizNnFbcGnocqROtnQUBl8uO3eovKvqHNAL8rkZkT1RQz1ncMcqwCzRmTya7tuKB+d0df/GHpRg4nu+6JMNjD0Rg+M6AOwuPP2UoM7Rdf63g+r55ZOPZV0aI9eT68zldldDOb4BJRH9MQVHswhKFWDaM0a7qshvZ09B2LMMAXHaIzz/nO7+2KiBrCB7OmOJOTfT6uAO7Dos88m4x2XGAPZ559sWag6nrTfZdCdxT3s3/aA6k9FrGuqPeRFcW3pD98SadIBMMj1n6ctCjmfXiLyHGEoXDYH3ZyD0FW7lEUWjEVH0UbU47n6oTRK7/Hr3SZMX5lyrkmedN9CQNIrHu4U86MuO9pX1E5ymbirC4ofb101+aiu2b6007AdZN99xrizjrvAZhyQq5BFVPdvhkt6IhBWGteQHoTngGRjDONlfbPHG0yeBq6IMlEcxdUhIzn6+7BlLjla/qEhiln+NJHJx9OU9y7Hd+n71G0Cx5gcniLD9SD5zbdN8kBRVOL6sQ1NtWpAqji9WFT34Nop+q9IoDHTnX6E/8fquaD6aD1r1LvoEqjKxUNzvDk5nVP9abbT6sF9+Y4J2l/dldvuZeB+3oQlZ/XPLIgrCc92dEjikqQqediuU31NbE0dPIjYz9byVKzah0C3nAdFZeG4qXXnO8g5KsRx8wcrenH8xr0vQm/cr6YzeFUNQv1gvLf7PapMU93tlci+JqTgdH3BfHF2d6juPrNem8zRtXP1p6n0XWFFvKTFPUO82qZDsJyoTTz4zHuw/dvPO8tV6uF+UxRjjGv+7M+slN6YKchMfhhXvXem/AqwxNTKHFD2rzGfV8v3lqsYKIXtq+fwbpORqdpqypuV3Gl3mtWdTTv4XBmYXEVJY6tHyvxEa4JUoqbTpyR+4lvfERnOoS5iHH57ewtC9kKXez+9YpCNfUH9swsdF2A2XUN+57XULJN9Q1nN6Deo+h79kcu1rTvZYcNkaxrYWdM+z5nFlXfX2lM7VGQM8fxYD+6c7bcobb9zYOfN/ekttHu7qnqeaWqN+G+hBCrUY+FzEhVt/Te78oe9HuE+R8nK7TJPkes6rq8Y45zK0dQtft2xBJpkjn6s1S9J6U3cozgLz0tWR/hqdY1E8vTW4fmmM9S9Z5ubvKNiw2N7mqh3nRfUH2gWwI5wXk1UG+q7V0zSY/rZ+bkrPP8WVsdF4n+rjlP0G9TXVVgBS1tnp+b80yaCcLIWO37zphH1P3PqY+UyVUFZo+J85qndON73OfuYBaVF8bMebJzQVavMZJloKbUFcrVQL3p5KvHQa7PeXjO56X1vovWTJntHQoanCGSYoz3hps4fV6SX0NeCmVFtmoVdA+vQ4mXOCE/Z8b3mMOGwDX8OyrldCoGoZcirPLSzm24LkNXwSMXp/qhVURX4mmPwUDsYgfpDZ/L+rj2iGw5F8U5RgSrULkurd5k9/jvgstDgMPRXPzwe7lnynYvgQBGQeHKo0XLN89NKypuxPf5Gkl2vnAX5rUeZp4K0cPN5Qv+qMoaVADcm433CkxsCMV1bx899rvM08lgq+H9PMkbU7xYbV9HU0wyuu8zPaJRzsBg9vGa0IuocHk+75tBIahnK/HOnk/WCyDWRbkFLWnkJ0EjH+2qulhzYlAE7eAZow0yJ5dxslEGKslDOkCj+WTL7WuPurqGqfCZxvS99xoXXKqDeyrXEPCzjKUGcJfWYhOuWft4dcOe72sCubeO5dmV/jUh21LmXoRmNlnzMVaZRpmYTcl+YnxuEPoov5SNlhGONBV+sMUqmtjXRqqXhLlm4fGsJA2gn7gixENxVHg+3JIvalXcmNp81fWx4Yty39csaMB1+aj0nB4c/rZvGqvRkoUZDc9qTmd4F9w7L/HaVzrOPXS40ZC9LwAW/9ltvSsAyOtwhp9Lfc/F3fQ1L6UJx5QnIKZsFQrf0+eoUgzTN8Izb3cTfutllEXEcsfD+nxfc2YQPa6Qw/jLZ/vua3tI0ZTuzC+PGS+pHo4F44Vdrclp4voIl+KdPiHXlyv8MAJds57M50Nhv+/0C79jKl+giGEPFPcMjE7ug6M18f3DYMhYLUUuem8NrWETy4AYh5I7BxiYep/cptvpe2RT+1LR0u/FUEz62y4YvNzYajllHpvsA5MV0rS+b952miJ6sW5IarVFMw82/lYLUV3wVXk0AwBjvVYpr4Pn3T44/XK/6eu4btsKypH84Yb5wKFD9NQof5QnOWQO7qp8M8ozhDco+5k6gmsdIseJTuKbv2hHKDZ/IdE1g/A5liD80k1+n0s4MtpvRUdr4uAeGmEIDzmxeGYCILvQYKnEghGGYew0hUdoDY745pQMzCkZ/sRWnidqmowmMUDN6BIEWcULe4gW0qLk0tdORul73JlirW16SB4l6Q9TxMUXW7922EbXc02yEHgJwIp9FVxnEZq9nQnV3/NOd5z9dOryLlt7mLted1CYcHQvbza6fusbioaK5eMVuIIaCzkN8ZvshiH2urEYrJ0EX1Dm6Ty9op7MBaGX59V83Q6NCSJhvq+W7O+B5/IQA/TmOCxKvh0CimEG20dSTOkKlX3NNgu6coYeTJiA9X2SxY/OJRPmXmpzjI7pGbdlpGigX0M+TSOyekwNo3puq0xrit8e4Yh+9sVcvWcejNmB4WAYqzouxCzaWxFHpv8kUhvqiUOY+hkXsQlP5yVRRyzf3ztKPjk6qS3BYOH1vEFZ19yY2gykLgUyTlXOJrvGV1X2+w2csN7u+UuI27V17fSQrECC8itYMy7ktYVXi3ZQtvONnlkLl2qcq5U32TcjoyBK6KI0ehbiNVV95/KrNFpqeDx6C1GEPZkDjw0PaczneXpjHB7dbEqgoYzVd3HAMo1MGvEVzFV+tvC6XXLimpsQzXmmkv5/XtzM76o+eswo68Orcl2x0X0oli/4yoRvupMRQWVNIISpWdIdr6+kKQbBLMs423O+9/gZQKrOXpZilD1rN6qf04WMgnohOspiHlatVzjevEJc2RT+zzw3RX2UF2shDR+gmMpj5x22Rz2EybpGyQHmuD3sX88kKATkwr+lwo+s3/cU28s7R5UjYvhZucUXrjZ7AnryvabyGHjiq1UcHXzOWlT0YVW+ph/NijmmLZ7XHj3DKQbZx8SsDqPrj5q5h7dp6wX1SZhElk023Sk+W2337C5Sc48EoxZ2z25DcQr4lOh0XmyqK1sMqBqRKqN8rMhqhPgKclCO5XEAojMhMyjLPTVAZ4lrApFXy06ABz52MBXOTAsyed5cNtRmVP7ifmkU0mX7StdlyfKhF7quvnayuAt+l9nAV40iC+j1fL5xD9zJfU6MZnPGogRNgvIMe+vm9KinD41yZjG+5gsoSgFDq1Ikyekm+1JvPpRDfV/4UVprDsGeq2UQYfPC1c29Kb8JbUJKa8lc8x76HII1RkoxrcBtA/GpaQuyfl2BVVErXpzsgSVrEubyeGqrREuUOOUGVxkH7QAtf9vSn7Nr58Y9lKmUoBqZo1fPQ5jrSXP7vsQzq8CSrt2w138aoZasEVaFxnLlCfOPYwMzdN+E3wT3FkF1o3twSZRL7OsKh47F+fU02H90O4hsKi4SuigLzxo1Hvc5eM3toTNCfVytovd00m7udFu7U1sWupLavFut+i2mZ4VUrhi20BhLUdcUU6E13fPUpdg2BuCmesYdbMrrHt8+ZHnKJI+/Fa0SOz5tDqEn0IyOHpZInXRqCD/u4DDKcxHqpvx6i9nzGPHi+jBEvdyKjis91Fci8ugQr+5Y0Bc3be3nPea93Kapo85NXfKuLu+PbnWZjU5LPK8O73u1oQsnIYPeg3A8XMh3nSiuhy2eMjTKByauWMluS/AQv0dVSMsjynxqrKMmw9Ww0sMM9I1y66vjC/rwOYx0hx6ukZYloFqf/aMzswmBtZh4gmbIh6nplDvjdoolT5qKGoqXeZzQs6IqzrOBGJhxM0KJXhJe/OK3Jvv+acoaOtlXDuD8HAeiCZHEe7/rDqbtdiRcMRnkNhDfB35t4cAajp+ppRxJ2Z0n8+vEwA3m/o2Nbl4tu5llX3uFYsZQw43vI3ZC/W5FRglBuFstRVRK9J4snakTPB3C2STvTdwx+M1nNeaqEV+mpvkLOdU94u7IeHFKlDjZXb6ryFtLbE7SXOW9XqIj+jGDcjwfed2jrB23Kmp84pmktumuoDWrdG/MQ0v7jSSC8GTq7Ik95kkbZcqul1U4s7enoTrckw3Uz5jNIOyfc1FnwxSpIKvPUvpdBdtQ6LiUYZdne/rlrTDxst45xx4P3D3PaKdb3kpOsZcVN9vYqUTWLL6wP3vTT/ltk0ErAk49WfqSumlU6rqzHLfi3UavpDszWmlorfBDHiVLVVzFuLpI3N1zKnqW2+78pGHFNWLXKJOVL3ueaQm5N1HptI4usuztpvwyJ9DDtBh2yLNiOT0Hde68Do1Hf7Gke3OMS3U59ePRXyscFm/uRlmWxskQvuw43LpMuvhctFj0eIRUboXDrH2lC2m8snLfPTY6GjJCoOeZefcRnmlK7NOUKCjpWXi9XLoJD9UDCDRfUeHLR0TQcU2awG06z0eeJss+cZVysM6UrBO9NGij/Snbzk99VpIuFup+VVEc4XwP5h7dySWK0J2wPx9I38QejzI4zXi2pVyDVcRcAi9ZgGdwW+WyO2720PfusTOsl0vJp0zzTqVJQdeNmxUuZzbtpvwiRApP1yOPXDjLPM17Ln1FpKYFYc1roXuoGnfXxRJvlryFdA32R+veitpxecyKm4CvzUAwFCvcLy6peK6s3qDVF4CwSYQuOCP5Eg1JgdAxDaD9xveNZ8kjzVLVXqIRCjo0i/0q/9n+PWH0nye5+eod/ygv5dQJvXxOmGKQZbXhrCiMsf+SKKYUhAy660rUXtFVT05Zn21stzFFnriG28702BVq391PFVYexZFGlQC9U53JJ91A4Qiy9vCDnh6cAQ9xkT36y0eayOqE9YFyztf02HkP1OzyTm2yvy3l4Z1s516HYYgR8W/mc6Hn97Q9s2BNZDOic91tEMkB+xXIxNMRzI/KWqG9bxoI8qmuspjrw/dyYqjekhwny/IwqaQrjLiaSm/x6pTJKjFwZVWe8Jx+a6pRtedU5WCYWmFJ1kJ61oHrishvQA78/zizQPLXE+s1SR23FLsYZRhfrrEsbV+gYLtTHnav3zi7ab6tWwWuKdFbdmfVnmlSEUosQflYdjp95tVcvBrImOt7EnTG0toCosoK8e+H0+l08mJyX4mHnW7ZoCpn/JAikT/jYafcfZNdJmYMXCge2qz2vCcR4FpFe7113i9+ZKLM1Lxuz4xqdqihfLQRXNtTKWzXeOkKeY6jpMLHGB7khyuUJQiE+xtbUQDAoHswiRfGbBbFRB2PyrM8OiqHpFRdhfs2imRe8FqWVXU9uC8Vfl3LHVTtZDHNezJIEgbhui7sozuAcl1s4JwVM87HTbkvnWTbweh4NbKRT7lcl8VNGrxX8R5IO/7i6OijcDItzzL0q8tcyRTfPX0QYrkKHwUjZByMs6bUrpNd3mf1G3DCQmt9Pk+vU8N9ZnG4mnIkxSNHelpyDY5Pr+RGV2jWQashaO77lMYamWSUKele9iUyc5vUKW25B9qzdJaj/QZ/ToSOLOrllLgPs3xzuTk6H0aoZ2KmrBsUge2eBde7kbrWWmIAhVGeoecX5d7rMmldBIpah6zESz13ss6hCytxS+XX5b7xxXAUef8Qpuo+q3U/do8vtA+qEW/k6/KwTXiDzYqRR2FkWgrMl7/53Zdr6raUEUPTEMt8lNGJ4JhGqg5y/y8=", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Sales.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"SalesID", type text}, {"AccountID", type text}, {"Date", type date}, {"Units", Int64.Type}, {"Revenue", Currency.Type}, {"Cost", Currency.Type}}, "en-US")
in
    Typed
