let
    Demo = Binary.Decompress(Binary.FromText("hVrdjpy3Db3fZ5l8EH8kSpdN00UD9MJIn8CxF0EKY7fwT1D06UtJ1IgcK6gv1t5Ew5FE8vCQR+9ePv/+9vHnn27vPr/96+XDV/3XT++/vtx+efnw9tvr7/99+fjLyx8vr99ebv94/+vb57++ffl6++e3Xz+8vX79/P7D1/H73/7z75fXLy9fbn/58PXb+09/f/v2+cvt3af3r68vH+cvfdmP3z7+9vL19vPrH2+/f3j5qP/t0yf9wpePT89we5cS3DBh+SHBD/2fLemfG1Ku+peMX+r4CQQ34HTjPFeshcJSL5GnZ+zG8GAMMm0z9jOfbFVuVK9GT8/UbZG3xfODVAS7yfELz48l9sbWQuFc68X56Zm7MQ7G0DbP82TzE3bMFKyhfVNGkSvD03Pu1rK3VuZukCvfD2gnp+qN2UJmQqGL+em5dGMl3FmZm2Hhdc51XGgUbq3YIUBqu1J7epZuTYK16UFq/Rw3dOdEaMGYmM1aGa5Wn55rN1aDsXnfBNSNzW+fP0GCC2wh5KrOugifnls31ryxbDc0TnFboSbh8m1NLojcLlFXQlJDkMKu7FTYePtyfh5qvDC0a9TDtgs0zKAnAMApzqDUuxvtc1IOccaQ1a1XK2qtZwCEDCD7KLZyT6d5ZYLemK3DIgnahX1rPQUgpACUcFL0oRFPaisBUSpcqN6EngQQkoDMnShlmzPP1bg7SzTN48oXqj+hZwHkE3LUti9u7eaMHEClXE1TCnoaQEiDMhcR9Wu2nBLbW3CDLeTWao8RzQLoaQAhDdiCrY29WYzY/UHYnK2kkgh5xkhPBAiJkO2jPG6OnB/ivdk6PWbWe+NurHnExWHM0KMUvm/K3McBPWwht1xavrKeFJOH3GnNXEVpWzMvYLTGK4pzoktdiuAxdxhji5A00MOuza6yBPhYK1nTOQ+fInrURedTBLxD29ob1INPi5pLfFXNeySPuvOklqhJ6k4DS9Tg0rWw5Eaa9oq6yB520QGlwRGA2U7fYdICSgW3QlfpdS972J3WbCOZXbzNnzF610JpteKsosXjrvepRmq5x8Y0VvDo0gZZD9qNicfd6YSF2IUft9aiE+ZC9ajexqWxi9VjLzrsBZ+fsjxxhF6NtnopHmHzyBt2Vvs5VmDYTzrsLAtJ05TX2KXkkXdubZW5EWw728MZbRF0UqE3pvsi8LCLruwBkcsCO+ux7OnNIly50xj0qIsexDOXHWj2wSYnEFeYVPRo6k4ij7rDHME6CG87FsrhqGuhIGsW9Jwi9qiLHsNTrbskGP2DcgJxLsI0koqyh13vA7s5S+rTxdE6v7QymAwVD7ozC4zuVCz3M5pTc7g3W6ioK5IuViwi8ahLjn7Q4HeLZuUVpCcSkgqBktN+cdXDLrmKQILOq+sy5VATGGrN5ao9eJsHXnL4QS2V+7aqxbOc8KNk1nLFGsCcPO4Oa2TnItj8dH5OQl7RsgkVFHbVDQwedoexsphKxfRAdjmUBFuovFmp7AXdGnrYnfdm+COjMPucx1iX18Kq/zdfVdkWk4ddciUBUv/7dgfJdKgGCh6NZzVg9ohLrhroZe9tLb4Kp2pADTXl+xmzR1xy7YFeD6fIKCNps3VZkijg9srCxSOuv34NRUfaVhGRw/2T6BnKNCcec2doJAuNnLa5uUUJLZotxKZ/9KD92qrH3GEN7DZmIzQ/aOUgNkK2UElE5Tpjo3ncndbMmzjYh7cWucdaV7R414s0QXPysDs9av6qabMFQ50cgW0lQeUCA4syeNSd1pLdbXI4aR9M0ZxdcFGWVS/sm0MPuzNubRHUTXZXqQuxa1+bRf1wQTdGHnSnSw3+asa9txXPAXbXylSVGo0Ck9nDLvlWOQs/7A04hC+vPqy3CVffW/aoywF1qY4EXXUPToCrVSHXS3rLXTzgsoehvPF7hRqnEwyJ8us2EDKLx9thDcLUI/YHcewBCwa0h6dLFIdy9YDLrsabP8Ez3ejQ+0JthvBKaqx5wGXXu5CUXUTNnSlycFtYWx9VJL23kjzgsitUSLjhe/UH7VCnMmilkkFmCnjAHdbIihKNRih0GxQ7SOPghMMLWvUKetRlz5pL2nuzCVQ7FT3RPohHRS7kUXcedFGL6dIZaWsqE+PtXmGU1HduWtjDLvuCEAZGixce+wPSPFKm2+8te9hlhx9K7TZQzvMWOqGHWiMcg5RSPOrOaFsw2HYqLCIYMHwt1KZEaLTKRTzqsqOAlHGXvkXejwxQFI1kurR62J1esJycjXdxB33ou22h+qJqJnQnNI+6/ta0kdv948qE47XlzKS9rRYrSR50PYLEmcBxb7ZSCTsijmmKgIfdaW6NHXGnwiKpsS6bowF7uCnoCnrQZT/TmjhpHrHtRv5hX1SUgdSrKBwJedTNfpaSys5PsxZ72/sspSIoD+97Y4+8wxrPy8U68Mh3Q9p1BjxKK0BAu/jUry175M2e1UsvRrdtKTa2i9E30Aov3VLxoDv3lb0D1uTi4IB7/JLSngv7nYlH3Xlnsgw8jni0WQx3Jma0gcAYA0r1qJv9dKG0TWUMkfgAHp3OZxy8SJoH3exZVqPvWr6IHotlpZ5VF2ka1ORBN/sGsuDOULPJId/Xwla1T+tUt4IH3emD+9xxb83CPfA/Xg6tpGyyF+WKHnOzVw9cw+KOe4AiaJoESnX7QcljbnY0nMqINF/5dNFxSl+VtV7UN8cedOfmFulsexYuJ49ahSxFW4QraXjU7DE3O8qGlffQbrW2sYlfwwNJTVtbNVY85GY3T7Qxis+DhzHKfZ5IHXK1ilbxkDsdahk02V9ohB7Yny1sTbvuwXNr9ZCb/cR5FKKd7A+dhk0wG7RMo9OozaOtvzEQ3HTerr8cLkxxe8zVuxKRPNpmN6THJvt4i5/FrdlCBW7R3l0jowUFrQxrCznclHMFS3Sm5bEWUG3QuuTSgoRWvIDgWwNTXspha9oXZr011vRsQUMrwZsjaOPsifngTiVPXPNF3VxQ0UrgkrzvbWmFsedezBCF83BpCypa8fXYaEwY6EYesyi9sj/UctDNBR2tuL6FSsePm29sMcWJ//K+VrTS06AFGa34bJ98zaDI3ECndO/WZHSPLeho4d7mCCUAOJ84uHoBtdno5ww6WvHt3oS14ow9wNpKhS5a5BEhHUUd6BaHHlZF70UwfT/HuqNH7qy5S0wpqGk+fM0LYaz+4IaVW4lYST12VSgFPW16dYG4bPJh53pQgW2htt1aSad0GBS1EjJ/TNb9gBLKUZ8j7IxyyEIpKGrFM3FfFCzywubuRBwUVq86zhoEtRLaIbSU2ncXJ5T3haLt8EVjc0FRK64hAnR6iQ0Hju0QN20oL+hiXwqKWnHSELKT9lfnF5J1Layi5XSgHKSgqBVP7edUPMyd41B8UXvWQCvjqQCkoKmJGyuitH3KpUmH3a2xYktKLi/onoAgqonjSCZGBmSqR46kTFiRaSQFBFltmONV92A6xDs23p1xS3WZFtWxuaCqias3CENijrMLxFPB0dYjtWtsLshq4nWTJPvSbL8QH22shVUbixl1EHQ18aguDuvsqMdpcZ+E0FWlWwu62rS2+J7XJ1bCRll4cTmN93RRV+chKGviw66KBdX2LD6c1uIuawnIo60HCOLa3F+yq8m7b1sD0NhSzoVZNOClFx2AoK7J90kRhrN/khWKqSaYAgSBLYTxfL8h+5OP7zfWQiWZOY+JKmBQ2MS1boR+wmJMs0ZIsbaCW+tMs0ceBp1NnM6mnez3L18oVtkltCmdyOOJD2BQ2sTNtrHWvbH1wYCf94WkWNvLLGAQ2sTLzX6GcWfqJ7m5j93raEYAg9I2N2fZM1X/UHmi6r8Wim6KB9kBDEqb+PH2NBfvLtrDNS2CAtxlXcCgtXkQIHRTQrs6aQcQgNy/d/AdwCC2Vdd6mUgZxTY8vZDKqNSOrjK2F9S26jpgq4zr4mJRXGtoiMQD2TEIbd6SHTQ+HoonXfa4EpXRFQIFqa16vjOFgbWvGSUnvt7FMZJJASiIbdUp//qNTlZcMnmkY6b9l0FQuiYOFOS26ubvimL46IgaEGDN4LNyYitkFPS26mZe2g+5B0mr9ERtyxgCSH8s1ROWguo2za2KMll2ABSI5milmp53DPiAgvBWXZ01rSygcZTK1kJ1GsCVx/aC9Fb9SCjPHAs04OHphNVtLT4NLuxZQUF7q64bs0ciYdwdH5qtXkwJdrZQCdpb9ZQHCfflrZcA0bcGhYqejYeUChTUt+rnQvMpQDAHR86jGYRtDOeAg/4WI5n3u9LV8JVDIBOTqC9Gm8JBgKthSl1dIN8feR1nQ4W4zFrGQYGrbk5NBLuvWKUsXt5ybZJKg0NxkOCqoynxMdGiUieWogu7yDLMBQmu+gcos634kznTgmdtiXnINcBBf2v+iQ0PIPZoJ8e3P9yfAgwJDjhocM1N+yxEdqrG6N39qdT5TJKDANd8OZzKcYg2OpbD/siJxoQUOAhwzWlmdk4/jI/nvL/20yIB46kIcFDgmi8SRv/n7hYKl1ORyIpLeKWOSzlocM2rZpOYWPCuEVFkJktfSw3B7AUVrvl5Atbvmic8vj1R6NDtdbUAcpDhmhMf7KFNyIX40GaJD8y1zNdTkIMQ1/wTD3C7W+qDnHBJ/1JmMlAzByWuuccsysLLd0WixXZnEZ5+kquM7QUprvlXBlT3wMPa4vgay9Zpz55lomYOWlzzbz0q7Yc7FovHIbPGnVa78ToDchDjmn8Y8P+eD9s6qtSfoeRxdUGMa76183POu+Bwau1QOUmy975BjmsB0mm7YGFmPkB6pqz1f+6uBD2ueYmVeQuPyzdReFzvgBWs56gZStDjmh/ZzcYzTJ4eCoTlmDTB+SALSlDkmhs8wRhnrKec9vMwd0LpXdbF8vQ/", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Performance.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"PeriodID", type text}, {"ProjectID", type text}, {"Date", type date}, {"RecognizedRevenue", Currency.Type}, {"LaborCost", Currency.Type}, {"SubcontractCost", Currency.Type}, {"Expenses", Currency.Type}, {"ActualHours", Int64.Type}, {"PlannedHours", Int64.Type}, {"CostBudget", Currency.Type}, {"Invoiced", Currency.Type}, {"Collected", Currency.Type}}, "en-US")
in
    Typed
