{
  "name": "Model",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Products",
        "lineageTag": "702e9323-56f5-55a3-bad0-4b653697f65e",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "lineageTag": "7e12cb5a-1fb6-5f25-9ad6-d10fb5bac631",
            "isHidden": true
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "summarizeBy": "none",
            "lineageTag": "cc002408-8f00-50a9-b15a-de4b3ebbc67d"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "lineageTag": "e953f17d-2291-577c-b4ef-34c57a602e6c"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier",
            "summarizeBy": "none",
            "lineageTag": "38b61fd8-9fcc-5bdf-a965-4294948d6a79"
          }
        ],
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"fZM9bgJBDIV7TsEBpmBs81dG0ERpkEgOQMgqQgIG7UKR22ckWxF5Hm83ll7heZ+/XV++Hsf76zbt9JU2h3v3XfqftH/cbudT10/2bx+zWU7b7lKmlprW+b2U8/CXmpLmCHKUXo7HbhhKf+qe0qxphjSnTbkOj8vh8/ycFk0LpCXtDv39KTfX3Bxyc9x1obkF5BbtXbOml5Betne1HlaQXuGu1sAacmvcVf+eZ/9zdW7uqg1koFXn5q7aQwZmdYZdtYEMtOrcvIEMnOo8cgMZaNV55AYyMKtz8wYy0Kpz8wYycKrzyA1koFXnkRsgYFbn5g0Q0CLnlv6dgBMFbmkDBLQocEt7IGBGzi1tgIAWObfs78CJAresAaBFgVvWAzAj55Y1ALTIuaV/Z+DEgVvaAAMtDtzSHhiYsXNLG2Cgxc4t/TsDJw7c0gYYaHHglvUAzNi5ZQ0ALXZu2d+BEwduWQNAiwO3tAcBZuLc0gYEaIlzS/8uwEkCt7QBAVoSuKU9CDAT55Y2IEBLnFv2d+AkgVvWANCSwC3rAZiJcytPfgE=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Products.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"ProductID\", type text}, {\"Product\", type text}, {\"Category\", type text}, {\"Supplier\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Stock",
        "lineageTag": "67ee9b0b-9a46-5838-b6c2-259aaa3afde6",
        "columns": [
          {
            "name": "LotID",
            "dataType": "string",
            "sourceColumn": "LotID",
            "summarizeBy": "none",
            "lineageTag": "c5722b24-846c-5d18-bf78-4d0ad73e45cf",
            "isHidden": true
          },
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "lineageTag": "52333c5e-a136-536b-a430-af59770b476b",
            "isHidden": true
          },
          {
            "name": "Warehouse",
            "dataType": "string",
            "sourceColumn": "Warehouse",
            "summarizeBy": "none",
            "lineageTag": "f67f59c2-de1b-59c3-9757-33fb63a5e649"
          },
          {
            "name": "SnapshotDate",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDate",
            "summarizeBy": "none",
            "lineageTag": "548d635b-561d-5c80-b38b-fa7f0b404e5e",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "ReceiptDate",
            "dataType": "dateTime",
            "sourceColumn": "ReceiptDate",
            "summarizeBy": "none",
            "lineageTag": "b967fd39-8f09-5e26-a53c-ba3598930636",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "AgeDays",
            "dataType": "int64",
            "sourceColumn": "AgeDays",
            "summarizeBy": "none",
            "lineageTag": "819f0a87-cc7b-5c65-a83e-143abf3d6bc6"
          },
          {
            "name": "AgeBand",
            "dataType": "string",
            "sourceColumn": "AgeBand",
            "summarizeBy": "none",
            "lineageTag": "1bef2f07-7757-54ac-87dd-a84de6cf294c"
          },
          {
            "name": "OnHand",
            "dataType": "int64",
            "sourceColumn": "OnHand",
            "summarizeBy": "none",
            "lineageTag": "af3f5e3f-782b-51b9-ab20-d1574c4ba6b4"
          },
          {
            "name": "Reserved",
            "dataType": "int64",
            "sourceColumn": "Reserved",
            "summarizeBy": "none",
            "lineageTag": "80809986-9282-5b63-a423-88b612f87726"
          },
          {
            "name": "UnitCost",
            "dataType": "decimal",
            "sourceColumn": "UnitCost",
            "summarizeBy": "none",
            "lineageTag": "079581a5-0b12-528b-adba-b8a81f839429"
          }
        ],
        "partitions": [
          {
            "name": "Stock",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"jVvbqh3JDX3Pr6Q2dKnuj5n4IcMYEmYY8nwyPsSGxB5sTyBv+Yf8Yb4kWlVSdfc2rWq8ofcxVNdtSVrS0n776ev3b9xfPn9699sv+PbXl8+v7z/99uXV/fTx5dcv7z99ffPy9dX9+PrL64dfx/c//P31zcu/v+D53cvHd+7PH/+Ex4+vX14//+v1nfv544evf/z05evv3m7b5t1PP/yMxw8vn19+ef/B0Ub5sbVH2ORrfZB3cXPB/+8//82ba96l6qhtW38BjReQe/vy/tPn12/Hh4evzrfs2vZ75312pThfZHQYo4P7/ss/Xv758reXd9++oDyCdxkfXkDbXGouZReTvCKOV8TrHWATPHPsK8jkkvNVBqcxOF2uHp++aowt0QWnS89jaLaWnh58MD75sffAL9qnLmN8uV53ePC9EA/DaAr4pCij6xhdLxdeHx6HNK+NmiP+K8j4NsY3a/X+gUFxnFvkW6N57X7r4/lhnDp262XvfMSBXJDN+wE7flyfO++2tT6YsZOLy5uMHYjjh7H0hisnchtvnv+TUcNvCLr4gTp+XC6+PCi6XCfmGH6JL0CXMDDHj+vT56NNNE+fB2P7cnt+wI4fxhYqzi/tdpe73cUsrxjw48flHuKDGLqpyAXw/bGReAGAH/DjhwEgcrHt8/NfNC3XDwDyw7wF34D5/RbwPr2FAUF+GAZwcB1lHAGN0TQAyI+r9ac+OCTZPqOYzUfwRwN//DBWTw++YKI6MJgcA0rujwYE+XG59ATb9YyAPpix4KKcPA308eN65ezwPJF4TP7O4JHBA3n8MBYeYPq+jYUXNuHKlyjjB/L4YR06X1qTc+OvfIo6+wAdP66WHh/wcmXrgxnz02pp4I0fNl48phS88B912hwNwPHDiFRnxEZ+Wdm3PvDGD8PnNKAEa08A3kRbGGjjh7167F1XzxfM5iqACwNwwYizsUeaMsy1NlfY+wjewsBbuA6yPDdHtTRPDsbOHxk+EBfMKMvBhh2cuGsGDZ8j6e4H6IIRYlNffByLT7G7PrHzMCAXrmPsKc4VdvY8u049EBfMKNtw7wxT2XyAl2LnLW8YwAtGnI0wdJ9HsOFgjY8ufqAuXMfZAnMpYUYKj4jP+0nCT8KAXTAjbXuwRZ5uL05fFQf2ohFqYz+AIqG2A0GQEwfu4nWgDaB3XlCPrfBOZOxAXVwEWsZ52S12w+RB9h4H8KIRaFuH3XxBDQCAlyAXB/DidZyNGM6Uaqy+OA7acnNxwC6aMTZh9T7IcD9uT899QC8aEZZw90Tj7Cq87AzxccAuXsfXk59tIKjTZOJAXTSDK3srIG1TZprB0mV8W7J6AjPleDYw30N7ltCethWlP3l5hk5J08smf4PRs7cAxLPS4jSJYaIlmw+gVrRpXHc7M0xhxeaZE/Adx3FhDd5KbzvFG3S+wFE1r3kE7EZGpyWZjz0o5+EhcwaZ1qCe8orMnzwUuzK++aSbLjeYfAUVDIdkgL+yocob6pLLp+5g4tg52yjjZh56W1F5XjzfdpbbrvBtyoXydoPLV1wa4+qQgFZev6A1+yWZj4jrPo08pnT/rh4m04rJe7hmioNMYd4642ION2h87DQ0D7jGYWiCmhyXHP6JU4DGMlqCrj6tSHyBsdQ9OtXO55RX5HyDxJ9cLNvntk9flgw+ddQHyUGYrfMtKO5yXVH4Bj/B7lV2z768TAeb2w0Kf8wiaz7Q0bItGfwpqLKv4lOSqYtfMfgGe4uTkPC8zKdkMN1g8OewxpfOZFBPvYQlhaee/YaomEWUEnMpcUXhc9+3FwrP78kz6y/pBonnyTltCpI2bd1d6fi85PAnW2WHw7YnvqKUG/y9OAmoabAggVqpN/h76n4qDD/FbhXGKlGttCV9P4eWjHXoyuu2ou+EMyfhITiANhPt6m+Q99i5RBYPVxGQszipSkvyXnDm+UBh2ddqXKzhBnvf4zGCotaYarzB3WM/thJmcNhmll3Tkrm3XqbZvSMvIk7uXvOKu4eeNYl/QGVyZrq13GDtz4GJ4J/Uu9W6pO2hF2jqtBT2p0mMvLYVb2/ds04fwwjlFSgfadsN6s7TY0QUJ9NTPrn15pfEnbB5CqSUgHGq+WajFW0vsFSOXrOkm2Dr6iJbuEHd2dirk8XXXp1KgrsWl8Q99+oMaW2SelAVg2tpxdwjpvYpKf2twP8Ym+8R95FoCOTD5O2t3KjGw63libnajV0sptU1cz+4V6SpFfcgo9sN6s4hOQHoWuRwpNeGVGTF3U8lSTb6NHmsVyXCJO87l4CjkRTfqwZhOpojXuAsSVmQVxHC8DMZX5sW5EY5OsvouCLvz7Xk7l4FrF4ViEV5ALa2zUPvRVVJ070IETZ952m8cFgUkXEMY3BZsfcCBgrvMlfPhho0PHkRImwGHzqP26Q61DB/0vFtSd8baks0PR0jlk1POLhXIeLa1zyVxnpo1PqSVyFiReF3JsgECkV5HU9LCn8qYsNe9OJUhrBK8Hy8kA60BA9HM49eVQjT2VR4Wg7+U4jwOH01WRUiDAb/HOSwZeZxokN40SEMEu8BIMqD28Qe4YWWeREhbA5/TLqhIDC51OF1SeJPpXAEHM0fvMgPBon/5vQTsCuHr/qDSeMrfE7Y3xC6Aii00KsIYRJ5JJ++aGU0qN2qAnFN458cNcPW765aNQiTyJ+KYxzeE2xYxsc7RB5ptvrM1um4Tp9WVL5g4/Cy4nWY/Eet1XiRIWw2n3vJZJObryi56LmXJZmnR78n4Qd8cOx0FLQiRBhsvuBrpkNJuKsaWedvNxh9xfJjOZhdN3+NOipIGLGW4HeIRsTrtR8t0nlVI65jbcX5h51mcKxmw5Ps2aseYQbcUx44KuKahXpVJIyQS3Bc5LXMl1HWV8+pgsR1zPWwexKigWLXHJpuEPvnmAenmTUv8aJJWMz+pJzD0fs2wS+ChFmSh8fcdnbqZ1LjRZCwmf03mgSkKNI3tCW3D/3qpATQUadCllc1wpK+CeLPzlC7ECeJjVdBwgy4oRPsmtV2Gci6fxUlTHK/y3il71yCtcoR1wE3HztF8ERWLHavYoQZbhO4HixclJj92kWPsLj9Ka+oPcwqTRQxwq7J7yViNDs4PfFyg9b7bm1akYcUVzSZ9KJGWLz+nIdzbIzTU6kWce1rCpxt3ft7IGv4OV7ViFWfzU5wYTHsIaRVxqsiYTfa7CUMBjtCtXgqFSRMAbB0VqnLx9mTmItKEqa7STA3HJT0+WQtInhRJSxuf6r1NRAc8XSiSRjUvkIDSrulIoPzZfo5kSVsak/d0dIADlu9n5AVYcJi9qeMLmPtYqkqSVjCH1h9rsfOKsGrKhKmi/G9uSOJocLqgRrBnMoShpOpSErSrqhw8lyblr68ihLXnubUncLARXeQQE41iVVrDfoy1OT67Sk/Ul3CYPXP7LD0rFS3H1ec/rm9KR/KACJKrHprDqhFW1GYEUJECYvVP+kCaHHJqil5USUMYn/KyGrpmNfJ6w1aHzox1pSEEGQ0q1BVwuD0z+6uEFJyjW8qTFwT+5OzCtCmQGzHYH+D1rcRKKaoAlVSS3de1Qm7yyZ0xGp8R5Sa7FjViWtq/9xPOsqYc//xBrePYKdwElqpD9NpiURhkftz1Rc54Vx8XlH7Cm4RduCPy5OeTi8Shc3sz70eXZXSaoTKFGatfusFR0VP3AvuXlWK61B7zmv4Tbx+OTgVKcw4+1xNoJ5Ry/SqVBiB1vevKpL0jkBRYr3qFNeBFn8NbgJiV6BNqdmpSrFqsuGNT7HAbdPliFJhMfonl4N8pqnG4kWpMCh9BSOPB9x0yqAOV5QKm9SnrvGIy0THzGQJIlZYjD52YlvS3rqgU9cbfP7UO5A6uxN/oTrFossGk0fxWJkZubR7eNUpTAW8Eyo5d7ab6ehVpLDqZ+f6iz+1M3rVKcxAeyo/dfVbti4qhUXoW6+2T1qMuq8W70SkMAj9cwrOXBApsNy5qBSrYv1xftj77AzzIlUsOm32lsDWtQJNpVSpsGTBQw4HlYKcVo9Uplj02jAD6D2/EiZbL4Dp9tuNmj1o4dY0SAAHA/SkSoXla1C9khScereO9IKSChWmr8lHgQlBelZMSdQKi9Ofqhe5M61YZHRYsfpzC25PnoMOjjcY/bO9j+q59I2T6BUWqz91zPiu6c6EiFStMBtuDqkoJCo1GlK1YlE8QIzbgjay+qwmSypWGO7mufQTe4CV4W3F6kOn1YK5CF8l21aZYlGrR41u2+2194FKgCSVKgxWf6oBIFJGpSYkQoXJ6b8tVs/uaRKxwmb1T/3+hPZ5p8uPS1rve8VS6h+jjiC0jkSoMFtuznp4xeabjM43WH3qJi+CNqo4h6MvNyr1yCJorJ2NDz+X0bXXFaU/ZUOwFg40EuVIdQqT0z/9xgqFb6VlpEqFQenz8UdOuMJteisVKa75fANu6ND17mf7NolMYbP5NvTwCfs+PwnuRKmwG+cPnZWj4UgvXnQKg9Cf2p/7r220Tk+iUqzq9OeEAP+Szp6XdD7gK/inBCl8BDYqU1iCOAixVJn7b4NmhFORYiGJH4IUr0Eb3EgVCiO6Flxa2TUO5ga8UnE2qk6Y9Xn8Hk3yf5ASrRuRihOLkhmYjYgbvIxC09OJOGGR+ef6eHPTTYkyYVP5U/7buqYsVy7KhM3kCQko7lelDZi8HL3oE3Z1noeC9Gt1Pu5nl1ds/qnww5kLZD0xNpUmzPh6JuSt/9JEGlhI1QkzwJ5/zRl7yIu6/bbi9OefyaDfX/k8qTax4vOpd73MfobeT9A91v8B\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Stock.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"LotID\", type text}, {\"ProductID\", type text}, {\"Warehouse\", type text}, {\"SnapshotDate\", type date}, {\"ReceiptDate\", type date}, {\"AgeDays\", Int64.Type}, {\"AgeBand\", type text}, {\"OnHand\", Int64.Type}, {\"Reserved\", Int64.Type}, {\"UnitCost\", Currency.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "lineageTag": "c3330859-c0aa-58d2-9088-42ffd92fcd4f",
        "columns": [
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "summarizeBy": "none",
            "lineageTag": "b0d05eef-241e-503f-891a-542e2bee5cfd",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"80lMSs3hCo70C/FwDfF0VnBx9fXnAgA=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Metrics.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Label\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "On Hand Units",
            "expression": "SUM(Stock[OnHand])",
            "formatString": "#,0",
            "description": "Sum of OnHand at the recorded grain.",
            "displayFolder": "Business metrics",
            "lineageTag": "fa94d798-48c8-5d4f-81fb-986b312124d1"
          },
          {
            "name": "Reserved Units",
            "expression": "SUM(Stock[Reserved])",
            "formatString": "#,0",
            "description": "Sum of Reserved at the recorded grain.",
            "displayFolder": "Business metrics",
            "lineageTag": "83c84ecb-14f2-5d7c-ba9f-555933e704a8"
          },
          {
            "name": "Available Units",
            "expression": "[On Hand Units] - [Reserved Units]",
            "formatString": "#,0",
            "description": "Physical stock less reservations.",
            "displayFolder": "Business metrics",
            "lineageTag": "6b236747-3c10-5294-a96b-807690a35c89"
          },
          {
            "name": "Stock Value",
            "expression": "SUMX(Stock, Stock[OnHand] * Stock[UnitCost])",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Physical stock valued at lot unit cost.",
            "displayFolder": "Business metrics",
            "lineageTag": "73afc16d-93bc-526f-8ae4-2e1367c5b73c"
          },
          {
            "name": "Available Value",
            "expression": "SUMX(Stock, (Stock[OnHand] - Stock[Reserved]) * Stock[UnitCost])",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Unreserved stock valued at cost.",
            "displayFolder": "Business metrics",
            "lineageTag": "9992a921-420a-57e8-8b50-b3507468b022"
          },
          {
            "name": "Aged Units",
            "expression": "CALCULATE([On Hand Units], KEEPFILTERS(Stock[AgeDays] > 90))",
            "formatString": "#,0",
            "description": "Stock received more than 90 days before the snapshot.",
            "displayFolder": "Business metrics",
            "lineageTag": "56d1d4c4-b705-504c-9884-1f8650143297"
          },
          {
            "name": "Aged Value",
            "expression": "CALCULATE([Stock Value], KEEPFILTERS(Stock[AgeDays] > 90))",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Value of stock older than 90 days.",
            "displayFolder": "Business metrics",
            "lineageTag": "70a98335-53c6-5661-927c-fb9ade142b44"
          },
          {
            "name": "Aged Value Share",
            "expression": "DIVIDE([Aged Value], [Stock Value])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Aged value / all selected stock value.",
            "displayFolder": "Business metrics",
            "lineageTag": "e9296dc7-99f4-5fc2-883f-dc72f3ffc945"
          },
          {
            "name": "Weighted Stock Age",
            "expression": "DIVIDE(SUMX(Stock, Stock[AgeDays] * Stock[OnHand]), [On Hand Units])",
            "formatString": "#,0.0",
            "description": "Unit-weighted age of on-hand stock.",
            "displayFolder": "Business metrics",
            "lineageTag": "965e6823-1563-50a0-b3c9-2ad3f14f0f6c"
          },
          {
            "name": "Occupied Lots",
            "expression": "COUNTROWS(FILTER(Stock, Stock[OnHand] > 0))",
            "formatString": "#,0",
            "description": "Lots with positive physical stock.",
            "displayFolder": "Business metrics",
            "lineageTag": "a8cc9fef-52d9-5be0-a943-298f52247e7d"
          },
          {
            "name": "Reserved Share",
            "expression": "DIVIDE([Reserved Units], [On Hand Units])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Reserved units / on-hand units.",
            "displayFolder": "Business metrics",
            "lineageTag": "ccd7241a-f0d4-5812-98c1-e6dbc386d5af"
          },
          {
            "name": "Product Count",
            "expression": "DISTINCTCOUNT(Stock[ProductID])",
            "formatString": "#,0",
            "description": "Distinct products represented in selected snapshot lots.",
            "displayFolder": "Business metrics",
            "lineageTag": "4f27941d-2ce6-5a8c-9b2b-87542c8dc8ac"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "52333c5e-a136-536b-a430-af59770b476b",
        "fromTable": "Stock",
        "fromColumn": "ProductID",
        "toTable": "Products",
        "toColumn": "ProductID",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      }
    ],
    "expressions": [
      {
        "name": "DataMode",
        "kind": "m",
        "expression": "\"Demo\" meta [IsParameterQuery=true, List={\"Demo\", \"Folder\"}, DefaultValue=\"Demo\", Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "DataFolder",
        "kind": "m",
        "expression": "\"C:/PowerBI/Astra/power-bi/03-inventory-stock-ageing/data/demo\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
