{
  "name": "Model",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Products",
        "lineageTag": "702e9323-56f5-55a3-bad0-4b653697f65e",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "lineageTag": "7e12cb5a-1fb6-5f25-9ad6-d10fb5bac631",
            "isHidden": true
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "summarizeBy": "none",
            "lineageTag": "cc002408-8f00-50a9-b15a-de4b3ebbc67d"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "summarizeBy": "none",
            "lineageTag": "e953f17d-2291-577c-b4ef-34c57a602e6c"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier",
            "summarizeBy": "none",
            "lineageTag": "38b61fd8-9fcc-5bdf-a965-4294948d6a79"
          }
        ],
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"fZM9bgJBDIV7TsEBpmBs81dG0ERpkEgOQMgqQgIG7UKR22ckWxF5Hm83ll7heZ+/XV++Hsf76zbt9JU2h3v3XfqftH/cbudT10/2bx+zWU7b7lKmlprW+b2U8/CXmpLmCHKUXo7HbhhKf+qe0qxphjSnTbkOj8vh8/ycFk0LpCXtDv39KTfX3Bxyc9x1obkF5BbtXbOml5Betne1HlaQXuGu1sAacmvcVf+eZ/9zdW7uqg1koFXn5q7aQwZmdYZdtYEMtOrcvIEMnOo8cgMZaNV55AYyMKtz8wYy0Kpz8wYycKrzyA1koFXnkRsgYFbn5g0Q0CLnlv6dgBMFbmkDBLQocEt7IGBGzi1tgIAWObfs78CJAresAaBFgVvWAzAj55Y1ALTIuaV/Z+DEgVvaAAMtDtzSHhiYsXNLG2Cgxc4t/TsDJw7c0gYYaHHglvUAzNi5ZQ0ALXZu2d+BEwduWQNAiwO3tAcBZuLc0gYEaIlzS/8uwEkCt7QBAVoSuKU9CDAT55Y2IEBLnFv2d+AkgVvWANCSwC3rAZiJcytPfgE=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Products.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"ProductID\", type text}, {\"Product\", type text}, {\"Category\", type text}, {\"Supplier\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Stock",
        "lineageTag": "67ee9b0b-9a46-5838-b6c2-259aaa3afde6",
        "columns": [
          {
            "name": "LotID",
            "dataType": "string",
            "sourceColumn": "LotID",
            "summarizeBy": "none",
            "lineageTag": "c5722b24-846c-5d18-bf78-4d0ad73e45cf",
            "isHidden": true
          },
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "summarizeBy": "none",
            "lineageTag": "52333c5e-a136-536b-a430-af59770b476b",
            "isHidden": true
          },
          {
            "name": "Warehouse",
            "dataType": "string",
            "sourceColumn": "Warehouse",
            "summarizeBy": "none",
            "lineageTag": "f67f59c2-de1b-59c3-9757-33fb63a5e649"
          },
          {
            "name": "SnapshotDate",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDate",
            "summarizeBy": "none",
            "lineageTag": "548d635b-561d-5c80-b38b-fa7f0b404e5e",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "ReceiptDate",
            "dataType": "dateTime",
            "sourceColumn": "ReceiptDate",
            "summarizeBy": "none",
            "lineageTag": "b967fd39-8f09-5e26-a53c-ba3598930636",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "AgeDays",
            "dataType": "int64",
            "sourceColumn": "AgeDays",
            "summarizeBy": "none",
            "lineageTag": "819f0a87-cc7b-5c65-a83e-143abf3d6bc6"
          },
          {
            "name": "AgeBand",
            "dataType": "string",
            "sourceColumn": "AgeBand",
            "summarizeBy": "none",
            "lineageTag": "1bef2f07-7757-54ac-87dd-a84de6cf294c"
          },
          {
            "name": "OnHand",
            "dataType": "int64",
            "sourceColumn": "OnHand",
            "summarizeBy": "none",
            "lineageTag": "af3f5e3f-782b-51b9-ab20-d1574c4ba6b4"
          },
          {
            "name": "Reserved",
            "dataType": "int64",
            "sourceColumn": "Reserved",
            "summarizeBy": "none",
            "lineageTag": "80809986-9282-5b63-a423-88b612f87726"
          },
          {
            "name": "UnitCost",
            "dataType": "decimal",
            "sourceColumn": "UnitCost",
            "summarizeBy": "none",
            "lineageTag": "079581a5-0b12-528b-adba-b8a81f839429"
          }
        ],
        "partitions": [
          {
            "name": "Stock",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"jVvbqh3JDX3Pr6Q2dKnuj5n4IcMYEmYY8nwyPsSGxB5sTyBv+Yf8Yb4kWlVSdfc2rWq8ofcxVNdtSVrS0n776ev3b9xfPn9699sv+PbXl8+v7z/99uXV/fTx5dcv7z99ffPy9dX9+PrL64dfx/c//P31zcu/v+D53cvHd+7PH/+Ex4+vX14//+v1nfv544evf/z05evv3m7b5t1PP/yMxw8vn19+ef/B0Ub5sbVH2ORrfZB3cXPB/+8//82ba96l6qhtW38BjReQe/vy/tPn12/Hh4evzrfMA3/vvM+uFOeLjA5jdHDff/nHyz9f/vby7tsXlEfwLuPDC2ibS82l7GKSV8Txini9A2yCZ459BZlccr7K4DQGp8vV49NXjbEluuB06XkMzdbS04MPxic/9h74RfvUZYwv1+sOD74X4mEYTQGfFGV0HaPr5cLrw+OQ5rVRc8R/BRnfxvhmrd4/MCiOc4t8azSv3W99PD+MU8duveydjziQC7J5P2DHj+tz59221gczdnJxeZOxA3H8MJbecOVEbuPN838yavgNQRc/UMePy8WXB0WX68Qcwy/xBegSBub4cX36fLSJ5unzYGxfbs8P2PHD2ELF+aXd7nK3u5jlFQN+/LjcQ3wQQzcVuQC+PzYSLwDwA378MABELrZ9fv6LpuX6AUB+mLfgGzC/3wLep7cwIMgPwwAOrqOMI6AxmgYA+XG1/tQHhyTbZxSz+Qj+aOCPH8bq6cEXTFQHBpNjQMn90YAgPy6XnmC7nhHQBzMWXJSTp4E+flyvnB2eJxKPyd8ZPDJ4II8fxsIDTN+3sfDCJlz5EmX8QB4/rEPnS2tybvyVT1FnH6Djx9XS4wNermx9MGN+Wi0NvPHDxovHlIIX/qNOm6MBOH4YkeqM2MgvK/vWB974YficBpRg7QnAm2gLA238sFePvevq+YLZXAVwYQAuGHE29khThrnW5gp7H8FbGHgL10GW5+aolubJwdj5I8MH4oIZZTnYsIMTd82g4XMk3f0AXTBCbOqLj2PxKXbXJ3YeBuTCdYw9xbnCzp5n16kH4oIZZRvunWEqmw/wUuy85Q0DeMGIsxGG7vMINhys8dHFD9SF6zhbYC4lzEjhEfF5P0n4SRiwC2akbQ+2yNPtxemr4sBeNEJt7AdQJNR2IAhy4sBdvA60AfTOC+qxFd6JjB2oi4tAyzgvu8VumDzI3uMAXjQCbeuwmy+oAQDwEuTiAF68jrMRw5lSjdUXx0Fbbi4O2EUzxias3gcZ7sft6bkP6EUjwhLunmicXYWXnSE+DtjF6/h68rMNBHWaTByoi2ZwZW8FpG3KTDNYuoxvS1ZPYKYczwbme2jPEtrTtqL0Jy/P0ClpetnkbzB69haAeFZanCYxTLRk8wHUijaN625nhims2DxzAr7jOC6sFTASnTjeoPMFjqp5zSNgNzI6Lcl87EE5Dw+ZM8i0BvWUV2T+5KHYlfHNJ910ucHkK6hgOCQD/JUNVd5Ql1w+dQcTx87ZRhk389Dbisrz4vm2s9x2hW9TLpS3G1y+4tIYV4cEtPL6Ba3ZL8l8RFz3aeQxpft39TCZVkzewzVTHGQK89YZF3O4QeNjp6F5wDUOQxPU5Ljk8E+cAjSW0RJ09WlF4guMpe7RqXY+p7wi5xsk/uRi2T63ffqyZPCpoz5IDsJsnW9BcZfrisI3+Al2r7J79uVlOtjcblD4YxZZ84GOlm3J4E9BlX0Vn5JMXfyKwTfYW5yEhOdlPiWD6QaDP4c1vnQmg3rqJSwpPPXsN0TFLKKUmEuJKwqf+769UHh+T55Zf0k3SDxPzmlTkLRp6+5Kx+clhz/ZKjsctj3xFaXc4O/FSUBNgwUJ1Eq9wd9T91Nh+Cl2qzBWiWqlLen7ObRkrENXXrcVfSecOQkPwQG0mWhXf4O8x84lsni4ioCcxUlVWpL3gjPPBwrLvlbjYg032PsejxEUtcZU4w3uHvuxlTCDwzaz7JqWzL31Ms3uHXkRcXL3mlfcPfSsSfwDKpMz063lBmt/DkwE/6TerdYlbQ+9QFOnpbA/TWLkta14e+uedfoYRiivQPlI225Qd54eI6I4mZ7yya03vyTuhM1TIKUEjFPNNxutaHuBpXL0miXdBFtXF9nCDerOxl6dLL726lQS3LW4JO65V2dIa5PUg6oYXEsr5h4xtU9J6W8F/sfYfI+4j0RDIB8mb2/lRjUebi1PzNVu7GIxra6Z+8G9Ik2tuAcZ3W5Qdw7JCUDXIocjvTakIivufipJstGnyWO9KhEmed+5BByNpPheNQjT0RzxAmdJyoK8ihCGn8n42rQgN8rRWUbHFXl/riV39ypg9apALMoDsLVtHnovqkqa7kWIsOk7T+OFw6KIzMcgg8uKvRcwUHiXuXo21KDhyYsQYTP40HncJtWhhvmTjm9L+t5QW6Lp6RixbHrCwb0KEde+5qk01kOj1pe8ChErCr8zQSZQKMrreFpS+FMRG/aiF6cyhFWC5+OFdKAleDiaefSqQpjOpsLTcvCfQoTH6avJqhBhMPjnIIctM48THcKLDmGQeA8AUR7cJvYIL7TMiwhhc/hj0g0FgcmlDq9LEn8qhSPgaP7gRX4wSPw3p5+AXTl81R9MGl/hc8L+htAVQKGFXkUIk8gj+fRFK6NB7VYViGsa/+SoGbZ+d9WqQZhE/lQc4/CeYMMyPt4h8kiz1We2Tsd1+rSi8gUbh5cVr8PkP2qtxosMYbP53Esmm9x8RclFz70syTw9+j0JP+CDY6ejoBUhwmDzBV8zHUrCXdXIOn+7wegrlh/Lwey6+WvUUUHCiLUEv0M0Il6v/WiRzqsacR1rK84/7DSDYzUbnmTPXvUIM+Ce8sBREdcs1KsiYYRcguMir2W+jLK+ek4VJK5jrofdkxANFLvm0HSD2D/HPDjNrHmJF03CYvYn5RyO3rcJfhEkzJI8POa2s1M/kxovgoTN7L/RJCBFkb6hLbl96FcnJYCOOhWyvKoRlvRNEH92htqFOElsvAoSZsANnWDXrLbLQNb9qyhhkvtdxit95xKsVY64Drj52CmCJ7JisXsVI8xwm8D1YOGixOzXLnqExe1PeUXtYVZpoogRdk1+LxGj2cHpiZcbtN53a9OKPKS4osmkFzXC4vXnPJxjY5yeSrWIa19T4Gzr3t8DWcPP8apGrPpsdoILi2EPIa0yXhUJu9FmL2Ew2BGqxVOpIGEKgKWzSl0+zp7EXFSSMN1NgrnhoKTPJ2sRwYsqYXH7U62vgeCIpxNNwqD2FRpQ2i0VGZwv08+JLGFTe+qOlgZw2Or9hKwIExazP2V0GWsXS1VJwhL+wOpzPXZWCV5VkTBdjO/NHUkMFVYP1AjmVJYwnExFUpJ2RYWT59q09OVVlLj2NKfuFAYuuoMEcqpJrFpr0JehJtdvT/mR6hIGq39mh6Vnpbr9uOL0z+1N+VAGEFFi1VtzQC3aisKMECJKWKz+SRdAi0tWTcmLKmEQ+1NGVkvHvE5eb9D60ImxpiSEIKNZhaoSBqd/dneFkJJrfFNh4prYn5xVgDYFYjsG+xu0vo1AMUUVqJJauvOqTthdNqEjVuM7otRkx6pOXFP7537SUcac+483uH0EO4WT0Ep9mE5LJAqL3J+rvsgJ5+LzitpXcIuwA39cnvR0epEobGZ/7vXoqpRWI1SmMGv1Wy84KnriXnD3qlJch9pzXsNv4vXLwalIYcbZ52oC9Yxaplelwgi0vn9VkaR3BIoS61WnuA60+GtwExC7Am1KzU5VilWTDW98igVumy5HlAqL0T+5HOQzTTUWL0qFQekrGHk84KZTBnW4olTYpD51jUdcJjpmJksQscJi9LET25L21gWdut7g86fegdTZnfgL1SkWXTaYPIrHyszIpd3Dq05hKuCdUMm5s91MR68ihVU/O9df/Kmd0atOYQbaU/mpq9+ydVEpLELferV90mLUfbV4JyKFQeifU3DmgkiB5c5FpVgV64/zw95nZ5gXqWLRabO3BLauFWgqpUqFJQsecjioFOS0eqQyxaLXhhlA7/mVMNl6AUy3327U7EELt6ZBAjgYoCdVKixfg+qVpODUu3WkF5RUqDB9TT4KTAjSs2JKolZYnP5UvcidacUio8OK1Z9bcHvyHHRwvMHon+19VM+lb5xEr7BY/aljxndNdyZEpGqF2XBzSEUhUanRkKoVi+IBYtwWtJHVZzVZUrHCcDfPpZ/YA6wMbytWHzqtFsxF+CrZtsoUi1o9anTbbq+9D1QCJKlUYbD6Uw0AkTIqNSERKkxO/22xenZPk4gVNqt/6vcntM87XX5c0nrfK5ZS/xh1BKF1JEKF2XJz1sMrNt9kdL7B6lM3eRG0UcU5HH25UalHFkFj7Wx8+LmMrr2uKP0pG4K1cKCRKEeqU5ic/uk3Vih8Ky0jVSoMSp+PP3LCFW7TW6lIcc3nG3BDh653P9u3SWQKm823oYdP2Pf5SXAnSoXdOH/orBwNR3rxolMYhP7U/tx/baN1ehKVYlWnPycE+Jd09ryk8wFfwT8lSOEjsFGZwhLEQYilytx/GzQjnIoUC0n8EKR4DdrgRqpQGNG14NLKrnEwN+CVirNRdcKsz+P3aJL/g5Ro3YhUnFiUzMBsRNzgZRSank7ECYvMP9fHm5tuSpQJm8qf8t/WNWW5clEmbCZPSEBxvyptwOTl6EWfsKvzPBSkX6vzcT+7vGLzT4Ufzlwg64mxqTRhxtczIW/9lybSwEKqTpgB9vxrzthDXtTttxWnP/9MBv3+yudJtYkVn0+962X2M/R+gu6x/g8=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Stock.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"LotID\", type text}, {\"ProductID\", type text}, {\"Warehouse\", type text}, {\"SnapshotDate\", type date}, {\"ReceiptDate\", type date}, {\"AgeDays\", Int64.Type}, {\"AgeBand\", type text}, {\"OnHand\", Int64.Type}, {\"Reserved\", Int64.Type}, {\"UnitCost\", Currency.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "lineageTag": "c3330859-c0aa-58d2-9088-42ffd92fcd4f",
        "columns": [
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "summarizeBy": "none",
            "lineageTag": "b0d05eef-241e-503f-891a-542e2bee5cfd",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"80lMSs3hCo70C/FwDfF0VnBx9fXnAgA=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Metrics.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Label\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "On Hand Units",
            "expression": "SUM(Stock[OnHand])",
            "formatString": "#,0",
            "description": "Sum of OnHand at the recorded grain.",
            "displayFolder": "Business metrics",
            "lineageTag": "fa94d798-48c8-5d4f-81fb-986b312124d1"
          },
          {
            "name": "Reserved Units",
            "expression": "SUM(Stock[Reserved])",
            "formatString": "#,0",
            "description": "Sum of Reserved at the recorded grain.",
            "displayFolder": "Business metrics",
            "lineageTag": "83c84ecb-14f2-5d7c-ba9f-555933e704a8"
          },
          {
            "name": "Available Units",
            "expression": "[On Hand Units] - [Reserved Units]",
            "formatString": "#,0",
            "description": "Physical stock less reservations.",
            "displayFolder": "Business metrics",
            "lineageTag": "6b236747-3c10-5294-a96b-807690a35c89"
          },
          {
            "name": "Stock Value",
            "expression": "SUMX(Stock, Stock[OnHand] * Stock[UnitCost])",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Physical stock valued at lot unit cost.",
            "displayFolder": "Business metrics",
            "lineageTag": "73afc16d-93bc-526f-8ae4-2e1367c5b73c"
          },
          {
            "name": "Available Value",
            "expression": "SUMX(Stock, (Stock[OnHand] - Stock[Reserved]) * Stock[UnitCost])",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Unreserved stock valued at cost.",
            "displayFolder": "Business metrics",
            "lineageTag": "9992a921-420a-57e8-8b50-b3507468b022"
          },
          {
            "name": "Aged Units",
            "expression": "CALCULATE([On Hand Units], KEEPFILTERS(Stock[AgeDays] > 90))",
            "formatString": "#,0",
            "description": "Stock received more than 90 days before the snapshot.",
            "displayFolder": "Business metrics",
            "lineageTag": "56d1d4c4-b705-504c-9884-1f8650143297"
          },
          {
            "name": "Aged Value",
            "expression": "CALCULATE([Stock Value], KEEPFILTERS(Stock[AgeDays] > 90))",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Value of stock older than 90 days.",
            "displayFolder": "Business metrics",
            "lineageTag": "70a98335-53c6-5661-927c-fb9ade142b44"
          },
          {
            "name": "Aged Value Share",
            "expression": "DIVIDE([Aged Value], [Stock Value])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Aged value / all selected stock value.",
            "displayFolder": "Business metrics",
            "lineageTag": "e9296dc7-99f4-5fc2-883f-dc72f3ffc945"
          },
          {
            "name": "Weighted Stock Age",
            "expression": "DIVIDE(SUMX(Stock, Stock[AgeDays] * Stock[OnHand]), [On Hand Units])",
            "formatString": "#,0.0",
            "description": "Unit-weighted age of on-hand stock.",
            "displayFolder": "Business metrics",
            "lineageTag": "965e6823-1563-50a0-b3c9-2ad3f14f0f6c"
          },
          {
            "name": "Occupied Lots",
            "expression": "COUNTROWS(FILTER(Stock, Stock[OnHand] > 0))",
            "formatString": "#,0",
            "description": "Lots with positive physical stock.",
            "displayFolder": "Business metrics",
            "lineageTag": "a8cc9fef-52d9-5be0-a943-298f52247e7d"
          },
          {
            "name": "Reserved Share",
            "expression": "DIVIDE([Reserved Units], [On Hand Units])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Reserved units / on-hand units.",
            "displayFolder": "Business metrics",
            "lineageTag": "ccd7241a-f0d4-5812-98c1-e6dbc386d5af"
          },
          {
            "name": "Product Count",
            "expression": "DISTINCTCOUNT(Stock[ProductID])",
            "formatString": "#,0",
            "description": "Distinct products represented in selected snapshot lots.",
            "displayFolder": "Business metrics",
            "lineageTag": "4f27941d-2ce6-5a8c-9b2b-87542c8dc8ac"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "52333c5e-a136-536b-a430-af59770b476b",
        "fromTable": "Stock",
        "fromColumn": "ProductID",
        "toTable": "Products",
        "toColumn": "ProductID",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      }
    ],
    "expressions": [
      {
        "name": "DataMode",
        "kind": "m",
        "expression": "\"Demo\" meta [IsParameterQuery=true, List={\"Demo\", \"Folder\"}, DefaultValue=\"Demo\", Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "DataFolder",
        "kind": "m",
        "expression": "\"C:/PowerBI/data-powerbi-portfolio/03-inventory-stock-ageing/data/demo\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
