"""Business specifications, deterministic fixtures and reference totals for ten solutions."""
import calendar
import datetime as dt
import random

ASOF=dt.date(2026,9,30)
MONEY='"PKR "#,0;("PKR "#,0);"PKR "0'
PCT='0.0%;(0.0%);0.0%'
NUM='#,0.0'

def date(n): return (ASOF-dt.timedelta(days=n)).isoformat()
def total(rows,col): return round(sum(r[col] for r in rows),4)
def ratio(a,b): return a/b if b else None
def table(rows,key,grain,dates=(),decimals=()):
    cols={}
    for c,v in rows[0].items():
        cols[c]='dateTime' if c in dates else 'decimal' if c in decimals or isinstance(v,float) else 'int64' if isinstance(v,int) else 'string'
    return dict(rows=rows,key=key,grain=grain,columns=cols)
def measure(name,dax,desc,fmt='#,0'): return dict(name=name,dax=dax,description=desc,format=fmt)
def summ(name,t,c,desc=None,fmt=MONEY): return measure(name,f'SUM({t}[{c}])',desc or f'Sum of {c} at the recorded grain.',fmt)
def page(title,slicers,cards,cat,vals,cat2,vals2,detail,note=None,kind2='clusteredBarChart'):
    p=dict(title=title,slicers=slicers,cards=cards,charts=[(vals[0]+' by '+cat.split('.')[-1],'clusteredBarChart',cat,vals),(vals2[0]+' by '+cat2.split('.')[-1],kind2,cat2,vals2)],table=detail)
    if note: p['note']=note
    return p
def base(slug,title,short,purpose,scope,rules,tables,rels,measures,pages,expected):
    tables['Metrics']=table([{'Label':'SYNTHETIC DEMO'}],'Label','one metadata row')
    if any(r[2]=='Calendar' for r in rels):
        start=dt.date(2025,1,1)
        days=[start+dt.timedelta(days=i) for i in range(730)]
        tables['Calendar']=table([{'Date':d.isoformat(),'Year':d.year,'Month':d.strftime('%Y-%m'),'Quarter':f'{d.year}-Q{(d.month-1)//3+1}'} for d in days],'Date','one calendar date',dates=['Date'])
    return dict(slug=slug,title=title,short=short,purpose=purpose,scope=scope,rules=rules,tables=tables,relationships=rels,measures=measures,pages=pages,expected=expected)

def dealership():
    rng=random.Random(101); rows=[]
    for i in range(180):
        days=rng.randint(3,350); sold=i%4!=0; held=rng.randint(1,days) if sold else days
        cost=rng.randrange(18,85)*100000; recon=rng.randrange(2,30)*10000
        revenue=cost+recon+rng.randrange(-5,20)*50000 if sold else 0
        rows.append(dict(VehicleID=f'V{i+1:04d}',Make=['Toyota','Honda','Suzuki','Kia','Hyundai'][i%5],Model=['Sedan','Hatchback','SUV'][i%3],Branch=['Karachi','Lahore','Islamabad'][i%3],Salesperson=f'Advisor {i%7+1}',Status='Sold' if sold else 'In Stock',PurchaseDate=date(days),SaleDate=date(days-held) if sold else '',PurchaseCost=cost,Reconditioning=recon,SalePrice=revenue,DaysHeld=held,AgeBand='0–30' if held<=30 else '31–60' if held<=60 else '61–90' if held<=90 else '90+'))
    sold=[r for r in rows if r['Status']=='Sold']; stock=[r for r in rows if r['Status']=='In Stock']
    rev=total(sold,'SalePrice'); cost=sum(r['PurchaseCost']+r['Reconditioning'] for r in sold)
    measures=[measure('Units Sold','CALCULATE(COUNTROWS(Vehicles), KEEPFILTERS(Vehicles[Status] = "Sold"))','Count of vehicles with completed sales.'),
        measure('Sales Revenue','CALCULATE(SUM(Vehicles[SalePrice]), KEEPFILTERS(Vehicles[Status] = "Sold"))','Sale price of sold vehicles, excluding tax.',MONEY),
        measure('Sold Vehicle Cost','CALCULATE(SUMX(Vehicles, Vehicles[PurchaseCost] + Vehicles[Reconditioning]), KEEPFILTERS(Vehicles[Status] = "Sold"))','Purchase plus reconditioning cost of sold vehicles.',MONEY),
        measure('Gross Profit','[Sales Revenue] - [Sold Vehicle Cost]','Vehicle gross profit before finance costs and operating overhead.',MONEY),
        measure('Gross Margin','DIVIDE([Gross Profit], [Sales Revenue])','Vehicle gross profit divided by sales revenue.',PCT),
        measure('Stock Units','CALCULATE(COUNTROWS(Vehicles), KEEPFILTERS(Vehicles[Status] = "In Stock"))','Vehicles in stock at the 30 September 2026 snapshot.'),
        measure('Stock Value','CALCULATE(SUMX(Vehicles, Vehicles[PurchaseCost] + Vehicles[Reconditioning]), KEEPFILTERS(Vehicles[Status] = "In Stock"))','Capitalized purchase and reconditioning cost of current stock.',MONEY),
        measure('Average Stock Age','CALCULATE(AVERAGE(Vehicles[DaysHeld]), KEEPFILTERS(Vehicles[Status] = "In Stock"))','Average days since purchase for current stock.',NUM),
        measure('Aged Stock Units','CALCULATE([Stock Units], KEEPFILTERS(Vehicles[DaysHeld] > 90))','Current unsold vehicles older than 90 days.'),
        measure('Aged Stock Value','CALCULATE([Stock Value], KEEPFILTERS(Vehicles[DaysHeld] > 90))','Cost tied up in stock older than 90 days.',MONEY),
        measure('Average Days to Sell','CALCULATE(AVERAGE(Vehicles[DaysHeld]), KEEPFILTERS(Vehicles[Status] = "Sold"))','Mean purchase-to-sale duration of completed sales.',NUM),
        measure('Profit per Vehicle','DIVIDE([Gross Profit], [Units Sold])','Mean gross profit per sold vehicle.',MONEY)]
    slicers=['Vehicles.Branch','Vehicles.Make','Vehicles.Salesperson']
    pages=[page('Executive overview',slicers,['Sales Revenue','Gross Profit','Stock Value','Aged Stock Units'],'Vehicles.Branch',['Gross Profit'],'Vehicles.Make',['Stock Value'],['Vehicles.Branch','Units Sold','Gross Margin','Stock Units','Average Stock Age']),
        page('Stock ageing',slicers,['Stock Units','Stock Value','Average Stock Age','Aged Stock Value'],'Vehicles.AgeBand',['Stock Value'],'Vehicles.Make',['Aged Stock Units'],['Vehicles.VehicleID','Vehicles.Make','Vehicles.Branch','Vehicles.AgeBand','Stock Units','Stock Value']),
        page('Sales performance',['Calendar.Month','Vehicles.Branch','Vehicles.Salesperson'],['Units Sold','Sales Revenue','Gross Margin','Average Days to Sell'],'Vehicles.Salesperson',['Gross Profit'],'Calendar.Month',['Sales Revenue','Gross Profit'],['Vehicles.Make','Units Sold','Sales Revenue','Sold Vehicle Cost','Profit per Vehicle'],note='Date filters apply to sale date. Stock is shown only on the other pages.',kind2='lineChart')]
    return base('01-dealership-profitability','Car Dealership Profitability & Inventory','Dealership intelligence','Identify profitable vehicles, compare branches and review capital trapped in ageing stock.','Current stock at 30 Sep 2026; completed sales by sale date.','One row per vehicle lifecycle. Sold vehicles require SaleDate >= PurchaseDate and nonzero SalePrice; unsold vehicles have blank SaleDate and zero SalePrice. Stock is a current snapshot, not historical inventory. No leads or conversion rate are inferred.',{'Vehicles':table(rows,'VehicleID','one vehicle lifecycle',dates=['PurchaseDate','SaleDate'],decimals=['PurchaseCost','Reconditioning','SalePrice'])},[('Vehicles','SaleDate','Calendar','Date')],measures,pages,{'Units Sold':len(sold),'Sales Revenue':rev,'Gross Profit':rev-cost,'Gross Margin':ratio(rev-cost,rev),'Stock Units':len(stock),'Stock Value':sum(r['PurchaseCost']+r['Reconditioning'] for r in stock),'Aged Stock Units':sum(r['DaysHeld']>90 for r in stock)})

def sales():
    rng=random.Random(102)
    accounts=[dict(AccountID=f'A{i:03d}',Customer=f'Demo Customer {i:02d}',Region=['South','North','Central'][i%3],Segment=['SMB','Mid-market','Enterprise'][i%3],Salesperson=f'Advisor {i%5+1}') for i in range(1,31)]
    rows=[]; targets=[]
    for day in range(365):
        for a in accounts:
            targets.append(dict(TargetID=f'T{len(targets)+1}',AccountID=a['AccountID'],Date=date(day),TargetRevenue=9000))
            if rng.random()<.12:
                units=rng.randint(1,20); rev=units*rng.randrange(4,20)*1000
                rows.append(dict(SalesID=f'S{len(rows)+1}',AccountID=a['AccountID'],Date=date(day),Units=units,Revenue=rev,Cost=round(rev*rng.uniform(.55,.9),2)))
    rev=total(rows,'Revenue'); cost=total(rows,'Cost'); target=total(targets,'TargetRevenue')
    ms=[summ('Revenue','Sales','Revenue'),summ('Cost of Sales','Sales','Cost'),measure('Gross Profit','[Revenue] - [Cost of Sales]','Revenue less cost of sales.',MONEY),measure('Gross Margin','DIVIDE([Gross Profit], [Revenue])','Gross profit / revenue.',PCT),summ('Units Sold','Sales','Units',fmt='#,0'),summ('Revenue Target','Targets','TargetRevenue','Daily account targets; date and account filters affect actual and target.'),measure('Target Attainment','DIVIDE([Revenue], [Revenue Target])','Revenue divided by target.',PCT),measure('Target Variance','[Revenue] - [Revenue Target]','Positive means ahead of target.',MONEY),measure('Sales Transactions','COUNTROWS(Sales)','Number of sales transactions.'),measure('Active Customers','DISTINCTCOUNT(Sales[AccountID])','Customers with a sale in the selected period.'),measure('Average Transaction','DIVIDE([Revenue], [Sales Transactions])','Revenue per sales transaction.',MONEY),measure('Revenue YTD','TOTALYTD([Revenue], \'Calendar\'[Date])','Calendar-year revenue through the last selected date; select a populated period.',MONEY),measure('Previous Month Revenue','CALCULATE([Revenue], DATEADD(\'Calendar\'[Date], -1, MONTH))','Revenue in the date selection shifted back one month. Use a single month for month-over-month comparison.',MONEY),measure('Month Growth','DIVIDE([Revenue] - [Previous Month Revenue], [Previous Month Revenue])','Revenue growth versus selected dates shifted back one month; blank if prior revenue is absent.',PCT)]
    sl=['Calendar.Month','Accounts.Region','Accounts.Salesperson']
    ps=[page('Revenue and targets',sl,['Revenue','Gross Profit','Target Attainment','Target Variance'],'Accounts.Region',['Revenue','Revenue Target'],'Calendar.Month',['Revenue','Revenue Target'],['Accounts.Salesperson','Revenue','Revenue Target','Target Variance','Gross Margin'],kind2='lineChart'),page('Customers and margins',sl,['Active Customers','Sales Transactions','Average Transaction','Gross Margin'],'Accounts.Segment',['Gross Profit'],'Accounts.Customer',['Revenue'],['Accounts.Customer','Revenue','Cost of Sales','Gross Profit','Gross Margin']),page('Sales team performance',sl,['Units Sold','Revenue','Gross Profit','Target Attainment'],'Accounts.Salesperson',['Revenue','Revenue Target'],'Calendar.Month',['Gross Profit'],['Accounts.Salesperson','Active Customers','Units Sold','Revenue','Target Attainment'],kind2='lineChart')]
    return base('02-executive-sales','Executive Sales Performance Dashboard','Sales performance','Compare actual sales against targets, understand margins and evaluate customers and salespeople.','01 Oct 2025–30 Sep 2026 transactions; daily account targets.','SalesID is unique; Units > 0. Targets have exactly one row per account/date. Revenue is net of discounts, before tax. Customer attributes describe current ownership, not historical salesperson assignment.',{'Accounts':table(accounts,'AccountID','one customer account'),'Sales':table(rows,'SalesID','one sales transaction',dates=['Date'],decimals=['Revenue','Cost']),'Targets':table(targets,'TargetID','one account per day',dates=['Date'],decimals=['TargetRevenue'])},[('Sales','AccountID','Accounts','AccountID'),('Targets','AccountID','Accounts','AccountID'),('Sales','Date','Calendar','Date'),('Targets','Date','Calendar','Date')],ms,ps,{'Revenue':rev,'Gross Profit':round(rev-cost,2),'Revenue Target':target,'Target Attainment':ratio(rev,target),'Sales Transactions':len(rows),'Active Customers':len({r['AccountID'] for r in rows})})

def inventory():
    rng=random.Random(103)
    products=[dict(ProductID=f'SKU{i:03d}',Product=f'Demo Product {i:02d}',Category=['Parts','Tools','Accessories','Consumables'][i%4],Supplier=f'Supplier {i%6+1}') for i in range(1,49)]
    rows=[]
    for i in range(240):
        onhand=rng.randint(0,120); reserved=rng.randint(0,onhand); cost=rng.randrange(2,70)*100; age=rng.randint(1,260)
        rows.append(dict(LotID=f'L{i+1:04d}',ProductID=products[i%48]['ProductID'],Warehouse=['Karachi','Lahore','Islamabad'][i%3],SnapshotDate=ASOF.isoformat(),ReceiptDate=date(age),AgeDays=age,AgeBand='0–30' if age<=30 else '31–60' if age<=60 else '61–90' if age<=90 else '90+',OnHand=onhand,Reserved=reserved,UnitCost=cost))
    ms=[summ('On Hand Units','Stock','OnHand',fmt='#,0'),summ('Reserved Units','Stock','Reserved',fmt='#,0'),measure('Available Units','[On Hand Units] - [Reserved Units]','Physical stock less reservations.'),measure('Stock Value','SUMX(Stock, Stock[OnHand] * Stock[UnitCost])','Physical stock valued at lot unit cost.',MONEY),measure('Available Value','SUMX(Stock, (Stock[OnHand] - Stock[Reserved]) * Stock[UnitCost])','Unreserved stock valued at cost.',MONEY),measure('Aged Units','CALCULATE([On Hand Units], KEEPFILTERS(Stock[AgeDays] > 90))','Stock received more than 90 days before the snapshot.'),measure('Aged Value','CALCULATE([Stock Value], KEEPFILTERS(Stock[AgeDays] > 90))','Value of stock older than 90 days.',MONEY),measure('Aged Value Share','DIVIDE([Aged Value], [Stock Value])','Aged value / all selected stock value.',PCT),measure('Weighted Stock Age','DIVIDE(SUMX(Stock, Stock[AgeDays] * Stock[OnHand]), [On Hand Units])','Unit-weighted age of on-hand stock.',NUM),measure('Occupied Lots','COUNTROWS(FILTER(Stock, Stock[OnHand] > 0))','Lots with positive physical stock.'),measure('Reserved Share','DIVIDE([Reserved Units], [On Hand Units])','Reserved units / on-hand units.',PCT),measure('Product Count','DISTINCTCOUNT(Stock[ProductID])','Distinct products represented in selected snapshot lots.')]
    sl=['Products.Category','Stock.Warehouse','Products.Supplier']
    ps=[page('Stock overview',sl,['Stock Value','Available Units','Aged Value','Weighted Stock Age'],'Products.Category',['Stock Value'],'Stock.Warehouse',['Stock Value'],['Stock.Warehouse','On Hand Units','Reserved Units','Stock Value','Aged Value']),page('Ageing exposure',sl,['Aged Units','Aged Value','Aged Value Share','Weighted Stock Age'],'Stock.AgeBand',['Stock Value'],'Products.Supplier',['Aged Value'],['Products.Product','Stock.AgeBand','On Hand Units','Aged Value','Weighted Stock Age']),page('Availability and lots',sl,['On Hand Units','Reserved Units','Available Value','Occupied Lots'],'Stock.Warehouse',['On Hand Units','Available Units'],'Products.Category',['Reserved Units'],['Stock.LotID','Products.Product','Stock.ReceiptDate','On Hand Units','Reserved Units','Stock Value'])]
    value=sum(r['OnHand']*r['UnitCost'] for r in rows); aged=sum(r['OnHand']*r['UnitCost'] for r in rows if r['AgeDays']>90)
    return base('03-inventory-stock-ageing','Inventory & Stock Ageing Analytics','Inventory analytics','Find ageing inventory, reserved stock and warehouse capital exposure at receipt-lot level.','Single stock snapshot at 30 Sep 2026; age measured from lot receipt.','Do not sum multiple snapshots. LotID is unique; 0 <= Reserved <= OnHand; UnitCost >= 0; ReceiptDate <= SnapshotDate; AgeDays must match date difference. Ageing is not a demand or reorder calculation.',{'Products':table(products,'ProductID','one product'),'Stock':table(rows,'LotID','one receipt lot in one warehouse',dates=['SnapshotDate','ReceiptDate'],decimals=['UnitCost'])},[('Stock','ProductID','Products','ProductID')],ms,ps,{'On Hand Units':total(rows,'OnHand'),'Available Units':total(rows,'OnHand')-total(rows,'Reserved'),'Stock Value':value,'Aged Value':aged,'Aged Value Share':ratio(aged,value),'Weighted Stock Age':ratio(sum(r['AgeDays']*r['OnHand'] for r in rows),total(rows,'OnHand'))})

def finance():
    rng=random.Random(104)
    departments=[dict(DepartmentID=f'D{i}',Department=n) for i,n in enumerate(['Sales','Services','Administration'],1)]
    pnl=[]; cash=[]
    for month in range(1,10):
        for d in departments:
            for cat in ['Revenue','COGS','Operating Expense']:
                amount=rng.randrange(30,85)*10000 if cat=='Revenue' else rng.randrange(10,30)*10000
                pnl.append(dict(LineID=f'P{len(pnl)+1}',DepartmentID=d['DepartmentID'],Date=f'2026-{month:02d}-01',Category=cat,Actual=amount,Budget=round(amount*rng.uniform(.85,1.15),2)))
            for cat in ['Customer Receipts','Supplier Payments','Payroll','Capital Expenditure','Loan Drawdown']:
                value=rng.randrange(10,50)*10000*(1 if cat in ['Customer Receipts','Loan Drawdown'] else -1)
                cash.append(dict(CashID=f'C{len(cash)+1}',DepartmentID=d['DepartmentID'],Date=f'2026-{month:02d}-01',Category=cat,CashMovement=value))
    ms=[measure('Revenue','CALCULATE(SUM(PnL[Actual]), PnL[Category] = "Revenue")','Accrual revenue; not customer receipts.',MONEY),measure('Cost of Sales','CALCULATE(SUM(PnL[Actual]), PnL[Category] = "COGS")','Positive cost of goods sold.',MONEY),measure('Operating Expense','CALCULATE(SUM(PnL[Actual]), PnL[Category] = "Operating Expense")','Positive operating expense excluding COGS.',MONEY),measure('Gross Profit','[Revenue] - [Cost of Sales]','Revenue less COGS.',MONEY),measure('Operating Profit','[Gross Profit] - [Operating Expense]','Before interest, tax and exceptional items.',MONEY),measure('Operating Margin','DIVIDE([Operating Profit], [Revenue])','Operating profit / accrual revenue.',PCT),measure('Budget Profit','SUMX(PnL, IF(PnL[Category] = "Revenue", PnL[Budget], -PnL[Budget]))','Budget revenue less budget costs.',MONEY),measure('Profit Variance','[Operating Profit] - [Budget Profit]','Positive means operating profit ahead of budget.',MONEY),measure('Signed Actual','SUMX(PnL, IF(PnL[Category] = "Revenue", PnL[Actual], -PnL[Actual]))','Category-level signed P&L contribution.',MONEY),measure('Signed Budget','SUMX(PnL, IF(PnL[Category] = "Revenue", PnL[Budget], -PnL[Budget]))','Category-level signed budget contribution.',MONEY),measure('Cash Inflow','CALCULATE(SUM(Cash[CashMovement]), KEEPFILTERS(Cash[CashMovement] > 0))','All positive cash movements including financing.',MONEY),measure('Cash Outflow','-CALCULATE(SUM(Cash[CashMovement]), KEEPFILTERS(Cash[CashMovement] < 0))','Absolute value of all negative cash movements.',MONEY),summ('Net Cash Movement','Cash','CashMovement','Cash receipts less payments; not a cash balance.'),measure('Operating Cash Movement','CALCULATE([Net Cash Movement], KEEPFILTERS(Cash[Category] IN {"Customer Receipts", "Supplier Payments", "Payroll"}))','Receipts less supplier payments and payroll; excludes capex and loans.',MONEY)]
    sl=['Calendar.Month','Departments.Department','Calendar.Quarter']
    ps=[page('Profit and loss',sl,['Revenue','Gross Profit','Operating Profit','Operating Margin'],'Departments.Department',['Operating Profit'],'Calendar.Month',['Revenue','Operating Profit'],['PnL.Category','Signed Actual','Signed Budget'],kind2='lineChart'),page('Budget performance',sl,['Operating Profit','Budget Profit','Profit Variance','Operating Expense'],'Departments.Department',['Operating Profit','Budget Profit'],'Calendar.Month',['Operating Profit','Budget Profit'],['Departments.Department','Revenue','Cost of Sales','Operating Expense','Profit Variance'],kind2='lineChart'),page('Cash movements',sl,['Cash Inflow','Cash Outflow','Net Cash Movement','Operating Cash Movement'],'Cash.Category',['Net Cash Movement'],'Calendar.Month',['Cash Inflow','Cash Outflow'],['Cash.Category','Cash Inflow','Cash Outflow','Net Cash Movement'],note='Cash movements only. Opening/closing balances and bank reconciliation are outside this release.',kind2='lineChart')]
    actual={c:sum(r['Actual'] for r in pnl if r['Category']==c) for c in ['Revenue','COGS','Operating Expense']}
    profit=actual['Revenue']-actual['COGS']-actual['Operating Expense']
    return base('04-financial-pnl-cashflow','Financial P&L / Cash Flow Dashboard','Finance intelligence','Explain operating profit, budget variance and the difference between earned revenue and cash movement.','Jan–Sep 2026 monthly accrual P&L and separate cash records.','PnL actual and budget amounts are positive; Category determines income/cost sign. CashMovement is signed (receipts positive). P&L and cash must be reconciled independently; there is no inferred bank balance. Monthly dates are month starts. Tax, interest, balance sheet, AR/AP ageing and cash forecasts are excluded.',{'Departments':table(departments,'DepartmentID','one department'),'PnL':table(pnl,'LineID','one department/category/month',dates=['Date'],decimals=['Actual','Budget']),'Cash':table(cash,'CashID','one department/cash category/month',dates=['Date'],decimals=['CashMovement'])},[('PnL','DepartmentID','Departments','DepartmentID'),('Cash','DepartmentID','Departments','DepartmentID'),('PnL','Date','Calendar','Date'),('Cash','Date','Calendar','Date')],ms,ps,{'Revenue':actual['Revenue'],'Operating Profit':profit,'Operating Margin':ratio(profit,actual['Revenue']),'Net Cash Movement':total(cash,'CashMovement'),'Cash Inflow':sum(r['CashMovement'] for r in cash if r['CashMovement']>0),'Cash Outflow':-sum(r['CashMovement'] for r in cash if r['CashMovement']<0)})

def retail():
    rng=random.Random(105)
    stores=[dict(StoreID=f'S{i}',Store=f'Demo Store {i}',Region=['South','North','Central'][i%3],Format=['Mall','High street'][i%2]) for i in range(1,10)]
    rows=[]
    for day in range(180):
        for s in stores:
            visitors=rng.randint(100,700); transactions=rng.randint(20,visitors//2); units=transactions*rng.randint(1,4)
            gross=units*rng.randrange(5,25)*100; refunds=round(gross*rng.uniform(0,.08),2); net=gross-refunds
            rows.append(dict(StoreDayID=f'R{len(rows)+1}',StoreID=s['StoreID'],Date=date(day),Visitors=visitors,Transactions=transactions,Units=units,GrossSales=gross,Refunds=refunds,NetCOGS=round(net*.62,2),Target=150000))
    net=total(rows,'GrossSales')-total(rows,'Refunds')
    ms=[summ('Gross Sales','Trading','GrossSales'),summ('Refunds','Trading','Refunds'),measure('Net Sales','[Gross Sales] - [Refunds]','Gross sales less refund amounts, excluding tax.',MONEY),summ('Net Cost of Sales','Trading','NetCOGS','Cost of sold goods less inventory cost restored by returns.'),measure('Gross Profit','[Net Sales] - [Net Cost of Sales]','Net sales less net COGS.',MONEY),measure('Gross Margin','DIVIDE([Gross Profit], [Net Sales])','Gross profit / net sales.',PCT),summ('Visitors','Trading','Visitors',fmt='#,0'),summ('Transactions','Trading','Transactions',fmt='#,0'),summ('Units Sold','Trading','Units','Gross units sold; return quantities are not supplied.',fmt='#,0'),measure('Store Conversion','DIVIDE([Transactions], [Visitors])','Purchase transactions / counted store visits; not unique customer conversion.',PCT),measure('Average Basket','DIVIDE([Net Sales], [Transactions])','Net sales / purchase transactions.',MONEY),summ('Sales Target','Trading','Target','Daily store net sales target.'),measure('Target Attainment','DIVIDE([Net Sales], [Sales Target])','Net sales / target.',PCT),measure('Refund Rate','DIVIDE([Refunds], [Gross Sales])','Refund amount / gross sales.',PCT)]
    sl=['Calendar.Month','Stores.Region','Stores.Format']
    ps=[page('Store performance',sl,['Net Sales','Gross Profit','Target Attainment','Store Conversion'],'Stores.Store',['Net Sales','Sales Target'],'Calendar.Month',['Net Sales'],['Stores.Store','Net Sales','Gross Margin','Target Attainment','Store Conversion'],kind2='lineChart'),page('Footfall and baskets',sl,['Visitors','Transactions','Average Basket','Units Sold'],'Stores.Store',['Store Conversion'],'Calendar.Month',['Transactions'],['Stores.Store','Visitors','Transactions','Store Conversion','Average Basket'],kind2='lineChart'),page('Margin and refunds',sl,['Gross Sales','Refunds','Refund Rate','Gross Margin'],'Stores.Store',['Gross Profit'],'Stores.Format',['Refunds'],['Stores.Store','Gross Sales','Refunds','Net Cost of Sales','Gross Profit'])]
    return base('05-retail-performance','Retail Store Performance Dashboard','Retail intelligence','Compare stores on sales, footfall conversion, basket value, refunds and gross margins.','180 trading days through 30 Sep 2026; one daily record per store.','0 <= Transactions <= Visitors; Refunds <= GrossSales. NetCOGS must already reflect returned inventory cost. Transaction and visitor counts are events, not distinct people. Targets are one per store/date. No SKU inventory or customer-level identity is implied.',{'Stores':table(stores,'StoreID','one store'),'Trading':table(rows,'StoreDayID','one store per trading date',dates=['Date'],decimals=['GrossSales','Refunds','NetCOGS','Target'])},[('Trading','StoreID','Stores','StoreID'),('Trading','Date','Calendar','Date')],ms,ps,{'Net Sales':round(net,2),'Gross Profit':round(net-total(rows,'NetCOGS'),2),'Visitors':total(rows,'Visitors'),'Transactions':total(rows,'Transactions'),'Store Conversion':ratio(total(rows,'Transactions'),total(rows,'Visitors')),'Average Basket':ratio(net,total(rows,'Transactions'))})

def ecommerce():
    rng=random.Random(106)
    channels=[dict(ChannelID=f'C{i}',Channel=n,Market='Pakistan') for i,n in enumerate(['Web direct','Marketplace','Social commerce'],1)]
    orders=[]; ads=[]
    for i in range(900):
        gross=rng.randrange(10,200)*100; discount=round(gross*rng.uniform(0,.2),2); refund=round((gross-discount)*rng.choice([0,0,0,0,1]),2)
        net=gross-discount-refund; cogs=round(net*.5,2)
        orders.append(dict(OrderID=f'O{i+1:05d}',ChannelID=channels[i%3]['ChannelID'],Date=date(rng.randrange(180)),CustomerID=f'Customer {i%320+1:04d}',GrossSales=gross,Discount=discount,Refund=refund,NetCOGS=cogs,ShippingCost=350,PaymentFee=round((gross-discount)*.025,2),FulfilmentCost=100))
    for day in range(180):
        for ch in channels:
            ads.append(dict(SpendID=f'A{len(ads)+1}',ChannelID=ch['ChannelID'],Date=date(day),AdSpend=rng.randrange(5,30)*100))
    net=total(orders,'GrossSales')-total(orders,'Discount')-total(orders,'Refund')
    contribution=net-sum(total(orders,c) for c in ['NetCOGS','ShippingCost','PaymentFee','FulfilmentCost'])
    spend=total(ads,'AdSpend')
    ms=[summ('Gross Sales','Orders','GrossSales'),summ('Discounts','Orders','Discount'),summ('Refunds','Orders','Refund'),measure('Net Revenue','[Gross Sales] - [Discounts] - [Refunds]','Revenue after discounts and refunds, before tax.',MONEY),summ('Net COGS','Orders','NetCOGS','Cost after recoverable returned goods are restored.'),measure('Variable Costs','SUM(Orders[ShippingCost]) + SUM(Orders[PaymentFee]) + SUM(Orders[FulfilmentCost])','Shipping, payment and fulfilment expenses including nonrefundable return costs.',MONEY),measure('Contribution before Ads','[Net Revenue] - [Net COGS] - [Variable Costs]','Contribution after order-level costs, before marketing.',MONEY),summ('Ad Spend','Advertising','AdSpend','Daily channel spend, stored separately to avoid order duplication.'),measure('Contribution after Ads','[Contribution before Ads] - [Ad Spend]','Contribution after paid media; not accounting net profit.',MONEY),measure('Contribution Margin','DIVIDE([Contribution after Ads], [Net Revenue])','Post-ad contribution / net revenue.',PCT),measure('Order Count','COUNTROWS(Orders)','All placed orders in the supplied cohort, including refunded orders.'),measure('Net AOV','DIVIDE([Net Revenue], [Order Count])','Net revenue / all cohort orders.',MONEY),measure('Revenue to Ad Spend','DIVIDE([Net Revenue], [Ad Spend])','Blended net revenue / all paid media spend; not attributed ROAS.',NUM),measure('Refund Rate','DIVIDE([Refunds], [Gross Sales] - [Discounts])','Refund amount / discounted sales.',PCT)]
    sl=['Calendar.Month','Channels.Channel','Calendar.Quarter']
    ps=[page('Profitability overview',sl,['Net Revenue','Contribution after Ads','Contribution Margin','Net AOV'],'Channels.Channel',['Contribution after Ads'],'Calendar.Month',['Net Revenue','Contribution after Ads'],['Channels.Channel','Net Revenue','Ad Spend','Contribution after Ads','Contribution Margin'],kind2='lineChart'),page('Marketing economics',sl,['Ad Spend','Revenue to Ad Spend','Contribution before Ads','Contribution after Ads'],'Channels.Channel',['Ad Spend'],'Calendar.Month',['Ad Spend','Contribution after Ads'],['Channels.Channel','Ad Spend','Revenue to Ad Spend','Order Count','Net AOV'],kind2='lineChart'),page('Discounts and returns',sl,['Gross Sales','Discounts','Refunds','Refund Rate'],'Channels.Channel',['Refunds'],'Calendar.Month',['Refunds'],['Channels.Channel','Gross Sales','Discounts','Refunds','Net COGS','Variable Costs'],kind2='lineChart')]
    return base('06-ecommerce-profitability','E-commerce Profitability Dashboard','Commerce profitability','Expose channel contribution after discounts, refunds, fulfilment and advertising costs.','180-day order cohorts through 30 Sep 2026; refunds attributed to original order date.','OrderID is unique. Refund <= GrossSales - Discount. NetCOGS reflects recoverable returns; payment/shipping costs may remain after a refund. AdSpend is one row per channel/date. Revenue-to-spend is blended efficiency, not causal ad attribution. No CAC, LTV or accounting net profit claims.',{'Channels':table(channels,'ChannelID','one acquisition/sales channel'),'Orders':table(orders,'OrderID','one order',dates=['Date'],decimals=['GrossSales','Discount','Refund','NetCOGS','ShippingCost','PaymentFee','FulfilmentCost']),'Advertising':table(ads,'SpendID','one channel per day',dates=['Date'],decimals=['AdSpend'])},[('Orders','ChannelID','Channels','ChannelID'),('Advertising','ChannelID','Channels','ChannelID'),('Orders','Date','Calendar','Date'),('Advertising','Date','Calendar','Date')],ms,ps,{'Net Revenue':round(net,2),'Ad Spend':spend,'Contribution before Ads':round(contribution,2),'Contribution after Ads':round(contribution-spend,2),'Order Count':len(orders),'Revenue to Ad Spend':ratio(net,spend)})

def crm():
    rng=random.Random(107)
    reps=[dict(OwnerID=f'R{i}',Owner=f'Advisor {i}',Team=['Inbound','Enterprise','Partners'][i%3]) for i in range(1,10)]
    rows=[]
    stages={'New':.1,'Qualified':.25,'Proposal':.5,'Negotiation':.75,'Won':1.,'Lost':0.}
    for i in range(420):
        age=rng.randint(1,180); stage=rng.choice(list(stages)); closed=stage in ['Won','Lost']; duration=rng.randint(0,age)
        rows.append(dict(OpportunityID=f'OP{i+1:04d}',OwnerID=reps[i%9]['OwnerID'],Source=['YouTube','Referral','Website','Outbound'][i%4],Stage=stage,CreatedDate=date(age),ClosedDate=date(age-duration) if closed else '',LastActivityDate=date(rng.randint(0,age)),Amount=rng.randrange(5,100)*10000,Probability=stages[stage],CycleDays=duration if closed else 0,IsOpen=0 if closed else 1))
    opened=[r for r in rows if r['IsOpen']]; won=[r for r in rows if r['Stage']=='Won']; closed=[r for r in rows if not r['IsOpen']]
    ms=[measure('Opportunities','COUNTROWS(Opportunities)','Count of opportunities created in the selected cohort.'),measure('Open Opportunities','CALCULATE(COUNTROWS(Opportunities), KEEPFILTERS(Opportunities[IsOpen] = 1))','Currently open opportunities in the creation cohort.'),measure('Open Pipeline','CALCULATE(SUM(Opportunities[Amount]), KEEPFILTERS(Opportunities[IsOpen] = 1))','Current amount of open opportunities.',MONEY),measure('Weighted Pipeline','CALCULATE(SUMX(Opportunities, Opportunities[Amount] * Opportunities[Probability]), KEEPFILTERS(Opportunities[IsOpen] = 1))','Open amount × stage probability; heuristic, not a calibrated forecast.',MONEY),measure('Won Deals','CALCULATE(COUNTROWS(Opportunities), KEEPFILTERS(Opportunities[Stage] = "Won"))','Won opportunities in the selected creation cohort.'),measure('Lost Deals','CALCULATE(COUNTROWS(Opportunities), KEEPFILTERS(Opportunities[Stage] = "Lost"))','Lost opportunities in the selected creation cohort.'),measure('Won Value','CALCULATE(SUM(Opportunities[Amount]), KEEPFILTERS(Opportunities[Stage] = "Won"))','Won deal amount; bookings, not recognized accounting revenue.',MONEY),measure('Win Rate','DIVIDE([Won Deals], [Won Deals] + [Lost Deals])','Wins divided by wins plus losses; excludes open deals.',PCT),measure('Average Won Deal','DIVIDE([Won Value], [Won Deals])','Won value / won count.',MONEY),measure('Average Sales Cycle','CALCULATE(AVERAGE(Opportunities[CycleDays]), KEEPFILTERS(Opportunities[Stage] = "Won"))','Mean creation-to-close days for wins.',NUM),measure('Stale Open Deals','CALCULATE([Open Opportunities], KEEPFILTERS(Opportunities[LastActivityDate] < DATE(2026,9,30) - 14))','Open deals with no activity for more than 14 days at the demo as-of date.'),measure('Stale Pipeline','CALCULATE([Open Pipeline], KEEPFILTERS(Opportunities[LastActivityDate] < DATE(2026,9,30) - 14))','Amount of stale open deals at the demo as-of date.',MONEY)]
    sl=['Calendar.Month','Owners.Team','Owners.Owner']
    ps=[page('Pipeline overview',sl,['Open Pipeline','Weighted Pipeline','Open Opportunities','Stale Open Deals'],'Opportunities.Stage',['Open Pipeline'],'Owners.Owner',['Open Pipeline'],['Owners.Owner','Open Opportunities','Open Pipeline','Weighted Pipeline','Stale Pipeline']),page('Wins and conversion',sl,['Won Deals','Won Value','Win Rate','Average Sales Cycle'],'Opportunities.Source',['Won Value'],'Calendar.Month',['Won Deals','Lost Deals'],['Owners.Owner','Won Deals','Lost Deals','Win Rate','Average Won Deal'],kind2='lineChart'),page('Follow-up priorities',sl,['Stale Open Deals','Stale Pipeline','Open Opportunities','Weighted Pipeline'],'Owners.Owner',['Stale Pipeline'],'Opportunities.Source',['Stale Open Deals'],['Opportunities.OpportunityID','Owners.Owner','Opportunities.Stage','Opportunities.LastActivityDate','Open Pipeline','Stale Open Deals'])]
    return base('07-sales-crm','Sales CRM Analytics Dashboard','Sales pipeline','Review open pipeline, cohort win rates, deal velocity and stale follow-up opportunities.','Creation-date cohorts; current stage/activity snapshot at 30 Sep 2026.','Month means CreatedDate, not ClosedDate. Stage histories and historical pipeline are unavailable. ClosedDate is required for Won/Lost and blank for open stages. Probability lies in [0,1]. Update fixed as-of DATE in stale-deal measures for a new reporting snapshot. No personal customer data is included.',{'Owners':table(reps,'OwnerID','one sales owner'),'Opportunities':table(rows,'OpportunityID','one current opportunity snapshot',dates=['CreatedDate','ClosedDate','LastActivityDate'],decimals=['Amount','Probability'])},[('Opportunities','OwnerID','Owners','OwnerID'),('Opportunities','CreatedDate','Calendar','Date')],ms,ps,{'Open Opportunities':len(opened),'Open Pipeline':total(opened,'Amount'),'Weighted Pipeline':round(sum(r['Amount']*r['Probability'] for r in opened),2),'Won Deals':len(won),'Win Rate':ratio(len(won),len(closed)),'Stale Open Deals':sum(r['LastActivityDate']<date(14) for r in opened)})

def hr():
    rng=random.Random(108)
    deps=[dict(DepartmentID=f'D{i}',Department=n,Location=['Karachi','Lahore'][i%2]) for i,n in enumerate(['Engineering','Sales','Operations','Finance','Support'],1)]
    rows=[]; hc={d['DepartmentID']:rng.randint(25,70) for d in deps}
    for month in range(1,10):
        end=dt.date(2026,month,calendar.monthrange(2026,month)[1]).isoformat()
        for d in deps:
            key=d['DepartmentID']; start=hc[key]; hired=rng.randint(0,6); left=rng.randint(0,4); finish=start+hired-left; hc[key]=finish
            hours=start*160; absent=rng.randint(0,start*12)
            rows.append(dict(SnapshotID=f'H{len(rows)+1}',DepartmentID=key,Date=end,OpeningHeadcount=start,ClosingHeadcount=finish,Hires=hired,Leavers=left,ScheduledHours=hours,AbsentHours=absent,OvertimeHours=rng.randint(0,start*10),Payroll=finish*rng.randrange(7,20)*10000))
    latest=[r for r in rows if r['Date']=='2026-09-30']
    average=sum(r['OpeningHeadcount'] for r in rows)/9
    ms=[measure('Headcount','VAR LastMonth = MAX(Workforce[Date]) RETURN CALCULATE(SUM(Workforce[ClosingHeadcount]), Workforce[Date] = LastMonth)','Closing headcount at the latest snapshot in the selected period; never sum months.'),measure('Average Opening Headcount','AVERAGEX(VALUES(Workforce[Date]), CALCULATE(SUM(Workforce[OpeningHeadcount])))','Average of selected monthly opening headcounts.',NUM),summ('Hires','Workforce','Hires',fmt='#,0'),summ('Leavers','Workforce','Leavers',fmt='#,0'),measure('Net Hiring','[Hires] - [Leavers]','Period hires less leavers.'),measure('Period Attrition','DIVIDE([Leavers], [Average Opening Headcount])','Leavers in selected months / average monthly opening headcount. Period rate, not annualized.',PCT),summ('Scheduled Hours','Workforce','ScheduledHours',fmt='#,0'),summ('Absent Hours','Workforce','AbsentHours',fmt='#,0'),measure('Absence Rate','DIVIDE([Absent Hours], [Scheduled Hours])','Absent hours / scheduled hours.',PCT),summ('Overtime Hours','Workforce','OvertimeHours',fmt='#,0'),summ('Payroll','Workforce','Payroll','Total payroll over selected months.'),measure('Payroll per Employee Month','DIVIDE([Payroll], SUM(Workforce[ClosingHeadcount]))','Payroll / sum of monthly closing headcounts; employee-month cost, not payroll / latest headcount.',MONEY)]
    sl=['Calendar.Month','Departments.Department','Departments.Location']
    ps=[page('Workforce overview',sl,['Headcount','Hires','Leavers','Period Attrition'],'Departments.Department',['Headcount'],'Calendar.Month',['Headcount'],['Departments.Department','Headcount','Hires','Leavers','Period Attrition'],kind2='lineChart'),page('Retention and hiring',sl,['Average Opening Headcount','Hires','Net Hiring','Period Attrition'],'Departments.Department',['Hires','Leavers'],'Calendar.Month',['Hires','Leavers'],['Departments.Department','Average Opening Headcount','Leavers','Period Attrition'],kind2='lineChart'),page('Attendance and cost',sl,['Payroll','Payroll per Employee Month','Absence Rate','Overtime Hours'],'Departments.Department',['Payroll'],'Calendar.Month',['Absence Rate'],['Departments.Department','Scheduled Hours','Absent Hours','Absence Rate','Payroll'],kind2='lineChart')]
    return base('08-hr-workforce','HR / Workforce Analytics System','Workforce intelligence','Monitor staffing, period attrition, attendance and payroll without double-counting monthly headcount.','Jan–Sep 2026 department/month snapshots; headcount uses latest selected month.','ClosingHeadcount = OpeningHeadcount + Hires - Leavers. Next month opening equals prior closing. All departments must have the same month coverage. AbsentHours <= ScheduledHours. Aggregate, synthetic HR data only; access controls for real employee information must be designed before deployment.',{'Departments':table(deps,'DepartmentID','one department'),'Workforce':table(rows,'SnapshotID','one department per month-end',dates=['Date'],decimals=['Payroll'])},[('Workforce','DepartmentID','Departments','DepartmentID'),('Workforce','Date','Calendar','Date')],ms,ps,{'Headcount':total(latest,'ClosingHeadcount'),'Hires':total(rows,'Hires'),'Leavers':total(rows,'Leavers'),'Period Attrition':ratio(total(rows,'Leavers'),average),'Absence Rate':ratio(total(rows,'AbsentHours'),total(rows,'ScheduledHours')),'Payroll':total(rows,'Payroll')})

def project_profit():
    rng=random.Random(109)
    projs=[dict(ProjectID=f'P{i:03d}',Project=f'Demo Engagement {i:02d}',Client=f'Client {i%6+1}',Manager=f'Manager {i%4+1}',Service=['Automation','Analytics','Software'][i%3]) for i in range(1,19)]
    rows=[]
    for month in range(1,10):
        for p in projs:
            hours=rng.randint(60,220); revenue=rng.randrange(15,70)*10000
            rows.append(dict(PeriodID=f'F{len(rows)+1}',ProjectID=p['ProjectID'],Date=f'2026-{month:02d}-01',RecognizedRevenue=revenue,LaborCost=hours*1800,SubcontractCost=rng.randrange(0,15)*10000,Expenses=rng.randrange(1,10)*10000,ActualHours=hours,PlannedHours=140,CostBudget=450000,Invoiced=revenue,Collected=round(revenue*rng.uniform(.6,1),2)))
    cost=sum(total(rows,c) for c in ['LaborCost','SubcontractCost','Expenses']); rev=total(rows,'RecognizedRevenue')
    ms=[summ('Recognized Revenue','Performance','RecognizedRevenue','Accrual revenue recognized for the reporting period.'),summ('Labor Cost','Performance','LaborCost'),summ('Subcontract Cost','Performance','SubcontractCost'),summ('Expenses','Performance','Expenses'),measure('Delivery Cost','[Labor Cost] + [Subcontract Cost] + [Expenses]','Direct project delivery cost excluding general overhead.',MONEY),measure('Project Profit','[Recognized Revenue] - [Delivery Cost]','Recognized revenue less direct delivery cost.',MONEY),measure('Project Margin','DIVIDE([Project Profit], [Recognized Revenue])','Project profit / recognized revenue.',PCT),summ('Cost Budget','Performance','CostBudget','Monthly allocated direct delivery budget.'),measure('Budget Remaining','[Cost Budget] - [Delivery Cost]','Allocated budget less actual cost; positive is under budget.',MONEY),summ('Actual Hours','Performance','ActualHours',fmt='#,0'),summ('Planned Hours','Performance','PlannedHours',fmt='#,0'),measure('Hours Variance','[Actual Hours] - [Planned Hours]','Positive means more hours consumed than planned.'),measure('Effective Revenue per Hour','DIVIDE([Recognized Revenue], [Actual Hours])','Recognized revenue per actual delivery hour.',MONEY),summ('Invoiced','Performance','Invoiced'),summ('Collected','Performance','Collected'),measure('Invoice Cash Gap','[Invoiced] - [Collected]','Selected-period invoices minus collections. Not accounts-receivable balance or overdue debt.',MONEY)]
    sl=['Calendar.Month','Projects.Manager','Projects.Service']
    ps=[page('Portfolio profitability',sl,['Recognized Revenue','Project Profit','Project Margin','Budget Remaining'],'Projects.Service',['Project Profit'],'Calendar.Month',['Recognized Revenue','Delivery Cost'],['Projects.Project','Recognized Revenue','Delivery Cost','Project Profit','Project Margin'],kind2='lineChart'),page('Delivery and budgets',sl,['Delivery Cost','Cost Budget','Hours Variance','Effective Revenue per Hour'],'Projects.Manager',['Delivery Cost','Cost Budget'],'Projects.Service',['Actual Hours','Planned Hours'],['Projects.Project','Cost Budget','Delivery Cost','Budget Remaining','Hours Variance']),page('Billing and collections',sl,['Invoiced','Collected','Invoice Cash Gap','Recognized Revenue'],'Projects.Client',['Invoiced','Collected'],'Calendar.Month',['Invoiced','Collected'],['Projects.Project','Invoiced','Collected','Invoice Cash Gap'],kind2='lineChart')]
    return base('09-project-profitability','Project Profitability Dashboard','Project intelligence','Find unprofitable engagements, budget overruns and differences between project revenue, invoices and receipts.','Jan–Sep 2026 monthly project performance.','One row per project/month. Recognized revenue is independent of invoices and cash. CostBudget is allocated monthly, not a repeated full-project budget. Collections can exceed current invoices with opening receivables in real data. Invoice cash gap is not an overdue balance; opening receivables and due dates are outside scope.',{'Projects':table(projs,'ProjectID','one project'),'Performance':table(rows,'PeriodID','one project per month',dates=['Date'],decimals=['RecognizedRevenue','LaborCost','SubcontractCost','Expenses','CostBudget','Invoiced','Collected'])},[('Performance','ProjectID','Projects','ProjectID'),('Performance','Date','Calendar','Date')],ms,ps,{'Recognized Revenue':rev,'Delivery Cost':cost,'Project Profit':rev-cost,'Project Margin':ratio(rev-cost,rev),'Budget Remaining':total(rows,'CostBudget')-cost,'Invoice Cash Gap':round(total(rows,'Invoiced')-total(rows,'Collected'),2)})

def operations():
    rng=random.Random(110)
    teams=[dict(TeamID=f'T{i}',Team=f'Operations Team {i}',Location=['Karachi','Lahore','Islamabad'][i%3]) for i in range(1,7)]
    rows=[]
    for i in range(720):
        age=rng.randint(0,180); allowance=rng.randint(2,10); complete=(i%5!=0 and age>=1); cycle=rng.randint(0,age) if complete else 0
        rows.append(dict(JobID=f'J{i+1:05d}',TeamID=teams[i%6]['TeamID'],Service=['Delivery','Installation','Maintenance'][i%3],Priority=['Standard','High','Urgent'][i%3],CreatedDate=date(age),DueDate=(ASOF-dt.timedelta(days=age)+dt.timedelta(days=allowance)).isoformat(),CompletedDate=date(age-cycle) if complete else '',Status='Completed' if complete else 'Open',CycleDays=cycle,OnTime=1 if complete and cycle<=allowance else 0,Rework=1 if complete and i%11==0 else 0,Cost=rng.randrange(1,40)*1000))
    done=[r for r in rows if r['Status']=='Completed']; opened=[r for r in rows if r['Status']=='Open']; late=[r for r in opened if r['DueDate']<ASOF.isoformat()]
    ms=[measure('Jobs Created','COUNTROWS(Jobs)','Jobs in selected creation-date cohorts.'),measure('Completed Jobs','CALCULATE(COUNTROWS(Jobs), KEEPFILTERS(Jobs[Status] = "Completed"))','Currently completed jobs in selected creation cohorts.'),measure('Open Jobs','CALCULATE(COUNTROWS(Jobs), KEEPFILTERS(Jobs[Status] = "Open"))','Current unfinished jobs in selected creation cohorts.'),measure('Completion Rate','DIVIDE([Completed Jobs], [Jobs Created])','Completed jobs / created jobs in cohort; not daily throughput.',PCT),summ('On Time Jobs','Jobs','OnTime','Completed jobs by due date.',fmt='#,0'),measure('On Time Rate','DIVIDE([On Time Jobs], [Completed Jobs])','Completed on-time jobs / all completed jobs.',PCT),measure('Average Cycle Days','CALCULATE(AVERAGE(Jobs[CycleDays]), KEEPFILTERS(Jobs[Status] = "Completed"))','Mean creation-to-completion days for finished work.',NUM),measure('Overdue Open Jobs','CALCULATE([Open Jobs], KEEPFILTERS(Jobs[DueDate] < DATE(2026,9,30)))','Open jobs whose due date precedes the demo snapshot date.'),summ('Rework Jobs','Jobs','Rework','Completed jobs flagged for rework.',fmt='#,0'),measure('Rework Rate','DIVIDE([Rework Jobs], [Completed Jobs])','Reworked completed jobs / completed jobs.',PCT),measure('First Pass Yield','DIVIDE([Completed Jobs] - [Rework Jobs], [Completed Jobs])','Completed without rework / all completed jobs.',PCT),summ('Recorded Cost','Jobs','Cost','Recorded cost incurred on all selected jobs; open jobs included.'),measure('Cost per Completed Job','DIVIDE(CALCULATE(SUM(Jobs[Cost]), KEEPFILTERS(Jobs[Status] = "Completed")), [Completed Jobs])','Cost associated with completed jobs / completed count.',MONEY)]
    sl=['Calendar.Month','Teams.Location','Jobs.Service']
    ps=[page('Management scorecard',sl,['Jobs Created','Open Jobs','On Time Rate','First Pass Yield'],'Teams.Team',['Completed Jobs','Open Jobs'],'Calendar.Month',['On Time Rate'],['Teams.Team','Jobs Created','Completed Jobs','On Time Rate','Rework Rate'],kind2='lineChart'),page('Backlog and service',sl,['Open Jobs','Overdue Open Jobs','Average Cycle Days','Completion Rate'],'Jobs.Priority',['Open Jobs','Overdue Open Jobs'],'Teams.Team',['Overdue Open Jobs'],['Jobs.JobID','Teams.Team','Jobs.Priority','Jobs.DueDate','Open Jobs','Overdue Open Jobs']),page('Quality and cost',sl,['Rework Jobs','Rework Rate','Recorded Cost','Cost per Completed Job'],'Jobs.Service',['First Pass Yield'],'Calendar.Month',['Recorded Cost'],['Teams.Team','Completed Jobs','Average Cycle Days','First Pass Yield','Cost per Completed Job'],kind2='lineChart')]
    return base('10-operations-kpis','Operations & Management KPI Dashboard','Operations intelligence','Track current backlog, on-time completion, service cycle time, rework and delivery cost.','Creation-date cohorts and current job status at 30 Sep 2026.','Month means CreatedDate. CompletedDate is required for Completed and blank for Open. OnTime and Rework are 0/1 and zero for open jobs. CompletedDate >= CreatedDate; CycleDays must match. DueDate is a calendar-date SLA, not business-hour SLA. Update as-of DATE in overdue measure when using a newer snapshot. Historical backlog and completion-date throughput need a separate event history.',{'Teams':table(teams,'TeamID','one operations team'),'Jobs':table(rows,'JobID','one current job snapshot',dates=['CreatedDate','DueDate','CompletedDate'],decimals=['Cost'])},[('Jobs','TeamID','Teams','TeamID'),('Jobs','CreatedDate','Calendar','Date')],ms,ps,{'Jobs Created':len(rows),'Completed Jobs':len(done),'Open Jobs':len(opened),'On Time Rate':ratio(total(done,'OnTime'),len(done)),'Overdue Open Jobs':len(late),'First Pass Yield':ratio(len(done)-total(done,'Rework'),len(done)),'Recorded Cost':total(rows,'Cost')})

def projects():
    return [fn() for fn in [dealership,sales,inventory,finance,retail,ecommerce,crm,hr,project_profit,operations]]
