let
    Demo = Binary.Decompress(Binary.FromText("bZbdahtBDIXv+ywyzGg0f5elvnChkEKewE2WJpDYwXYKffseaWazCrQ1pOvMGenok7S9Px3frk/n2/c97Ze34+X2upzs4Xhb6O5tOT2ffh+W4+PD+f10o28v5+unLw7Pl+VKP5bjn+VypfuHp+Xx/WV5PJzf8fj11xWXjX/f4cDt+XUZTz+Pfy/nl5cvh0j7SBy47ELcpUgpUSqUiSlzCxR7ohgCcWsBf74cmPbsz9dAFRdQpBgZB2MT/LpQ5DoVifbpU4RASahAIzhBvVKu+CaM00J78adLpZIokCCNyviZECsIdclDkGmfvUA67sXliWoTJB4bJY7UiozzZTPMO27qVvT6gDQKUmtRzVIuM6G6GbbzcFs6TiONmCBoXFC0jqeahqJthkcE0Q8KRFk0o4IIOWyW+2bZzsOvWQ5aeTCQnpEbyhSmhRg2z6aAYb0QEWppenNF/VHaMCNERzlZkbSQpEG0LIAGEUCkVqfAYTYBLBdAVQyoPk6jDLkI5b7m5DCbQl1rgOlaAjLuuIXXEI70CGG29e+wHWEbwTbS0aE2BTxnpIAQ2mqk9GreSEeHWnbJLEswE6VpAKVWhWQFER1rE8AyPoMEGoJq1+/0J0+FY20KHR8lncb4pIpWRNS0puRYjwgwDbofprVVuWlv1ZkUO9gmUcsZHpI5telDXRvPKrFjnf/HumtKfWPNjrUJhmt1MVyrItekAz5ts4NtksFbm1w6FGMBIIu0bg0He8TI1lJkw4ysKoYoICDLGsLBNgU852Y2dBWRYIoqU/sok4NdVtjJXBhspJcZFVir5FCXFTVGzPaMmQ4YxIbGmuTYkTaB9jd2k5KWuWcYlqXFKXCoR4SuCWdbHDpCMYA9GiJyL3NTOtQmgeGcrWG7dlNJGHVB3DZdJMe6GmuYFuuN0eFZh1AX7KxqcqzrXK812vYb6zWjIQVdjvUx2yM51ibBffjoUGSMga4xrDOUtqwuHGsTwDW8j92RocAqA2VqfY3gUNcVtZKQgbooR5S2xtW2Y93MNs6OkahWWXSTYJhLXQWOtgnguYo101jisTBhdfSy1snRbtO0KLxpWj+t6HjP8w52m/tSN6TO9YCNXVmiK6s41m01ney9YqZBHmtN5v3iQHfr7qym7S2nb92s48PbJhPH2c7DLco+DOtrEXsbCeJJynxrieM8QrBG0X4t9uJFDEYzjAlSgeM8YqCouOGjqPb6xaB16VPhQJsChrP+50HMKZhhLWmZy5ihfw==", BinaryEncoding.Base64), Compression.Deflate),
    Source = if DataMode = "Demo" then Demo else if DataMode = "Folder" then File.Contents(DataFolder & "/Workforce.csv") else error "DataMode must be Demo or Folder",
    Parsed = Csv.Document(Source, [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {{"SnapshotID", type text}, {"DepartmentID", type text}, {"Date", type date}, {"OpeningHeadcount", Int64.Type}, {"ClosingHeadcount", Int64.Type}, {"Hires", Int64.Type}, {"Leavers", Int64.Type}, {"ScheduledHours", Int64.Type}, {"AbsentHours", Int64.Type}, {"OvertimeHours", Int64.Type}, {"Payroll", Currency.Type}}, "en-US")
in
    Typed
