{
  "name": "Model",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Teams",
        "lineageTag": "5eed3baa-6a35-5538-b849-02c58da39f06",
        "columns": [
          {
            "name": "TeamID",
            "dataType": "string",
            "sourceColumn": "TeamID",
            "summarizeBy": "none",
            "lineageTag": "da758a78-2d1e-5f96-86a2-c872b21bae32",
            "isHidden": true
          },
          {
            "name": "Team",
            "dataType": "string",
            "sourceColumn": "Team",
            "summarizeBy": "none",
            "lineageTag": "323f323b-7070-557e-ac7e-b134fc8ead8b"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location",
            "summarizeBy": "none",
            "lineageTag": "16b0e421-059c-5b93-9911-950dc5217332"
          }
        ],
        "partitions": [
          {
            "name": "Teams",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"C0lNzPV00QkBUjo++cmJJZn5eVwhhjr+BalFYE6xAkhOwVDHJzEjvyiVK8QIQ85Ix7M4JzE3MSkxhSvEGEPaWMc7sSgxOSOTK8QEQ9IEbq4phpwpsrlmGNJmcHMB\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Teams.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"TeamID\", type text}, {\"Team\", type text}, {\"Location\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Jobs",
        "lineageTag": "6680574f-b5e4-5064-889b-2368ae7d7bc0",
        "columns": [
          {
            "name": "JobID",
            "dataType": "string",
            "sourceColumn": "JobID",
            "summarizeBy": "none",
            "lineageTag": "28ee9bff-6d24-5712-9b17-4b9e29afbab9",
            "isHidden": true
          },
          {
            "name": "TeamID",
            "dataType": "string",
            "sourceColumn": "TeamID",
            "summarizeBy": "none",
            "lineageTag": "461cd7e3-9b52-539b-a11f-d2795ee07ee5",
            "isHidden": true
          },
          {
            "name": "Service",
            "dataType": "string",
            "sourceColumn": "Service",
            "summarizeBy": "none",
            "lineageTag": "5590656e-35a1-5e76-8d9c-d642f1d52460"
          },
          {
            "name": "Priority",
            "dataType": "string",
            "sourceColumn": "Priority",
            "summarizeBy": "none",
            "lineageTag": "9a966d6d-6d4f-5aed-b0ea-a15500313aaa"
          },
          {
            "name": "CreatedDate",
            "dataType": "dateTime",
            "sourceColumn": "CreatedDate",
            "summarizeBy": "none",
            "lineageTag": "4a6254c2-a3c8-51fc-9ff4-bd95e87b7aa4",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "sourceColumn": "DueDate",
            "summarizeBy": "none",
            "lineageTag": "9cb041bb-4604-5b72-83f2-e89f872175e6",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "CompletedDate",
            "dataType": "dateTime",
            "sourceColumn": "CompletedDate",
            "summarizeBy": "none",
            "lineageTag": "8bca05b1-491c-5b11-9da3-657f76451cae",
            "formatString": "dd MMM yyyy"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "summarizeBy": "none",
            "lineageTag": "26644e9b-6272-55a9-9c6f-2ba875e308a2"
          },
          {
            "name": "CycleDays",
            "dataType": "int64",
            "sourceColumn": "CycleDays",
            "summarizeBy": "none",
            "lineageTag": "39913bd7-3a5a-513f-969e-8fb5ebec2753"
          },
          {
            "name": "OnTime",
            "dataType": "int64",
            "sourceColumn": "OnTime",
            "summarizeBy": "none",
            "lineageTag": "4d9124fd-58be-5b80-a490-e7b520ce2c48"
          },
          {
            "name": "Rework",
            "dataType": "int64",
            "sourceColumn": "Rework",
            "summarizeBy": "none",
            "lineageTag": "8ad480b7-cd8c-5ef1-ae49-186b907f7d8b"
          },
          {
            "name": "Cost",
            "dataType": "decimal",
            "sourceColumn": "Cost",
            "summarizeBy": "none",
            "lineageTag": "cca1d683-75d6-55b6-8718-4fcc753c78b2"
          }
        ],
        "partitions": [
          {
            "name": "Jobs",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"nV1drx3HcXzPb7kEdr53n62H2EDgIGZ+AGNf2EQkyqBoB/r3Ofee3e6q3plu0Q5gH1DRcHdnpqe6urrmDz//z+9/ePn4+umnx//86fXrPz//+fXlP79+/vnr52+/vvzu6+unb69/+eHxXy8//OP1/X9/9/NPf//x9frTP3379O0fv7z87tc///j4x7/+8vLHLx8///T68l+v//fz1/99/D//8u3f/rA9/pNePqaXH15//PzP16+/vv1rX/7y6etfXvKW+4etf8hFf+4vL3/8++uXl+39//J4/NvPMfLLx/zy+y+/fPv044+fvn3++cvLv3/+69/Of7F9KJuMsbXz5/4hHfrIL3t6H7M0GbO8fCwv//Hp85dvr18+fXm8/H9//evrl2/nv14/bEN+pk0GzRUGTeWwT1pfPtbl27YPuemTJv1Jgz7ffpch28vH5rx8zrPRM7582Z+PeciY/eVj915eBq1vb4yzUqoMMvyZTVV/HufPwbNS2vuYSR9s92a660wPnZ/jw2N96Ji9vo+pU3K4E/14uB1X4DXm41vqmMdznst2DfqYJGeeh36/x8+uKxLHzM/nTPKgKXkT/XjOoc/ZaU6SrOqU3Yl9PII+Tdat8vissADfHiy9dBmzePP8WHX6XFvR6dlhyJqfz6ljVm+ed10w9JiPvwl29HPIIkM2d56HRpqhj/z+pzrm23s/plmW4+Nr+dNc9ScHryRDDH9WN9glWScYd0k+d4nsvMeK9Wa5vf3rMv6uj4jLr41nTNAHPbxprhhntqxTgtOc8hlo5Enz5s3zofN86Dybvdff5yRLPMzJnefHy2/6M/OJIi/7+AfOxD6mQk8l2TGd18oZp2VJP/6hH6dhm+iQCZd0Tu8rMGUZswYTnZr+3PWvKrd9okM2b5p3DIFyQh1vTwzRkA+oRzBy5rjqiO1tMdImkY32+DjepB76orRQ+Ou9LxSNMY+/1z+L631uGseY8owHMuLhTfGOOEH28uN50z0SygZ5RF5vhh/nZdKfDfeNjjkMYigu5HpMpm661OdRq7iIq+r+qLo/6tuJD/vj+e1k4RUfcB34ySAspP0WC/QYLi7c4o1WdW5we/T9uef067l4q75N5/UTcCdtuV6eX1PH9PHWrpt3vx0kcrYXF29VPd8gQB/maO8niJNNUlzA1RS9AGAdvO+aPdxLhLgAHW36M/U7OtKpri7i2nVz0MecBQhZkdUFXLtGhf3tQKWDRN61RoArA0zt8pOWSx4cE6oLuIYCQcA05lXLM91JsqGrC7h4SpI/JRK0q4+4dn3hnbZfpdPpLU7oq7uA69Bh3gMDTolsk+oCrl1X9KFw9YGAMUi394UiwLz6cAvGOfQIOPgkudC+PqYLt+Z75OBMcdgxm4u2xttLytToMZ8we6rFwOrmwy0OO4VTRdklzYVbOx7p8LK8+rJJtZuLt6ouvoqTsuHBmVo326T5gIvhka5FSnbSSTXok7qQi5PFMZ+WK8bqmC7oavrKbXnGNx9zdeVSIDUxSexIhhRoLuiCDHvo9xu8+0oxYL25sKvjGZXhHKXvN8xEdx93EbLO23zQkxXQY767wIuogM2wKrKHu4u8DkGtacOtQmlYZdTaI+C1NVx0U2ydnutPQn93gdeOGeKmkZ/yulyYp+kBz1WAL4NZxhixD851ug+7Dp3Z40Zz6aQGNBeTbvJcCLvew0yCBL67qOug6KwRgRZfqiZQdx91EfyAgJi228pRdDMCmktWzsCTmZLFbnfzcFEXZ52D5kQ+3/BBV9fl1zV/MudJ2roJXSPguTaNCDg/TAhnJgWGC7uqJjqQVwzOeY5zQcpEDx92HTrSoYezIVUqb5QRwC4ckU8TeCwXd3EiqyGB0pNmU57hIy9IiRkK3zjmBBt6uMhrIGOW+nyfnByzjrm7yKtpEGyaOu98xD82iNkpuw+9OMqupmV3oZcleeBPLSuqj+UCL6aYAa7j8iubZHfPISPYBZnEpkGWxjw4RuwBz7URLQ+DW/YnSQq6u5iLCfrGmEsfKwJdeJyM+UqpT0qv6Iy4oItKWcj94NdL3WaMe0B2AZgpgK+rmZIEbPDhgy4+lxaRKzVGIoeLuXjnbXMgfLiQCypNQx9w8Oc7Z0QC6uFjro7MFBwmtPyOxkH6CDAXptgQt3Dl5BOx6pgu6CIuAOA6oc2TvdBYeISoCyBsYl5FxghA16YFjrSo+J6piSaMhwu6OO7DsUKLb9h5DouLQBFCGoH0z5XGX4O+HQR+yKY9DAezeVCt4aXNBV0Wh0yr8GmLqC6MzLp7t3FfgE3GdDEX0yn6k0BD3nhO0hbUFrmgKI9ZbmcJvHpYW9RX35RkoSTgJDCSjOliLshqh90luwwRUF1YRQWKCkN0fqLgrDPiQ66dFBbAChCOez849TEDqgvqnokSCjiKMyWLKQVMF3w8YByIkTP1iZQitMWnHJ0k+lxRXXGbvTXXFYtZfMnFW4zx+3yPDEYhKfl4i46nBICE8GqXkH0OGiAuXI1w5M2SWolbKaC5uIZHceuQMXzI1fTgbMt8KZVKsCOlCHI1+SmJT+OyfjuTMNknyUVcVQ8oKrpRefFcPJJBpexDrqrFEshATeRKF/OvowaiLiyfj8Vxkl3URXF0o0IMBK9n7U4fK9J0ZS1bZog0VC5PzKu8vbzPXWsQhAjB3HUzyzoHNUYJEzDTzZB8O0fEHJUY8XTmapZUdFJ2YRftFNjNhFovDk5iTXZhV9UxKyo3KI+4jnidaB92UX0aeBUWq2z26CtBiRFoR6zX0qFy8CFfIk0XUOz7PIN/45SC8hMVIiR+zSREEmtKJOqC/AQOfGJb85NYkVVdXODVtEzWKLuj+FUTJQKp+Mir6VHSDUkAp98zKArTl4oLvYjpS5zIy3YrLvSqOicVD/qNhE3Zrr+wzgjVobH6gGZLlwB8bRCqgU6iBy0G5VQXfVVd1RWVn/Scx2AO423ig4k+5GdJ00Q+1YjrAtqWGE34frs5lGuAvrBeCVQzM3tETaXqo68DaTNUpNoaTwKQUyO6C1jHgk8MGPswJ191wRed0CnN+a5UffDFoEY3CqHXvRikWQPwBUtlVed+iwEME2uAvhBy6fHMi8eG7uajL+ZsDlynt9CtwKkF8i4k682ZIl+wueCLAFzWuhtXP1+oxp+aD75Yf9vxaSHSPJ9Tx3SxF+843TMseTpMQGwu9iKwCVQ9z/OT2IR59sHXoDDY58l8c7HXgZwexgdCH6Yan1pAeWVdflhLII1ENzu6RdgLjj4sOVKOe559cvT1iPKaQpzEYg5GDj2ivEDCuM9lwm+PGfRJQKSB6glNyqXFkg3cXezFLTFaUpgk9Hp69kDehSLmFWW4KUF1DhoVGpF9zPgTHzTR6ukB6wWVW0uy6MwGlUYkrRdC0nHYD+hjLyapgJmjSN15R3cXeh2SLqbNlib0qBuBgP5aICwHobXyLGNpQjZCpFVxOmgOJOKNQNGF2TtgfQwCrTAsGkFdESt2EJjTPQZoABxhYZHCHsRagFrNQMLhYq1OxYlFp8R+fk9Zf8PFWlQOM9FK99bwsRahDQQJmGrXswVBF6CLtfi4XNAf1TL0I4BaWTkPCPx8glSuGKX9ewRdIKikEHjxj/L2e1Rd1Cc1EFjfdg/Ki8Ia8a7BWTmXtazAPSK68HDTI4rAQjXq0bRHvYvQwAJaDqpMd/ugLtiyrQjTFXntaRkywlqFQs+svJj2QEqPEIa6VyCqVgPL9whrAfwFRiXdcaUOGdJc2osAn4/bSc85kShxBFDrO3CmbJPDxVq2N2m+TY6wvAjzCrkSbuAzqYNBI6gF5dkD/9SqXyQlOQKkNRPNDuZTigU0x29uXdxJDJ5t4MbtfESarq7IwYQuXSv/AtKyytsTVUr+dfhIqyq1VUkBQ+WYixGWQHNEcnrVcEDHJRPCT0rlevm8udCLKJUVRXqWYyRJzpuPvTh4tWmimLcIelH7iywWDDTZlJ7y5mIvbnQ98G+axulzzKh5MUNhDAqCFGm2w7x8oKXH3pgxX5FXkCgyZoC9WCI3LfzmLSwyQgiEuEA46eBFnbeA58Iy0b5YgWdLbpIxAzE9J2CA8oCleX7Aa0fnFEGv3O8TbWqM+1MirTsluciLo0S/sVzPIQIp/Vz6yKSCkdrlFAm78EQBXeGkx0amOQXAa143YX1+GRxmc4porikhzHLc28tHthHomdHnWUpOAc+FkBDelnYwt+nnFDUxAnJti71n4EhOIc0FxDWURakL79QRXWdyzi726uQJAnCEJHyJmLOcgyZGLPuabngdI9TTgxwE1g11AtkPmKMKI6gu9vmYu1Ez5BxJu+i8E6QzabYUJiPnqItx3hFPOco5qOzoHBQYsZeFT3k9knOkpwcpKlCiVLgzup+cIz09Sl2B0aNJMbWEnCPoBQWERTXmqvDIRBcXe7E4DjxHyAfmSXvJYxYfeqmO6kmlTaFXCeRdCP63+VJJ6cmwFH3XSE8PesUFw3LK4xS7lu8ReAHFMinRSoabi4u9WL29yhyNgDaXyDxCT5Sy4EhzicwjroP4bWZJLHdTA8qQLvLifQLYn2hXI+vNxUVeBwavfOBPiDPPp5THrJF7xFyXymjELJ0aAC8k58wZL+CtRpTXnB0mysuwrrn6yAtKvQC2jYy0P2XRsvWqi7y4h1iplpkMEuYkkNQnTaVQEdnvAFFDRI3EXSDdM9tEEWGNCozUaTiP/SYi1EjbBSAdWE5C2BfnqhPtIy8W4i60DMl4UuQWaLvYDAt+WlWzzEmLpF0g9Z1bFeTm4y7OkEmkakOCTkkLYNe8r5k+3n7iflk5LehiBPscOAFpmt+XtFKbuYW6rinbPMPsUkTJLbDr2rQKn+atpbkFknpkehZtY9UAjxaVFkGKiikpWT0kc5g0F3Q1FB0n4EFoj5wFXz2Me6DrkjVYcZPwAZ+1DH8O6uMuFsIz7tLMs7vAi18X+Gvm4nYGcz3gvLAus9CrnCVMERHl7uMuFgysiLTNULm5RwXHSXrWjYD97MXTt4+aGRW124Kjvm1UcMTUaUEyFLYByD0S1kNpBly7cKZPyllo7Nwj5AVUOMCRey+oJigjbGUEreaBf2orC0p5je/w7WpzsXAegVUqtEPCquHPZ+R2eUTKro0KHVM4t1uYOSLSa/qgVAO+4r9+wEBWv0FVlAqkd7mTRJ4RQi+QJuW5YiWPCHrBqgPoxYqfRJBwBE6p6GqqiJO63E7GXl81cpBAt0ZI8NINjiiY24NqI74ueUHaracfcw8MJFiGgBMiC2X3gRcXtqjMA491HnQ6qIu8LBMnEJO+npGE5z2Q1KPRJwiR2Y6IvVvyHlUbyzZ75o3NVxORaHsk6yJic9p8kvdAUo/JBAj0iRx9ej3Ac0XYa2EoTEmjUQrn3cVebIBA6vCbVEzm+Qj8I1CSlXAZ3Xg52SZHhLsy4K6FXUE+AsILeTjIa2eaLNknx3f0M4L6feItKVHmCEuNExvDbkqNxmAsH5GkHrTbZb73qtGj5eO39jP2JQd5RJVG1CQ1XOh3ckVC/xGovNgKcR75n3sv6wJ0URdltBhxcE6G+X5lC1Ve4HtG4uY7FCkyqIu7SG1olcJZxghqjZiV5Pmi5oa+EhvUKzmFtSj2cyJqpfj29ORtipZ83GFqyKniG9SzShj2ySRl1iEjCwnshFr40xffn5497qGJjGySKseu4vvTD10qpNkhwvBCrbr8Qg8J6MCGYkeysFXpleL703OamHF6JvSAzIpvUH9gGcq4qekKDAzquRkb9vLdlVnS0OIb1Fu/kene24SzeY4YEV4kCpQoQxYSZ+1NpyS07fqtj5lkyMgtdSkaljys+P70bJG3qEocVDspgTs9d/xW/IsQNJi2neLb068QOyGRUyInsKH47vQ7bWEIYsNmAQnHjMqMiNO3uRay+Pb0OhMOYfFcKjLNvjs9oSJoqmKm/jIok4AQ29ODMALYBuJ/hh00UHhh7QgqFgi7zsWjnzMSeC2nRLK7EjjUzxuRjbPpaRsH7xrALiz9LrQwl75LNopvUs9nPCCwdD+ihAEqgUs9Y2GozqT7g2rk8W3qGwnX07SAUnybemqFhKLRpH6iDxVVGSFr2qA60+9oRpaO71LPXiGLKs/p9qB403epn5sYGnXNyYcLd1hil/qCy3GqJSqhSz200Wo5hrKTw2SMxTep5woCVd2sGkQ2SWBRb7vNAWtiPLQr2veoJw581S1oRAPF96i3dDhNicxr4FE/L0AZcXR5yqN1zMijfgKEzb0Bz22iAMm3qKdxih72dOidmh+Z5sChnnKTtGj/ShwgfIf6rhuvW5I+65tGTBe4sQHTNe7RVDdvYFI/sBsBJAhMq7DLVok86uc3fG0T23bFR75HPZ3FWEuY9FnKHgks6hnD7lNWpfgO9atyNLs8m+ax4jvUA0zoyLOy9cFJqsjyCwzq5yoY47x9ieolZvsG9UT5rOz5k9EMlNCgnhb21LmrBA71O5a2QUszKbIJ01V8g3oKXOiiSZbWza7pSFNPck/YPbdOETnyAn96VisuSqtnyUi2c2RPj70T25wQLqE9fcetNk2ZjPFeCfzpO+IENCFtTkgI/elBcQwqGC7DPzM7WTmRQT36g5OMFlbOc5fIAg8M6jt1Y7QFz+Ub1DMfvOEM33hWpWl8g3p2fiSvekAM3azo7xHUwypi/1WLbSKHenBng8LJNNuRxeM71IOg5paYaOgKLerRLBqU3PQFNz6OfYN6LvlCF8ptUSOn5xvU8wKEjgQSpQ77/UJFPXTFQ/W8WCiSVGVefIt6lqWWRQ7vW9RbsbG8LPU+JTtmhLvQY2VhEHX53uugv/UuRgKIlDGeriMypO9Qz6YjUNSbaCN0TgKDeqbpF1cxlsigHq8kAbaQHozv/Si+Q/38dkfjunTZGEpEDCzquRkPdIZkmVQMcPBN6gfqmIH/oUlptzEjsovUSPNTPnCpXzqUtfsxL0MGuAtsGjHhpitLT22OBETfop7v21lUY87gJdsksKifkzXWg68f5kF9k3ruTi5TyUrxTepZm7MwgTQ3S5fApB5gDNG36abrxe3su9TbCpYsdOqmOnl6HTMgu9BagYy2bjUjOfcCk3pKLawqVafVRV7UJbItnuvSZeq7BpJ64GwBDFPsOtGcznMkqF/ctjxZO8LJVd+knhEiNBgRpzTsmEGBEQyTjDnUkCFCSf30BvZ8uzEGuJXqu9Tb6wKm2cTZDSSovfou9Uzg6jwXx1G+Bi71fdXbPXHg0+8ZdDJyhWd6cWn1berJrL0skrHzsjCpctTApn5uYDtY2FWee0/I1roFovpC0iE5UNP9iJfSSfWd6nettrFu7IaF4TipoVU9prd1rhSuvlU991VCpwNVEAovQN+pnr8f3W5wg62Cu2pgVU9NCXiNM20UNiyovlP9vEXLQPZuIHv1neqplrzq0KqhUz04ATDbYAsIulSiCuM0TFMqlo0vYPV96tnsMs+3ybuwJgk6rIFNfcM0B1Izdjri4mD1Ter5jgjWpMqE+B717HcA83GTpAJoqIFJPfXyoVtGvaEZfVMXc/HVa5BREFo/yWvZy75FPXXcINlQJthQFk7gUc9q3H2ujai+Rz1beaykTYNBa4086hF0LS7jvXRx8AXDGuPAhSx/Omn4lWjoW9Tbxk3I1nhIqCjUyKKeGetpDl9Di/prIb8hN2KILVGvAMl3qO9kXA4RgXQgbD5afYN6uogXr3KgHNRw/zUwqGdiBQ4Tol8P+z1d1LWbO6+mF8lW36F+Lt02h9zYDZILHOqXVxlPbD/11Isc6hPwjqse9mqCrO9Qz/c3UDfxje0SSrcGDvXc25fncrvqW9QzbIXGExJFF06Pq29R31FUjpchTVRE8JyRcSpKkwA4TK7tkNXje9Szm/eir3ujm6Wq71DPUKHPmfoaONSvegfYTd4YrVTfoZ6CF1+1dO9H0DGDLsZEpVn5ySoYwuuBPf1hMncJ29ttSA3bvju9d62Zpia+O/3yNlCrfIdmhBq407OPbcVVbgX6UuKuvjs9D0l3zt22iFIgvjs9Z2UL4vXsb9CvGbl24XUGRretSyWguvIxe21O7d73roRo35ueTVsWdhSbUMznkD7iYg0McPSTbkNZz74z/fxyUHOSXD5q8py+NT3vERO2ZIjwUiBQNsFz3bsulFbwfenZDQVCPtX227nxZJP4zvRQvyI9IH2/bszaa2xMT9fYT9fOZc2pXzTAXOj8MJejVt+YnkN9ns/JYdPFwJjennHytPQBb4MG9UVslF75tmTjDlh9q/puSghTGHJqBhQbBl711rRm2lhafa96elvQILBK2MZp36zeipenqP9yvtElGLjV88VUMC+7XUBJpRzVd6uHKw8bxh0qyJyGCpqf+G713HF+v6vpHCPEXYCRQDBAbOtmIqvvVs+HClTv7npPfdVITn/cZ8fayl+GzzIngVk949+GT3/DhxJ8fKt67urOi1Pet6qfezYOA7yMa1wNvOrZzinjF7izU4JpfK/6jloVVKZSysPXT1Tfqp7jPzQYHfYxkVsJvOqVr7mbcOux7JvVLwUSJPs5c1mJNL5ZfaNbJ6EXjW8FNZazNbCrHyh0WtUZr+5I+YSRXf1G8jNIgBC3M0yM3Ooz9XVM7z+pgVs96RmwPE11WnNO+Wb1fKaQZ9KtzChrx3er576dxTxXI++qgVs9yQY2eOQJuaKf8zuuBdrn6q7qm9Xz5oCmuTEBhRKoA7N6nmb9lnlyKQE8aFBmnBEOJnidpfNrnpvvVc83MkKDAnlZsRKmBVb1nGEYGeQug/x2cdeqLf485wRnNt+rvuL2XX2+kSmbaoFVPefvUJ7Jt90sXGnznerBynttCN84k2++Ub29NnhKQLbAqJ6bT6C/g2ik7YkxdUpc2MWVDs1RZk1fSR80Mu2C9bK49tyQmi02qgc7HdgmE9MkXeK+UT3Xo9IcdzXfqd5W7aaHiRF3tcConk0bEy7Fe+3ykEGjTkbIpBZ3dqfKFxK0yKieTVKn8OYCDfqcPu7izWdilwQF36ie79SDUvLMoVLHjHAXPZf8TSRmeF56rhMdqbuwe2fRUVXsu/tG9Tb2w7EKE70z6dB8p3rCCvYubB0jvJARnBlAosNymjMuyHLxrer5kIedSLrwZ5uRfsDIqR6cEckCDSYlM+ZsgVO9DTXyp3cfQ12QvlO9d5mWRFXfqJ6VqYtrNjbqzm2hTT0mEiQeu8XDpEsncO2CZ4NUjxsP38kBeXHfpB6OdevThhyQecrApZ5T8Pu9J+cgwQ1BqDkDWRJ162+cxjffpZ6mBFvtaY+YMncLXOrJdgpF4TP/bX35wCwVWeZFm9FujqjIpB47l8Y8YWyBST0IS+jSavYar8U8WIS7YLHQPY23Gr/sPd+lnkx5MAkldVIzp15gU78bi2KZ526PKGgIapFPPQr18+KI933quf458OeyXtQCm/qKUQGz2sldbooxfZ96SuM3irZ32YU+6L/kU79NWHF9zBB2VVya0+b45tvUs88KsBf1vqaLvmtUayQ+YBoTMtHCLTCpZ5059CCSkONM7yRlDE3qCdEAfrA4RN88dKkHlFkXKWNgU8+f78AvaWuNsvFCl3o4OkG8SJfbVMML+C71rGCAB76XqCUWBib13DENgGuf7Dud5O+gusZc29V8l/p53LeGHkbI1gKb+rnQ2qhIj8wBwXep5zsSQIiM0PC6V0p4Kd+knnupIC2jd0/MnoUW9TjmvZ71HCOQ08+uazKlk+3psSJfzzeo5zZGkMGQd2026CgwqG/GClF+7nfQKtvEt6fnboSFItdcUtt8d3qu4xnvWv18PuIiZSbKPekqDFO1bL49PTuzKXjgzIT9D5rvTk/cLdRVC1/lYGoJLfSnX2TwJE4ybtTNN6jny9RN4UTe1jeot3bq8Kc2W5SdF9jTdxLbwfHE2aK5H6FF/vTYdw199xNRpYZY35+eTWIhh6Ja8mbHjK7DhthlGk8kNwnt6ad3GfCiVq3/c8iA6MJsBzw9JqpoPTkDf3oobVRTaoQTykiam29Qzz1LUMebXHGsR5TvUM/30DDTJUdS4FDPNx8t7jQ7K9y6pn2HembggKnhasxuGAvfop672mBvU5fDs24OY4ZeqTsuw+mKzIzlIod61Nzlqeau+Qb1bKOW8f1vS0VpgcCgfs49mjY8c49D8/3pV62lKd/huqycyJ8ebzcGZpNRQzFYJHCot5c5U+jSJ4vEXYpa0aqXnuzsD5RmvuZb1M8vJzFH8s63DbXAop468fICjVw0vcy0b1FPXp8ri/WniyHcR9l8j3or9Z2zXYFJPa/BMX+yotvvHDQS1UPJbnHn1ZlyK9sQmdSjurLhJzDVUA3dPfCo55sYV9d2mxb07nvUMw2+KGh136PetqhOw382xfgeuNTPwZepnbRqPuB3+KWCIPLW2g2ai+6b1FsHfYllVMwz5eQeuNR7eHiXMaIiI/mZTmH6ZeeX9MECl/pZE4HRXG98APTApJ7ZlUVF0FTOu29Sz30JALFn7IC8uu9Rzx2mxlBN1nTgUc8+FKYGIxvWN6Vn4m1xJ/lZfpdjqfu29Est3B0V6RoOXOlXtqGM/U2e031f+k5+iMaeQN810tKTM56sNy6uPU3EdEwfbLGaPM0HbXzSdd+Xnny7NxJq3vPs66Drvi/9KiikiQ+FxNTAlt76Xk4Vdt23pZ8XPE1cqdnEKt+YntXBVDNfsbY9cKXnWYaf1DHBt61135SeCUKyFAZAWM1ujlzp+TGnbEqPXemh8Eya8vv5oYE5sqWHi2Ohy5xkUmdKp0MGnhGo1Fu031VTVuyBKz1fSQU/CftXE7t8V3r2UljNSmRLj0rUPF8tjS9Y64EvPSeHi4vMTsN33XuRMb3Efntnx02dKYC6+8b0c/8l43vZTKLYA2N68uHYuB9ecqUeGdOjeBK4vTwJXrKFfWP6uTrYBOqLPNIPGKro6d5YWUiUkqh75vuYvjE9a1rBKI8tR/gxfWN6vlO1TvmUHvjSz3N3C36Hyd2770wP3rKVWv9pUV8FeB00sEkFJ3TQ7dGRcgZZnZMIeSFxu3JEtKjJd6fnHd3muXv33ek5qgJooCvW+GbbHpjTMyxfOC5dqbuc8747PTuh08ULGL2M0qJH9vQI/Y1tuYCFwI+e2bI23xuRH/3MCcqo1VIyRaHuG9IzViUvBjjXkzlDAkN6MsdjeA3hSvVW56CBUwTaySwkrZtZgr4fPWsrTHucjhGhLdS3gMYOY8thigXdN6Rf3jxAibXxM+q+IT3JjFe+DlfTouyMwJEe7PLHsuX1cnCVreJb0ltKfSY/7b4jfddw1REEUhgoNgELLOkHFmLxakwa1J6Yvic9e3YvqMaL1tIxo6ZF0gXA5r5ViWBOQr8I0FiXefjyPek7UbWLDOIwF4N135Pe3uI1BVtGgNoDT3oi+uGSodkt5HouRZb02Py+40zdoqwOGRlGAOboU31KDwzp+V4w8s40GRj0/XTfkZ7dQXXGy6S9UGp/PXKkR6iV8bXvSYkM6UOtuZ+6IS6Gxf6+Ib13wQm8awC1EmnfIOLc9M+w/CKshczj4sr1tJ2BWmc66lkE2RAkEzgrZ7O+BprQkh5WNdSIZhmZDBk5o2I3kVFy6XP9dr+IlHANwQc8LUt0zO/QcgESufn6gESlB5b08xbD3epJmlk/kSf9Iv0kob8lRHxP+o4Yx5qj6hhR4yI2n2mFiDUBfFFA903pbWPhFGdmvnKs+570lNNyMnbT1ykcCUzpWbix2H1SJZK94pvSc5mSj3nFNL4r/XyxGEyzcedUD1zpu5I9na42JFMybpztvik9NUBivTJbjAjqzO6b0rOLAPgSkxrE5CiBKT1Dh4UXZ49M6TGUAvTCHKUeJh/zTenJLgLcGjdPTNgDV/p5imt89+zVPcN3pefMGxRitHYK5T3DN6UnI1x7zncZI1TQU3SRn3ShC9+RPnxTet6+cOgRzNzNqwZeXbMrTsw0n15nSceM/FHxKnL4CnSabul59OnLR2ZddAX09FrM4dvSz9WE5nK5iz+S+vMIfOlXcji+K6AweBi+L/3ymuBJiivQc0S+9Hwx03T5NL5TYwS29KCKG7fWBpkV35be2iHNvx/XToZvS78iWkkiVo3n6ghs6aEMOOiRidE8iMkYvi09N5yDfdzEsVfgyPBt6SH77jcn4U3GiK5hxHogmKDQfUovREUO35eevQYhQBAe1gz3HDNyjDjn2WENk1k6gS89Z44ARqjf/BI+vr/8/wM=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Jobs.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"JobID\", type text}, {\"TeamID\", type text}, {\"Service\", type text}, {\"Priority\", type text}, {\"CreatedDate\", type date}, {\"DueDate\", type date}, {\"CompletedDate\", type date}, {\"Status\", type text}, {\"CycleDays\", Int64.Type}, {\"OnTime\", Int64.Type}, {\"Rework\", Int64.Type}, {\"Cost\", Currency.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "lineageTag": "2b47e7d0-2dcd-5bc5-9551-3436a3dc6488",
        "columns": [
          {
            "name": "Label",
            "dataType": "string",
            "sourceColumn": "Label",
            "summarizeBy": "none",
            "lineageTag": "4c886701-f52d-5fa9-be20-5309d41154ee",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"80lMSs3hCo70C/FwDfF0VnBx9fXnAgA=\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Metrics.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Label\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Jobs Created",
            "expression": "COUNTROWS(Jobs)",
            "formatString": "#,0",
            "description": "Jobs in selected creation-date cohorts.",
            "displayFolder": "Business metrics",
            "lineageTag": "fd678cc0-dd82-52e9-8879-441aa91b3998"
          },
          {
            "name": "Completed Jobs",
            "expression": "CALCULATE(COUNTROWS(Jobs), KEEPFILTERS(Jobs[Status] = \"Completed\"))",
            "formatString": "#,0",
            "description": "Currently completed jobs in selected creation cohorts.",
            "displayFolder": "Business metrics",
            "lineageTag": "d5f64e8e-c30d-55ed-b05a-9a439b2cdfd6"
          },
          {
            "name": "Open Jobs",
            "expression": "CALCULATE(COUNTROWS(Jobs), KEEPFILTERS(Jobs[Status] = \"Open\"))",
            "formatString": "#,0",
            "description": "Current unfinished jobs in selected creation cohorts.",
            "displayFolder": "Business metrics",
            "lineageTag": "6ae63621-02f3-5c6c-81af-7acd92ebd441"
          },
          {
            "name": "Completion Rate",
            "expression": "DIVIDE([Completed Jobs], [Jobs Created])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Completed jobs / created jobs in cohort; not daily throughput.",
            "displayFolder": "Business metrics",
            "lineageTag": "a14b30bb-80b2-5994-88f3-bc6fd98975e9"
          },
          {
            "name": "On Time Jobs",
            "expression": "SUM(Jobs[OnTime])",
            "formatString": "#,0",
            "description": "Completed jobs by due date.",
            "displayFolder": "Business metrics",
            "lineageTag": "7f5772c5-f584-5a32-8040-9a0435749243"
          },
          {
            "name": "On Time Rate",
            "expression": "DIVIDE([On Time Jobs], [Completed Jobs])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Completed on-time jobs / all completed jobs.",
            "displayFolder": "Business metrics",
            "lineageTag": "9db2d6c7-2046-5506-b45d-523174a6cfcb"
          },
          {
            "name": "Average Cycle Days",
            "expression": "CALCULATE(AVERAGE(Jobs[CycleDays]), KEEPFILTERS(Jobs[Status] = \"Completed\"))",
            "formatString": "#,0.0",
            "description": "Mean creation-to-completion days for finished work.",
            "displayFolder": "Business metrics",
            "lineageTag": "cf1f50c0-06ae-548f-a30b-4f60ac148ea3"
          },
          {
            "name": "Overdue Open Jobs",
            "expression": "CALCULATE([Open Jobs], KEEPFILTERS(Jobs[DueDate] < DATE(2026,9,30)))",
            "formatString": "#,0",
            "description": "Open jobs whose due date precedes the demo snapshot date.",
            "displayFolder": "Business metrics",
            "lineageTag": "bedcde1d-f9ab-52ce-9dcd-680e1205d82b"
          },
          {
            "name": "Rework Jobs",
            "expression": "SUM(Jobs[Rework])",
            "formatString": "#,0",
            "description": "Completed jobs flagged for rework.",
            "displayFolder": "Business metrics",
            "lineageTag": "c6bffec7-6438-5206-97c8-9ec53477fc26"
          },
          {
            "name": "Rework Rate",
            "expression": "DIVIDE([Rework Jobs], [Completed Jobs])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Reworked completed jobs / completed jobs.",
            "displayFolder": "Business metrics",
            "lineageTag": "01edfd34-b88e-5dfc-aa00-3893083830fa"
          },
          {
            "name": "First Pass Yield",
            "expression": "DIVIDE([Completed Jobs] - [Rework Jobs], [Completed Jobs])",
            "formatString": "0.0%;(0.0%);0.0%",
            "description": "Completed without rework / all completed jobs.",
            "displayFolder": "Business metrics",
            "lineageTag": "ef84f3b4-a7ee-5f5f-b685-2a5bdebb10ee"
          },
          {
            "name": "Recorded Cost",
            "expression": "SUM(Jobs[Cost])",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Recorded cost incurred on all selected jobs; open jobs included.",
            "displayFolder": "Business metrics",
            "lineageTag": "5c83d594-de97-5eec-b4c2-0554325da7e7"
          },
          {
            "name": "Cost per Completed Job",
            "expression": "DIVIDE(CALCULATE(SUM(Jobs[Cost]), KEEPFILTERS(Jobs[Status] = \"Completed\")), [Completed Jobs])",
            "formatString": "\"PKR \"#,0;(\"PKR \"#,0);\"PKR \"0",
            "description": "Cost associated with completed jobs / completed count.",
            "displayFolder": "Business metrics",
            "lineageTag": "cfcceacb-2a78-596c-ab75-49574ba7302d"
          }
        ]
      },
      {
        "name": "Calendar",
        "lineageTag": "2a9d50b9-4f36-5655-8c67-c8205a46f2ce",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "lineageTag": "b9e54988-f91a-519d-95bf-7ce1d3a98d1e",
            "formatString": "dd MMM yyyy",
            "isKey": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "lineageTag": "e2b1fa3c-f3ae-5373-a97d-61200afd0ab4"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "summarizeBy": "none",
            "lineageTag": "d28606e5-ebd8-5ccc-9298-9a1745a073ee"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "lineageTag": "2aa0f450-34b6-5f0f-8bab-153986425350"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Demo = Binary.Decompress(Binary.FromText(\"hdo9qyNXGoXRfH7LNfTepz5zpxN0OGEHDRPZ0LT/v2fs232pUvksEEjiibTQRoHeX798//r2n69fvr39+/ffvv/37fMfX759//rtX/3U9ZdP+d/j7f8v397f//38OR+96AN9QV/RN/Qd/UA/5z2f0OEX+AV+gV/gF/gFfoFf4Ff4FX6FX+FX+BV+hV/hV/gVfgN+Y+rX27772os+0Bf0FX1D39EP9HPer/t+6PAL/AK/wC/wC/wCv8Av8Cv8Cr/Cr/Ar/Aq/wq/w69Rv3PY3XnvRB/qCvqJv6Dv6gX7O+3V/Dx1+gV/gF/gFfoFf4Bf4BX6FX+FX+BV+hV/hV/gVfoVf4TfgN6Z+y23fy3vvRy/6QF/QV/QNfUc/0M95v+77ocMv8Av8Ar/AL/AL/AK/wK/wK/wKv8Kv8Cv8Cr/Cr/Ar/MbUb73td33tRR/oC/qKvqHv6Af6Oe/X/T50+AV+gV/gF/gFfoFf4Bf4FX6FX+FX+BV+hV/hV/gVfoXfgN+Y+m23fW+vvegDfUFf0Tf0Hf1AP+f9uu+HDr/AL/AL/AK/wC/wC/wCv8Kv8Cv8Cr/Cr/Ar/Aq/wq/wG1O//bbf/b2Pj170gb6gr+gb+o5+oJ/zft3vQ4df4Bf4BX6BX+AX+AV+gV/hV/gVfoVf4Vf4FX6FX+FX+A34janfcdv38dqLPtAX9BV9Q9/RD/Rz3q/7fujwC/wCv8Av8Av8Ar/AL/Ar/Aq/wq/wK/wKv8Kv8Cv8Cr8BvzH1O2/7Pl970Qf6gr6ib+g7+oF+zvt13w8dfoFf4Bf4BX6BX+AX+AV+hV/hV/gVfoVf4Vf4FX6FX+E3Zn75dN3v+5f1l8/LRy/6QF/QV/QNfUc/0M95v+z3qcMv8Av8Ar/AL/AL/AK/wK/wK/wKv8Kv8Cv8Cr/Cr/Ar/Ab8xtTvdv+VvPaiD/QFfUXf0Hf0A/2c9+u+Hzr8Ar/AL/AL/AK/wC/wC/wKv8Kv8Cv8Cr/Cr/Ar/Aq/wm9M/W73XelrL/pAX9BX9A19Rz/Qz3m/7vehwy/wC/wCv8Av8Av8Ar/Ar/Ar/Aq/wq/wK/wKv8Kv8Cv8BvzGP/ttH/fZf32IH39mbe/3J9vHffakD/QFfUXf0Hf0A/2c97/3PenwC/wCv8Av8Av8Ar/AL/Ar/Aq/wq/wK/wKv8Kv8Cv8Cr8BvzH1+/H7/aP3tRd9oC/oK/qGvqMf6Oe8X/f90OEX+AV+gV/gF/gFfoFf4Ff4FX6FX+FX+BV+hV/h16nfuO1vvPaiD/QFfUXf0Hf0A/2c9+v+Hjr8Ar/AL/AL/AK/wC/wC/wKv8Kv8Cv8Cr/Cr/Ar/Aq/wm/Ab0z9ltu+l/fej170gb6gr+gb+o5+oJ/zft33Q4df4Bf4BX6BX+AX+AV+gV/hV/gVfoVf4Vf4FX6FX+FX+I2p33rb7/raiz7QF/QVfUPf0Q/0c96v+33o8Av8Ar/AL/AL/AK/wC/wK/wKv8Kv8Cv8Cr/Cr/Ar/Aq/Ab8x9dtu+95ee9EH+oK+om/oO/qBfs77dd8PHX6BX+AX+AV+gV/gF/gFfoVf4Vf4FX6FX+FX+BV+hV/hN6Z++22/+3sfH73oA31BX9E39B39QD/n/brfhw6/wC/wC/wCv8Av8Av8Ar/Cr/Ar/Aq/wq/wK/wKv8Kv8BvwG1O/47bv47UXfaAv6Cv6hr6jH+jnvF/3/dDhF/gFfoFf4Bf4BX6BX+BX+BV+hV/hV/gVfoVf4Vf4FX4DfmPqd972fb72og/0BX1F39B39AP9nPfrvh86/AK/wC/wC/wCv8Av8Av8Cr/Cr/Ar/Aq/wq/wK/wKv8JvzPx+3me/9/cv68/7kZ/32ZM+0Bf0FX1D39EP9HPeL/t96vAL/AK/wC/wC/wCv8Av8Cv8Cr/Cr/Ar/Aq/wq/wK/wKvwG/MfW73X8lr73oA31BX9E39B39QD/n/brvhw6/wC/wC/wCv8Av8Av8Ar/Cr/Ar/Aq/wq/wK/wKv8Kv8BtTv9t9V/raiz7QF/QVfUPf0Q/0c96v+33o8Av8Ar/AL/AL/AK/wC/wK/wKv8Kv8Cv8Cr/Cr/Ar/Aq/Ab/xD35/Ag==\", BinaryEncoding.Base64), Compression.Deflate),",
                "    Source = if DataMode = \"Demo\" then Demo else if DataMode = \"Folder\" then File.Contents(DataFolder & \"/Calendar.csv\") else error \"DataMode must be Demo or Folder\",",
                "    Parsed = Csv.Document(Source, [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Parsed, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Date\", type date}, {\"Year\", Int64.Type}, {\"Month\", type text}, {\"Quarter\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "dataCategory": "Time"
      }
    ],
    "relationships": [
      {
        "name": "461cd7e3-9b52-539b-a11f-d2795ee07ee5",
        "fromTable": "Jobs",
        "fromColumn": "TeamID",
        "toTable": "Teams",
        "toColumn": "TeamID",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      },
      {
        "name": "4a6254c2-a3c8-51fc-9ff4-bd95e87b7aa4",
        "fromTable": "Jobs",
        "fromColumn": "CreatedDate",
        "toTable": "Calendar",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection",
        "fromCardinality": "many",
        "toCardinality": "one"
      }
    ],
    "expressions": [
      {
        "name": "DataMode",
        "kind": "m",
        "expression": "\"Demo\" meta [IsParameterQuery=true, List={\"Demo\", \"Folder\"}, DefaultValue=\"Demo\", Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "DataFolder",
        "kind": "m",
        "expression": "\"C:/PowerBI/data-powerbi-portfolio/10-operations-kpis/data/demo\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}
